IFEM: /home/runner/work/IFEM-2/IFEM-2/src/ASM/LR/ASMu2Drecovery.C File Reference
ASMu2Drecovery.C File Reference
Recovery techniques for unstructured LR B-splines.
#include "LRSpline/LRSplineSurface.h"
#include "LRSpline/Element.h"
#include "ASMu2D.h"
#include "IntegrandBase.h"
#include "CoordinateMapping.h"
#include "GaussQuadrature.h"
#include "GlbL2projector.h"
#include "SparseMatrix.h"
#include "DenseMatrix.h"
#include "SplineUtils.h"
#include "Function.h"
#include "Profiler.h"
#include <array>
#include <GoTools/geometry/SplineSurface.h>
Functions
static void expandTensorGrid (const RealArray *in, RealArray *out)
Expands a tensor parametrization point to an unstructured one.
static void evalMonomials (int p1, int p2, double x, double y, Vector &P)
Evaluates monomials in 2D up to the specified order.
Detailed Description
Recovery techniques for unstructured LR B-splines.
Date
February 2012
Author
Kjetil A. Johannessen and Knut Morten Okstad / SINTEF
Function Documentation
expandTensorGrid()
static void expandTensorGrid (const RealArray * in, RealArray * out) static
Expands a tensor parametrization point to an unstructured one.
Takes as input a tensor mesh, for instance in[0] = {0,1,2} in[1] = {2,3,5} and expands this to an unstructured representation, i.e., out[0] = {0,1,2,0,1,2,0,1,2} out[1] = {2,2,2,3,3,3,5,5,5}
Referenced by ASMu2D::assembleL2matrices(), ASMu3D::assembleL2matrices(), ASMu2D::scRecovery(), and ASMu3D::scRecovery().