IFEM: GlobalNodes Class Reference
GlobalNodes Class Reference
Class establishing global node numbers for unstructed FE models.
#include <GlobalNodes.h>
Public Types
using IntVec = std::vector< int >
Convenience typedef.
using LRSplineVec = std::vector< const LR::LRSpline * >
Convenience typedef.
using InterfaceVec = std::vector< ASM::Interface >
Convenience typedef.
Static Public Member Functions
static IntVec getBoundaryNodes (const LR::LRSpline &lr, int dim, int lidx, int orient)
Extract local boundary nodes for a LR spline.
static std::vector< IntVec > calcGlobalNodes (const LRSplineVec &pchs, const InterfaceVec &interfaces)
Calculate global node numbers for a FE model.
Detailed Description
Class establishing global node numbers for unstructed FE models.
Member Function Documentation
calcGlobalNodes()
std::vector< GlobalNodes::IntVec > GlobalNodes::calcGlobalNodes (const LRSplineVec & pchs, const InterfaceVec & interfaces) static
Calculate global node numbers for a FE model.
Parameters
pchs The spline patches in the model
interfaces The topological connections for the spline patches
References getBoundaryNodes(), and utl::renumber().
Referenced by AdaptiveSetup::calcRefinement().
getBoundaryNodes()
GlobalNodes::IntVec GlobalNodes::getBoundaryNodes (const LR::LRSpline & lr, int dim, int lidx, int orient) static
Extract local boundary nodes for a LR spline.
Parameters
lr The LR spline to extract boundary nodes for
dim The dimension of the boundary to extract
lidx The local index of the boundary to extract
orient Orientation of nodes on boundary
References ASMLRSpline::Sort().
Referenced by calcGlobalNodes(), ASMu3D::extendRefinementDomain(), and ASMLRSpline::getBoundaryCovered().
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/ASM/LR/GlobalNodes.h
/home/runner/work/IFEM-2/IFEM-2/src/ASM/LR/GlobalNodes.C