IFEM: BasisFunctionCache< Dim > Class Template Reference
BasisFunctionCache< Dim > Class Template Reference abstract
Base class for basis function caches.
#include <BasisFunctionCache.h>
Classes
struct Quadrature
Template struct holding information about a quadrature.
Public Member Functions
BasisFunctionCache ()
Default constructor.
BasisFunctionCache (const BasisFunctionCache &rhs)
Copy-constructor.
virtual ~BasisFunctionCache ()=default
Empty destructor.
void clear ()
Clears the basis function cache.
bool init (int nd)
Initialize the basis function cache according to policy.
const BasisFunctionVals & getVals (size_t el, size_t gp, bool reduced=false)
Obtain basis function values/derivatives in an integration point.
void setIntegrand (const Integrand *itg)
Defines the integrand to be used.
const std::array< int, Dim > & nGauss (bool reduced=false)
Returns number of integration points.
const std::array< const double *, Dim > & weight (bool reduced=false) const
Return integration scheme weights.
const std::array< const double *, Dim > & coord (bool reduced=false) const
Return integration scheme nodes.
bool hasReduced () const
Returns whether or not a reduced quadrature is enabled.
virtual double getParam (int dir, size_t el, size_t gp, bool reduced=false) const
Obtain a single integration point parameter.
void resizeThreadBuffers ()
Called if application changes number of threads.
Public Attributes
int basis = 1
Basis to use.
Protected Member Functions
virtual bool internalInit ()=0
Class-specified initialization.
virtual BasisFunctionVals calculatePt (size_t el, size_t gp, bool reduced=false) const =0
Calculates basis function info in a single integration point.
virtual void calculateAll ()=0
Calculates basis function info in all integration points.
virtual size_t index (size_t el, size_t gp, bool reduced) const
Obtain global integration point index.
std::array< size_t, Dim > gpIndex (size_t gp, bool reduced) const
Obtain structured integration point indices.
Protected Attributes
std::vector< BasisFunctionVals > values
Cache for main quadrature.
std::vector< BasisFunctionVals > valuesRed
Cache for reduced quadrature.
const Integrand * integrand = nullptr
Integrand to use.
int nderiv = 0
Number of derivatives.
std::shared_ptr< Quadrature > mainQ
Main quadrature information.
std::shared_ptr< Quadrature > reducedQ
Reduced quadrature information.
size_t nTotal = 0
Total number of main integration points.
size_t nTotalRed = 0
Total number of reduced integration points.
Detailed Description
template<size_t Dim>
class BasisFunctionCache< Dim >
Base class for basis function caches.
Constructor & Destructor Documentation
~BasisFunctionCache()
template<size_t Dim> virtual BasisFunctionCache< Dim >::~BasisFunctionCache () virtual default
Empty destructor.
Reimplemented in ASMs2DLag::BasisFunctionCache, ASMs2DmxLag::BasisFunctionCache, ASMs3DLag::BasisFunctionCache, ASMs3DmxLag::BasisFunctionCache, ASMu2DLag::BasisFunctionCache, ASMu2D::BasisFunctionCache, and ASMu3D::BasisFunctionCache.
Member Function Documentation
calculateAll()
template<size_t Dim> virtual void BasisFunctionCache< Dim >::calculateAll () protected pure virtual
Calculates basis function info in all integration points.
Implemented in ASMs2D::BasisFunctionCache, ASMs2DLag::BasisFunctionCache, ASMs2DmxLag::BasisFunctionCache, ASMs3D::BasisFunctionCache, ASMs3DLag::BasisFunctionCache, ASMs3DmxLag::BasisFunctionCache, ASMu2D::BasisFunctionCache, and ASMu3D::BasisFunctionCache.
calculatePt()
template<size_t Dim> virtual BasisFunctionVals BasisFunctionCache< Dim >::calculatePt (size_t el, size_t gp, bool reduced = false) const protected pure virtual
Calculates basis function info in a single integration point.
Parameters
el Element of integration point (0-indexed)
gp Integratin point on element (0-indexed)
reduced If true, returns values for reduced integration scheme
Implemented in ASMs2D::BasisFunctionCache, ASMs3D::BasisFunctionCache, ASMu2D::BasisFunctionCache, ASMu3D::BasisFunctionCache, ASMs2DLag::BasisFunctionCache, ASMs2DmxLag::BasisFunctionCache, ASMs3DLag::BasisFunctionCache, and ASMs3DmxLag::BasisFunctionCache.
coord()
template<size_t Dim> const std::array< const double *, Dim > & BasisFunctionCache< Dim >::coord (bool reduced = false) const inline
Return integration scheme nodes.
Parameters
reduced True to return reduced quadrature
References BasisFunctionCache< Dim >::mainQ, and BasisFunctionCache< Dim >::reducedQ.
Referenced by ASMs2D::integrate(), ASMs2Dmx::integrate(), ASMs2DmxLag::integrate(), ASMs3D::integrate(), ASMs3DLag::integrate(), ASMs3Dmx::integrate(), ASMs3DmxLag::integrate(), ASMu2D::integrate(), ASMu2Dmx::integrate(), ASMu3D::integrate(), ASMu3Dmx::integrate(), and ASMs2DLag::integrateElm().
getParam()
template<size_t Dim> double BasisFunctionCache< Dim >::getParam (int dir, size_t el, size_t gp, bool reduced = false) const virtual
Obtain a single integration point parameter.
Parameters
dir Direction of for integration point
el Element number in given direction
gp Integration point in given direction
reduced True to return parameter for reduced quadrature
Reimplemented in ASMs2DLag::BasisFunctionCache, ASMs3DLag::BasisFunctionCache, and ASMu2DLag::BasisFunctionCache.
References BasisFunctionCache< Dim >::Quadrature::gpar, and BasisFunctionCache< Dim >::Quadrature::ng.
Referenced by ASMs2DLag::assembleL2matrices(), ASMs3DLag::assembleL2matrices(), ASMs2D::integrate(), ASMs2Dmx::integrate(), ASMs2DmxLag::integrate(), ASMs3D::integrate(), ASMs3DLag::integrate(), ASMs3Dmx::integrate(), ASMs3DmxLag::integrate(), ASMu2D::integrate(), ASMu2Dmx::integrate(), ASMu3D::integrate(), ASMu3Dmx::integrate(), and ASMs2DLag::integrateElm().
getVals()
template<size_t Dim> const BasisFunctionVals & BasisFunctionCache< Dim >::getVals (size_t el, size_t gp, bool reduced = false)
Obtain basis function values/derivatives in an integration point.
Parameters
el Element of integration point (0-indexed)
gp Integratin point on element (0-indexed)
reduced If true, returns values for reduced integration scheme
References ASM::cachePolicy, and ASM::NO_CACHE.
Referenced by ASMs2DLag::assembleL2matrices(), ASMs3DLag::assembleL2matrices(), ASMs2D::integrate(), ASMs3D::integrate(), ASMs3DLag::integrate(), ASMu2D::integrate(), ASMu3D::integrate(), and ASMs2DLag::integrateElm().
gpIndex()
template<size_t Dim> std::array< size_t, Dim > BasisFunctionCache< Dim >::gpIndex (size_t gp, bool reduced) const protected
Obtain structured integration point indices.
Parameters
gp Global integration point
reduced If true, returns values for reduced integration scheme
index()
template<size_t Dim> size_t BasisFunctionCache< Dim >::index (size_t el, size_t gp, bool reduced) const protected virtual
Obtain global integration point index.
Parameters
el Element of integration point (0-indexed)
gp Integration point on element (0-indexed)
reduced If true return index for reduced integration scheme
Reimplemented in ASMs2D::BasisFunctionCache, ASMs3D::BasisFunctionCache, ASMs2DLag::BasisFunctionCache, and ASMs3DLag::BasisFunctionCache.
References BasisFunctionCache< Dim >::Quadrature::ng.
init()
template<size_t Dim> bool BasisFunctionCache< Dim >::init (int nd)
Initialize the basis function cache according to policy.
Parameters
nd Number of derivatives
Referenced by ASMs2DLag::assembleL2matrices(), ASMs3DLag::assembleL2matrices(), ASMs2D::integrate(), ASMs2DLag::integrate(), ASMs3D::integrate(), ASMs3DLag::integrate(), ASMu2DLag::integrate(), ASMu2D::integrate(), and ASMu3D::integrate().
internalInit()
template<size_t Dim> virtual bool BasisFunctionCache< Dim >::internalInit () protected pure virtual
Class-specified initialization.
Implemented in ASMs2D::BasisFunctionCache, ASMs2DLag::BasisFunctionCache, ASMs3D::BasisFunctionCache, ASMs3DLag::BasisFunctionCache, ASMu2D::BasisFunctionCache, and ASMu3D::BasisFunctionCache.
nGauss()
template<size_t Dim> const std::array< int, Dim > & BasisFunctionCache< Dim >::nGauss (bool reduced = false) inline
Returns number of integration points.
Parameters
reduced True to return reduced quadrature
References BasisFunctionCache< Dim >::mainQ, and BasisFunctionCache< Dim >::reducedQ.
Referenced by ASMs2DLag::assembleL2matrices(), ASMs3DLag::assembleL2matrices(), ASMs2D::integrate(), ASMs2Dmx::integrate(), ASMs2DmxLag::integrate(), ASMs3D::integrate(), ASMs3DLag::integrate(), ASMs3Dmx::integrate(), ASMs3DmxLag::integrate(), ASMu2D::integrate(), ASMu2Dmx::integrate(), ASMu3D::integrate(), ASMu3Dmx::integrate(), and ASMs2DLag::integrateElm().
setIntegrand()
template<size_t Dim> void BasisFunctionCache< Dim >::setIntegrand (const Integrand * itg) inline
Defines the integrand to be used.
Parameters
itg Integrand to use
References BasisFunctionCache< Dim >::integrand.
Referenced by ASMs2D::integrate(), ASMs2DLag::integrate(), ASMs3D::integrate(), ASMs3DLag::integrate(), ASMu2DLag::integrate(), ASMu2D::integrate(), ASMu2Dmx::integrate(), ASMu3D::integrate(), and ASMu3Dmx::integrate().
weight()
template<size_t Dim> const std::array< const double *, Dim > & BasisFunctionCache< Dim >::weight (bool reduced = false) const inline
Return integration scheme weights.
Parameters
reduced True to return reduced quadrature
References BasisFunctionCache< Dim >::mainQ, and BasisFunctionCache< Dim >::reducedQ.
Referenced by ASMs2DLag::assembleL2matrices(), ASMs3DLag::assembleL2matrices(), ASMs2D::integrate(), ASMs2Dmx::integrate(), ASMs2DmxLag::integrate(), ASMs3D::integrate(), ASMs3DLag::integrate(), ASMs3Dmx::integrate(), ASMs3DmxLag::integrate(), ASMu2D::integrate(), ASMu2Dmx::integrate(), ASMu3D::integrate(), ASMu3Dmx::integrate(), and ASMs2DLag::integrateElm().
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/ASM/BasisFunctionCache.h
/home/runner/work/IFEM-2/IFEM-2/src/ASM/BasisFunctionCache.C