IFEM: DomainDecomposition Class Reference
DomainDecomposition Class Reference
Class containing domain decomposition related partitioning.
#include <DomainDecomposition.h>
Classes
struct BlockInfo
Struct with information per matrix block.
class OrientIterator
Iterator for matching nodes on edges/faces with a given orientation and index.
class SlaveOrder
Functor to order ghost connections.
Public Member Functions
DomainDecomposition ()
Default constructor.
bool setup (const ProcessAdm &adm, const SIMbase &sim)
Setup domain decomposition.
bool setup (const ProcessAdm &adm, const IntMat &neighs, const IntMat &meqn)
Setup domain decomposition.
void setup (const int neq)
Setup single-process domain decomposition.
std::vector< std::set< int > > getSubdomains (int nx, int ny, int nz, int overlap, size_t block) const
Obtain local subdomains for an equation block.
int getMinEq (size_t idx=0) const
Get first equation owned by this process.
int getMaxEq (size_t idx=0) const
Get last equation owned by this process.
int getNoGlbEqs (size_t idx=0) const
Get total number of equations in a block.
int getMinNode () const
Get first node owned by this process.
int getMaxNode () const
Get last node owned by this process.
int getMinDOF () const
Get first DOF owned by this process.
int getMaxDOF () const
Get last DOF owned by this process.
void setPatchOwner (size_t p, size_t owner)
Set owner for a patch.
int getPatchOwner (size_t p) const
Get process owning patch p.
int getGlobalEq (int lEq, size_t idx=0) const
Get global equation number.
const IntVec & getMLGEQ (size_t idx=0) const
Obtain local-to-global equation mapping.
const std::set< int > & getBlockEqs (size_t idx) const
Obtain local-to-global equation mapping.
const std::map< int, int > & getG2LEQ (size_t idx) const
Obtain global-to-local equation mapping.
const IntVec & getMLGN () const
Obtain local-to-global node mapping.
const SAMpatch * getSAM () const
Returns associated SAM.
size_t getNoBlocks () const
Returns number of matrix blocks.
bool isPartitioned () const
Returns whether a graph based partition is used.
const IntVec & getElms () const
Returns elements in partition.
void setElms (const IntVec &elms, const std::string &save)
Set elements in partition.
void clear ()
Clear out partitioning information.
Static Public Member Functions
static IntMat calcSubdomains (size_t nel1, size_t nel2, size_t nel3, size_t g1, size_t g2, size_t g3, size_t overlap)
Calculates subdomains with a given overlap.
Public Attributes
std::set< ASM::Interface, SlaveOrder > ghostConnections
Connections to other processes.
Private Member Functions
bool calcGlobalNodeNumbers (const ProcessAdm &adm, const SIMbase &sim)
Calculate the global node numbers for given finite element model.
bool calcGlobalEqNumbers (const ProcessAdm &adm, const SIMbase &sim)
Calculate the global equation numbers for an element model.
template<class Callback >
bool calcGlobalEqNumbersPart (const ProcessAdm &adm, const Callback &cb)
Calculate the global equation numbers for a partitioned model.
bool sanityCheckCorners (const SIMbase &sim)
Sanity check model.
bool graphPartition (const ProcessAdm &adm, const IntMat &neigh)
Setup domain decomposition based on graph partitioning.
Static Private Member Functions
static IntMat calcSubdomains1D (size_t nel1, size_t g1, size_t overlap)
Calculates a 1D partitioning with a given overlap.
static IntMat calcSubdomains2D (size_t nel1, size_t nel2, size_t g1, size_t g2, size_t overlap)
Calculates 2D subdomains with a given overlap.
static IntMat calcSubdomains3D (size_t nel1, size_t nel2, size_t nel3, size_t g1, size_t g2, size_t g3, size_t overlap)
Calculates 3D subdomains with a given overlap.
Private Attributes
std::map< int, int > patchOwner
Process that owns a particular patch.
IntVec MLGN
Process-local-to-global node numbers.
std::vector< BlockInfo > blocks
Equation mappings for all matrix blocks.
IntVec myElms
Elements in partition.
int minDof = 0
First DOF we own.
int maxDof = 0
Last DOF we own.
int minNode = 0
First node we own.
int maxNode = 0
Last node we own.
const SAMpatch * sam = nullptr
The assembly handler the DD is constructed for.
std::string savePart
Non-empty to save partitioning to file.
Detailed Description
Class containing domain decomposition related partitioning.
Member Function Documentation
calcSubdomains()
IntMat DomainDecomposition::calcSubdomains (size_t nel1, size_t nel2, size_t nel3, size_t g1, size_t g2, size_t g3, size_t overlap) static
Calculates subdomains with a given overlap.
Parameters
[in] nel1 Number of knot-spans in first parameter direction.
[in] nel2 Number of knot-spans in second parameter direction.
[in] nel3 Number of knot-spans in third parameter direction.
[in] g1 Number of subdomains in first parameter direction.
[in] g2 Number of subdomains in second parameter direction.
[in] g3 Number of subdomains in third parameter direction.
[in] overlap Overlap of subdomains.
nel values determine the dimensionality.
References calcSubdomains1D(), calcSubdomains2D(), and calcSubdomains3D().
Referenced by getSubdomains().
calcSubdomains1D()
IntMat DomainDecomposition::calcSubdomains1D (size_t nel1, size_t g1, size_t overlap) static private
Calculates a 1D partitioning with a given overlap.
Parameters
[in] nel1 Number of knot-spans in first parameter direction.
[in] g1 Number of subdomains in first parameter direction.
[in] overlap Overlap of subdomains.
Referenced by calcSubdomains().
calcSubdomains2D()
IntMat DomainDecomposition::calcSubdomains2D (size_t nel1, size_t nel2, size_t g1, size_t g2, size_t overlap) static private
Calculates 2D subdomains with a given overlap.
Parameters
[in] nel1 Number of knot-spans in first parameter direction.
[in] nel2 Number of knot-spans in second parameter direction.
[in] g1 Number of subdomains in first parameter direction.
[in] g2 Number of subdomains in second parameter direction.
[in] overlap Overlap of subdomains.
Referenced by calcSubdomains().
calcSubdomains3D()
IntMat DomainDecomposition::calcSubdomains3D (size_t nel1, size_t nel2, size_t nel3, size_t g1, size_t g2, size_t g3, size_t overlap) static private
Calculates 3D subdomains with a given overlap.
Parameters
[in] nel1 Number of knot-spans in first parameter direction.
[in] nel2 Number of knot-spans in second parameter direction.
[in] nel3 Number of knot-spans in third parameter direction.
[in] g1 Number of subdomains in first parameter direction.
[in] g2 Number of subdomains in second parameter direction.
[in] g3 Number of subdomains in third parameter direction.
[in] overlap Overlap of subdomains.
Referenced by calcSubdomains().
getBlockEqs()
const std::set< int > & DomainDecomposition::getBlockEqs (size_t idx) const inline
Obtain local-to-global equation mapping.
Parameters
idx Block equation index (global block not included).
References blocks.
Referenced by ISTL::BlockPreconditioner::apply(), ISTL::BlockPreconditioner::BlockPreconditioner(), calcGlobalEqNumbers(), PETScMatrix::initAssembly(), ISTL::BlockPreconditioner::post(), ISTL::BlockPreconditioner::pre(), and PETScMatrix::setParameters().
getG2LEQ()
const std::map< int, int > & DomainDecomposition::getG2LEQ (size_t idx) const inline
Obtain global-to-local equation mapping.
Parameters
idx Block equation index
References blocks.
Referenced by _eig_ax(), ISTL::BlockPreconditioner::BlockPreconditioner(), eig_sol_(), SAMpatchPETSc::expandSolution(), PETScMatrix::setupGlb2Blk(), and PETScMatrix::solveEig().
getGlobalEq()
int DomainDecomposition::getGlobalEq (int lEq, size_t idx = 0) const
Get global equation number.
Parameters
lEq Local equation number
idx Block to get index for
References blocks.
Referenced by _eig_ax(), PETScMatrix::add(), PETScVectors::assemble(), eig_sol_(), PETScVector::endAssembly(), PETScMatrix::initAssembly(), PETScSolParams::setupAdditiveSchwarz(), PETScMatrix::setupGlb2Blk(), and ISTLSolParams::setupPC().
getSubdomains()
std::vector< std::set< int > > DomainDecomposition::getSubdomains (int nx, int ny, int nz, int overlap, size_t block) const
Obtain local subdomains for an equation block.
Parameters
nx Number of domains in x
ny Number of domains in y
nz Number of domains in z
overlap Overlap
block Block to obtain equations for
Returns
Vector with equations on each subdomain
References blocks, calcSubdomains(), SAM::getElmEqns(), SAM::getElmNodes(), getNoBlocks(), SAM::getNodeEqns(), SAM::getNodeType(), SAMpatch::getNoPatches(), ASMstruct::getNoStructElms(), and getSAM().
Referenced by PETScSolParams::setupAdditiveSchwarz(), and ISTLSolParams::setupPCInternal().
sanityCheckCorners()
bool DomainDecomposition::sanityCheckCorners (const SIMbase & sim) private
Sanity check model.
Collects the corners of all patches in the model and make sure nodes with matching coordinates have the same global node ID.
References ProcessAdm::dd, ASMbase::getCoord(), ASM2D::getCorner(), ASM3D::getCorner(), SIMbase::getLocalPatchIndex(), getMLGN(), ASMbase::getNoBasis(), ASMbase::getNodeID(), SIMbase::getNoPatches(), ProcessAdm::getNoProcs(), ASMbase::getNoSpaceDim(), SIMbase::getNoSpaceDim(), SIMbase::getPatch(), getPatchOwner(), SIMadmin::getProcessAdm(), and ProcessAdm::isParallel().
Referenced by setup().
setup() [1/3]
void DomainDecomposition::setup (const int neq)
Setup single-process domain decomposition.
neq Number of equations
References blocks.
setup() [2/3]
bool DomainDecomposition::setup (const ProcessAdm & adm, const IntMat & neighs, const IntMat & meqn)
Setup domain decomposition.
Parameters
[in] adm Process administrator to setup dd across
[in] neighs Element connection graph for model
[in] meqn Matrix of element equation numbers
References blocks, calcGlobalEqNumbersPart(), IFEM::cout, getMaxEq(), getMinEq(), ProcessAdm::getNoProcs(), ProcessAdm::getProcId(), graphPartition(), and ProcessAdm::isParallel().
setup() [3/3]
bool DomainDecomposition::setup (const ProcessAdm & adm, const SIMbase & sim)
Setup domain decomposition.
Parameters
[in] adm Process administrator to setup dd across
[in] sim Simulator with model to partition
References LinSolParams::BlockParams::basis, blocks, calcGlobalEqNumbers(), calcGlobalEqNumbersPart(), calcGlobalNodeNumbers(), LinSolParams::BlockParams::comps, IFEM::cout, ProcessAdm::dd, ASMbase::generateThreadGroupsFromElms(), LinSolParams::getBlock(), utl::getDigits(), SIMbase::getElmConnectivities(), SAM::getEquation(), SAM::getEquations(), SIMbase::getFEModel(), ASMbase::getLMType(), getMaxEq(), getMaxNode(), getMinEq(), getMinNode(), LinSolParams::getNoBlocks(), ASMbase::getNodeID(), ASMbase::getNoNodes(), ProcessAdm::getNoProcs(), SIMbase::getPatch(), ProcessAdm::getProcId(), getSAM(), SIMbase::getSAM(), SIMbase::getSolParams(), ghostConnections, graphPartition(), ASMbase::isLMn(), ProcessAdm::isParallel(), myElms, sam, and sanityCheckCorners().
Referenced by SIMbase::merge(), and SIMbase::preprocessC().
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/ASM/DomainDecomposition.h
/home/runner/work/IFEM-2/IFEM-2/src/ASM/DomainDecomposition.C