IFEM: SIMmodal Class Reference
SIMmodal Class Reference abstract
Class with support for assembly of modal linear equation systems.
#include <SIMmodal.h>
Public Member Functions
virtual const Vectors & expandSolution (const Vectors &, bool=false)=0
Expands and returns the current dynamic solution.
const Vectors & expandedSolution () const
Returns the current expanded dynamic solution.
const Vector & expandedSolution (int idx) const
Returns the current expanded dynamic solution.
size_t numExpSolution () const
Returns the number of expanded dynamic solution vectors.
virtual bool projectModes (Matrices &, std::vector< std::string > &, SIMoptions::ProjectionMethod)
Projects the secondary solution associated with the eigenmodes.
Protected Member Functions
SIMmodal (std::vector< Mode > &modes)
The constructor initializes the reference to the eigenmodes.
virtual ~SIMmodal ()
The destructor deletes the dynamically allocated members.
bool parseParams (const tinyxml2::XMLElement *elem)
Parses structural damping parameters from an XML element.
const Vectors & expandSolution (const Vectors &mSol)
Calculates the dynamic solution from the previous modal solution.
bool assembleModalSystem (const TimeDomain &time, const Vectors &mSol, double beta, double gamma)
Administers assembly of the modal equation system.
bool swapSystem (AlgEqSystem *&sys, SAM *&sam)
Swaps the modal equation system before/after load vector assembly.
bool saveModes (std::map< std::string, std::string > &data) const
Writes the eigenmodes to a serialization container.
bool restoreModes (const std::map< std::string, std::string > &data)
Restores the eigenmodes from a serialization container.
Protected Attributes
std::vector< Mode > & myModes
Array of eigenmodes.
Vector Rhs
Current right-hand-side load vector of the dynamic system.
Vectors sol
Expanded solution vectors from the modal solution.
bool parsed
Set to true after the model has been initialized.
double alpha1
Mass-proportional damping parameter.
double alpha2
Stiffness-proportional damping parameter.
Private Attributes
AlgEqSystem * modalSys
The modal equation system.
SAM * modalSam
Auxiliary data for FE assembly management.
ElmMats * myElmMat
Nodal (single-DOF) element matrices.
Detailed Description
Class with support for assembly of modal linear equation systems.
This class contains a separate AlgEqSystem object and an associated SAM object, used for assembling the modal system of equations.
Member Function Documentation
assembleModalSystem()
bool SIMmodal::assembleModalSystem (const TimeDomain & time, const Vectors & mSol, double beta, double gamma) protected
Administers assembly of the modal equation system.
Parameters
[in] time Parameters for time-dependent simulations
[in] mSol Previous modal solution
[in] beta Newmark time integration parameter
[in] gamma Newmark time integration parameter
This method assembles the diagonal modal equation system of the dynamic problem, integrated by the Newmark HHT-method. If beta is set to zero, a quasi-static solution is calculated instead, in which the modal mass and damping is ignored and only the modal stiffness (i.e., the angular eigenfrequencies squared) enter the equation system.
References ElmMats::A, alpha1, alpha2, AlgEqSystem::assemble(), ElmMats::b, LinAlg::DIAG, TimeDomain::dt, AlgEqSystem::finalize(), TimeDomain::first, AlgEqSystem::init(), AlgEqSystem::initialize(), TimeDomain::it, modalSam, modalSys, myElmMat, myModes, ElmMats::redim(), ElmMats::resize(), Rhs, ElmMats::setStepSize(), and LocalIntegral::vec.
expandedSolution()
const Vector & SIMmodal::expandedSolution (int idx) const
Returns the current expanded dynamic solution.
Parameters
[in] idx Solution vector index
References sol.
expandSolution()
const Vectors & SIMmodal::expandSolution (const Vectors & mSol) protected
Calculates the dynamic solution from the previous modal solution.
Parameters
[in] mSol Previous modal solution
References myModes, and sol.
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/SIM/SIMmodal.h
/home/runner/work/IFEM-2/IFEM-2/src/SIM/SIMmodal.C