IFEM: GlobalIntegral Class Reference
GlobalIntegral Class Reference
Abstract base class representing a system level integrated quantity.
#include <GlobalIntegral.h>
Public Member Functions
GlobalIntegral ()
The default constructor.
virtual ~GlobalIntegral ()
Empty destructor.
virtual void initialize (char)
Initializes the integrated quantity to zero.
virtual bool finalize (bool)
Finalizes the integrated quantity after element assembly.
virtual bool assemble (const LocalIntegral *, int)
Adds a LocalIntegral object into a corresponding global object.
virtual bool threadSafe () const
Returns true if all elements can be assembled in parallel.
virtual bool haveContributions (size_t, const std::vector< Property > &) const
Returns false if no contributions from a specified patch.
Detailed Description
Abstract base class representing a system level integrated quantity.
Member Function Documentation
assemble()
virtual bool GlobalIntegral::assemble (const LocalIntegral * , int) inline virtual
Adds a LocalIntegral object into a corresponding global object.
Reimplemented in AlgEqSystem, GlbForceVec, ReactionsOnly, and GlbNorm.
Referenced by ASMstruct::diracPoint(), ASMu2D::diracPoint(), ASMu3D::diracPoint(), ASMsupel::integrate(), ASMs1D::integrate(), ASMs1DLag::integrate(), ASMs1DSpec::integrate(), ASMs2D::integrate(), ASMs2Dmx::integrate(), ASMs2DmxLag::integrate(), ASMs2DSpec::integrate(), ASMs2DTri::integrate(), ASMs3D::integrate(), ASMs3DLag::integrate(), ASMs3Dmx::integrate(), ASMs3DmxLag::integrate(), ASMs3DSpec::integrate(), ASMu2D::integrate(), ASMu2Dmx::integrate(), ASMu3D::integrate(), ASMu3Dmx::integrate(), ASMs2D::integrate(), ASMs2Dmx::integrate(), ASMs3Dmx::integrate(), ASMu2D::integrate(), ASMu2Dmx::integrate(), ASMs2D::integrate(), ASMs3D::integrate(), ASMu2D::integrate(), ASMs1D::integrate(), ASMs1DLag::integrate(), ASMs2D::integrate(), ASMs2DLag::integrate(), ASMs2Dmx::integrate(), ASMs2DmxLag::integrate(), ASMs2DSpec::integrate(), ASMs2DTri::integrate(), ASMs3D::integrate(), ASMs3DLag::integrate(), ASMs3Dmx::integrate(), ASMs3DmxLag::integrate(), ASMs3DSpec::integrate(), ASMu2D::integrate(), ASMu2Dmx::integrate(), ASMu3D::integrate(), ASMu3Dmx::integrate(), ASMs3D::integrateEdge(), ASMs3DLag::integrateEdge(), ASMs3DSpec::integrateEdge(), and ASMs2DLag::integrateElm().
finalize()
virtual bool GlobalIntegral::finalize (bool) inline virtual
Finalizes the integrated quantity after element assembly.
Reimplemented in AlgEqSystem, ReactionsOnly, and GlbForceVec.
Referenced by SIMbase::assembleSystem().
haveContributions()
virtual bool GlobalIntegral::haveContributions (size_t , const std::vector< Property > &) const inline virtual
Returns false if no contributions from a specified patch.
Reimplemented in ReactionsOnly.
initialize()
virtual void GlobalIntegral::initialize (char) inline virtual
Initializes the integrated quantity to zero.
Reimplemented in AlgEqSystem, ReactionsOnly, and GlbForceVec.
Referenced by SIMbase::assembleSystem().
threadSafe()
virtual bool GlobalIntegral::threadSafe () const inline virtual
Returns true if all elements can be assembled in parallel.
Reimplemented in GlbNorm.
Referenced by ASMs2D::integrate(), ASMs2DLag::integrate(), ASMs2Dmx::integrate(), ASMs3D::integrate(), ASMs3DLag::integrate(), ASMs3Dmx::integrate(), ASMu2DLag::integrate(), ASMu2D::integrate(), ASMu2Dmx::integrate(), ASMu3D::integrate(), ASMu3Dmx::integrate(), ASMs2D::integrate(), ASMs3D::integrate(), and ASMu2D::integrate().
The documentation for this class was generated from the following file:
/home/runner/work/IFEM-2/IFEM-2/src/ASM/GlobalIntegral.h