IFEM: RealFunc Class Reference
RealFunc Class Reference
Scalar-valued unary function of a spatial point.
#include <Function.h>
Public Member Functions
unsigned char getType () const override
Returns the function type flag.
std::vector< Real > getValue (const Vec3 &X) const override
Returns the function value as an array.
virtual Vec3 gradient (const Vec3 &X) const
Evaluates first derivatives of the function.
virtual SymmTensor hessian (const Vec3 &X) const
Evaluates second derivatives of the function.
Real getScalarValue (const Vec3 &X) const override
Returns a representative scalar equivalent of the function value.
Real timeDerivative (const Vec3 &X) const
Returns the time derivative of the function.
Public Member Functions inherited from utl::SpatialFunction< Real >
virtual Real deriv (const Vec3 &, int) const
Returns a first-derivative of the function.
virtual Real dderiv (const Vec3 &, int, int) const
Returns a second-derivative of the function.
Public Member Functions inherited from utl::Function< Arg, Result >
virtual ~Function ()
Empty destructor.
virtual bool isZero () const
Returns whether the function is identically zero or not.
virtual bool isConstant () const
Returns whether the function is time-independent or not.
Result operator() (const Arg &x) const
Operator returning the function value for the given argument.
Public Member Functions inherited from FunctionBase
virtual ~FunctionBase ()
Empty destructor.
size_t dim () const
Returns the number of components of the return value.
virtual bool initPatch (size_t)
Sets the active patch.
virtual bool inDomain (const Vec3 &) const
Checks if a specified point is within the function domain.
virtual void setParam (const std::string &, Real)
Sets an additional parameter in the function.
void setParam (const std::string &name, const Vec3 &value)
Sets additional parameter values in the function.
Protected Member Functions
RealFunc ()
The constructor is protected to allow sub-class instances only.
Protected Member Functions inherited from utl::SpatialFunction< Real >
SpatialFunction (const Real &val)
The constructor is protected to allow sub-class instances only.
virtual std::vector< Real > evalGradient (const Vec3 &) const
Returns the gradient of the function as a 1D array.
virtual std::vector< Real > evalHessian (const Vec3 &) const
Returns the hessian of the function as a 1D array.
virtual std::vector< Real > evalTimeDerivative (const Vec3 &) const
Returns the time derivatives of the function as a 1D array.
Protected Member Functions inherited from utl::Function< Arg, Result >
Function ()
The constructor is protected to allow sub-class instances only.
virtual Result evaluate (const Arg &x) const =0
Evaluates the function for the argument x.
Protected Member Functions inherited from FunctionBase
FunctionBase ()
The constructor is protected to allow sub-class instances only.
Additional Inherited Members
Public Types inherited from utl::Function< Arg, Result >
typedef Arg Input
Input type.
typedef Result Output
Output type.
Protected Attributes inherited from utl::SpatialFunction< Real >
Real zero
Return value for default implementations of derivatives.
Protected Attributes inherited from FunctionBase
size_t ncmp
Number of components in the return value.
Detailed Description
Scalar-valued unary function of a spatial point.
Member Function Documentation
getScalarValue()
Real RealFunc::getScalarValue (const Vec3 & X) const inline override virtual
Returns a representative scalar equivalent of the function value.
Implements FunctionBase.
References utl::Function< Arg, Result >::evaluate().
getType()
unsigned char RealFunc::getType () const inline override virtual
Returns the function type flag.
Implements FunctionBase.
getValue()
std::vector< Real > RealFunc::getValue (const Vec3 & X) const inline override virtual
Returns the function value as an array.
Implements FunctionBase.
References utl::Function< Arg, Result >::evaluate().
gradient()
virtual Vec3 RealFunc::gradient (const Vec3 & X) const inline virtual
Evaluates first derivatives of the function.
Reimplemented in EvalFuncSpatial< Scalar >, EvalFuncSpatial< Scalar >, and FieldFunction.
References utl::SpatialFunction< Real >::deriv().
Referenced by EvalFuncSpatial< Scalar >::gradient().
hessian()
virtual SymmTensor RealFunc::hessian (const Vec3 & X) const inline virtual
Evaluates second derivatives of the function.
Reimplemented in EvalFuncSpatial< Scalar >, EvalFuncSpatial< Scalar >, and FieldFunction.
References utl::SpatialFunction< Real >::dderiv().
Referenced by EvalFuncSpatial< Scalar >::hessian().
The documentation for this class was generated from the following file:
/home/runner/work/IFEM-2/IFEM-2/src/Utility/Function.h