IFEM: Fields Class Reference
Fields Class Reference abstract
Base class for vector fields.
#include <Fields.h>
Public Member Functions
virtual ~Fields ()
Empty destructor.
unsigned char getNoFields () const
Returns the number of field components.
size_t getNoElm () const
Returns the number of elements.
size_t getNoNodes () const
Returns the number of nodal/control points.
const char * getFieldName () const
Returns the name of field.
virtual bool valueNode (size_t node, Vector &vals) const
Computes the value at a given node/control point.
virtual bool valueFE (const ItgPoint &x, Vector &vals) const =0
Computes the value for a given local coordinate.
virtual bool valueCoor (const Vec4 &x, Vector &vals) const
Computes the value for a given global coordinate.
virtual bool gradFE (const ItgPoint &x, Matrix &grad) const =0
Computes the gradient for a given local coordinate.
virtual bool gradCoor (const Vec4 &x, Matrix &grad) const
Computes the gradient for a given global coordinate.
virtual bool hessianFE (const ItgPoint &x, Matrix3D &H) const
Computes the hessian for a given local coordinate.
Static Public Member Functions
static Fields * create (const ASMbase *pch, const RealArray &v, char basis=1, int nf=0, const char *name=nullptr)
Creates a dynamically allocated field object.
Protected Member Functions
Fields (const char *name=nullptr)
The constructor sets the field name.
Protected Attributes
unsigned char nf
Number of field components.
size_t nelm
Number of elements/knot-spans.
size_t nno
Number of nodes/control points.
std::string fname
Name of the field.
Vector values
Field values.
Detailed Description
Base class for vector fields.
This class incapsulates the data and methods needed to store and evaluate a vector field. This is an abstract base class, and the fields associated with a specific field type are implemented as subclasses, for instance 1D, 2D and 3D spline formulations or Lagrange formulations.
Constructor & Destructor Documentation
Fields()
Fields::Fields (const char * name = nullptr) inline explicit protected
The constructor sets the field name.
Parameters
[in] name Name of field
References fname.
Member Function Documentation
create()
Fields * Fields::create (const ASMbase * pch, const RealArray & v, char basis = 1, int nf = 0, const char * name = nullptr) static
Creates a dynamically allocated field object.
Parameters
[in] pch The spline patch on which the field is to be defined on
[in] v Array of nodal/control point field values
[in] basis Basis to use from patch
[in] nf Number of components in field
[in] name Name of field
References nf.
Referenced by FieldsFuncBase::addPatchField(), and SIMdependency::extractPatchDependencies().
gradCoor()
virtual bool Fields::gradCoor (const Vec4 & x, Matrix & grad) const inline virtual
Computes the gradient for a given global coordinate.
Parameters
[in] x Global coordinate of evaluation point
[out] grad Gradient at given global coordinate
gradFE()
virtual bool Fields::gradFE (const ItgPoint & x, Matrix & grad) const pure virtual
Computes the gradient for a given local coordinate.
Parameters
[in] x Local coordinate of evaluation point
[out] grad Gradient at local point in given element
Implemented in LagrangeFields2D, LagrangeFields3D, LRSplineFields2D, LRSplineFields2Dmx, LRSplineFields3D, LRSplineFields3Dmx, SplineFields1D, SplineFields2D, SplineFields2Dmx, SplineFields3D, and SplineFields3Dmx.
hessianFE()
virtual bool Fields::hessianFE (const ItgPoint & x, Matrix3D & H) const inline virtual
Computes the hessian for a given local coordinate.
Parameters
[in] x Local coordinate of evaluation point
[out] H Hessian at local point in given element
Reimplemented in LRSplineFields2D, LRSplineFields2Dmx, LRSplineFields3D, LRSplineFields3Dmx, SplineFields1D, SplineFields2D, SplineFields2Dmx, SplineFields3D, and SplineFields3Dmx.
valueCoor()
virtual bool Fields::valueCoor (const Vec4 & x, Vector & vals) const inline virtual
Computes the value for a given global coordinate.
Parameters
[in] x Global/physical coordinate for point
[out] vals Values at given global coordinate
Reimplemented in LRSplineFields2D, LRSplineFields2Dmx, LRSplineFields3D, LRSplineFields3Dmx, SplineFields2D, SplineFields2Dmx, SplineFields3D, and SplineFields3Dmx.
valueFE()
virtual bool Fields::valueFE (const ItgPoint & x, Vector & vals) const pure virtual
Computes the value for a given local coordinate.
Parameters
[in] x Local coordinate of evaluation point
[out] vals Values at local point in given element
Implemented in LagrangeFields2D, LagrangeFields3D, LRSplineFields2D, LRSplineFields2Dmx, LRSplineFields3D, LRSplineFields3Dmx, SplineFields1D, SplineFields2D, SplineFields2Dmx, SplineFields3D, and SplineFields3Dmx.
Referenced by ASMs2D::evalProjSolution(), ASMs3D::evalProjSolution(), ASMu2D::evalProjSolution(), ASMu3D::evalProjSolution(), and ASMs1D::evalProjSolution().
valueNode()
bool Fields::valueNode (size_t node, Vector & vals) const virtual
Computes the value at a given node/control point.
Parameters
[in] node 1-based node/control point index
[out] vals Values at given node/control point
Reimplemented in LagrangeFields2D, LagrangeFields3D, LRSplineFields2D, LRSplineFields2Dmx, LRSplineFields3D, LRSplineFields3Dmx, SplineFields2D, SplineFields2Dmx, SplineFields3D, and SplineFields3Dmx.
References utl::vector< T >::fill(), nf, nno, utl::vector< T >::ptr(), utl::vector< T >::resize(), and values.
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/ASM/Fields.h
/home/runner/work/IFEM-2/IFEM-2/src/ASM/Fields.C