IFEM: DefaultGeometry3D Class Reference
DefaultGeometry3D Class Reference
Default model generator for 3D FEM simulators.
#include <ModelGenerator.h>
Public Member Functions
DefaultGeometry3D (const tinyxml2::XMLElement *geo)
The constructor forwards to the base class.
virtual ~DefaultGeometry3D ()
Empty destructor.
virtual bool createTopologySets (SIMinput &sim) const
Creates topology sets for the specified sim object.
Public Member Functions inherited from ModelGenerator
ModelGenerator (const tinyxml2::XMLElement *elem)
The constructor initializes the common members.
virtual ~ModelGenerator ()
Empty destructor.
virtual bool createGeometry (SIMinput &sim) const
Creates geometry for the specified sim object..
virtual bool createTopology (SIMinput &) const
Creates topology for multi-patch geometries.
Protected Member Functions
virtual std::string createG2 (int, bool rational=false) const
Generates the G2 description of the geometry.
Protected Member Functions inherited from ModelGenerator
bool topologySets () const
Returns true if topology sets is to be generated.
Additional Inherited Members
Protected Attributes inherited from ModelGenerator
const tinyxml2::XMLElement * geo
Pointer to XML element describing geometry.
Detailed Description
Default model generator for 3D FEM simulators.
Generates a hexahedral domain.
Member Function Documentation
createG2()
std::string DefaultGeometry3D::createG2 (int , bool rational = false) const protected virtual
Generates the G2 description of the geometry.
Reimplemented from ModelGenerator.
References IFEM::cout, ModelGenerator::geo, utl::getAttribute(), parseKnots(), Vec3::x, Vec3::y, and Vec3::z.
createTopologySets()
bool DefaultGeometry3D::createTopologySets (SIMinput & sim) const virtual
Creates topology sets for the specified sim object.
Implements ModelGenerator.
References SIMinput::topology(), and ModelGenerator::topologySets().
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/SIM/ModelGenerator.h
/home/runner/work/IFEM-2/IFEM-2/src/SIM/ModelGenerator.C