IFEM: FieldFunction Class Reference
FieldFunction Class Reference
A scalar-valued spatial function, defined through scalar fields.
#include <FieldFunctions.h>
Public Member Functions
FieldFunction (const std::string &fileName, const std::string &basisName, const std::string &fieldName, int level=0)
The constructor creates a field from the provided HDF5-file.
FieldFunction (const std::vector< Field * > &fields)
Wrap existing field.
virtual ~FieldFunction ()
Empty destructor.
bool initPatch (size_t pIdx) override
Sets the active patch.
Vec3 gradient (const Vec3 &X) const override
Evaluates first derivatives of the function.
SymmTensor hessian (const Vec3 &X) const override
Evaluates second derivatives of the function.
Public Member Functions inherited from RealFunc
unsigned char getType () const override
Returns the function type flag.
std::vector< Real > getValue (const Vec3 &X) const override
Returns the function value as an array.
Real getScalarValue (const Vec3 &X) const override
Returns a representative scalar equivalent of the function value.
Real timeDerivative (const Vec3 &X) const
Returns the time derivative of the function.
Public Member Functions inherited from utl::SpatialFunction< Real >
virtual Real deriv (const Vec3 &, int) const
Returns a first-derivative of the function.
virtual Real dderiv (const Vec3 &, int, int) const
Returns a second-derivative of the function.
Public Member Functions inherited from utl::Function< Arg, Result >
virtual ~Function ()
Empty destructor.
virtual bool isZero () const
Returns whether the function is identically zero or not.
virtual bool isConstant () const
Returns whether the function is time-independent or not.
Result operator() (const Arg &x) const
Operator returning the function value for the given argument.
Public Member Functions inherited from FunctionBase
virtual ~FunctionBase ()
Empty destructor.
size_t dim () const
Returns the number of components of the return value.
virtual bool inDomain (const Vec3 &) const
Checks if a specified point is within the function domain.
virtual void setParam (const std::string &, Real)
Sets an additional parameter in the function.
void setParam (const std::string &name, const Vec3 &value)
Sets additional parameter values in the function.
Public Member Functions inherited from FieldFuncScalarBase
FieldFuncScalarBase (const std::string &fileName, const std::string &basisName, const std::string &fieldName, int level=0)
The constructor creates a field from the provided HDF5-file.
virtual ~FieldFuncScalarBase ()
The destructor deletes the scalar fields.
Protected Member Functions
Real evaluate (const Vec3 &X) const override
Evaluates the scalar field function.
Protected Member Functions inherited from RealFunc
RealFunc ()
The constructor is protected to allow sub-class instances only.
Protected Member Functions inherited from utl::SpatialFunction< Real >
SpatialFunction (const Real &val)
The constructor is protected to allow sub-class instances only.
virtual std::vector< Real > evalGradient (const Vec3 &) const
Returns the gradient of the function as a 1D array.
virtual std::vector< Real > evalHessian (const Vec3 &) const
Returns the hessian of the function as a 1D array.
virtual std::vector< Real > evalTimeDerivative (const Vec3 &) const
Returns the time derivatives of the function as a 1D array.
Protected Member Functions inherited from utl::Function< Arg, Result >
Function ()
The constructor is protected to allow sub-class instances only.
virtual Result evaluate (const Arg &x) const =0
Evaluates the function for the argument x.
Protected Member Functions inherited from FunctionBase
FunctionBase ()
The constructor is protected to allow sub-class instances only.
Protected Member Functions inherited from FieldFuncScalarBase
FieldFuncScalarBase ()
Default constructor.
virtual void addPatchField (ASMbase *pch, const std::vector< Real > &coefs, int, int)
Adds a patch-wise field with the given coefficient values.
virtual void clearField ()
Clears the field container.
void clearFieldInt ()
Non-virtual actual implementation of clearField()
Protected Member Functions inherited from FieldFuncHDF5
FieldFuncHDF5 ()
Default constructor.
FieldFuncHDF5 (const std::string &fileName)
The constructor opens the provided HDF5-file.
FieldFuncHDF5 (const FieldFuncHDF5 &)=delete
No copying of this class.
virtual ~FieldFuncHDF5 ()
The destructor closes the HDF5-file.
bool load (const std::vector< std::string > &fieldNames, const std::string &basisName, int level, bool isScalar=false)
Loads field values for the specified time level.
int findClosestLevel (double time) const
Finds the level whose time is closest to the specified time.
Protected Member Functions inherited from FieldFuncBase
FieldFuncBase ()
Default constructor.
FieldFuncBase (const FieldFuncBase &)=delete
No copying of this class.
virtual ~FieldFuncBase ()
The destructor deletes the patches.
bool setPatch (size_t pIdx)
Sets the active patch.
Additional Inherited Members
Public Types inherited from utl::Function< Arg, Result >
typedef Arg Input
Input type.
typedef Result Output
Output type.
Protected Attributes inherited from utl::SpatialFunction< Real >
Real zero
Return value for default implementations of derivatives.
Protected Attributes inherited from FunctionBase
size_t ncmp
Number of components in the return value.
Protected Attributes inherited from FieldFuncScalarBase
int currentLevel
Current time level to evaluate at.
std::string fName
Name of field.
std::string bName
Name of basis.
std::vector< Field * > field
The scalar field to be evaluated.
Protected Attributes inherited from FieldFuncHDF5
bool hasMultipleLevels
True if we have multiple time levels.
int lastLevel
The last time level read from.
Protected Attributes inherited from FieldFuncBase
std::vector< ASMbase * > patch
The patches on which the field is defined.
size_t pidx
Current patch index.
size_t npch
Number of patches in the field.
Static Protected Attributes inherited from FieldFuncBase
static constexpr int FIXED_LEVEL = 1 << 24
Bit flag in level for using fixed.
Detailed Description
A scalar-valued spatial function, defined through scalar fields.
Constructor & Destructor Documentation
FieldFunction() [1/2]
FieldFunction::FieldFunction (const std::string & fileName, const std::string & basisName, const std::string & fieldName, int level = 0)
The constructor creates a field from the provided HDF5-file.
Parameters
[in] fileName Name of the HDF5-file
[in] basisName Name of the basis which the field values refer to
[in] fieldName Name of the field in the HDF5-file
[in] level Time level to read for
FieldFunction() [2/2]
FieldFunction::FieldFunction (const std::vector< Field * > & fields)
Wrap existing field.
Parameters
fields Field to evaluate
Takes ownership of given fields.
References FieldFuncScalarBase::currentLevel, FieldFuncScalarBase::field, FieldFuncHDF5::hasMultipleLevels, FieldFuncHDF5::lastLevel, and FieldFuncBase::npch.
Member Function Documentation
gradient()
Vec3 FieldFunction::gradient (const Vec3 & X) const override virtual
Evaluates first derivatives of the function.
Reimplemented from RealFunc.
References FieldFuncScalarBase::bName, FieldFuncScalarBase::currentLevel, FieldFuncScalarBase::field, FieldFuncHDF5::findClosestLevel(), FieldFuncScalarBase::fName, Vec4::idx, FieldFuncHDF5::load(), FieldFuncBase::pidx, utl::vector< T >::ptr(), utl::vector< T >::size(), Vec4::t, and Vec4::u.
hessian()
SymmTensor FieldFunction::hessian (const Vec3 & X) const override virtual
Evaluates second derivatives of the function.
Reimplemented from RealFunc.
References FieldFuncScalarBase::bName, utl::matrix< T >::cols(), FieldFuncScalarBase::currentLevel, FieldFuncScalarBase::field, FieldFuncHDF5::findClosestLevel(), FieldFuncScalarBase::fName, FieldFuncHDF5::load(), FieldFuncBase::pidx, utl::matrix< T >::rows(), Vec4::t, and Vec4::u.
initPatch()
bool FieldFunction::initPatch (size_t pIdx) inline override virtual
Sets the active patch.
Reimplemented from FunctionBase.
References FieldFuncBase::setPatch().
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/Utility/FieldFunctions.h
/home/runner/work/IFEM-2/IFEM-2/src/Utility/FieldFunctions.C