IFEM: SIMinput Class Reference
SIMinput Class Reference abstract
Sub-class with functionality for model input and setup.
#include <SIMinput.h>
Classes
struct ICInfo
Struct holding information about an initial condition.
Public Types
typedef std::vector< ICInfo > InitialCondVec
Convenience declaration.
typedef std::vector< unsigned char > CharVec
Convenience declaration.
typedef std::pair< int, Vec3 > IdxVec3
Convenience declaration.
Public Types inherited from SIMdependency
typedef std::vector< ASMbase * > PatchVec
Spline patch container.
Public Member Functions
virtual ~SIMinput ()
Empty destructor.
virtual const char ** getPrioritizedTags () const
Returns a list of prioritized XML-tags.
bool readTopologyOnly (const std::string &fileName)
Reads patch topology from the specified input file.
int getUniquePropertyCode (const std::string &setName, int comp=0)
Returns a unique integer code for a Property set.
size_t setVecProperty (int code, Property::Type ptype, VecFunc *field=nullptr, int pflag=-1)
Defines a vector field property.
bool setTracProperty (int code, Property::Type ptype, TractionFunc *field=nullptr)
Defines a traction field property.
size_t setPropertyType (int code, Property::Type ptype, int pindex=-1, char basis=1)
Defines the type of a property set.
bool setNeumann (const std::string &prop, const std::string &type, int ndir, int code)
Defines a Neumann boundary condition property by parsing a string.
std::vector< int > getFunctionsForElements (const std::vector< int > &elements)
Finds the set of basis functions with support on a set of elements.
bool refine (const LR::RefineData &prm)
Refines the mesh adaptively.
bool refine (const LR::RefineData &prm, Vector &sol)
Refines the mesh adaptively.
bool refine (const LR::RefineData &prm, Vectors &sol)
Refines the mesh adaptively.
int refine (const RealFunc &refC, double refTol)
Refines the mesh based on a mesh density function.
bool readPatches (std::istream &isp, const char *whiteSpace="")
Reads patches from given input stream.
bool addConnection (int mst, int slv, int mIdx, int sIdx, bool coordCheck=false, int dim=1, int thick=1)
Connects two patches.
const std::vector< ASM::Interface > & getInterfaces () const
Obtain a const reference to model topology.
int restartBasis (const std::string &restartFile, int restartStep)
Handles application restarts by reading a serialized basis.
virtual bool createFEMmodel (char resetNumb='y')
Creates the computational FEM model from the spline patches.
virtual void clonePatches (const PatchVec &, const std::map< int, int > &)
Creates the computational FEM model by copying the given patches.
virtual bool hasIC (const std::string &name) const
Checks whether a named initial condition is present.
bool setInitialConditions (SIMdependency *fieldHolder=nullptr)
Sets the initial conditions.
virtual bool deSerialize (const SerializeMap &)
Deserialization support (for simulation restart).
const TopEntity & getEntity (const std::string &name) const
Returns reference to a named topology entity.
TopEntity & topology (const std::string &name)
Returns access to a named topology entity (for model generators).
const TopologySet & getTopology () const
Returns the whole topology set container (for testing only).
bool getTopItemNodes (const TopItem &titem, std::vector< int > &glbNodes) const
Returns the node numbers associated with a topological item.
IdxVec3 * getDiscretePoint (int idx)
Returns pointer to an indexed discrete point.
virtual std::vector< std::vector< int > > getElmConnectivities () const
Returns the element-to-element connectivities.
Public Member Functions inherited from SIMbase
virtual ~SIMbase ()
The destructor frees the dynamically allocated objects.
bool readModel (const char *fileName)
Reads model data from the specified input file *fileName.
virtual void clearProperties ()
Initializes the property containers of the model.
virtual void initForSingleStep ()
Interface for app-specific single-step simulation initialisation.
virtual void initForMultiStep ()
Interface for app-specific multi-step simulation initialisation.
virtual bool preprocessC (const IntVec &ignored, bool fixDup, double time0)
Performs some pre-processing tasks on the FE model.
virtual bool merge (SIMbase *that, const std::map< int, int > *old2new=nullptr, int poff=0)
Merges the global equation system of that simulator with this.
bool initSystem (LinAlg::MatrixType mType, size_t nMats=1, size_t nVec=1, size_t nScl=0, bool withRF=false)
Allocates the system matrices of the FE problem to be solved.
bool initSystem (const SIMbase *that)
Lets this simulator share equation system with that simulator.
void initLHSbuffers ()
Initializes left-hand-side element matrix buffers for integrand.
bool setAssociatedRHS (size_t iMat, size_t iVec)
Associates a system vector to a system matrix.
bool setMode (int mode, bool needIntegr=true, bool resetSol=false)
Defines the solution mode before the element assembly is started.
void setIntegrationPrm (unsigned short int i, double prm)
Initializes an integration parameter for the integrand.
void setQuadratureRule (size_t ng, bool redimBuffers=false, bool printQP=false)
Defines the spatial numerical integration scheme to use.
virtual bool printProblem () const
Prints out problem-specific data to the log stream.
const IntegrandBase * getProblem () const
Returns a pointer to the problem-specific data object.
virtual ASM::InterfaceChecker * getInterfaceChecker (size_t) const
Returns interface checker type for model.
void clearProblem ()
Clears the reference to the problem-specific data object.
virtual std::string getName () const
Returns the name of this simulator.
virtual bool mixedProblem () const
Returns whether a mixed formulation is used (used by HDF5 output).
const LinSolParams * getSolParams () const
Returns the linear equation solver parameters (for PETSc).
virtual unsigned short int getNoParamDim () const =0
Returns the number of parameter dimensions in the model.
virtual size_t getNoSpaceDim () const
Returns the number of spatial dimensions in the model.
size_t getNoFields (int basis=0) const
Returns the number of primary solution fields.
size_t getNoDOFs (bool subSim=false) const
Returns the model size in terms of number of DOFs.
size_t getNoNodes (int basis=0) const
Returns the model size in terms of number of unique nodes.
size_t getNoElms (bool includeXelms=false, bool includeZelms=false) const
Returns the model size in terms of number of elements.
size_t getNoSolutions (bool allocated=false) const
Returns the number of solution vectors.
int getNoPatches () const
Returns the total number of patches in the model.
size_t getNoEquations () const
Returns the number of unknowns in the linear equation system.
size_t getNoConstraints () const
Returns the number of constraint equations in the model.
virtual size_t getNoRHS () const
Returns the number of right-hand-side vectors.
unsigned char getNoBasis () const
Returns the number of bases in the model.
char getNodeType (int inod) const
Returns the type (DOF classification) of the specified global node.
Vec4 getNodeCoord (int inod) const
Returns the spatial coordinates of the specified global node.
bool isFixed (int inod, int dof=123) const
Returns true if all DOFs in the specified global node are fixed.
int getGlobalNode (int node) const
Returns the global node number from a process-local node number.
int getLocalNode (int node) const
Returns the process-local node number from a global node number.
bool getElmNodes (IntVec &mnpc, int iel) const
Finds the Matrix of Nodal Point Correspondance for element iel.
void getBoundaryNodes (int pcode, IntVec &glbNodes, std::vector< Vec3 > *XYZ=nullptr) const
Finds the list of global nodes associated with a boundary.
int findClosestNode (const Vec3 &) const
Finds the node that is closest to the given point X.
IntVec getNodeSet (const std::string &setName) const
Returns a predefined node set.
bool initDirichlet (double time=0.0)
Initializes time-dependent in-homogeneous Dirichlet coefficients.
bool hasTimeDependentDirichlet () const
Checks for time-dependent in-homogeneous Dirichlet conditions.
virtual bool updateDirichlet (double time=0.0, const Vector *prevSol=nullptr, bool tangent=false)
Updates the time-dependent in-homogeneous Dirichlet coefficients.
virtual bool updateConfiguration (const Vector &)
Updates problem-dependent state based on the current solution.
virtual bool updateRotations (const RealArray &, double=0.0)
Updates the nodal rotations for problems with rotational DOFs.
bool updateGrid (const RealArray &displ)
Updates the grid coordinates.
bool updateGrid (const std::string &field)
Updates the grid coordinates.
void setRefined (int nref)
Sets the refinement status (for restart of adaptive simulations).
int getRefined () const
Returns current refinement status.
bool hasElementActivator (double t1=-1.0, double t0=0.0) const
Returns true if an element activation function is specified.
void updateForNewElements (Vector &solution, const TimeDomain &time, int verbose=0) const
Modifies the current solution vector when activating elements.
virtual bool assembleSystem (const TimeDomain &time, const Vectors &prevSol, bool newLHSmatrix=true, bool poorConvg=false)
Administers assembly of the linear equation system.
bool assembleSystem (double t0=0.0, const Vectors &pSol=Vectors())
Administers assembly of the linear equation system.
bool extractLoadVec (Vector &loadVec, size_t idx=0, const char *hd=nullptr) const
Extracts the assembled load vector for inspection/visualization.
bool extractScalars (RealArray &values) const
Extracts the assembled global scalar quantities.
double extractScalar (size_t idx=0) const
Extracts an assembled global scalar quantity.
bool applyDirichlet (Vector &glbVec) const
Applies the Dirichlet conditions to given vector.
bool solveEqSystem (Vector &solution, size_t idxRHS, double *rCond, int printSol=0, bool dumpEqSys=false, const char *compName="displacement")
Solves the assembled linear system of equations for a given load.
virtual bool solveSystem (Vector &solution, int printSol, double *rCond, const char *compName="displacement", size_t idxRHS=0)
Solves the assembled linear system of equations for a given load.
bool solveSystem (Vector &solution, int printSol=0, const char *compName="displacement")
Solves the assembled linear system of equations for a given load.
bool solveSystem (Vectors &solution, int printSol=0, const char *cmpName="displacement")
Solves a linear system of equations with multiple right-hand-sides.
void getWorstDofs (const Vector &x, const Vector &r, size_t nWorst, double eps, int iteNorm, std::map< std::pair< int, int >, RealArray > &worst) const
Finds the DOFs showing the worst convergence behavior.
virtual void iterationNorms (const Vector &x, const Vector &r, double &eNorm, double &rNorm, double &dNorm) const
Evaluates some iteration norms for convergence assessment.
double solutionNorms (const Vector &x, double *inf=nullptr, size_t *ind=nullptr, size_t nf=0, char type='D') const
Evaluates some norms of the primary solution vector.
bool solutionNorms (const TimeDomain &time, const Vectors &psol, const Vectors &ssol, Vectors &gNorm, Matrix *eNorm=nullptr, const char *name=nullptr)
Integrates some solution norm quantities.
bool solutionNorms (const TimeDomain &time, const Vectors &psol, Vectors &gNorm, Matrix *eNorm=nullptr)
Integrates some solution norm quantities.
bool solutionNorms (const Vector &psol, const Vectors &ssol, Matrix &eNorm, Vectors &gNorm, const char *name=nullptr)
Integrates some solution norm quantities.
bool solutionNorms (const Vector &psol, Matrix &eNorm, Vectors &gNorm)
Integrates some solution norm quantities.
bool solutionNorms (const Vector &psol, const Vectors &ssol, Vectors &gNorm, const char *name=nullptr)
Integrates some solution norm quantities.
virtual void printStep (int istep, const TimeDomain &time) const
Prints out load/time step identification.
virtual void printSolutionSummary (const Vector &solution, int printSol=0, const char *compName=nullptr, std::streamsize outPrec=0)
Prints a summary of the calculated solution to std::cout.
bool getCurrentReactions (RealArray &RF, const Vector &psol, int pcode=0) const
Computes the total reaction forces in the model.
bool haveReactions (int pcode=0) const
Checks for total reaction forces associated with a boundary.
virtual const RealArray * getReactionForces () const
Returns current reaction force container.
bool systemModes (std::vector< Mode > &solution, int nev, int ncv, int iop, double shift, size_t iA=0, size_t iB=1)
Performs a generalized eigenvalue analysis of the assembled system.
bool systemModes (std::vector< Mode > &solution, size_t iA=0, size_t iB=1)
Performs a generalized eigenvalue analysis of the assembled system.
virtual bool haveBoundaryReactions (bool=false) const
Returns whether reaction forces are to be computed or not.
bool assembleForces (const Vector &solution, double t0, RealArray *R, Vector *S=nullptr)
Assembles reaction and interface forces for specified boundaries.
virtual bool project (Matrix &ssol, const Vector &psol, SIMoptions::ProjectionMethod method=SIMoptions::GLOBAL, const TimeDomain &time=TimeDomain()) const
Projects the secondary solution associated with a primary solution.
bool project (Vector &ssol, const Vector &psol, SIMoptions::ProjectionMethod method=SIMoptions::GLOBAL, size_t iComp=0) const
Projects the secondary solution associated with a primary solution.
bool projectAnaSol (Vector &ssol, SIMoptions::ProjectionMethod method) const
Projects the analytical secondary solution, if any.
bool project (RealArray &values, const FunctionBase *f, int basis=1, int iField=0, int nFields=1, SIMoptions::ProjectionMethod method=SIMoptions::GLOBAL, double time=0.0) const
Projects a function onto the specified basis.
bool evalSecondarySolution (Matrix &field, int pindx) const
Evaluates the secondary solution field for specified patch.
virtual bool fieldProjections () const
Returns whether projections must be handled through fields or not.
virtual bool haveAnaSol () const
Returns whether an analytical solution is available or not.
virtual bool haveDualSol () const
Returns whether a dual solution is available or not.
NormBase * getNormIntegrand () const
Returns a pointer to a norm integrand object for this simulator.
ForceBase * getBoundaryForceIntegrand (const Vec3 *X0=nullptr) const
Returns a pointer to a force integrand object for this simulator.
ForceBase * getNodalForceIntegrand () const
Returns a pointer to a force integrand object for this simulator.
const SAM * getSAM () const
Returns a const pointer to the SAM object of this simulator.
void registerDependency (const std::string &name, SIMdependency *sim, short int nvc=1, unsigned char basis=1)
Registers a dependency on a field from another SIM object.
bool extractPatchSolution (const Vectors &sol, size_t pindx) const
Extracts all local solution vector(s) for a specified patch.
size_t extractPatchSolution (const RealArray &sol, RealArray &vec, const ASMbase *pch, unsigned char nndof=0, unsigned char basis=0) const
Extracts a local solution vector for a specified patch.
bool injectPatchSolution (RealArray &sol, const RealArray &vec, const ASMbase *pch, unsigned char nndof=0, unsigned char basis=0) const
Injects a patch-wise solution vector into the global vector.
bool extractElmRes (const Matrix &glbRes, Vector &elRes, size_t row, int pindx, std::string &name, const char *prefix=nullptr) const
Extracts element results for a specified patch.
bool extractElmRes (const Matrix &glbRes, Vector &elRes, size_t row, int pindx) const
Extracts element results for a specified patch.
bool extractElmRes (const Vector &glbRes, Vector &elRes, int pindx) const
Extracts element results for a specified patch.
int getLocalPatchIndex (int patchNo) const
Returns the local patch index for the given global patch number.
const PatchVec & getFEModel () const
Returns a const reference to our FEM model.
ASMbase * getPatch (int idx, bool glbIndex=false) const
Returns a pointer to a specified patch of our FEM model.
bool setPatchMaterial (size_t patch) const
Initializes material properties for the given patch.
const std::map< int, int > & getGlob2LocMap () const
Returns a const reference to our global-to-local node mapping.
PropertyVec::const_iterator begin_prop () const
Returns the beginning of the property array.
PropertyVec::const_iterator end_prop () const
Returns the end of the property array.
SystemMatrix * getRayleighDampingMatrix (size_t iM=1, size_t iK=0) const
Returns current Rayleigh system damping matrix.
SystemMatrix * getLHSmatrix (size_t idx=0, bool copy=false) const
Returns current system left-hand-side matrix.
SystemVector * getRHSvector (size_t idx=0, bool copy=false) const
Returns current system right-hand-side vector.
void addToRHSvector (size_t idx, const SystemVector &vec, double scale=1.0)
Adds a system vector to the given right-hand-side vector.
RealFunc * getSclFunc (int code) const
Returns a scalar function associated with code.
void setMDflag (char flag)
Sets the multi-dimension simulator sequence flag.
bool isFirst () const
Returns true, if this is the equation system owner.
void dumpEqSys (bool initialBlankLine=false)
Dumps left-hand-side matrix and right-hand-side vector to file.
void dumpSolVec (const Vector &x, bool isExpanded=true, bool expOnly=false)
Dumps a solution vector to file.
virtual int printNRforces (const IntVec &={}) const
Prints out nodal reaction forces to the log stream.
virtual void registerDependency (SIMdependency *sim, const std::string &name, short int nvc, const PatchVec &patches, char diffBasis=0, int component=1)
Registers a dependency on a field from another SIM object.
virtual void registerDependency (SIMdependency *sim, const std::string &name, short int nvc, const PatchVec &patches, const int *MADOF)
Registers a dependency on a field from another SIM object.
virtual void registerDependency (SIMdependency *sim, const std::string &name, short int nvc=1)
Registers a dependency on a field from another SIM object.
Public Member Functions inherited from SIMadmin
virtual ~SIMadmin ()
Empty destructor.
virtual bool read (const char *fileName)
Reads model data from the specified input file *fileName.
virtual bool preprocess (const IntVec &ignored={}, bool fixDup=false)
Performs some pre-processing tasks on the FE model.
const ProcessAdm & getProcessAdm () const
Returns the parallel process administrator.
int getGlobalProcessID () const
Returns the global process ID.
const std::string & getHeading () const
Returns the simulator heading.
void setHeading (const std::string &heading)
Defines the simulator heading.
void printHeading (int &supStep) const
Prints the heading of this simulator, if any, to IFEM::cout.
Public Member Functions inherited from XMLInputBase
bool readXML (const char *fileName, bool verbose=true)
Reads an XML input file.
bool loadXML (const char *xml)
Loads data from an XML-formatted text string.
Public Member Functions inherited from SIMdependency
virtual ~SIMdependency ()
Empty destructor.
bool fillField (const std::string &name, const std::vector< double > &values)
Initializes the nodal vector of named field in this SIM.
virtual std::vector< double > * getField (const std::string &name)
Returns the nodal vector of named field in this SIM.
virtual const std::vector< double > * getField (const std::string &name) const
Returns the nodal vector of named field in this SIM.
const std::vector< double > * getDependentField (const std::string &name) const
Returns the nodal vector of named field in a dependent SIM.
ASMbase * getDependentPatch (const std::string &name, int pindx) const
Returns a spline patch associated with a dependent field.
void registerField (const std::string &name, const std::vector< double > &vec)
Registers a named field with associated nodal vector in this SIM.
Protected Types
typedef std::map< std::string, std::string > SerializeMap
Convenience type.
Protected Types inherited from SIMbase
typedef std::map< int, RealFunc * > SclFuncMap
Scalar field container.
typedef std::map< int, VecFunc * > VecFuncMap
Vector field container.
typedef std::map< int, TractionFunc * > TracFuncMap
Traction field container.
typedef std::multimap< int, IntegrandBase * > IntegrandMap
Property code to integrand map.
Protected Types inherited from SIMadmin
using IntVec = std::vector< int >
Convenience alias.
Protected Member Functions
SIMinput (IntegrandBase *itg)
The constructor just forwards to the base class constructor.
virtual bool parse (char *keyWord, std::istream &is)
Parses a data section from an input stream.
virtual bool parse (const tinyxml2::XMLElement *elem)
Parses a data section from an XML document.
virtual bool parseGeometryDimTag (const tinyxml2::XMLElement *elem)=0
Parses a dimension-specific subelement of the geometry XML-tag.
bool parsePeriodic (const tinyxml2::XMLElement *elem)
Parses the periodic XML-tag.
virtual bool parseOutputTag (const tinyxml2::XMLElement *elem)
Parses a subelement of the resultoutput XML-tag.
FunctionBase * parseDualTag (const tinyxml2::XMLElement *elem, int ftype=1)
Parses the dualfield tag.
int parseMaterialSet (const tinyxml2::XMLElement *elem, int mindex)
Parses the "set" attribute of a material XML-tag.
bool parseTopologySet (const tinyxml2::XMLElement *elem, std::vector< int > &patches) const
Parses the "set" attribute of a refine/raiseorder XML-tag.
bool parsePatchList (const tinyxml2::XMLElement *elem, std::vector< int > &patches) const
Parses a list of patch indices from an XML-tag.
virtual IntFunc * parseElemActivator (const std::string &, const std::string &) const
Parses an element activation function.
bool createPropertySet (const std::string &setName, int pc)
Creates a set of Property objects.
virtual ASMbase * readPatch (std::istream &isp, int pchInd, const CharVec &unf=CharVec(), const char *whiteSpace="") const =0
Reads a patch from given input stream.
virtual bool readNodes (std::istream &isn, int pchInd, int basis=0, bool oneBased=false)
Reads global node data for a patch from given input stream.
virtual void readNodes (std::istream &isn)
Reads node numbers from given input stream.
virtual ModelGenerator * getModelGenerator (const tinyxml2::XMLElement *geo) const =0
Instantiates a FEM model generator.
virtual bool connectPatches (const ASM::Interface &ifc, bool coordCheck)=0
Connects two patches.
bool saveBasis (SerializeMap &data) const
Writes current basis to a serialization container.
bool restoreBasis (const SerializeMap &data)
Restores the basis from a serialization container.
Protected Member Functions inherited from SIMbase
SIMbase (IntegrandBase *itg)
The constructor initializes the pointers to dynamic data members.
VecFunc * getVecFunc (size_t patch, Property::Type ptype) const
Returns a vector function associated with given patch and property.
virtual bool addConstraint (int patch, int lndx, int ldim, int dirs, int code, int &ngnod, char basis=1, bool ovrD=false)
Preprocesses a user-defined Dirichlet boundary property.
virtual void preprocessA ()
Preprocessing performed before the FEM model generation.
virtual bool preprocessBeforeAsmInit (int &)
Specialized preprocessing performed before assembly initialization.
virtual bool preprocessB ()
Preprocessing performed after the system assembly initialization.
virtual void preprocessResultPoints ()=0
Preprocesses the result sampling points.
int renumberNodes (bool renumMNPC=false)
Renumbers the global node numbers after resolving patch topology.
virtual bool renumberNodes (const std::map< int, int > &)
Interface for renumbering of app-specific node number tables.
virtual bool extractPatchSolution (IntegrandBase *problem, const Vectors &sol, size_t pindx) const
Extracts all local solution vector(s) for a specified patch.
char getMDflag () const
Returns the multi-dimension simulator sequence flag.
virtual void shiftGlobalNums (int, int)
Shifts global node and element numbers by constant offsets.
virtual bool initMaterial (size_t)
Initializes material properties for integration of interior terms.
virtual bool initBodyLoad (size_t)
Initializes the body load properties for current patch.
virtual bool initNeumann (size_t)
Initializes for integration of Neumann terms for a given property.
virtual bool assembleDiscreteTerms (const IntegrandBase *, const TimeDomain &)
Assembles problem-dependent discrete terms, if any.
virtual bool assembleDiscreteItems (const IntegrandBase *itg, const TimeDomain &time, const Vectors &)
Assembles problem-dependent discrete terms, if any.
virtual double externalEnergy (const Vectors &psol, const TimeDomain &) const
Computes (possibly problem-dependent) external energy contribution.
virtual bool postProcessNorms (Vectors &, Matrix *)
Applies app-specific post-processing on norms.
void generateThreadGroups (const Property &p, bool silence=false)
Generates element groups for multi-threading of boundary integrals.
void changeNumThreads ()
Called if number of threads changes.
bool addMADOF (unsigned char basis, unsigned char nndof, bool other=true)
Adds a MADOF with an extraordinary number of DOFs on a given basis.
double * theExtEnerg ()
Returns a pointer to the external energy path integral value.
const double * getExtEnerg () const
Returns a const pointer to the external energy path integral value.
Protected Member Functions inherited from SIMadmin
SIMadmin (const char *heading=nullptr)
The default constructor initializes the process administrator.
SIMadmin (SIMadmin &anotherSIM)
Copy constructor.
Protected Member Functions inherited from XMLInputBase
const tinyxml2::XMLElement * loadFile (tinyxml2::XMLDocument &doc, const char *fileName, bool verbose=false)
Loads an XML input file into a tinyxml2::XMLDocument object.
Protected Member Functions inherited from SIMdependency
SIMdependency ()
The constructor is protected to allow sub-class instances only.
bool extractPatchDependencies (IntegrandBase *problem, const PatchVec &model, size_t pindx) const
Extracts local solution vector(s) for all dependent fields.
Static Protected Member Functions
static std::istream * getPatchStream (const char *tag, const char *patch)
Helper method returning a stream for patch geometry input.
Protected Attributes
ModelGenerator * myGen
Model generator.
TopologySet myEntitys
Set of named topological entities.
std::vector< IdxVec3 > myTopPts
Discrete points not belonging to any patch.
std::vector< ASM::Interface > myInterfaces
Topology interface descriptions.
std::map< std::string, InitialCondVec > myICs
Initial condition definitions.
Protected Attributes inherited from SIMbase
unsigned char nsd
Number of spatial dimensions.
PatchVec myModel
The actual NURBS/spline model.
PropertyVec myProps
Physical property mapping.
SclFuncMap myScalars
Scalar property fields.
VecFuncMap myVectors
Vector property fields.
TracFuncMap myTracs
Traction property fields.
IntegrandBase * myProblem
The main integrand of this simulator.
IntegrandMap myInts
Set of all integrands involved.
AnaSol * mySol
Analytical/Exact solution.
FunctionBase * dualField
Dual solution field (extraction function)
std::vector< FunctionBase * > extrFunc
Extraction functions for VCP.
int nGlbNodes
Total number of unique nodes in the model.
int isRefined
Indicates if the model is adaptively refined.
bool lagMTOK
Indicates if global multipliers is OK with multithreading.
bool fixZeros
If true, constrain zero pivots before solving.
std::vector< DumpData > lhsDump
Coefficient matrix dump specifications.
std::vector< DumpData > rhsDump
Right-hand-side vector dump specifications.
std::vector< DumpData > solDump
Solution vector dump specifications.
int nGlPatches
Number of global patches.
IntVec myPatches
Global patch numbers for current processor.
IntVec myLoc2Glb
Local-to-global node number mapping.
std::map< int, int > myGlb2Loc
Global-to-local node number mapping.
const std::map< int, int > * g2l
Pointer to global-to-local node mapping.
std::map< int, int > myDegenElm
Degenerated elements mapping.
std::set< int > myDupNodes
Set of duplicated nodes.
AlgEqSystem * myEqSys
The actual linear equation system.
SAM * mySam
Auxiliary data for FE assembly management.
LinSolParams * mySolParams
Input parameters for PETSc.
LinSolParams * myGl2Params
Input parameters for PETSc, for L2 projection.
Protected Attributes inherited from SIMadmin
ProcessAdm adm
Parallel administrator.
int myPid
Processor ID in parallel simulations.
int nProc
Number of processors in parallel simulations.
std::string myHeading
Heading written before reading the input file.
Private Member Functions
bool parseGeometryTag (const tinyxml2::XMLElement *elem)
Parses a subelement of the geometry XML-tag.
bool parseBCTag (const tinyxml2::XMLElement *elem)
Parses a subelement of the boundaryconditions XML-tag.
bool parseICTag (const tinyxml2::XMLElement *elem)
Parses the initialconditions XML-tag.
bool parseLinSolTag (const tinyxml2::XMLElement *elem)
Parses a subelement of the linearsolver XML-tag.
bool setInitialCondition (SIMdependency *fieldHolder, const std::string &fileName, const InitialCondVec &info)
Sets initial conditions from a file.
Private Attributes
bool isReading
If true, we are reading multiple patch tags.
bool isSaved
If true, the basis has been serialized.
Additional Inherited Members
Public Attributes inherited from SIMadmin
SIMoptions & opt
Simulation control parameters.
Static Public Attributes inherited from SIMbase
static bool ignoreDirichlet = false
Set to true for free vibration analysis.
static bool preserveNOrder = false
Set to true to preserve node ordering.
Static Public Attributes inherited from SIMadmin
static int msgLevel = 2
Controls the console output amount during solving.
Detailed Description
Sub-class with functionality for model input and setup.
This class extends the SIMbase class with some added functionalities for reading model definitions from input file. This also includes reading initial conditions from HDF5-files and adaptive refinement. These items are put in a separate sub-class to hide them away from the SIMbase class, which contains the actual simulation driver (i.e., the computational methods).
Member Function Documentation
addConnection()
bool SIMinput::addConnection (int mst, int slv, int mIdx, int sIdx, bool coordCheck = false, int dim = 1, int thick = 1) inline
Connects two patches.
Parameters
[in] mst Master patch
[in] slv Slave patch
[in] mIdx Boundary index on master patch
[in] sIdx Boundary index on slave patch
[in] coordCheck If true, check for matching coordinates
[in] dim Dimensionality of connection
[in] thick Thickness of connection
References connectPatches().
Referenced by MultiPatchModelGenerator1D::createTopology(), MultiPatchModelGenerator2D::createTopology(), and MultiPatchModelGenerator3D::createTopology().
clonePatches()
virtual void SIMinput::clonePatches (const PatchVec & , const std::map< int, int > &) inline virtual
Creates the computational FEM model by copying the given patches.
Reimplemented in SIM2D, and SIM3D.
connectPatches()
virtual bool SIMinput::connectPatches (const ASM::Interface & ifc, bool coordCheck) protected pure virtual
Connects two patches.
Parameters
[in] ifc Patch interface definition
[in] coordCheck If false, do not check for matching coordinates
Implemented in SIMdummy< SIMgeneric >, SIM2D, SIM3D, and SIM1D.
Referenced by addConnection().
createFEMmodel()
bool SIMinput::createFEMmodel (char resetNumb = 'y') virtual
Creates the computational FEM model from the spline patches.
Parameters
[in] resetNumb If 'y', start element and node numbers from zero
Implements SIMbase.
Reimplemented in SIMsupel, and SIMdummy< SIMgeneric >.
References IFEM::cout, SIMbase::myModel, SIMoptions::nGauss, SIMadmin::opt, and ASMbase::resetNumbering().
Referenced by MultiPatchModelGenerator1D::createTopology(), MultiPatchModelGenerator2D::createTopology(), MultiPatchModelGenerator3D::createTopology(), SIM1D::parse(), SIM2D::parse(), SIM3D::parse(), parse(), SIM1D::parseBCTag(), SIM2D::parseBCTag(), SIM3D::parseBCTag(), SIM1D::parseGeometryTag(), SIM2D::parseGeometryTag(), and SIM3D::parseGeometryTag().
createPropertySet()
bool SIMinput::createPropertySet (const std::string & setName, int pc) protected
Creates a set of Property objects.
Parameters
[in] setName Name of the topology set the property is defined on
[in] pc The property code to be associated with this set
References myEntitys, and SIMbase::myProps.
Referenced by getUniquePropertyCode().
getElmConnectivities()
IntMat SIMinput::getElmConnectivities () const virtual
Returns the element-to-element connectivities.
Implements SIMbase.
Reimplemented in SIMdummy< SIMgeneric >.
References SIMoptions::discretization, ASMbase::getElmConnectivities(), SIMbase::getNoElms(), myInterfaces, SIMbase::myModel, SIMbase::nsd, and SIMadmin::opt.
getFunctionsForElements()
IntVec SIMinput::getFunctionsForElements (const std::vector< int > & elements)
Finds the set of basis functions with support on a set of elements.
Parameters
[in] elements 0-based element indices
Returns
0-based node indices with support on the given elements
References SIMbase::myModel.
Referenced by refine().
getModelGenerator()
virtual ModelGenerator * SIMinput::getModelGenerator (const tinyxml2::XMLElement * geo) const protected pure virtual
Instantiates a FEM model generator.
Parameters
[in] geo XML element containing geometry definition
Implemented in SIMdummy< SIMgeneric >, SIM1D, SIM2D, and SIM3D.
Referenced by SIMgeneric::createDefaultModel(), and parse().
getPatchStream()
std::istream * SIMinput::getPatchStream (const char * tag, const char * patch) static protected
Helper method returning a stream for patch geometry input.
Parameters
[in] tag The XML-tag containing the patch geometry definition
[in] patch The value of the tag, either a file name or g2 string
References IFEM::cout.
Referenced by SIM1D::parseGeometryTag(), SIM2D::parseGeometryTag(), SIM3D::parseGeometryTag(), and parseGeometryTag().
getPrioritizedTags()
const char ** SIMinput::getPrioritizedTags () const virtual
Returns a list of prioritized XML-tags.
Reimplemented from XMLInputBase.
Referenced by MultiStepSIM::getPrioritizedTags().
getUniquePropertyCode()
int SIMinput::getUniquePropertyCode (const std::string & setName, int comp = 0)
Returns a unique integer code for a Property set.
Parameters
[in] setName Name of the topology set the property is defined on
[in] comp The solution components on which the property is applied
The actual Property objects are also created (one for each entity in the topology set) and their type is set to UNDEFINED. The method setPropertyType must be used to assign the actual Property type.
References createPropertySet(), and SIMbase::myProps.
Referenced by parseBCTag(), and parseMaterialSet().
hasIC()
bool SIMinput::hasIC (const std::string & name) const virtual
Checks whether a named initial condition is present.
Reimplemented from SIMdependency.
References myICs.
parse() [1/2]
bool SIMinput::parse (char * keyWord, std::istream & is) protected virtual
Parses a data section from an input stream.
Parameters
[in] keyWord Keyword of current data section to read
is The file stream to read from
Reimplemented from SIMadmin.
Reimplemented in SIM1D, SIM2D, SIM3D, SIMoutput, and SIMoutput.
References IFEM::cout, createFEMmodel(), SIMoptions::format, SIMbase::getLocalPatchIndex(), SIMbase::getNoParamDim(), SIMbase::ignoreDirichlet, Property::ldim, Property::lindx, SIMbase::myModel, SIMbase::myPatches, SIMadmin::myPid, SIMbase::myProps, SIMbase::myScalars, SIMbase::nGlPatches, SIMadmin::opt, utl::parseRealFunc(), Property::patch, Property::pindx, utl::readLine(), readNodes(), readPatch(), readPatches(), SIMoptions::saveInc, and setPropertyType().
Referenced by SIMoutput::parse().
parse() [2/2]
bool SIMinput::parse (const tinyxml2::XMLElement * elem) protected virtual
Parses a data section from an XML document.
Parameters
[in] elem The XML element to parse
Reimplemented from SIMadmin.
Reimplemented in SIM1D, SIM2D, SIM3D, SIMoutput, and SIMsupel.
References ModelGenerator::createGeometry(), ModelGenerator::createTopologySets(), SIMoptions::eig, SIMbase::fixZeros, utl::getAttribute(), IntegrandBase::getLinearSystemType(), getModelGenerator(), SIMbase::lhsDump, GlbL2::MatrixType, ASMbase::modelSize, myGen, SIMbase::myGl2Params, SIMbase::myModel, SIMbase::myPatches, SIMbase::myProblem, SIMbase::mySolParams, SIMbase::nGlPatches, noDumpDataYet, SIMadmin::opt, SIMadmin::parse(), parseBCTag(), SIMoptions::parseConsoleTag(), SIMoptions::parseDiscretizationTag(), SIMoptions::parseEigSolTag(), parseGeometryTag(), parseICTag(), parseLinSolTag(), parseOutputTag(), SIMoptions::parseRestartTag(), LinAlg::PETSC, LinSolParams::read(), SIMbase::rhsDump, SIMoptions::setLinearSolver(), GlbL2::SolverParams, LinAlg::SYMMETRIC, and LinAlg::UMFPACK.
parseElemActivator()
IntFunc * SIMinput::parseElemActivator (const std::string & , const std::string &) const protected virtual
Parses an element activation function.
The default implementation returns an identity mapping.
parseGeometryDimTag()
virtual bool SIMinput::parseGeometryDimTag (const tinyxml2::XMLElement * elem) protected pure virtual
Parses a dimension-specific subelement of the geometry XML-tag.
Implemented in SIMdummy< SIMgeneric >, SIM1D, SIM2D, and SIM3D.
Referenced by readTopologyOnly().
parseMaterialSet()
int SIMinput::parseMaterialSet (const tinyxml2::XMLElement * elem, int mindex) protected
Parses the "set" attribute of a material XML-tag.
Parameters
[in] elem The XML element extract the set name from
[in] mindex Index into problem-dependent material property container
Returns
The property code to be associated with the material
References utl::getAttribute(), getUniquePropertyCode(), and setPropertyType().
parseOutputTag()
bool SIMinput::parseOutputTag (const tinyxml2::XMLElement * elem) protected virtual
Parses a subelement of the resultoutput XML-tag.
Reimplemented in SIMoutput.
References IFEM::cout, SIMbase::DumpData::eps, SIMbase::DumpData::expand, SIMbase::DumpData::fname, SIMbase::DumpData::format, utl::getAttribute(), SIMbase::lhsDump, LinAlg::MATLAB, LinAlg::MATRIX_MARKET, noDumpDataYet, SIMadmin::opt, SIMoptions::parseOutputTag(), SIMbase::rhsDump, SIMbase::solDump, and SIMbase::DumpData::step.
Referenced by parse(), and SIMoutput::parseOutputTag().
parsePatchList()
bool SIMinput::parsePatchList (const tinyxml2::XMLElement * elem, std::vector< int > & patches) const protected
Parses a list of patch indices from an XML-tag.
Parameters
[in] elem The XML element extract the patch indices from
[in] patches List of patch indices
References utl::getAttribute(), SIMbase::myModel, and SIMbase::nGlPatches.
Referenced by parseTopologySet().
parsePeriodic()
bool SIMinput::parsePeriodic (const tinyxml2::XMLElement * elem) protected
Parses the periodic XML-tag.
This method can not be part of the SIMinput::parseGeometryTag() method, since the periodicities must be processed after the patches have been order-elevated and/or refined. The method is instead invoked from the dimension-specific sub-classes which handle the refinements.
References ASMbase::closeBoundaries(), IFEM::cout, utl::getAttribute(), SIMbase::getPatch(), and SIMbase::nGlPatches.
Referenced by SIM1D::parseGeometryTag(), SIM2D::parseGeometryTag(), and SIM3D::parseGeometryTag().
parseTopologySet()
bool SIMinput::parseTopologySet (const tinyxml2::XMLElement * elem, std::vector< int > & patches) const protected
Parses the "set" attribute of a refine/raiseorder XML-tag.
Parameters
[in] elem The XML element extract the set name from
[in] patches List of patch indices of the specified set
References utl::getAttribute(), SIMbase::getNoParamDim(), myEntitys, and parsePatchList().
Referenced by SIM1D::parseGeometryTag(), SIM2D::parseGeometryTag(), and SIM3D::parseGeometryTag().
readNodes() [1/2]
virtual void SIMinput::readNodes (std::istream & isn) inline protected virtual
Reads node numbers from given input stream.
Parameters
[in] isn The input stream to read from
Reimplemented in SIM2D, and SIM3D.
readNodes() [2/2]
virtual bool SIMinput::readNodes (std::istream & isn, int pchInd, int basis = 0, bool oneBased = false) inline protected virtual
Reads global node data for a patch from given input stream.
Parameters
[in] isn The input stream to read from
[in] pchInd 0-based index of the patch to read node data for
[in] basis The basis to read node data for (when mixed FEM, 0 = all)
[in] oneBased If true the read node numbers are assumed one-based. If false they are assumed to be zero-based.
Reimplemented in SIM2D, and SIM3D.
Referenced by parse().
readPatch()
virtual ASMbase * SIMinput::readPatch (std::istream & isp, int pchInd, const CharVec & unf = CharVec(), const char * whiteSpace = "") const protected pure virtual
Reads a patch from given input stream.
Parameters
[in] isp The input stream to read from
[in] pchInd 0-based index of the patch to read
[in] unf Number of unknowns per basis function for each field
[in] whiteSpace For message formatting
Implemented in SIMdummy< SIMgeneric >, SIMsupel, SIM1D, SIM2D, and SIM3D.
Referenced by parse(), readPatches(), and setInitialCondition().
readPatches()
bool SIMinput::readPatches (std::istream & isp, const char * whiteSpace = "")
Reads patches from given input stream.
Parameters
[in] isp The input stream to read from
[in] whiteSpace For message formatting
References IFEM::cout, SIMbase::getLocalPatchIndex(), SIMbase::myModel, SIMbase::nsd, and readPatch().
Referenced by MultiPatchModelGenerator1D::createGeometry(), MultiPatchModelGenerator2D::createGeometry(), MultiPatchModelGenerator3D::createGeometry(), ModelGenerator::createGeometry(), parse(), and parseGeometryTag().
readTopologyOnly()
bool SIMinput::readTopologyOnly (const std::string & fileName)
Reads patch topology from the specified input file.
Parameters
[in] fileName Path to XML file to read patch topology from
This method is typically invoked by coupled simulators using shared grids. It is then invoked for the simulator that owns the grid to resolve the patch topology, in case the other simulators using the grid invokes SIMbase::preprocess() first.
References XMLInputBase::loadFile(), SIMbase::nGlbNodes, parseGeometryDimTag(), and SIMbase::renumberNodes().
refine() [1/4]
bool SIMinput::refine (const LR::RefineData & prm)
Refines the mesh adaptively.
Parameters
[in] prm Input data used to control the refinement
References refine().
Referenced by AdaptiveSIM::adaptMesh(), SIM1D::parse(), refine(), refine(), refine(), and refine().
refine() [2/4]
bool SIMinput::refine (const LR::RefineData & prm, Vector & sol)
Refines the mesh adaptively.
Parameters
[in] prm Input data used to control the refinement
[in] sol Vector to interpolate onto refined mesh
References utl::vector< T >::empty(), refine(), and utl::vector< T >::swap().
refine() [3/4]
bool SIMinput::refine (const LR::RefineData & prm, Vectors & sol)
Refines the mesh adaptively.
Parameters
[in] prm Input data used to control the refinement
[in] sol Vectors to interpolate onto refined mesh
References LR::RefineData::elements, LR::RefineData::errors, SIMbase::extractPatchSolution(), utl::findIndex(), SIMbase::getNoNodes(), SIMbase::getPatch(), SIMbase::isRefined, isSaved, ASMbase::isShared(), LR::RefineData::MLGN, SIMbase::myModel, SIMbase::nGlPatches, and refine().
refine() [4/4]
int SIMinput::refine (const RealFunc & refC, double refTol)
Refines the mesh based on a mesh density function.
Parameters
[in] refC Mesh refinement criteria function
[in] refTol Mesh refinement threshold
Returns
Positive value on refinement, negative value on error, zero if no elements are refined
Refines all elements for which refC(X0) < refTol, where X0 is the element center.
References LR::RefineData::elements, ASMbase::generateFEMTopology(), ASMbase::getElmID(), getFunctionsForElements(), ASMbase::getNoElms(), SIMbase::isRefined, SIMbase::myModel, SIMbase::nGlPatches, LR::RefineData::options, refine(), and ASMbase::resetNumbering().
restartBasis()
int SIMinput::restartBasis (const std::string & restartFile, int restartStep)
Handles application restarts by reading a serialized basis.
Parameters
[in] restartFile Path to file to read restart basis from
[in] restartStep Index of the time step to read restart basis for
Returns
One-based index of the first time step to solve after restart. If zero, no restart specified. If one, no serialized basis stored. If negative, read failure.
References IFEM::cout, SIMbase::getName(), HDF5Restart::readData(), and restoreBasis().
restoreBasis()
bool SIMinput::restoreBasis (const SerializeMap & data) protected
Restores the basis from a serialization container.
Parameters
[in] data Container for serialized data
References IFEM::cout, SIMbase::getName(), SIMbase::isRefined, SIMbase::myModel, SIMbase::myPatches, and SIMbase::nGlPatches.
Referenced by restartBasis().
saveBasis()
bool SIMinput::saveBasis (SerializeMap & data) const protected
Writes current basis to a serialization container.
Parameters
data Container for serialized data
References IFEM::cout, ASMbase::getMinimumSize(), SIMbase::getName(), SIMbase::isRefined, isSaved, SIMbase::myModel, and ASMbase::write().
setInitialCondition()
bool SIMinput::setInitialCondition (SIMdependency * fieldHolder, const std::string & fileName, const InitialCondVec & info) private
Sets initial conditions from a file.
Parameters
fieldHolder The SIM-object to inject the initial conditions into
[in] fileName Path to file to read the initial conditions from
[in] info Initial condition information
References SIMadmin::adm, ProcessAdm::broadcast(), ProcessAdm::dd, ASMbase::evaluate(), SIMdependency::getField(), HDF5Reader::getFieldSize(), SIMbase::getLocalPatchIndex(), SIMbase::getNoFields(), ASMbase::getNoNodes(), ProcessAdm::getProcId(), ASMbase::injectNodeVec(), DomainDecomposition::isPartitioned(), SIMbase::myModel, readPatch(), HDF5Reader::readString(), HDF5Reader::readVector(), and utl::vector< T >::size().
Referenced by setInitialConditions().
setInitialConditions()
bool SIMinput::setInitialConditions (SIMdependency * fieldHolder = nullptr)
Sets the initial conditions.
Parameters
fieldHolder The SIM-object to inject the initial conditions into, nullptr means this.
References IFEM::cout, SIMdependency::getField(), myICs, utl::parseRealFunc(), SIMbase::project(), and setInitialCondition().
setNeumann()
bool SIMinput::setNeumann (const std::string & prop, const std::string & type, int ndir, int code)
Defines a Neumann boundary condition property by parsing a string.
Parameters
[in] prop The string to parse the property definition from
[in] type Additional option defining the type of property definition
[in] ndir Direction of the surface traction on the Neumann boundary
[in] code The property code to be associated with this property
References SIMbase::getNoFields(), SIMbase::myScalars, SIMbase::myTracs, SIMbase::myVectors, SIMbase::nsd, utl::parseRealFunc(), utl::parseTracFunc(), utl::parseVecFunc(), and setPropertyType().
Referenced by parseBCTag().
setPropertyType()
size_t SIMinput::setPropertyType (int code, Property::Type ptype, int pindex = -1, char basis = 1)
Defines the type of a property set.
Parameters
[in] code The property code to be associated with the property type
[in] ptype The property type to be associated with the given code
[in] pindex 0-based index into problem-dependent property container
[in] basis 1-based index into basis associated with property
Negative values on pindex are used to flag the use of local axes for Dirichlet boundary conditions as follows: pindex=-2 : Compute local axes directions directly at the Greville points. pindex=-3 : Compute local axes directions by projecting the local tangent direction onto the spline basis, to obtain directions at control points.
References ASMbase::getNoParamDim(), SIMbase::getPatch(), LOCAL_AXES, LOCAL_PROJECTED, SIMbase::myModel, SIMbase::myProps, and SIMbase::preserveNOrder.
Referenced by parse(), parseBCTag(), parseMaterialSet(), setNeumann(), setTracProperty(), and setVecProperty().
setTracProperty()
bool SIMinput::setTracProperty (int code, Property::Type ptype, TractionFunc * field = nullptr)
Defines a traction field property.
Parameters
[in] code The property code to be associated with the property
[in] ptype The property type to be associated with the given code
[in] field The traction field representing the physical property
References SIMbase::myTracs, and setPropertyType().
setVecProperty()
size_t SIMinput::setVecProperty (int code, Property::Type ptype, VecFunc * field = nullptr, int pflag = -1)
Defines a vector field property.
Parameters
[in] code The property code to be associated with the property
[in] ptype The property type to be associated with the given code
[in] field The vector field representing the physical property
[in] pflag Flag for local axis directions (see setPropertyType)
References SIMbase::myVectors, and setPropertyType().
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/SIM/SIMinput.h
/home/runner/work/IFEM-2/IFEM-2/src/SIM/SIMinput.C