IFEM: XMLInputBase Class Reference
XMLInputBase Class Reference abstract
Base class for XML based input file parsing.
#include <XMLInputBase.h>
Public Member Functions
bool readXML (const char *fileName, bool verbose=true)
Reads an XML input file.
bool loadXML (const char *xml)
Loads data from an XML-formatted text string.
Protected Member Functions
const tinyxml2::XMLElement * loadFile (tinyxml2::XMLDocument &doc, const char *fileName, bool verbose=false)
Loads an XML input file into a tinyxml2::XMLDocument object.
virtual bool parse (const tinyxml2::XMLElement *elem)=0
Parses a data section from an XML element.
virtual const char ** getPrioritizedTags () const
Returns a list of prioritized XML-tags.
Private Member Functions
bool handlePriorityTags (const tinyxml2::XMLElement *base, std::vector< const tinyxml2::XMLElement * > &parsed, bool verbose)
Handles the parsing order for certain XML-tags.
Detailed Description
Base class for XML based input file parsing.
This class is inherited by SIMadmin for input parsing handling, and can also be used by applications for pre-parsing of the input file.
Member Function Documentation
getPrioritizedTags()
virtual const char ** XMLInputBase::getPrioritizedTags () const inline protected virtual
Returns a list of prioritized XML-tags.
Reimplemented in MultiStepSIM, and SIMinput.
Referenced by handlePriorityTags().
handlePriorityTags()
bool XMLInputBase::handlePriorityTags (const tinyxml2::XMLElement * base, std::vector< const tinyxml2::XMLElement * > & parsed, bool verbose) private
Handles the parsing order for certain XML-tags.
Parameters
[in] base The base tag containing the elements to be prioritized
[out] parsed Vector of XML-elements that was parsed
[in] verbose If true, print the tags being parsed
Certain tags need to be parsed before others. This method takes care of this. It is called by the readXML() method in order to read the top level tags in the required order. It can also be called by the application-specific SIM class prior to parsing its data blocks. In that case the getPrioritizedTags() method should be reimplemented by the sub-class to take care of the application-specific tags.
References IFEM::cout, getPrioritizedTags(), and parse().
Referenced by readXML().
loadFile()
const tinyxml2::XMLElement * XMLInputBase::loadFile (tinyxml2::XMLDocument & doc, const char * fileName, bool verbose = false) protected
Loads an XML input file into a tinyxml2::XMLDocument object.
Parameters
[out] doc The top-level node of the XML-file
[in] fileName File to read
[in] verbose If true, print the file(s) being read
Returns
Pointer to the root element of the XML-file
References IFEM::cout.
Referenced by SIMinput::readTopologyOnly(), and readXML().
loadXML()
bool XMLInputBase::loadXML (const char * xml)
Loads data from an XML-formatted text string.
This method is a convenience offered for unit testing only.
References parse().
parse()
virtual bool XMLInputBase::parse (const tinyxml2::XMLElement * elem) protected pure virtual
Parses a data section from an XML element.
Implemented in SIMSemi3D< PlaneSolver >, SIMSolver< T1 >, SIMSolverAdapImpl< T1, AdapSim >, SIMSolverTS< T1 >, AdaptiveSIM, EigenModeSIM, EigenModeSIM, GenAlphaSIM, GenAlphaSIM, HHTSIM, HHTSIM, MultiStepSIM, MultiStepSIM, NewmarkNLSIM, NewmarkNLSIM, NewmarkSIM, NewmarkSIM, NewmarkSIM, NonLinSIM, SIM1D, SIM2D, SIM3D, SIMadmin, SIMinput, SIMmultiCpl, SIMmultiCpl, SIMoutput, SIMsupel, SIMSemi3D< PlaneSolver >, SIMSolverAdapInternal< T1 >, and SIMargsBase.
Referenced by handlePriorityTags(), loadXML(), and readXML().
readXML()
bool XMLInputBase::readXML (const char * fileName, bool verbose = true)
Reads an XML input file.
Parameters
[in] fileName File to read
[in] verbose If true, print the tags being parsed
References IFEM::cout, handlePriorityTags(), loadFile(), and parse().
Referenced by SIMadmin::read().
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/SIM/XMLInputBase.h
/home/runner/work/IFEM-2/IFEM-2/src/SIM/XMLInputBase.C