IFEM: TimeIntegration::SIMExplicitRKE< Solver > Class Template Reference
TimeIntegration::SIMExplicitRKE< Solver > Class Template Reference
Explicit embedded Runge-Kutta based time stepping for SIM classes.
#include <SIMExplicitRKE.h>
Public Member Functions
SIMExplicitRKE (Solver &solv, Method type, double tol)
Constructor.
bool solveStep (TimeStep &tp) override
Computes the solution for the current time step.
Public Member Functions inherited from TimeIntegration::SIMExplicitRK< Solver >
SIMExplicitRK (Solver &solv, Method type, bool standalone=true)
Constructor.
const ProcessAdm & getProcessAdm () const
Returns the parallel process administrator.
bool solveRK (Vectors &stages, const TimeStep &tp)
Applies the Runge-Kutta scheme.
bool advanceStep (TimeStep &tp)
Advances the time step one step forward.
bool saveModel (char *fileName, int &geoBlk, int &nBlock)
Opens a new VTF-file and writes the model geometry to it.
bool saveStep (const TimeStep &tp, int &nBlock)
Saves the converged results of a given time step to VTF file.
void registerFields (DataExporter &exporter)
Registers fields for output to a data exporter.
bool serialize (std::map< std::string, std::string > &data)
Serialize internal state for restarting purposes.
bool deSerialize (const std::map< std::string, std::string > &data)
Set internal state from a serialized state.
void setLinear (bool enable)
Mark operator as linear to avoid repeated assembly and factorization.
Private Attributes
RealArray bs
Runge-Kutta coefficients for embedded method.
double errTol
Truncation error tolerance.
Additional Inherited Members
Protected Attributes inherited from TimeIntegration::SIMExplicitRK< Solver >
Solver & solver
Reference to simulator.
RKTableaux RK
Tableaux of Runge-Kutta coefficients.
bool alone
If true, this is a standalone solver.
bool linear = false
If true operators are constant.
bool assemble = true
If true, assemble operators.
Detailed Description
template<class Solver>
class TimeIntegration::SIMExplicitRKE< Solver >
Explicit embedded Runge-Kutta based time stepping for SIM classes.
Template can be instanced over any SIM implementing ISolver, and which derive from SIMbase.
Constructor & Destructor Documentation
SIMExplicitRKE()
template<class Solver > TimeIntegration::SIMExplicitRKE< Solver >::SIMExplicitRKE (Solver & solv, Method type, double tol) inline
Constructor.
Parameters
solv The simulator to do time stepping for
type The Runge-Kutta scheme to use
tol Tolerance for ERK truncation error control
References TimeIntegration::RKTableaux::A, TimeIntegration::RKTableaux::b, TimeIntegration::BOGACKISHAMPINE, TimeIntegration::SIMExplicitRKE< Solver >::bs, TimeIntegration::RKTableaux::c, TimeIntegration::FEHLBERG, TimeIntegration::HEUNEULER, TimeIntegration::RKTableaux::order, utl::matrix< T >::resize(), and TimeIntegration::SIMExplicitRK< Solver >::RK.
Member Function Documentation
solveStep()
template<class Solver > bool TimeIntegration::SIMExplicitRKE< Solver >::solveStep (TimeStep & tp) inline override virtual
Computes the solution for the current time step.
Reimplemented from TimeIntegration::SIMExplicitRK< Solver >.
References TimeIntegration::SIMExplicitRK< Solver >::assemble, TimeIntegration::SIMExplicitRKE< Solver >::bs, TimeStep::cutback(), TimeDomain::dt, error(), TimeIntegration::SIMExplicitRKE< Solver >::errTol, TimeIntegration::RKTableaux::order, TimeIntegration::SIMExplicitRK< Solver >::RK, TimeIntegration::SIMExplicitRK< Solver >::solver, TimeIntegration::SIMExplicitRK< Solver >::solveRK(), TimeStep::step, TimeDomain::t, and TimeStep::time.
The documentation for this class was generated from the following file:
/home/runner/work/IFEM-2/IFEM-2/Apps/Utils/SIMExplicitRKE.h