IFEM: IFEM Class Reference
IFEM Class Reference
Class holding global IFEM configuration.
#include <IFEM.h>
Static Public Member Functions
static int Init (int arg_c, char **arg_v, const char *title=nullptr, bool silent=false)
Initializes the IFEM library.
static void Close ()
Closes the IFEM library.
static void applyCommandLineOptions (SIMoptions &opt)
Applies command-line argument values to the general input options.
static SIMoptions & getOptions ()
Returns a reference to the general input options.
static void registerCallback (ControlCallback &cb)
Registers a fifo instruction callback.
static bool pollControllerFifo ()
Polls the control fifo for instructions.
Static Public Attributes
static utl::LogStream cout
Combined standard out for parallel processes.
static std::shared_ptr< std::ostringstream > memoryLog
Logging data stored in memory.
Static Private Attributes
static SIMoptions cmdOptions
General input options.
static int argc = 0
The number of command-line arguments.
static char ** argv = nullptr
The command-line arguments.
static ControlFIFO * fifo = nullptr
Control fifo helper.
Detailed Description
Class holding global IFEM configuration.
Member Function Documentation
Init()
int IFEM::Init (int arg_c, char ** arg_v, const char * title = nullptr, bool silent = false) static
Initializes the IFEM library.
Parameters
[in] arg_c The number of command-line arguments
[in] arg_v The command-line arguments
[in] title The title of the IFEM simulator
[in] silent True to suppress output
Returns
The MPI process ID
References utl::LogStream::addExtraLog(), argc, argv, cmdOptions, cout, fifo, IFEM_VERSION_STRING, LinAlgInit::increfs(), LinAlgInit::Init(), memoryLog, LinAlgInit::myPid, ControlFIFO::open(), SIMoptions::parseOldOptions(), and utl::LogStream::setPIDs().
Referenced by main().
The documentation for this class was generated from the following files:
IFEM.h
/home/runner/work/IFEM-2/IFEM-2/src/IFEM.C