IFEM: ASMs3Dmx Class Reference
ASMs3Dmx Class Reference
Driver for assembly of structured 3D spline mixed FE models.
#include <ASMs3Dmx.h>
Public Member Functions
ASMs3Dmx (const CharVec &n_f)
The constructor initializes the dimension of each basis.
ASMs3Dmx (const ASMs3Dmx &patch, const CharVec &n_f=CharVec(2, 0))
Copy constructor.
virtual ~ASMs3Dmx ()=default
Empty Destructor.
virtual const Go::SplineVolume * getBasis (int basis=1) const
Returns the spline surface representing a basis of this patch.
virtual Go::SplineVolume * getBasis (int basis=1)
Returns the spline surface representing a basis of this patch.
virtual Go::SplineSurface * getBoundary (int dir, int basis=1)
Returns the spline curve representing a boundary of this patch.
virtual bool generateFEMTopology ()
Generates the finite element topology data for the patch.
virtual void clear (bool retainGeometry)
Clears the contents of the patch, making it empty.
virtual Vec3 getCoord (size_t inod) const
Returns the global coordinates for the given node.
virtual bool readBasis (std::istream &is, size_t basis)
Reads a basis from the given input stream.
virtual size_t getNoBasis () const
Returns the number of bases.
virtual size_t getNoNodes (int basis) const
Returns the total number of nodes in this patch.
virtual unsigned char getNoFields (int basis) const
Returns the number of solution fields.
virtual unsigned char getNodalDOFs (size_t inod) const
Returns the number of DOFs per node.
virtual char getNodeType (size_t inod) const
Returns the classification of a node.
virtual void initMADOF (const int *sysMadof)
Initializes the patch level MADOF array for mixed problems.
virtual bool connectPatch (int face, ASM3D &neighbor, int nface, int norient, int basis, bool coordCheck, int thick)
Connects all matching nodes on two adjacent boundary faces.
virtual void closeBoundaries (int dir, int, int)
Makes two opposite boundary faces periodic.
virtual bool integrate (Integrand &integrand, GlobalIntegral &glbInt, const TimeDomain &time)
Evaluates an integral over the interior patch domain.
virtual bool integrate (Integrand &integrand, int lIndex, GlobalIntegral &glbInt, const TimeDomain &time)
Evaluates a boundary integral over a patch edge.
virtual bool integrate (Integrand &integrand, GlobalIntegral &glbInt, const TimeDomain &time, const ASM::InterfaceChecker &iChk)
Evaluates an integral over element interfaces in the patch.
virtual int evalPoint (const double *xi, double *param, Vec3 &X) const
Evaluates the geometry at a specified point.
virtual bool getSolution (Matrix &sField, const Vector &locSol, const IntVec &nodes) const
Extract the primary solution field at the specified nodes.
virtual bool evalSolution (Matrix &sField, const Vector &locSol, const RealArray *gpar, bool regular, int deriv, int nf) const
Evaluates the primary solution field at the given points.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const RealArray *gpar, bool regular) const
Evaluates the secondary solution field at the given points.
virtual bool separateProjectionBasis () const
Checks if a separate projection basis is used for this patch.
virtual void extractNodeVec (const RealArray &globVec, RealArray &nodeVec, unsigned char, int basis) const
Extracts nodal results for this patch from the global vector.
virtual bool injectNodeVec (const RealArray &nodeVec, RealArray &globVec, unsigned char, int basis) const
Injects nodal results for this patch into a global vector.
virtual void generateThreadGroups (const Integrand &integrand, bool silence, bool ignoreGlobalLM)
Generates element groups for multi-threading of interior integrals.
virtual void generateThreadGroups (char lIndex, bool silence, bool)
Generates element groups for multi-threading of boundary integrals.
virtual bool getSize (int &n1, int &n2, int &n3, int basis) const
Returns the number of nodal points in each parameter direction.
virtual bool evalSolution (Matrix &sField, const Vector &locSol, const int *npe, int n_f, bool piola) const
Evaluates the primary solution field at all visualization points.
virtual bool evalSolution (Matrix &sField, const Vector &locSol, const RealArray *gpar, bool regular=true, int deriv=0, int=0) const
Evaluates the primary solution field at the given points.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const int *npe=nullptr, char project=0) const
Evaluates the secondary solution field at all visualization points.
virtual Go::GeomObject * evalSolution (const IntegrandBase &integrand) const
Projects the secondary solution field onto the primary basis.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const RealArray *gpar, bool regular=true) const
Evaluates the secondary solution field at the given points.
Public Member Functions inherited from ASMs3D
ASMs3D (unsigned char n_f=3)
Default constructor.
ASMs3D (const ASMs3D &patch, unsigned char n_f)
Special copy constructor for sharing of FE data.
ASMs3D (const ASMs3D &patch)
Default copy constructor copying everything.
virtual void copyParameterDomain (const ASMbase *other)
Copies the parameter domain from the other patch.
virtual bool read (std::istream &)
Creates an instance by reading the given input stream.
virtual bool write (std::ostream &, int) const
Writes the geometry of the SplineVolume object to given stream.
virtual bool addXElms (short int dim, short int item, size_t nXn, IntVec &nodes)
Adds extraordinary elements associated with a patch boundary.
virtual size_t getNodeIndex (int globalNum, bool noAddedNodes=false) const
Returns local 1-based index of the node with given global number.
virtual int getNodeID (size_t inod, bool noAddedNodes=false) const
Returns the global node number for the given node.
virtual bool getElementCoordinates (Matrix &X, int iel, bool forceItg=false) const
Returns a matrix with nodal coordinates for an element.
virtual void getNodalCoordinates (Matrix &X, bool geo=false) const
Returns a matrix with all nodal coordinates within the patch.
virtual Vec3 getElementCenter (int iel) const
Returns the coordinate of the element center.
virtual bool updateCoords (const Vector &displ)
Updates the nodal coordinates for this patch.
virtual void getBoundary1Nodes (int lEdge, IntVec &nodes, int basis, int=0, bool local=false, bool open=false) const
Finds the global (or patch-local) node numbers on a patch boundary.
virtual int getCorner (int I, int J, int K, int basis) const
Returns the node index for a given corner.
bool assignNodeNumbers (BlockNodes &nodes, int basis=0)
Assigns new global node numbers for all nodes of the patch.
virtual bool checkRightHandSystem ()
Checks that the patch is modelled in a right-hand-side system.
virtual bool refine (int dir, const RealArray &xi)
Refines the parametrization by inserting extra knots.
virtual bool uniformRefine (int dir, int nInsert)
Refines the parametrization by inserting extra knots uniformly.
virtual bool raiseOrder (int ru, int rv, int rw, bool setOrder=false)
Raises the order of the SplineVolume object for this patch.
virtual bool createProjectionBasis (bool init)
Creates a separate projection basis for this patch.
virtual void constrainFace (int dir, bool open, int dof, int code=0, char basis=1)
Constrains all DOFs on a given boundary face.
virtual size_t constrainFaceLocal (int dir, bool open, int dof, int code=0, bool project=false, char T1='\0')
Constrains all DOFs in local directions on a given boundary face.
virtual void constrainEdge (int lEdge, bool open, int dof, int code=0, char basis=1)
Constrains all DOFs on a given boundary edge.
virtual void constrainLine (int fdir, int ldir, double xi, int dof, int code=0, char basis=1)
Constrains all DOFs along a line on a given boundary face.
virtual void constrainCorner (int I, int J, int K, int dof, int code=0, char basis=1)
Constrains a corner node identified by the three parameter indices.
virtual void constrainNode (double xi, double eta, double zeta, int dof, int code=0)
Constrains a node identified by three relative parameter values.
virtual bool collapseFace (int face, int edge=0, int basis=1)
Collapses a degenerated face into a single node or edge.
virtual bool addRigidCpl (int lindx, int ldim, int basis, int &gMaster, const Vec3 &Xmaster, bool extraPt)
Adds MPCs representing a rigid coupling to this patch.
virtual void setNodeNumbers (const IntVec &nodes)
Sets the global node numbers for this patch.
virtual bool updateDirichlet (const std::map< int, RealFunc * > &func, const std::map< int, VecFunc * > &vfunc, double time, const std::map< int, int > *g2l, bool tangent)
Updates the time-dependent in-homogeneous Dirichlet coefficients.
virtual bool selfInterconnect (const std::vector< Ipair > &nodes, double xtol)
Connects a list of node pairs to each other.
virtual bool integrateEdge (Integrand &integrand, int lEdge, GlobalIntegral &glbInt, const TimeDomain &time)
Evaluates a boundary integral over a patch edge.
virtual int findElementContaining (const double *param) const
Returns the element that contains a specified spatial point.
virtual double findPoint (Vec3 &X, double *param) const
Searches for the specified Cartesian point in the patch.
virtual bool getGridParameters (RealArray &prm, int dir, int nSegSpan) const
Calculates parameter values for visualization nodal points.
virtual bool tesselate (ElementBlock &grid, const int *npe) const
Creates a hexahedron element model of this patch for visualization.
virtual bool evalProjSolution (Matrix &sField, const Vector &locSol, const int *npe, int n_f) const
Evaluates the projected solution field at all visualization points.
virtual bool evaluate (const ASMbase *basis, const Vector &locVec, RealArray &vec, int basisNum) const
Evaluates and interpolates a field over a given geometry.
virtual bool evaluate (const Field *field, RealArray &vec, int basisNum) const
Evaluates and interpolates a field over a given geometry.
virtual bool evaluate (const FunctionBase *func, RealArray &vec, int basisNum, double time) const
Evaluates and interpolates a function over a given geometry.
virtual void generateThreadGroupsFromElms (const IntVec &elms)
Generates element groups from a partition.
virtual void generateProjThreadGroupsFromElms (const IntVec &elms)
Generate element groups from a partition.
virtual bool getOrder (int &p1, int &p2, int &p3) const
Returns the polynomial order in each parameter direction.
virtual bool getNoStructElms (int &n1, int &n2, int &n3) const
Returns the number of elements in each parameter direction.
virtual void getElmConnectivities (IntMat &neigh, int basis=ASM::INTEGRATION_BASIS) const
Calculates the matrix of element neighbour connectivities.
virtual IntMat getElmNodes (int basis) const
Returns the matrix of nodal point correspondance for given basis.
virtual size_t getNoBoundaryElms (char lIndex, char ldim) const
Returns the number of elements on a boundary.
virtual size_t getNoProjectionNodes () const
Returns the number of projection nodes for this patch.
virtual bool getParameterDomain (Real2DMat &u, IntVec *corners) const
Returns parameter values and node numbers of the domain corners.
virtual void evaluateBasis (double u, double v, double w, Vector &N) const
Evaluates the basis functions at the specified point.
void extractBasis (double u, double v, double w, Vector &N, Matrix &dNdu, bool fromRight=true) const
Establishes matrices with basis functions and 1st derivatives.
void extractBasis (double u, double v, double w, Vector &N, Matrix &dNdu, Matrix3D &d2Ndu2, bool fromRight=true) const
Establishes matrices with basis functions, 1st and 2nd derivatives.
void extractBasis (double u, double v, double w, int dir, int p, Vector &dN, bool fromRight=true) const
Establishes a vector with basis function derivatives.
virtual Field * getProjectedField (const Vector &coefs) const
Returns a field using the projection basis.
virtual Fields * getProjectedFields (const Vector &coefs, size_t=0) const
Returns a field using the projection basis.
Public Member Functions inherited from ASMstruct
virtual ~ASMstruct ()
The destructor frees the dynamically allocated spline objects.
virtual bool empty () const
Checks if the patch is empty.
virtual bool diracPoint (Integrand &integr, GlobalIntegral &glInt, const double *u, const Vec3 &pval)
Integrates a spatial dirac-delta function over a patch.
virtual void swapProjectionBasis ()
Swaps between the first and second projection basis.
virtual bool evalSolution (Matrix &sField, const Vector &locSol, const int *npe, int n_f=0, bool piola=false) const
Evaluates the primary solution field at all visualization points.
virtual bool evalSolution (Matrix &sField, const Vector &locSol, const RealArray *gpar, bool regular=true, int deriv=0, int n_f=0) const
Evaluates the primary solution field at the given points.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const int *npe=nullptr, char project=0) const
Evaluates the secondary solution field at all visualization points.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const RealArray *gpar, bool regular=true) const
Evaluates the secondary solution field at the given points.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const IntVec &elements) const
Evaluates the secondary solution field at element centers.
Public Member Functions inherited from ASMbase
virtual ~ASMbase ()
The destructor frees the dynamically allocated data objects.
ASMbase * cloneUnShared () const
Returns a copy of this patch with identical FE discretization.
virtual void addHole (double, double, double)
Adds a circular immersed boundary in the physical geometry.
virtual void addHole (double, double, double, double, double)
Adds an oval immersed boundary in the physical geometry.
virtual bool setGeometry (RealFunc *, double, double)
Defines the immersed geometry from a scalar function.
bool addLagrangeMultipliers (size_t iel, const IntVec &mGLag, unsigned char nnLag=1)
Adds a set of Lagrange multipliers to the specified element.
bool addGlobalLagrangeMultipliers (const IntVec &mGLag, unsigned char nnLag=1)
Adds global Lagrange multipliers to the system.
virtual void setGauss (int ng)
Defines the numerical integration scheme nGauss in the patch.
void setNoFields (unsigned char n)
Defines the number of solution fields in the patch.
void setElementActivator (IntFunc *efunc)
Sets the element activation function.
const IntFunc * getElementActivator () const
Returns a pointer to the element activation function.
virtual void setMinimumSize (double)
Sets the minimum element size for adaptive refinement.
virtual double getMinimumSize (int=0) const
Defines the minimum element size for adaptive refinement.
virtual bool checkElementSize (int, bool=true) const
Checks if the specified element is larger than the minimum size.
unsigned char getNoSpaceDim () const
Returns the number of spatial dimensions.
unsigned char getNoParamDim () const
Returns the number of parameter dimensions.
unsigned char getNoLagPerNode () const
Returns the number of Lagrange multipliers per node.
size_t getElmIndex (int globalNum) const
Returns local 1-based index of element with given global number.
int getElmID (size_t iel) const
Returns the global element number for the given element.
bool isLMn (size_t n) const
Returns true if node n is a Lagrange multiplier node.
bool isRMn (size_t n) const
Returns true if node n is a master node of a rigid coupling.
char getLMType (size_t inod) const
Returns the type of a Lagrange multiplier node.
void getBoundaryElms (int lIndex, IntVec &elms, int orient=-1, bool local=false) const
Finds the global (or patch-local) element numbers on a boundary.
int getNodeSetIdx (const std::string &setName) const
Returns (1-based) index of a predefined node set in the patch.
const IntVec & getNodeSet (int iset) const
Returns an indexed predefined node set.
IntVec & getNodeSet (const std::string &setName, int &idx)
Returns a named node set for update.
bool isInNodeSet (int iset, int inod) const
Checks if node inod is within predefined node set iset.
int parseNodeSet (const std::string &setName, const char *cset, bool assumeZeroBased=false)
Defines a node set by parsing a list of node numbers.
virtual int parseNodeBox (const std::string &, const char *)
Defines a node set by parsing a 3D bounding box.
void convertNodeSets ()
Converts node number sets to internal (1-based) node indices.
virtual int getElementSetIdx (const std::string &) const
Returns (1-based) index of a predefined element set in the patch.
virtual const IntVec & getElementSet (int) const
Returns an indexed predefined element set.
virtual bool getElementSet (int, std::string &) const
Returns the name of an indexed predefined element set.
virtual bool isInElementSet (int, int) const
Checks if an element is within a predefined element set.
virtual int parseElemSet (const std::string &, const char *)
Defines an element set by parsing a list of element numbers.
virtual int parseElemBox (const std::string &, const std::string &, const char *)
Defines an element set by parsing a 3D bounding box.
virtual std::pair< size_t, double > findClosestNode (const Vec3 &) const
Finds the node that is closest to the given point.
void printNodes (std::ostream &os) const
Prints out the nodal coordinates of this patch to the given stream.
void printElements (std::ostream &os) const
Prints out element connections of this patch to the given stream.
virtual void printElmInfo (int, const IntegrandBase *) const
Prints out additional app-dependent element information.
virtual void shiftGlobalNodeNums (int nshift)
Increase all global node numbers by nshift.
void setGlobalNodeNums (const IntVec &nodes)
Sets the global node numbers for this patch.
const IntVec & getMyNodeNums () const
Returns the actual global node numbers of this patch.
const IntVec & getGlobalNodeNums () const
Returns the global node numbers of this patch.
virtual void shiftGlobalElmNums (int eshift)
Increase all global element numbers by eshift.
const IntVec & getGlobalElementNums () const
Returns the global element numbers of this patch.
void setActiveElements (IntVec *active)
Sets the list of active elements during assembly.
bool isElementActive (int iel, double time=-1.0) const
Returns true if element with 0-based index iel is active.
bool inActive (double time=-1.0) const
Returns true if none of the elements in the patch are active.
double getAge (int iel, double time) const
Returns the age of the element with 0-based index iel.
bool isElementInPartition (int iel) const
Returns true if element is in process partition.
const IntVec & getElementNodes (int iel) const
Returns the nodal point correspondance array for an element.
size_t getNoElms (bool includeZeroVolElms=false, bool includeXElms=false) const
Returns the total number of elements in this patch.
int getMaxElmNo () const
Returns the highest external element number in this patch.
size_t getNoMPCs () const
Returns the total number of multi-point constraint equations.
virtual void getNoIntPoints (size_t &nPt, size_t &nIPt)
Computes the total number of integration points in this patch.
virtual void getNoBouPoints (size_t &nPt, char ldim, char lindx)
Computes the number of boundary integration points in this patch.
BCVec::const_iterator begin_BC () const
Returns the beginning of the BCode array.
BCVec::const_iterator end_BC () const
Returns the end of the BCode array.
IntMat::const_iterator begin_elm () const
Returns the beginning of the MNPC array.
IntMat::const_iterator end_elm () const
Returns the end of the MNPC array.
MPCIter begin_MPC () const
Returns the beginning of the mpcs set.
MPCIter end_MPC () const
Returns the end of the mpcs set.
MPC * findMPC (int node, int dof) const
Returns a pointer to the MPC object for a specified slave, if any.
bool isShared () const
Returns true if this patch shares FE data with another patch.
bool hasXNodes () const
Returns true if this patch has additional (extraordinary) nodes.
bool mergeNodes (size_t inod, int globalNum, bool verbose=true)
Merges a given node in this patch with a given global node.
int renumberNodes (std::map< int, int > &old2new, int &nNod)
Renumbers the global node numbers in this patch.
bool renumberNodes (const std::map< int, int > &old2new, const std::vector< int > &new2old={}, int renumGN=0, std::map< int, int > *degenElm=nullptr)
Renumbers the global node numbers referred by this patch.
virtual bool initConstraints ()
Initializes the multi-point constraint coefficients.
bool hasTimeDependentDirichlet (const std::map< int, RealFunc * > &func, const std::map< int, VecFunc * > &vfunc)
Checks for time-dependent in-homogeneous Dirichlet conditions.
virtual bool transform (const Matrix &)
Applies a transformation matrix from local to global system.
virtual bool validateThreadGroups (const SAM *) const
Validates the threading groups based on the assembly data in SAM.
virtual ElementBlock * immersedGeometry (char *) const
Returns an additional geometry to visualize (immersed boundaries).
virtual ElementBlock * extraGeometry (char *) const
Returns an additional geometry to visualize (spiders, etc.).
virtual void filterResults (Matrix &, const ElementBlock *) const
Filters out result point values that are outside physical domain.
virtual bool immersedSolution (Matrix &, const Vector &) const
Evaluates the primary solution at the immersed geometry points.
virtual bool extraSolution (Matrix &, const Vector &) const
Evaluates the primary solution at the extra geometry points.
virtual bool evalSolutionPiola (Matrix &sField, const Vector &locSol, const RealArray *gpar, bool regular) const
Evaluates the primary solution field with Piola mapping.
bool globalL2projection (Matrix &sField, const L2Integrand &integrand, bool continuous=false, bool enforceEnds=false) const
Projects the secondary solution using a (discrete) global L2-fit.
bool L2projection (Matrix &sField, IntegrandBase *integrand, const TimeDomain &time)
Projects the secondary solution using a continuous global L2-fit.
bool L2projection (Matrix &fVals, FunctionBase *func, double t=0.0)
Projects an explicit function using a continuous global L2-fit.
bool L2projection (const std::vector< Matrix * > &fVals, const std::vector< FunctionBase * > &funcs, double t=0.0)
Projects explicit functions using a continuous global L2-fit.
virtual size_t getNoRefineNodes () const
Returns the number of nodes on refinement basis for this patch.
virtual size_t getNoRefineElms () const
Returns the number of elements on refinement basis for this patch.
virtual const ASMbase * getOutputMaster () const
Returns the master patch to use for VTF- and HDF5-output.
void extractElmRes (const Vector &globRes, Vector &elmRes, size_t internalFirst=0) const
Extracts element results for this patch from a global vector.
void extractElmRes (const Matrix &globRes, Vector &elmRes, size_t irow) const
Extracts element results for this patch from a global matrix.
bool extractNodalVec (const RealArray &globVec, RealArray &nodeVec, const int *madof, int ngnod=-1) const
Extracts nodal results for this patch from the global vector.
bool injectNodalVec (const RealArray &nodeVec, RealArray &globVec, const IntVec &madof, int basis=0) const
Injects nodal results for this patch into the global vector.
bool add2PC (int slave, int dir, int master, int code=0)
Creates and adds a two-point constraint to this patch.
bool addMPC (MPC *&mpc, int code=0, bool verbose=false, bool overrideD=false)
Adds a general multi-point-constraint (MPC) equation to this patch.
void addRigidCouplings (int gMaster, const Vec3 &Xmaster, const IntVec &slaveNodes)
Adds MPC-equations representing a rigid coupling to this patch.
void addNodalCouplings (int slave, const IntVec &masters, const RealArray &weights)
Adds MPC-equations for general nodal couplings in this patch.
void constrainPatch (int dof, int code=0)
Constrains all nodes in the patch.
void constrainNodes (const IntVec &nodes, int dof, int code=0, bool overrideD=false)
Constrains a list of nodes in the patch.
bool constrainXnode (int node, int dof, int code=0)
Constrains an extraordinary node in the patch.
int prescribe (size_t inod, int dirs, int code, bool overrideD=false)
Constrains DOFs in the given node to the given value.
int fix (size_t inod, int dirs=123)
Constrains DOFs in the given node to zero.
bool isFixed (int node, int dof, bool all=false) const
Checks if the given DOFs are fixed.
Public Member Functions inherited from ASM3D
virtual ~ASM3D ()
Empty destructor.
ASMbase * clone (const CharVec &nf=CharVec()) const
Returns a copy of this patch with identical FE discretization.
virtual bool refine (int dir, const std::vector< double > &xi)=0
Refines the parametrization by inserting extra knots.
virtual bool getGridParameters (std::vector< double > &prm, int dir, int nSegSpan) const =0
Calculates parameter values for visualization nodal points.
Protected Member Functions
virtual int getFirstItgElmNode () const
Returns 0-based index of first node on integration basis.
virtual int getLastItgElmNode () const
Returns 0-based index of last node on integration basis.
virtual void getBoundaryNodes (int lIndex, IntVec &nodes, int basis, int thick, int, bool local) const
Finds the global (or patch-local) node numbers on a patch boundary.
std::array< int, 3 > getMaxSplineOrder () const
Returns the maximum spline orders for thread groups calculations.
Protected Member Functions inherited from ASMs3D
bool integrate (Integrand &integrand, GlobalIntegral &glbInt, const TimeDomain &time, const Real3DMat &itgPts)
Evaluates an integral over the interior patch domain.
virtual void findBoundaryElms (IntVec &elms, int lIndex, int=0) const
Finds the patch-local element numbers on a patch boundary.
virtual bool assembleL2matrices (SystemMatrix &A, SystemVector &B, const L2Integrand &integrand, bool continuous) const
Assembles L2-projection matrices for the secondary solution.
bool connectBasis (int face, ASMs3D &neighbor, int nface, int norient, int basis=1, int slave=0, int master=0, bool coordCheck=true, int thick=1)
Connects all matching nodes on two adjacent boundary faces.
void getGaussPointParameters (RealArray &uGP, int dir, int nGauss, const double *xi) const
Extracts parameter values of the Gauss points in one direction.
bool getGrevilleParameters (RealArray &prm, int dir, int basisNum=1) const
Calculates parameter values for the Greville points.
bool getQuasiInterplParameters (RealArray &prm, int dir) const
Calculates parameter values for the Quasi-Interpolation points.
bool getElementCoordinatesPrm (Matrix &X, double u, double v, double w) const
Returns a matrix with nodal coordinates for element spanning given parameters.
double getParametricVolume (int iel) const
Returns the volume in the parameter space for an element.
double getParametricArea (int iel, int dir) const
Returns boundary face area in the parameter space for an element.
virtual void getElementBorders (int iel, double *u) const
Computes the element border parameters.
void getElementBorders (int i1, int i2, int i3, double *u, double *v, double *w) const
Computes the element border parameters.
double getElementCorners (int i1, int i2, int i3, std::vector< Vec3 > &XC, RealArray *uC=nullptr) const
Computes the element corner coordinates.
void getCornerPoints (int i1, int i2, int i3, std::vector< utl::Point > &XC) const
Computes the element corner coordinates and parameters.
void generateThreadGroups (size_t strip1, size_t strip2, size_t strip3, bool silence, bool ignoreGlobalLM)
Generates element groups for multi-threading of interior integrals.
void generateThreadGroups (size_t strip1, size_t strip2, size_t strip3, char lIndex, bool silence, bool)
Generates element groups for multi-threading of boundary integrals.
virtual void changeNumThreads ()
Hook for changing number of threads.
Protected Member Functions inherited from ASMstruct
ASMstruct (unsigned char n_p, unsigned char n_s, unsigned char n_f)
The constructor sets the number of space dimensions and fields.
ASMstruct (const ASMstruct &patch, unsigned char n_f)
Special copy constructor for sharing of FE data.
bool addXNodes (unsigned short int dim, size_t nXn, IntVec &nodes)
Adds extraordinary nodes associated with a patch boundary.
bool checkThreadGroups (const std::vector< std::set< int > > &nodes, int group, bool ignoreGlobalLM)
Performs a sanity check on the thread groups.
Protected Member Functions inherited from ASMbase
ASMbase (unsigned char n_p, unsigned char n_s, unsigned char n_f)
The constructor sets the number of space dimensions and fields.
ASMbase (const ASMbase &patch, unsigned char n_f)
Special copy constructor for sharing of FE data.
ASMbase (const ASMbase &patch)
Default copy constructor, copying everything except neighbors.
void addLocal2GlobalCpl (int iSlave, int master, const Tensor &Tlg)
Creates constraint equations coupling global DOFs to local DOFs.
bool add3PC (int slave, int dir, int master1, int master2, int code=0)
Creates and adds a three-point constraint to this patch.
bool addPeriodicity (size_t master, size_t slave, int dir)
Creates and adds a periodicity constraint to this patch.
void makePeriodic (size_t master, size_t slave, int dirs=123)
Creates periodicity constraints between two nodes in this patch.
void addNeighbor (ASMbase *pch)
Adds a patch to the list of neighbors of this patch.
bool createRgdMasterNode (int &gMaster, const Vec3 &Xmaster)
Creates an additional master node for a rigid coupling.
void addRigidMPC (int gSlave, int gMaster, const Vec3 &dX)
Adds MPC-equations representing a rigid arm to a 6-DOF node.
int getNoGaussPt (int p, bool neumann=false) const
Returns the number of Gauss points to use in one direction.
int searchCtrlPt (RealArray::const_iterator cit, RealArray::const_iterator end, const Vec3 &X, int dimension, double xtol=0.001) const
Helper method used by evalPoint to search for a control point.
bool allDofs (int dirs) const
Returns true if dirs constains all local DOFs in the patch.
bool writeLagBasis (std::ostream &os, const char *type) const
Writes a Lagrangian basis to the given stream.
Protected Member Functions inherited from ASM3D
ASM3D ()
The constructor is protected to allow objects of sub-classes only.
Protected Attributes
std::vector< std::shared_ptr< Go::SplineVolume > > m_basis
Vector of bases.
Protected Attributes inherited from ASMs3D
std::shared_ptr< Go::SplineVolume > svol
The actual spline volume object.
bool swapW
Has the w-parameter direction been swapped?
const IndexVec & nodeInd
IJK-triplets for the control points (nodes)
IndexVec myNodeInd
The actual IJK-triplet container.
std::map< size_t, size_t > xnMap
Node index map used by getCoord()
std::map< size_t, size_t > nxMap
Node index map used by getNodeID()
std::vector< DirichletFace > dirich
Inhomogeneous Dirichlet boundary condition data.
ThreadGroups threadGroupsVol
Element groups for multi-threaded volume assembly.
std::map< char, ThreadGroups > threadGroupsFace
Element groups for multi-threaded face assembly.
std::vector< std::unique_ptr< BasisFunctionCache > > myCache
Basis function cache.
Protected Attributes inherited from ASMstruct
std::shared_ptr< Go::GeomObject > geomB
Pointer to spline object of the geometry basis.
std::shared_ptr< Go::GeomObject > projB
Pointer to spline object of the projection basis.
std::shared_ptr< Go::GeomObject > projB2
Pointer to spline object of the secondary projection basis.
ThreadGroups projThreadGroups
Element groups for multi-threaded assembly - projection basis.
ThreadGroups proj2ThreadGroups
Element groups for multi-threaded assembly - second projection basis.
Protected Attributes inherited from ASMbase
unsigned char ndim
Number of parametric dimensions (1, 2 or 3)
unsigned char nsd
Number of space dimensions (ndim <= nsd <= 3)
unsigned char nf
Number of primary solution fields (1 or larger)
unsigned char nLag
Number of Lagrange multipliers per node.
size_t nel
Number of regular elements in this patch.
size_t nnod
Number of regular nodes in this patch.
const IntVec & MLGE
Matrix of Local to Global Element numbers.
const IntVec & MLGN
Matrix of Local to Global Node numbers.
const IntMat & MNPC
Matrix of Nodal Point Correspondance.
const char shareFE
Flag telling whether this patch shares its data with another patch.
BCVec BCode
Array of Boundary Condition codes.
MPCMap dCode
Inhomogeneous Dirichlet condition codes for the MPCs.
MPCSet mpcs
All multi-point constraints with the slave in this patch.
std::vector< ASM::NodeSet > nodeSets
Node sets for explicit Dirichlet BCs.
IntVec myMLGE
The actual Matrix of Local to Global Element numbers.
IntVec myMLGN
The actual Matrix of Local to Global Node numbers.
IntMat myMNPC
The actual Matrix of Nodal Point Correspondance.
IntVec myElms
Elements on patch - used with partitioning.
int nGauss
Numerical integration scheme for this patch.
size_t firstEl
Global index to first element within this patch.
size_t firstIp
Global index to first interior integration point.
std::map< char, size_t > firstBp
Global indices to first integration point for the Neumann boundaries.
ASM::PatchVec neighbors
Patches having nodes in common with this one.
std::map< size_t, XYZ > myRmaster
Rigid master nodal points.
Additional Inherited Members
Public Types inherited from ASMbase
using BCVec = std::vector< BC >
Nodal boundary condition container.
Public Types inherited from ASM3D
typedef std::vector< unsigned char > CharVec
Convenience type.
Static Public Member Functions inherited from ASMs3D
static void scatterInd (int n1, int n2, int n3, int p1, int p2, int p3, const int *start, IntVec &index)
Auxilliary function for computation of basis function indices.
Static Public Member Functions inherited from ASMbase
static void resetNumbering (int n=0)
Resets the global element and node counters.
static int renumberNodes (const ASM::PatchVec &model, std::map< int, int > &old2new)
Renumbers all global node numbers in the entire model.
static void mergeAndGetAllMPCs (const ASM::PatchVec &model, MPCSet &allMPCs)
Computes the set of all MPC-equations over the whole model.
static void resolveMPCchains (const MPCSet &allMPCs, const ASM::PatchVec &model, bool setPtrOnly=false)
Resolves (possibly multi-level) chaining in MPC-equations.
Static Public Member Functions inherited from ASM3D
static ASMbase * create (ASM::Discretization type, const CharVec &nf, bool mixedFEM=false)
Creates a three-parametric patch of specified discretization type.
static ASMbase * create (ASM::Discretization type, unsigned char nf=1)
Creates a three-parametric patch of specified discretization type.
Public Attributes inherited from ASMbase
size_t idx
Index of this patch in the multi-patch model.
Static Public Attributes inherited from ASMbase
static bool fixHomogeneousDirichlet = true
If true, pre-eliminate fixed DOFs.
static int dbgElm = 0
One-based element index to print debugging info for.
static double modelSize = 1.0
Characteristic model size.
Protected Types inherited from ASMbase
using XYZ = std::array< double, 3 >
Convenience type definition.
Static Protected Member Functions inherited from ASMbase
static bool deformedConfig (const Matrix &Xnod, Vectors &eVec, bool force2nd=false)
Calculates the deformed configuration for current element.
static bool collapseNodes (ASMbase &pch1, int node1, ASMbase &pch2, int node2)
Collapses the given two nodes into one.
Static Protected Member Functions inherited from ASM3D
static double getElementSize (const std::vector< Vec3 > &XC)
Returns characteristic element size based on corner coordinates.
Static Protected Attributes inherited from ASMbase
static std::map< int, int > xNode
Auxilliary node number map used when establishing Dirichlet constraints.
static int gEl = 0
Global element counter.
static int gNod = 0
Global node counter.
Private Types inherited from ASMmxBase
enum MixedType {
NONE = 0 , FULL_CONT_RAISE_BASIS1 , REDUCED_CONT_RAISE_BASIS1 , FULL_CONT_RAISE_BASIS2 ,
REDUCED_CONT_RAISE_BASIS2 , DIV_COMPATIBLE , SUBGRID
}
Enum defining available mixed formulation types.
typedef std::vector< std::shared_ptr< Go::SplineSurface > > SurfaceVec
Convenience type.
typedef std::vector< std::shared_ptr< Go::SplineVolume > > VolumeVec
Convenience type.
Private Member Functions inherited from ASMmxBase
ASMmxBase (const std::vector< unsigned char > &n_f)
The constructor sets the number of field variables.
void initMx (const std::vector< int > &MLGN, const int *sysMadof)
Initializes the patch level MADOF array.
void extractNodeVecMx (const RealArray &glbVec, RealArray &nodVec, int basis) const
Extracts nodal results for this patch from the global vector.
void injectNodeVecMx (RealArray &glbVec, const RealArray &nodVec, int basis) const
Injects nodal results for this patch into a global vector.
bool getSolutionMx (Matrix &sField, const Vector &locSol, const std::vector< int > &nodes) const
Extracts the primary solution field at the specified nodes.
Static Private Member Functions inherited from ASMmxBase
static SurfaceVec establishBases (Go::SplineSurface *surf, MixedType type)
Establish mixed bases in 2D.
static VolumeVec establishBases (Go::SplineVolume *svol, MixedType type)
Establish mixed bases in 3D.
static Go::SplineSurface * adjustBasis (const Go::SplineSurface &surf, const std::array< SplineUtils::AdjustOp, 2 > &ops)
Returns a C^p-1 basis of one degree higher than *surf.
static Go::SplineVolume * adjustBasis (const Go::SplineVolume &svol, const std::array< SplineUtils::AdjustOp, 3 > &ops)
Returns a C^p-1 basis of one degree higher than *svol.
Private Attributes inherited from ASMmxBase
bool piola = false
True if last used integrand was Piola mapped.
std::vector< size_t > elem_size
Number of basis functions per element in each basis.
std::vector< size_t > nb
Total number of basis functions in each basis.
std::vector< unsigned char > nfx
Number of fields on each basis.
Static Private Attributes inherited from ASMmxBase
static MixedType Type = ASMmxBase::FULL_CONT_RAISE_BASIS1
Type of mixed formulation used.
static char itgBasis = 2
1-based index of basis representing the integration elements
static bool includeExtra = false
True to include extra basis (geometry/projection) as FE basis.
Detailed Description
Driver for assembly of structured 3D spline mixed FE models.
This class implements a two-field mixed formulation with splines as basis functions. The first field is of one order higher than the second field, and its basis is obtained by order-elevating the input spline object once. By default, the geometry is represented by the second (lower order) basis, however, by negating the n_f1 argument to the constructor, the first basis is used instead.
Member Function Documentation
clear()
void ASMs3Dmx::clear (bool retainGeometry) virtual
Clears the contents of the patch, making it empty.
Parameters
[in] retainGeometry If true, the spline geometry is not cleared. This is used to reinitialize the patch after it has been refined.
Reimplemented from ASMs3D.
References ASMs3D::clear(), ASMstruct::geomB, m_basis, ASMstruct::projB, separateProjectionBasis(), and ASMs3D::svol.
closeBoundaries()
void ASMs3Dmx::closeBoundaries (int dir, int , int) virtual
Makes two opposite boundary faces periodic.
Parameters
[in] dir Parameter direction defining the periodic faces
Reimplemented from ASMs3D.
References ASMs3D::closeBoundaries(), and ASMmxBase::nb.
connectPatch()
bool ASMs3Dmx::connectPatch (int face, ASM3D & neighbor, int nface, int norient, int basis, bool coordCheck, int thick) virtual
Connects all matching nodes on two adjacent boundary faces.
Parameters
[in] face Local face index of this patch, in range [1,6]
neighbor The neighbor patch
[in] nface Local face index of neighbor patch, in range [1,6]
[in] norient Relative face orientation flag (see class ASMs3D)
[in] basis Which basis to connect, or 0 for all.
[in] coordCheck False to disable coordinate checks (periodic connections)
[in] thick Thickness of connection
Reimplemented from ASMs3D.
References ASMbase::addNeighbor(), ASMs3D::connectBasis(), ASMmxBase::nb, and ASMs3D::swapW.
evalPoint()
int ASMs3Dmx::evalPoint (const double * xi, double * param, Vec3 & X) const virtual
Evaluates the geometry at a specified point.
Parameters
[in] xi Dimensionless parameters in range [0.0,1.0] of the point
[out] param The (u,v,w) parameters of the point in knot-span domain
[out] X The Cartesian coordinates of the point
Returns
Local node number within the patch that matches the point, if any
0 if no node (control point) matches this point
Reimplemented from ASMs3D.
References m_basis, ASMbase::searchCtrlPt(), and ASMs3D::svol.
evalSolution() [1/7]
Go::GeomObject * ASMs3D::evalSolution (const IntegrandBase & integrand) const virtual
Projects the secondary solution field onto the primary basis.
Parameters
[in] integrand Object with problem-specific data and methods
Reimplemented from ASMs3D.
evalSolution() [2/7]
bool ASMs3D::evalSolution (Matrix & sField, const IntegrandBase & integrand, const int * npe = nullptr, char project = 0) const virtual
Evaluates the secondary solution field at all visualization points.
Parameters
[out] sField Solution field
[in] integrand Object with problem-specific data and methods
[in] npe Number of visualization nodes over each knot span
[in] project Flag indicating result recovery method (0=none, 'D'=direct evaluation, 'S'=superconvergent recovery)
The secondary solution is derived from the primary solution, which is assumed to be stored within the integrand for current patch. If npe is null, the solution is recovered or evaluated at the Greville points and then projected onto the spline basis to obtain the control point values, which then are returned through sField. If npe is not null and project is defined, the solution is also projected onto the spline basis, and then evaluated at the npe points.
Reimplemented from ASMs3D.
evalSolution() [3/7]
bool ASMs3Dmx::evalSolution (Matrix & sField, const IntegrandBase & integrand, const RealArray * gpar, bool regular) const virtual
Evaluates the secondary solution field at the given points.
Parameters
[out] sField Solution field
[in] integrand Object with problem-specific data and methods
[in] gpar Parameter values of the result sampling points
[in] regular Flag indicating how the sampling points are defined
The secondary solution is derived from the primary solution, which is assumed to be stored within the integrand for current patch. When regular is true, it is assumed that the parameter value array gpar forms a regular tensor-product point grid of dimension gpar[0].size() X gpar[1].size() X gpar[2].size(). Otherwise, we assume that it contains the u, v and w parameters directly for each sampling point.
Reimplemented from ASMs3D.
References MxFiniteElement::basis(), ASMmxBase::elem_size, utl::matrixBase< T >::empty(), IntegrandBase::evalSol(), SplineUtils::extractBasis(), utl::matrix< T >::fillColumn(), ASMbase::firstIp, utl::gather(), ASM::GEOMETRY_BASIS, getBasis(), ASMs3D::getNodalCoordinates(), ItgPoint::iGP, ASMmxBase::itgBasis, MxFiniteElement::Jacobian(), m_basis, ASMmxBase::nb, utl::matrix< T >::resize(), ASMs3D::scatterInd(), utl::vector< T >::size(), utl::matrixBase< T >::size(), ASMs3D::svol, ItgPoint::u, ItgPoint::v, and ItgPoint::w.
evalSolution() [4/7]
bool ASMs3D::evalSolution (Matrix & sField, const IntegrandBase & integrand, const RealArray * gpar, bool regular = true) const virtual
Evaluates the secondary solution field at the given points.
Parameters
[out] sField Solution field
[in] integrand Object with problem-specific data and methods
[in] gpar Parameter values of the result sampling points
[in] regular Flag indicating how the sampling points are defined
The secondary solution is derived from the primary solution, which is assumed to be stored within the integrand for current patch. When regular is true, it is assumed that the parameter value array gpar forms a regular tensor-product point grid of dimension gpar[0].size() X gpar[1].size() X gpar[2].size(). Otherwise, we assume that it contains the u, v and w parameters directly for each sampling point.
Reimplemented from ASMs3D.
evalSolution() [5/7]
bool ASMs3D::evalSolution (Matrix & sField, const Vector & locSol, const int * npe, int n_f, bool piola) const virtual
Evaluates the primary solution field at all visualization points.
Parameters
[out] sField Solution field
[in] locSol Solution vector in DOF-order
[in] npe Number of visualization nodes over each knot span
[in] n_f If nonzero, mixed evaluates n_f fields on first basis
[in] piola If true, use piola mapping
Reimplemented from ASMs3D.
evalSolution() [6/7]
bool ASMs3Dmx::evalSolution (Matrix & sField, const Vector & locSol, const RealArray * gpar, bool regular, int deriv, int nf) const virtual
Evaluates the primary solution field at the given points.
Parameters
[out] sField Solution field
[in] locSol Solution vector local to current patch
[in] gpar Parameter values of the result sampling points
[in] regular Flag indicating how the sampling points are defined
[in] deriv Derivative order to return
[in] nf If non-zero evaluates nf fields on first basis
When regular is true, it is assumed that the parameter value array gpar forms a regular tensor-product point grid of dimension gpar[0].size() X gpar[1].size() X gpar[2].size(). Otherwise, we assume that it contains the u, v and w parameters directly for each sampling point.
Reimplemented from ASMs3D.
References utl::vector< T >::begin(), utl::vector< T >::end(), utl::matrix< T >::fillColumn(), utl::gather(), m_basis, utl::matrix< T >::multiply(), ASMmxBase::nb, ASMbase::nf, ASMmxBase::nfx, utl::vector< T >::push_back(), utl::matrix< T >::resize(), ASMs3D::scatterInd(), and utl::vector< T >::size().
evalSolution() [7/7]
bool ASMs3D::evalSolution (Matrix & sField, const Vector & locSol, const RealArray * gpar, bool regular = true, int deriv = 0, int = 0) const virtual
Evaluates the primary solution field at the given points.
Parameters
[out] sField Solution field
[in] locSol Solution vector local to current patch
[in] gpar Parameter values of the result sampling points
[in] regular Flag indicating how the sampling points are defined
[in] deriv Derivative order to return
When regular is true, it is assumed that the parameter value array gpar forms a regular tensor-product point grid of dimension gpar[0].size() X gpar[1].size() X gpar[2].size(). Otherwise, we assume that it contains the u, v and w parameters directly for each sampling point.
Reimplemented from ASMs3D.
extractNodeVec()
void ASMs3Dmx::extractNodeVec (const RealArray & globVec, RealArray & nodeVec, unsigned char , int basis) const virtual
Extracts nodal results for this patch from the global vector.
Parameters
[in] globVec Global solution vector in DOF-order
[out] nodeVec Nodal result vector for this patch
[in] basis Which basis (or 0 for both) to extract nodal values for
Reimplemented from ASMbase.
References ASMmxBase::extractNodeVecMx().
generateFEMTopology()
bool ASMs3Dmx::generateFEMTopology () virtual
Generates the finite element topology data for the patch.
The data generated are the element-to-node connectivity array, the node-to-IJ-index array, as well as global node and element numbers.
Reimplemented from ASMs3D.
References ASMmxBase::adjustBasis(), ASMmxBase::DIV_COMPATIBLE, ASMmxBase::elem_size, ASMmxBase::establishBases(), ASMbase::firstEl, ASMmxBase::FULL_CONT_RAISE_BASIS1, ASMmxBase::FULL_CONT_RAISE_BASIS2, ASMbase::gEl, ASMstruct::geomB, getBasis(), getFirstItgElmNode(), ASMbase::gNod, ASMmxBase::includeExtra, ASM::INTEGRATION_BASIS, ASMmxBase::itgBasis, m_basis, ASMbase::myMLGE, ASMbase::myMLGN, ASMbase::myMNPC, ASMs3D::myNodeInd, ASMmxBase::nb, ASMbase::nel, ASMbase::nnod, ASMs3D::nodeInd, ASMmxBase::NONE, ASMstruct::projB, ASMstruct::projB2, SplineUtils::Raise, ASMmxBase::REDUCED_CONT_RAISE_BASIS1, ASMmxBase::REDUCED_CONT_RAISE_BASIS2, ASMbase::shareFE, ASMmxBase::SUBGRID, ASMs3D::svol, and ASMmxBase::Type.
generateThreadGroups() [1/2]
void ASMs3Dmx::generateThreadGroups (char lIndex, bool silence, bool) virtual
Generates element groups for multi-threading of boundary integrals.
Parameters
[in] lIndex Local index [1,6] of the boundary face
[in] silence If true, suppress threading group outprint
Reimplemented from ASMs3D.
References ASMs3D::generateThreadGroups(), getMaxSplineOrder(), ASMbase::nel, and ASMs3D::threadGroupsFace.
generateThreadGroups() [2/2]
void ASMs3Dmx::generateThreadGroups (const Integrand & integrand, bool silence, bool ignoreGlobalLM) virtual
Generates element groups for multi-threading of interior integrals.
Parameters
[in] integrand Object with problem-specific data and methods
[in] silence If true, suppress threading group outprint
[in] ignoreGlobalLM If true ignore global multipliers in sanity check
Reimplemented from ASMs3D.
References ASMs3D::generateThreadGroups(), getMaxSplineOrder(), ASMbase::nel, ThreadGroups::oneGroup(), ThreadGroups::stripDir, and ASMs3D::threadGroupsVol.
getBasis() [1/2]
Go::SplineVolume * ASMs3Dmx::getBasis (int basis = 1) virtual
Returns the spline surface representing a basis of this patch.
Reimplemented from ASMs3D.
getBasis() [2/2]
const Go::SplineVolume * ASMs3Dmx::getBasis (int basis = 1) const virtual
Returns the spline surface representing a basis of this patch.
Reimplemented from ASMs3D.
References ASMs3D::getBasis(), and m_basis.
Referenced by evalSolution(), generateFEMTopology(), SplineFields3Dmx::gradFE(), SplineFields3Dmx::hessianFE(), integrate(), integrate(), integrate(), SplineFields3Dmx::valueCoor(), and SplineFields3Dmx::valueFE().
getBoundary()
Go::SplineSurface * ASMs3Dmx::getBoundary (int dir, int basis = 1) virtual
Returns the spline curve representing a boundary of this patch.
Parameters
[in] dir Parameter direction defining which boundary to return
[in] basis The basis to get the boundary for
Reimplemented from ASMs3D.
References m_basis.
getBoundaryNodes()
void ASMs3Dmx::getBoundaryNodes (int lIndex, IntVec & nodes, int basis, int thick, int , bool local) const protected virtual
Finds the global (or patch-local) node numbers on a patch boundary.
Parameters
[in] lIndex Local index of the boundary edge
nodes Array of node numbers
[in] basis Which basis to grab nodes for (0 for all)
[in] thick Thickness of connection
[in] local If true return patch-local node numbers
Reimplemented from ASMs3D.
References ASMs3D::getBoundaryNodes(), and m_basis.
getCoord()
Vec3 ASMs3Dmx::getCoord (size_t inod) const virtual
Returns the global coordinates for the given node.
Parameters
[in] inod 1-based node index local to current patch
Reimplemented from ASMs3D.
References K, m_basis, ASMbase::MLGN, ASMmxBase::nb, ASMs3D::nodeInd, and ASMs3D::xnMap.
getFirstItgElmNode()
int ASMs3Dmx::getFirstItgElmNode () const protected virtual
Returns 0-based index of first node on integration basis.
Reimplemented from ASMs3D.
References ASMmxBase::elem_size, and ASMmxBase::itgBasis.
Referenced by generateFEMTopology().
getLastItgElmNode()
int ASMs3Dmx::getLastItgElmNode () const protected virtual
Returns 0-based index of last node on integration basis.
Reimplemented from ASMs3D.
References ASMmxBase::elem_size, and ASMmxBase::itgBasis.
getNoBasis()
virtual size_t ASMs3Dmx::getNoBasis () const inline virtual
Returns the number of bases.
Reimplemented from ASMbase.
References m_basis.
Referenced by integrate().
getNodalDOFs()
unsigned char ASMs3Dmx::getNodalDOFs (size_t inod) const virtual
Returns the number of DOFs per node.
Parameters
[in] inod 1-based node index local to current patch
Reimplemented from ASMbase.
References ASMbase::isLMn(), ASMmxBase::nb, ASMmxBase::nfx, and ASMbase::nLag.
getNodeType()
char ASMs3Dmx::getNodeType (size_t inod) const virtual
Returns the classification of a node.
Parameters
[in] inod 1-based node index local to current patch
Reimplemented from ASMbase.
References ASMbase::isLMn(), and ASMmxBase::nb.
getNoFields()
unsigned char ASMs3Dmx::getNoFields (int basis) const virtual
Returns the number of solution fields.
Reimplemented from ASMbase.
References ASMbase::nf, and ASMmxBase::nfx.
Referenced by SplineFields3Dmx::gradFE(), SplineFields3Dmx::hessianFE(), and SplineFields3Dmx::SplineFields3Dmx().
getNoNodes()
size_t ASMs3Dmx::getNoNodes (int basis) const virtual
Returns the total number of nodes in this patch.
Reimplemented from ASMs3D.
References ASMbase::getNoNodes(), and ASMmxBase::nb.
Referenced by SplineFields3Dmx::gradFE(), SplineFields3Dmx::hessianFE(), SplineFields3Dmx::SplineFields3Dmx(), and SplineFields3Dmx::valueFE().
getSize()
bool ASMs3Dmx::getSize (int & n1, int & n2, int & n3, int basis) const virtual
Returns the number of nodal points in each parameter direction.
Parameters
[out] n1 Number of nodes in first (u) direction
[out] n2 Number of nodes in second (v) direction
[out] n3 Number of nodes in third (w) direction
[in] basis Which basis to return size parameters for
Reimplemented from ASMs3D.
References ASMs3D::getSize(), and m_basis.
getSolution()
bool ASMs3Dmx::getSolution (Matrix & sField, const Vector & locSol, const IntVec & nodes) const virtual
Extract the primary solution field at the specified nodes.
Parameters
[out] sField Solution field
[in] locSol Solution vector local to current patch
[in] nodes 1-based local node numbers to extract solution for
Reimplemented from ASMbase.
References ASMmxBase::getSolutionMx().
initMADOF()
void ASMs3Dmx::initMADOF (const int * sysMadof) virtual
Initializes the patch level MADOF array for mixed problems.
Reimplemented from ASMbase.
References ASMmxBase::initMx(), and ASMbase::MLGN.
injectNodeVec()
bool ASMs3Dmx::injectNodeVec (const RealArray & nodeVec, RealArray & globVec, unsigned char , int basis) const virtual
Injects nodal results for this patch into a global vector.
Parameters
[in] nodeVec Nodal result vector for this patch
[out] globVec Global solution vector in DOF-order
[in] basis Which basis (or 0 for both) to extract nodal values for
Reimplemented from ASMbase.
References ASMmxBase::injectNodeVecMx().
integrate() [1/3]
bool ASMs3Dmx::integrate (Integrand & integrand, GlobalIntegral & glbInt, const TimeDomain & time) virtual
Evaluates an integral over the interior patch domain.
Parameters
integrand Object with problem-specific data and methods
glbInt The integrated quantity
[in] time Parameters for nonlinear/time-dependent simulations
Reimplemented from ASMs3D.
References GlobalIntegral::assemble(), Vec4::assign(), MxFiniteElement::basis(), ASM::cachePolicy, BasisFunctionCache< Dim >::clear(), BasisFunctionCache< Dim >::coord(), LocalIntegral::destruct(), FiniteElement::detJxW, ASMmxBase::elem_size, Integrand::ELEMENT_CORNERS, ItgPoint::eta, Integrand::evalIntMx(), Integrand::finalizeElement(), ASMbase::firstEl, ASMbase::firstIp, FiniteElement::G, Integrand::G_MATRIX, ASM::GEOMETRY_BASIS, getBasis(), ASMs3D::getElementCoordinates(), ASMs3D::getElementCorners(), utl::getGmat(), Integrand::getIntegrandType(), Integrand::getLocalIntegral(), getNoBasis(), BasisFunctionCache< Dim >::getParam(), ASMs3D::getParametricVolume(), FiniteElement::h, MxFiniteElement::Hessian(), ItgPoint::idx, ItgPoint::iel, ItgPoint::iGP, Integrand::initElement(), ASMmxBase::itgBasis, MxFiniteElement::Jacobian(), m_basis, ASMbase::MLGE, ASMbase::MNPC, ASMs3D::myCache, ASMbase::myElms, ASMmxBase::nb, ASMbase::nel, BasisFunctionCache< Dim >::nGauss(), ThreadGroups::oneStripe(), ASM::PRE_CACHE, PROFILE2, LocalIntegral::ref(), Integrand::SECOND_DERIVATIVES, ThreadGroups::size(), ASMs3D::svol, TimeDomain::t, ASMs3D::threadGroupsVol, GlobalIntegral::threadSafe(), ItgPoint::u, ItgPoint::v, ItgPoint::w, BasisFunctionCache< Dim >::weight(), FiniteElement::XC, ItgPoint::xi, and ItgPoint::zeta.
integrate() [2/3]
bool ASMs3Dmx::integrate (Integrand & integrand, GlobalIntegral & glbInt, const TimeDomain & time, const ASM::InterfaceChecker & iChk) virtual
Evaluates an integral over element interfaces in the patch.
Parameters
integrand Object with problem-specific data and methods
glbInt The integrated quantity
[in] time Parameters for nonlinear/time-dependent simulations
[in] iChk Object checking if an element interface has contributions
Reimplemented from ASMs3D.
References GlobalIntegral::assemble(), Vec4::assign(), MxFiniteElement::basis(), LocalIntegral::destruct(), FiniteElement::detJxW, ASMmxBase::elem_size, Integrand::ELEMENT_CORNERS, ItgPoint::eta, Integrand::evalIntMx(), SplineUtils::extractBasis(), Integrand::finalizeElement(), ASMbase::firstEl, ASM::GEOMETRY_BASIS, getBasis(), Integrand::getBouIntegrationPoints(), GaussQuadrature::getCoord(), ASMs3D::getElementBorders(), ASMs3D::getElementCoordinates(), ASMs3D::getElementCorners(), Integrand::getIntegrandType(), Integrand::getLocalIntegral(), ASMs3D::getParametricArea(), GaussQuadrature::getWeight(), FiniteElement::h, ASM::InterfaceChecker::hasContribution(), ItgPoint::idx, ItgPoint::iel, ItgPoint::iGP, Integrand::initElement(), Integrand::INTERFACE_TERMS, ASMbase::isElementInPartition(), ASMmxBase::itgBasis, MxFiniteElement::Jacobian(), m_basis, ASMbase::MLGE, ASMbase::MNPC, ASMbase::myElms, ASMmxBase::nb, ASMbase::nel, ASMbase::nGauss, Integrand::NORMAL_DERIVS, FiniteElement::p, PROFILE2, LocalIntegral::ref(), ASMs3D::svol, TimeDomain::t, ItgPoint::u, ItgPoint::v, LocalIntegral::vec, ItgPoint::w, FiniteElement::XC, ItgPoint::xi, and ItgPoint::zeta.
integrate() [3/3]
bool ASMs3Dmx::integrate (Integrand & integrand, int lIndex, GlobalIntegral & glbInt, const TimeDomain & time) virtual
Evaluates a boundary integral over a patch edge.
Parameters
integrand Object with problem-specific data and methods
[in] lIndex Local index of the boundary edge
glbInt The integrated quantity
[in] time Parameters for nonlinear/time-dependent simulations
Reimplemented from ASMs3D.
References GlobalIntegral::assemble(), Vec4::assign(), MxFiniteElement::basis(), LocalIntegral::destruct(), FiniteElement::detJxW, ASMmxBase::elem_size, Integrand::ELEMENT_CORNERS, ItgPoint::eta, Integrand::evalBouMx(), SplineUtils::extractBasis(), Integrand::finalizeElementBou(), ASMbase::firstBp, ASMbase::firstEl, ASM::GEOMETRY_BASIS, getBasis(), GaussQuadrature::getCoord(), ASMs3D::getElementCoordinates(), ASMs3D::getElementCorners(), SplineUtils::getGaussParameters(), Integrand::getIntegrandType(), Integrand::getLocalIntegral(), ASMs3D::getParametricArea(), GaussQuadrature::getWeight(), FiniteElement::h, ItgPoint::idx, ItgPoint::iel, ItgPoint::iGP, Integrand::initElementBou(), ASMmxBase::itgBasis, MxFiniteElement::Jacobian(), m_basis, ASMbase::MLGE, ASMbase::MNPC, ASMbase::myElms, ASMmxBase::nb, ASMbase::nGauss, PROFILE2, LocalIntegral::ref(), Integrand::setNeumannOrder(), ThreadGroups::size(), ASMs3D::svol, TimeDomain::t, ASMs3D::threadGroupsFace, ItgPoint::u, ItgPoint::v, ItgPoint::w, FiniteElement::XC, ItgPoint::xi, and ItgPoint::zeta.
readBasis()
bool ASMs3Dmx::readBasis (std::istream & is, size_t basis) virtual
Reads a basis from the given input stream.
Reimplemented from ASMbase.
References m_basis, ASMmxBase::nb, and ASMmxBase::nfx.
separateProjectionBasis()
bool ASMs3Dmx::separateProjectionBasis () const virtual
Checks if a separate projection basis is used for this patch.
Reimplemented from ASMs3D.
References m_basis.
Referenced by clear().
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/ASM/ASMs3Dmx.h
/home/runner/work/IFEM-2/IFEM-2/src/ASM/ASMs3Dmx.C