IFEM: LinSolParams::BlockParams Class Reference
LinSolParams::BlockParams Class Reference
Linear solver settings for a block of the linear system.
#include <LinSolParams.h>
Classes
struct DirSmoother
Settings for a directional smoother.
Public Member Functions
BlockParams ()
Default constructor.
bool read (const tinyxml2::XMLElement *child, const std::string &prefix="")
Read settings from XML block.
Public Member Functions inherited from SettingMap
void addValue (const std::string &key, const std::string &value)
Add a value to the store.
std::string getStringValue (const std::string &key) const
Obtain a value as a string.
int getIntValue (const std::string &key) const
Obtain a value as an integer.
double getDoubleValue (const std::string &key) const
Obtain a value as an double.
bool hasValue (const std::string &key) const
Checks if the store holds a value for a key.
Public Attributes
size_t basis
Basis for block.
size_t comps
Components from basis (1, 2, 3, 12, 13, 23, 123, ..., 0 = all)
std::vector< DirSmoother > dirSmoother
Directional smoother data.
Additional Inherited Members
Protected Attributes inherited from SettingMap
std::map< std::string, std::string > values
Map of key-value pairs.
Detailed Description
Linear solver settings for a block of the linear system.
Member Function Documentation
read()
bool LinSolParams::BlockParams::read (const tinyxml2::XMLElement * child, const std::string & prefix = "")
Read settings from XML block.
Parameters
[in] child XML block
[in] prefix Prefix to add to read data
References SettingMap::addValue(), basis, comps, dirSmoother, utl::getAttribute(), SettingMap::getIntValue(), SettingMap::getStringValue(), utl::getValue(), SettingMap::hasValue(), and read().
Referenced by read().
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/LinAlg/LinSolParams.h
/home/runner/work/IFEM-2/IFEM-2/src/LinAlg/LinSolParams.C