IFEM: NewmarkSIM Class Reference
NewmarkSIM Class Reference
Newmark-based solution driver for dynamic isogeometric FEM simulators.
#include <NewmarkSIM.h>
Public Member Functions
NewmarkSIM (SIMbase &sim)
The constructor initializes default solution parameters.
virtual bool parse (const tinyxml2::XMLElement *elem)
Parses a data section from an XML document.
virtual void printProblem (bool stopInputTimer=false) const
Prints out problem-specific data to the log stream.
virtual void initPrm ()
Initializes time integration parameters for the integrand.
bool initAcc (double zero_tolerance=1.0e-8, std::streamsize outPrec=0)
Calculates initial accelerations.
virtual bool advanceStep (TimeStep &param, bool updateTime=true)
Advances the time step one step forward.
virtual SIM::ConvStatus solveStep (TimeStep &param, SIM::SolutionMode=SIM::STATIC, double zero_tolerance=1.0e-8, std::streamsize outPrec=0)
Solves the dynamic equations by a predictor/multi-corrector method.
SIM::ConvStatus solveIteration (TimeStep &param)
Solves the linearized system of current iteration.
int getMaxit () const
Returns the maximum number of iterations.
virtual bool isDynamic () const
Returns whether this is a dynamic solution driver or not.
const Vector & getVelocity () const
Returns a const reference to current velocity vector.
const Vector & getAcceleration () const
Returns a const reference to current velocity vector.
bool saveStep (int iStep, TimeStep &param)
Saves the converged solution to VTF file for a given time step.
virtual void dumpResults (double time, utl::LogStream &os, std::streamsize precision=3, bool formatted=true) const
Dumps solution variables at user-defined points.
virtual bool parse (const tinyxml2::XMLElement *elem)
Parses a data section from an XML document.
virtual bool parse (char *keyWord, std::istream &is)
Parses a data section from an input stream.
virtual bool parse (const tinyxml2::XMLElement *elem)
Parses a data section from an XML document.
bool saveStep (int iStep, double time, const char *vecName=nullptr)
Saves the converged solution to VTF file of a given time/load step.
bool saveStep (int iStep, int &rBlock, double time, const char *vecName=nullptr)
Saves the converged solution to VTF file of a given time/load step.
bool saveStep (int iStep, int &rBlock, const char *vecName)
Saves the converged solution to VTF file of a given time/load step.
Public Member Functions inherited from MultiStepSIM
virtual const char ** getPrioritizedTags () const
Returns a list of prioritized XML-tags.
virtual void initSol (size_t nSol=1, size_t nDof=0)
Initializes the primary solution vectors.
bool initEqSystem (bool withRF=true, size_t nScl=0)
Allocates the FE system matrices.
virtual bool preprocess (const std::vector< int > &ignored, bool fixDup)
Performs some pre-processing tasks on the FE model.
void setStartGeo (int gID)
Initializes the geometry block counter.
bool saveModel (const char *fileName)
Opens a new VTF-file and writes the model geometry to it.
bool saveModel (double initialTime=0.0)
Writes the model geometry to the currently opened VTF-file.
bool saveModel (int &gBlock, int &rBlock, double time=0.0)
Writes the model geometry and BCs to an already opened VTF-file.
bool saveStep (int iStep, double time, const char *vecName=nullptr)
Saves the converged solution to VTF file of a given time/load step.
bool saveStep (int iStep, int &rBlock, double time, const char *vecName=nullptr)
Saves the converged solution to VTF file of a given time/load step.
bool saveStep (int iStep, int &rBlock, const char *vecName)
Saves the converged solution to VTF file of a given time/load step.
virtual bool serialize (SerializeMap &data) const
Serializes the solution vectors for restarting purposes.
virtual bool deSerialize (const SerializeMap &data)
Restores the solution vectors from a serialized state.
bool checkForRestart ()
Restores the solution from a serialized state in case of restart.
void dumpStep (int iStep, double time, utl::LogStream &os, bool withID=true) const
Dumps the primary solution for inspection.
bool hasPointResultFile () const
Returns whether a points result file has been defined or not.
bool savePoints (double time, int step) const
Saves point-wise solution to file for a given time/load step.
virtual bool isLinear () const
Returns whether this solution driver is linear or not.
const SIMoutput & getModel () const
Returns a const reference to the FE model.
void setSubIteration (SubIt flag)
Updates the sub-iteration flag.
SubIt getSubIteration () const
Returns the sub-iteration flag.
virtual size_t numSolution () const
Returns the number of solution vectors.
virtual const Vector & realSolution (int i=0) const
Returns a const reference to the current real solution vector.
virtual const Vectors & realSolutions (bool=false)
Returns a const reference to the current real solution vectors.
double * theRefNorm ()
Returns a pointer to the reference norm variable.
const double * getRefNorm () const
Returns a const pointer to the reference norm variable.
Public Member Functions inherited from SIMsolution
virtual const Vectors & getSolutions () const
Returns a const reference to the solution vectors.
virtual Vectors & theSolutions ()
Returns a reference to the solution vectors (for assignment).
virtual const Vector & getSolution (int ix=0) const
Returns a const reference to current solution vector.
virtual void setSolution (const RealArray &s, int ix=0)
Modifies the current solution vector (used by sub-iterations only).
Public Member Functions inherited from SIMadmin
virtual ~SIMadmin ()
Empty destructor.
virtual bool read (const char *fileName)
Reads model data from the specified input file *fileName.
virtual bool preprocessC (const IntVec &, bool, double=0.0)
Performs some pre-processing tasks on the FE model.
const ProcessAdm & getProcessAdm () const
Returns the parallel process administrator.
int getGlobalProcessID () const
Returns the global process ID.
const std::string & getHeading () const
Returns the simulator heading.
void setHeading (const std::string &heading)
Defines the simulator heading.
void printHeading (int &supStep) const
Prints the heading of this simulator, if any, to IFEM::cout.
Public Member Functions inherited from XMLInputBase
bool readXML (const char *fileName, bool verbose=true)
Reads an XML input file.
bool loadXML (const char *xml)
Loads data from an XML-formatted text string.
Static Public Attributes
static const char * inputContext = "newmarksolver"
Input file context for solver parameters.
Static Public Attributes inherited from SIMadmin
static int msgLevel = 2
Controls the console output amount during solving.
Protected Member Functions
virtual bool solutionNorms (const TimeDomain &, double zero_tolerance=1.0e-8, std::streamsize outPrec=0)
Computes and prints some solution norm quantities.
virtual SIM::ConvStatus checkConvergence (TimeStep &param)
Checks whether the corrector iterations have converged or diverged.
virtual bool predictStep (TimeStep &param)
Calculates predicted velocities and accelerations.
virtual bool correctStep (TimeStep &param, bool=false)
Updates configuration variables (solution vector) in an iteration.
virtual void finalizeRHSvector (bool)
Finalizes the right-hand-side vector on the system level.
Protected Member Functions inherited from MultiStepSIM
MultiStepSIM (SIMbase &sim)
The constructor initializes the FE model reference.
void printStep (const TimeStep &param) const
Prints out time/load step identification.
int getLastSavedStep () const
Returns the last step that was saved to VTF.
Protected Member Functions inherited from SIMsolution
SIMsolution ()=default
The default constructor is protected to allow sub-classes only.
virtual ~SIMsolution ()=default
Empty default destructor.
void initSolution (size_t ndof, size_t nsol=1)
Initializes the solution vectors.
void pushSolution (unsigned short int nVecState=1)
Pushes the solution vector stack.
bool saveSolution (SerializeMap &data, const std::string &name) const
Writes current solution to a serialization container.
bool restoreSolution (const SerializeMap &data, const std::string &name)
Restores the solution from a serialization container.
Protected Member Functions inherited from SIMadmin
SIMadmin (const char *heading=nullptr)
The default constructor initializes the process administrator.
SIMadmin (SIMadmin &anotherSIM)
Copy constructor.
Protected Member Functions inherited from XMLInputBase
const tinyxml2::XMLElement * loadFile (tinyxml2::XMLDocument &doc, const char *fileName, bool verbose=false)
Loads an XML input file into a tinyxml2::XMLDocument object.
Protected Attributes
double alpha1
Mass-proportional damping parameter.
double alpha2
Stiffness-proportional damping parameter.
double beta
Newmark time integration parameter.
double gamma
Newmark time integration parameter.
bool solveDisp
If true, use incremental displacements as unknowns.
char predictor
Predictor type flag.
int maxit
Maximum number of iterations in a time step.
int maxIncr
Maximum number of iterations with increasing norm.
int nupdat
Number of iterations with updated tangent.
int saveIts
Time step for which iteration result should be saved.
char saveVelAc
Flag the saving of velocity and acceleration to VTF.
double rTol
Relative convergence tolerance.
double aTol
Absolute convergence tolerance.
double divgLim
Relative divergence limit.
unsigned short int cNorm
Option for which convergence norm to use.
std::string factor_file
File for storage of factorized Newton matrix.
bool write_factor
If true, write new factorized Newton matrix.
bool read_factor
If true, read factorized Newton matrix.
LinAlg::StorageFormat fmt
Factorized Newton matrix storage format.
Protected Attributes inherited from MultiStepSIM
SIMoutput & model
The isogeometric FE model.
Vector loadVec
System load vector (for output to VTF)
Vector residual
Residual force vector.
Vector linsol
Linear solution vector.
NormOp refNopt
Reference norm option.
double refNorm
Reference norm value used in convergence checks.
double rCond
Reciprocal condition number of the linear equation system.
SubIt subiter
Sub-iteration flag.
size_t nRHSvec
Number of right-hand-side vectors to assemble.
char rotUpd
Option for how to update of nodal rotations.
int geoBlk
Running VTF geometry block counter.
int nBlock
Running VTF result block counter.
Protected Attributes inherited from SIMsolution
Vectors solution
Stack of solution vectors.
Protected Attributes inherited from SIMadmin
ProcessAdm adm
Parallel administrator.
int myPid
Processor ID in parallel simulations.
int nProc
Number of processors in parallel simulations.
std::string myHeading
Heading written before reading the input file.
Additional Inherited Members
Public Types inherited from MultiStepSIM
enum SubIt { ITER = 0 , FIRST = 1 , LAST = 2 , NONE = 3 }
Enum describing sub-iteration status.
Public Attributes inherited from SIMadmin
SIMoptions & opt
Simulation control parameters.
Protected Types inherited from MultiStepSIM
enum NormOp { MAX , ALL }
Enum describing reference norm options.
Protected Types inherited from SIMsolution
using SerializeMap = std::map< std::string, std::string >
Convenience type.
Protected Types inherited from SIMadmin
using IntVec = std::vector< int >
Convenience alias.
Static Protected Member Functions inherited from SIMsolution
static std::string serialize (const double *v, size_t n)
Helper method for serializing a double array into a text string.
static void deSerialize (const std::string &data, double *v, size_t n)
Helper method for deserializing a double array from a text string.
Detailed Description
Newmark-based solution driver for dynamic isogeometric FEM simulators.
Member Function Documentation
advanceStep()
bool NewmarkSIM::advanceStep (TimeStep & param, bool updateTime = true) virtual
Advances the time step one step forward.
Reimplemented from MultiStepSIM.
Reimplemented in GenAlphaSIM.
References MultiStepSIM::advanceStep(), and SIMsolution::pushSolution().
Referenced by GenAlphaSIM::advanceStep().
correctStep()
bool NewmarkSIM::correctStep (TimeStep & param, bool = false) protected virtual
Updates configuration variables (solution vector) in an iteration.
Reimplemented in GenAlphaSIM, HHTSIM, and NewmarkNLSIM.
References beta, utl::debugPrint(), TimeDomain::dt, gamma, MultiStepSIM::linsol, MultiStepSIM::model, MultiStepSIM::rotUpd, SIMsolution::solution, solveDisp, TimeStep::time, SIMbase::updateConfiguration(), and SIMbase::updateRotations().
Referenced by solveIteration(), and solveStep().
dumpResults()
void NewmarkSIM::dumpResults (double time, utl::LogStream & os, std::streamsize precision = 3, bool formatted = true) const virtual
Dumps solution variables at user-defined points.
Parameters
[in] time Current time
[in] os The output stream to write the solution to
[in] precision Number of digits after the decimal point
[in] formatted If false, write all result points on a single line
Reimplemented from MultiStepSIM.
References SIMoutput::dumpMoreResults(), SIMoutput::dumpResults(), SIMoutput::dumpVector(), getAcceleration(), getVelocity(), MultiStepSIM::model, and MultiStepSIM::realSolution().
finalizeRHSvector()
void NewmarkSIM::finalizeRHSvector (bool) protected virtual
Finalizes the right-hand-side vector on the system level.
Reimplemented in HHTSIM, and NewmarkNLSIM.
References SIMbase::addToRHSvector(), SIMbase::getRHSvector(), MultiStepSIM::model, and MultiStepSIM::nRHSvec.
Referenced by solveIteration(), and solveStep().
initPrm()
void NewmarkSIM::initPrm () virtual
Initializes time integration parameters for the integrand.
Reimplemented from MultiStepSIM.
Reimplemented in GenAlphaSIM, HHTSIM, and NewmarkNLSIM.
References alpha1, alpha2, beta, gamma, SIMbase::initForMultiStep(), SIMbase::initLHSbuffers(), maxit, MultiStepSIM::model, MultiStepSIM::nRHSvec, nupdat, SIMbase::setIntegrationPrm(), and solveDisp.
isDynamic()
virtual bool NewmarkSIM::isDynamic () const inline virtual
Returns whether this is a dynamic solution driver or not.
Reimplemented from MultiStepSIM.
parse() [1/4]
bool SIMadmin::parse (char * keyWord, std::istream & is) virtual
Parses a data section from an input stream.
Reimplemented from MultiStepSIM.
parse() [2/4]
bool MultiStepSIM::parse (const tinyxml2::XMLElement * elem) virtual
Parses a data section from an XML document.
Parameters
[in] elem The XML element to parse
Reimplemented from MultiStepSIM.
parse() [3/4]
bool SIMadmin::parse (const tinyxml2::XMLElement * elem) virtual
Parses a data section from an XML document.
Reimplemented from MultiStepSIM.
parse() [4/4]
bool NewmarkSIM::parse (const tinyxml2::XMLElement * elem) virtual
Parses a data section from an XML document.
Reimplemented from MultiStepSIM.
Reimplemented in GenAlphaSIM, GenAlphaSIM, HHTSIM, HHTSIM, NewmarkNLSIM, and NewmarkNLSIM.
References alpha1, alpha2, aTol, beta, LinAlg::BINARY, cNorm, divgLim, factor_file, fmt, gamma, utl::getAttribute(), utl::getValue(), inputContext, maxIncr, maxit, MultiStepSIM::model, MultiStepSIM::nRHSvec, nupdat, SIMoutput::parse(), MultiStepSIM::parse(), predictor, MultiStepSIM::rCond, read_factor, MultiStepSIM::refNopt, MultiStepSIM::rotUpd, rTol, saveIts, saveVelAc, solveDisp, and write_factor.
Referenced by GenAlphaSIM::parse(), HHTSIM::parse(), and NewmarkNLSIM::parse().
predictStep()
bool NewmarkSIM::predictStep (TimeStep & param) protected virtual
Calculates predicted velocities and accelerations.
Reimplemented in GenAlphaSIM, HHTSIM, and NewmarkNLSIM.
References utl::vector< T >::add(), beta, utl::debugPrint(), TimeDomain::dt, gamma, SIMbase::getNoFields(), SIMbase::getNoNodes(), MultiStepSIM::model, predictor, MultiStepSIM::rotUpd, utl::vector< T >::size(), SIMsolution::solution, TimeStep::time, SIMbase::updateConfiguration(), and SIMbase::updateRotations().
Referenced by GenAlphaSIM::predictStep(), solveIteration(), and solveStep().
printProblem()
void NewmarkSIM::printProblem (bool stopInputTimer = false) const virtual
Prints out problem-specific data to the log stream.
Parameters
[in] stopInputTimer If true, stop file input timer before print
Reimplemented from MultiStepSIM.
Reimplemented in HHTSIM, and NewmarkNLSIM.
References alpha1, alpha2, beta, IFEM::cout, gamma, nupdat, predictor, MultiStepSIM::printProblem(), and solveDisp.
Referenced by HHTSIM::printProblem(), and NewmarkNLSIM::printProblem().
saveStep() [1/4]
bool MultiStepSIM::saveStep (int iStep, double time, const char * vecName = nullptr)
Saves the converged solution to VTF file of a given time/load step.
Parameters
[in] iStep Time/load step identifier
[in] time Current time/load parameter
[in] vecName Optional name of primary solution vector field
saveStep() [2/4]
bool MultiStepSIM::saveStep (int iStep, int & rBlock, const char * vecName)
Saves the converged solution to VTF file of a given time/load step.
Parameters
[in] iStep Time/load step identifier
rBlock Running result block counter
[in] vecName Name of primary solution vector field
This method only writes the primary solution vector as a vector field. It is mainly used when this simulator is a component in a coupled simulation, and where the secondary solution is of minor interest.
saveStep() [3/4]
bool MultiStepSIM::saveStep (int iStep, int & rBlock, double time, const char * vecName = nullptr)
Saves the converged solution to VTF file of a given time/load step.
Parameters
[in] iStep Time/load step identifier
rBlock Running result block counter
[in] time Current time/load parameter
[in] vecName Optional name of primary solution vector field
Use this method when other simulators write results to the same VTF-file. The internal result block counter nBlock is syncronized with the argument rBlock before the results of this simulator are written, to avoid that multiple result blocks receive the same result block ID.
saveStep() [4/4]
bool NewmarkSIM::saveStep (int iStep, TimeStep & param)
Saves the converged solution to VTF file for a given time step.
Parameters
[in] iStep Time step identifier
[in] param Time stepping parameters
References SIMbase::getNoFields(), MultiStepSIM::model, MultiStepSIM::nBlock, MultiStepSIM::numSolution(), saveStep(), saveVelAc, TimeDomain::t, TimeStep::time, and SIMoutput::writeGlvS1().
Referenced by saveStep(), and solveStep().
solutionNorms()
bool NewmarkSIM::solutionNorms (const TimeDomain & , double zero_tolerance = 1.0e-8, std::streamsize outPrec = 0) protected virtual
Computes and prints some solution norm quantities.
Parameters
[in] zero_tolerance Truncate norm values smaller than this to zero
[in] outPrec Number of digits after the decimal point in norm print
Reimplemented from MultiStepSIM.
References ProcessAdm::cout, SIMbase::getNoFields(), SIMadmin::getProcessAdm(), MultiStepSIM::model, SIMadmin::msgLevel, utl::LogStream::precision(), MultiStepSIM::realSolutions(), SIMbase::solutionNorms(), utl::trunc(), and utl::zero_print_tol.
Referenced by solveIteration(), and solveStep().
solveIteration()
SIM::ConvStatus NewmarkSIM::solveIteration (TimeStep & param)
Solves the linearized system of current iteration.
Parameters
[in] param Time stepping parameters
References SIMbase::assembleSystem(), checkConvergence(), correctStep(), SIMbase::extractLoadVec(), finalizeRHSvector(), TimeDomain::first, TimeStep::iter, MultiStepSIM::linsol, MultiStepSIM::model, SIMadmin::msgLevel, nupdat, predictStep(), MultiStepSIM::rCond, MultiStepSIM::residual, SIMbase::setMode(), SIMsolution::solution, solutionNorms(), SIMbase::solveEqSystem(), TimeDomain::t, TimeStep::time, and SIMbase::updateDirichlet().
solveStep()
SIM::ConvStatus NewmarkSIM::solveStep (TimeStep & param, SIM::SolutionMode = SIM::STATIC, double zero_tolerance = 1.0e-8, std::streamsize outPrec = 0) virtual
Solves the dynamic equations by a predictor/multi-corrector method.
Parameters
param Time stepping parameters
[in] zero_tolerance Truncate norm values smaller than this to zero
[in] outPrec Number of digits after the decimal point in norm print
Implements MultiStepSIM.
References SIMbase::assembleSystem(), LinAlg::BINARY, checkConvergence(), correctStep(), IFEM::cout, ProcessAdm::cout, TimeDomain::dt, SystemMatrix::dump(), SIMbase::dumpSolVec(), SIMbase::extractLoadVec(), factor_file, finalizeRHSvector(), TimeDomain::first, fmt, MultiStepSIM::getLastSavedStep(), SIMbase::getLHSmatrix(), SIMadmin::getProcessAdm(), TimeStep::iter, MultiStepSIM::linsol, SystemMatrix::load(), MultiStepSIM::loadVec, maxit, MultiStepSIM::model, SIMadmin::msgLevel, SIMoptions::nGauss, MultiStepSIM::nRHSvec, nupdat, SIMadmin::opt, predictStep(), MultiStepSIM::printStep(), PROFILE1, MultiStepSIM::rCond, read_factor, MultiStepSIM::residual, saveIts, saveStep(), SIMbase::setMode(), SIMbase::setQuadratureRule(), SIMsolution::solution, solutionNorms(), SIMbase::solveEqSystem(), SIMbase::solveSystem(), TimeStep::step, MultiStepSIM::subiter, TimeDomain::t, TimeStep::time, SIMbase::updateDirichlet(), and write_factor.
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/SIM/NewmarkSIM.h
/home/runner/work/IFEM-2/IFEM-2/src/SIM/NewmarkSIM.C