IFEM: ASMu3Dmx Class Reference
ASMu3Dmx Class Reference
Driver for assembly of unstructured 3D spline mixed FE models.
#include <ASMu3Dmx.h>
Public Member Functions
ASMu3Dmx (const CharVec &n_f)
The constructor initializes the dimension of each basis.
ASMu3Dmx (const ASMu3Dmx &patch, const CharVec &n_f=CharVec(3, 0))
Copy constructor.
virtual ~ASMu3Dmx ()=default
Empty destructor.
virtual const LR::LRSplineVolume * getBasis (int basis=1) const
Returns the spline volume representing a basis of this patch.
virtual LR::LRSplineVolume * getBasis (int basis=1)
Returns the spline volume representing a basis of this patch.
virtual bool readBasis (std::istream &is, size_t basis)
Reads a basis from the given input stream.
virtual bool generateFEMTopology ()
Generates the finite element topology data for the patch.
virtual void clear (bool retainGeometry)
Clears the contents of the patch, making it empty.
virtual size_t getNoBasis () const
Returns the number of bases.
virtual size_t getNoNodes (int basis) const
Returns the total number of nodes in this patch.
virtual unsigned char getNoFields (int basis) const
Returns the number of solution fields.
virtual unsigned char getNodalDOFs (size_t inod) const
Returns the number of DOFs per node.
virtual char getNodeType (size_t inod) const
Returns the classification of a node.
virtual Vec3 getCoord (size_t inod) const
Returns the global coordinates for the given node.
virtual void initMADOF (const int *sysMadof)
Initializes the patch level MADOF array for mixed problems.
virtual bool integrate (Integrand &integrand, GlobalIntegral &glbInt, const TimeDomain &time)
Evaluates an integral over the interior patch domain.
virtual bool integrate (Integrand &integrand, int lIndex, GlobalIntegral &glbInt, const TimeDomain &time)
Evaluates a boundary integral over a patch edge.
virtual bool getSolution (Matrix &sField, const Vector &locSol, const IntVec &nodes) const
Extracts the primary solution field at the specified nodes.
virtual bool evalSolution (Matrix &sField, const Vector &locSol, const RealArray *gpar, bool, int deriv, int nf) const
Evaluates the primary solution field at the given points.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const RealArray *gpar, bool) const
Evaluates the secondary solution field at the given points.
virtual void extractNodeVec (const RealArray &globVec, RealArray &nodeVec, unsigned char, int basis) const
Extracts nodal results for this patch from the global vector.
virtual bool injectNodeVec (const RealArray &nodeVec, RealArray &globVec, unsigned char, int basis) const
Injects nodal results for this patch into a global vector.
virtual size_t getNoRefineNodes () const
Returns the number of refinement nodes for this patch.
virtual size_t getNoRefineElms () const
Returns the number of refinement elements for this patch.
virtual bool refine (const LR::RefineData &prm, Vectors &sol)
Refines the mesh adaptively.
virtual void remapErrors (RealArray &errors, const RealArray &origErr, bool elemErrors) const
Remaps element-wise errors from geometry mesh to refinement mesh.
virtual bool separateProjectionBasis () const
Checks if a separate projection basis is used for this patch.
virtual bool evalSolution (Matrix &sField, const Vector &locSol, const int *npe, int n_f, bool piola) const
Evaluates the primary solution field at all visualization points.
virtual bool evalSolution (Matrix &sField, const Vector &locSol, const RealArray *gpar, bool=false, int deriv=0, int=0) const
Evaluates the primary solution field at the given points.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const int *npe, char project='\0') const
Evaluates the secondary solution field at all visualization points.
virtual LR::LRSpline * evalSolution (const IntegrandBase &integrand) const
Projects the secondary solution field onto the primary basis.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const RealArray *gpar, bool=false) const
Evaluates the secondary solution field at the given points.
virtual bool refine (int dir, const RealArray &xi)
Refines the parametrization by inserting extra tensor knots.
virtual bool refine (const LR::RefineData &prm, Vectors &sol)
Refines the mesh adaptively.
virtual bool refine (const LR::RefineData &prm, Vectors &sol)
Refines the mesh adaptively.
Public Member Functions inherited from ASMu3D
ASMu3D (unsigned char n_f=3)
Default constructor.
ASMu3D (const ASMu3D &patch, unsigned char n_f=0)
Copy constructor.
virtual ~ASMu3D ()
Empty destructor.
virtual bool read (std::istream &)
Creates an instance by reading the given input stream.
virtual bool write (std::ostream &, int) const
Writes the geometry of the SplineVolume object to given stream.
virtual bool getElementCoordinates (Matrix &X, int iel, bool forceItg=false) const
Returns a matrix with nodal coordinates for an element.
virtual void getElmConnectivities (IntMat &neighs, int basis=ASM::INTEGRATION_BASIS) const
Calculates the matrix of element neighbour connectivities.
virtual IntMat getElmNodes (int basis) const
Returns the matrix of nodal point correspondance for given basis.
virtual void getNodalCoordinates (Matrix &X, bool=false) const
Returns a matrix with all nodal coordinates within the patch.
virtual bool updateCoords (const Vector &displ)
Updates the nodal coordinates for this patch.
virtual void getBoundaryNodes (int lIndex, IntVec &nodes, int basis, int, int orient, bool local) const
Finds the global (or patch-local) node numbers on a patch boundary.
virtual void getBoundary1Nodes (int lEdge, IntVec &nodes, int basis, int orient, bool local, bool open=false) const
Finds the global (or patch-local) node numbers on a patch boundary.
virtual int getCorner (int I, int J, int K, int basis) const
Returns the node index for a given corner.
virtual bool getOrder (int &p1, int &p2, int &p3) const
Returns the polynomial order in each parameter direction.
virtual size_t getNoProjectionNodes () const
Returns the number of projection nodes for this patch.
virtual bool uniformRefine (int dir, int nInsert)
Refines the parametrization by inserting tensor knots uniformly.
virtual bool raiseOrder (int ru, int rv, int rw, bool setOrder)
Raises the order of the tensor spline object for this patch.
virtual bool createProjectionBasis (bool init)
Creates a separate projection basis for this patch.
virtual void setMinimumSize (double size)
Sets the minimum element volume for adaptive refinement.
virtual double getMinimumSize (int nrefinements) const
Defines the minimum element volume for adaptive refinement.
virtual bool checkElementSize (int elmId, bool globalNum=true) const
Checks if the specified element is larger than the minimum size.
void copyRefinement (LR::LRSplineVolume *basis, int multiplicity=1) const
Copies the refinement to another spline volume.
virtual void constrainFace (int dir, bool open, int dof, int code=0, char basis=1)
Constrains all DOFs on a given boundary face.
virtual size_t constrainFaceLocal (int dir, bool open, int dof, int code=0, bool project=false, char T1='\0')
Constrains all DOFs in local directions on a given boundary face.
virtual void constrainEdge (int lEdge, bool open, int dof, int code=0, char basis=1)
Constrains all DOFs on a given boundary edge.
virtual void constrainLine (int fdir, int ldir, double xi, int dof, int code=0, char basis=1)
Constrains all DOFs along a line on a given boundary face.
virtual void constrainCorner (int I, int J, int K, int dof, int code=0, char basis=1)
Constrains a corner node identified by the three parameter indices.
virtual void constrainNode (double xi, double eta, double zeta, int dof, int code=0)
Constrains a node identified by three relative parameter values.
virtual bool connectPatch (int face, ASM3D &neighbor, int nface, int norient, int=0, bool coordCheck=true, int thick=1)
Connects all matching nodes on two adjacent boundary faces.
virtual void getNoBouPoints (size_t &nPt, char ldim, char lindx)
Computes the number of boundary integration points in this patch.
virtual bool integrateEdge (Integrand &integrand, int lEdge, GlobalIntegral &glbInt, const TimeDomain &time)
Evaluates a boundary integral over a patch edge.
virtual bool diracPoint (Integrand &integrand, GlobalIntegral &glbInt, const double *param, const Vec3 &pval)
Integrates a spatial dirac-delta function over a patch.
virtual bool updateDirichlet (const std::map< int, RealFunc * > &func, const std::map< int, VecFunc * > &vfunc, double time, const std::map< int, int > *g2l=nullptr, bool tangent=false)
Updates the time-dependent in-homogeneous Dirichlet coefficients.
virtual int evalPoint (const double *xi, double *param, Vec3 &X) const
Evaluates the geometry at a specified point.
virtual int findElementContaining (const double *param) const
Returns the element that contains a specified spatial point.
virtual double findPoint (Vec3 &X, double *param) const
Searches for the specified Cartesian point in the patch.
virtual bool getGridParameters (RealArray &prm, int dir, int nSegSpan) const
Calculates parameter values for visualization nodal points.
virtual bool tesselate (ElementBlock &grid, const int *npe) const
Creates a hexahedron element model of this patch for visualization.
virtual bool evalProjSolution (Matrix &sField, const Vector &locSol, const int *npe, int n_f) const
Evaluates the projected solution field at all visualization points.
virtual bool evaluate (const FunctionBase *func, RealArray &vec, int, double time) const
Evaluates and interpolates a function over a given geometry.
virtual Field * getProjectedField (const Vector &coefs) const
Returns a field using the projection basis.
virtual Fields * getProjectedFields (const Vector &coefs, size_t=0) const
Returns a field using the projection basis.
void setOutputMaster (const ASMu3D *pch)
Sets the master patch to use for VTF- and HDF5-output.
virtual const ASMbase * getOutputMaster () const
Returns the master patch to use for VTF- and HDF5-output.
bool faceL2projection (const DirichletFace &face, const FunctionBase &values, Real2DMat &result, double time, bool tangent=false) const
Projects inhomogenuous dirichlet conditions by continuous L2-fit.
virtual bool transferGaussPtVars (const LR::LRSpline *old_basis, const RealArray &oldVar, RealArray &newVar, int nGauss) const
Transfers Gauss point variables from old basis to this patch.
virtual bool transferGaussPtVarsN (const LR::LRSpline *old_basis, const RealArray &oldVar, RealArray &newVar, int nGauss) const
Transfers Gauss point variables from old basis to this patch.
virtual bool transferCntrlPtVars (const LR::LRSpline *old_basis, RealArray &newVar, int nGauss) const
Transfers control point variables from old basis to this patch.
virtual size_t getNoBoundaryElms (char lIndex, char ldim) const
Returns the number of elements on a boundary.
virtual bool transferCntrlPtVars (const LR::LRSpline *oldBasis, RealArray &newVar, int nGauss) const=0
Transfers control point variables from old basis to this patch.
bool transferCntrlPtVars (LR::LRSpline *oldBasis, const RealArray &oldVar, RealArray &newVar, int nGauss, int nf=1) const
Transfers control point variables from old basis to this patch.
Public Member Functions inherited from ASMLRSpline
virtual ~ASMLRSpline ()
Empty destructor.
virtual bool empty () const
Checks if the patch is empty.
virtual bool getParameterDomain (Real2DMat &, IntVec *) const
Returns parameter values and node numbers of the domain corners.
const LR::LRSpline * getRefinementBasis () const
Returns a const pointer to refinement basis.
IntVec getFunctionsForElements (const IntVec &elements, bool globalId=false) const
Returns a list of basis functions having support on given elements.
void getFunctionsForElements (IntSet &functions, const IntVec &elements, bool globalId=true) const
Returns a list of basis functions having support on given elements.
virtual IntVec getBoundaryCovered (const IntSet &nodes) const
Returns all boundary functions that are covered by the given nodes.
IntVec getOverlappingNodes (const IntSet &nodes, int dir=7) const
Returns all functions whose support overlap with the input nodes.
IntVec getOverlappingNodes (int node, int dir=7) const
Returns all functions whose support overlap with the input node.
bool transferCntrlPtVars (LR::LRSpline *oldBasis, const RealArray &oldVar, RealArray &newVar, int nGauss, int nf=1) const
Transfers control point variables from old basis to this patch.
virtual std::pair< size_t, double > findClosestNode (const Vec3 &X) const
Finds the node that is closest to the given point X.
virtual Vec3 getElementCenter (int iel) const
Returns the coordinates of the element center.
virtual void getNoIntPoints (size_t &nPt, size_t &nIPt)
Computes the total number of integration points in this patch.
virtual void swapProjectionBasis ()
Swaps between the first and second projection basis.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const IntVec &elements) const
Evaluates the secondary solution field at element centers.
Public Member Functions inherited from ASMbase
virtual ~ASMbase ()
The destructor frees the dynamically allocated data objects.
ASMbase * cloneUnShared () const
Returns a copy of this patch with identical FE discretization.
virtual void addHole (double, double, double)
Adds a circular immersed boundary in the physical geometry.
virtual void addHole (double, double, double, double, double)
Adds an oval immersed boundary in the physical geometry.
virtual bool setGeometry (RealFunc *, double, double)
Defines the immersed geometry from a scalar function.
virtual bool addXElms (short int dim, short int item, size_t nXn, IntVec &nodes)
Adds extraordinary elements associated with a patch boundary.
bool addLagrangeMultipliers (size_t iel, const IntVec &mGLag, unsigned char nnLag=1)
Adds a set of Lagrange multipliers to the specified element.
bool addGlobalLagrangeMultipliers (const IntVec &mGLag, unsigned char nnLag=1)
Adds global Lagrange multipliers to the system.
virtual void setGauss (int ng)
Defines the numerical integration scheme nGauss in the patch.
void setNoFields (unsigned char n)
Defines the number of solution fields in the patch.
void setElementActivator (IntFunc *efunc)
Sets the element activation function.
const IntFunc * getElementActivator () const
Returns a pointer to the element activation function.
unsigned char getNoSpaceDim () const
Returns the number of spatial dimensions.
unsigned char getNoParamDim () const
Returns the number of parameter dimensions.
unsigned char getNoLagPerNode () const
Returns the number of Lagrange multipliers per node.
virtual size_t getNodeIndex (int globalNum, bool=false) const
Returns local 1-based index of the node with given global number.
virtual int getNodeID (size_t inod, bool=false) const
Returns the global node number for the given node.
size_t getElmIndex (int globalNum) const
Returns local 1-based index of element with given global number.
int getElmID (size_t iel) const
Returns the global element number for the given element.
bool isLMn (size_t n) const
Returns true if node n is a Lagrange multiplier node.
bool isRMn (size_t n) const
Returns true if node n is a master node of a rigid coupling.
char getLMType (size_t inod) const
Returns the type of a Lagrange multiplier node.
void getBoundaryElms (int lIndex, IntVec &elms, int orient=-1, bool local=false) const
Finds the global (or patch-local) element numbers on a boundary.
int getNodeSetIdx (const std::string &setName) const
Returns (1-based) index of a predefined node set in the patch.
const IntVec & getNodeSet (int iset) const
Returns an indexed predefined node set.
IntVec & getNodeSet (const std::string &setName, int &idx)
Returns a named node set for update.
bool isInNodeSet (int iset, int inod) const
Checks if node inod is within predefined node set iset.
int parseNodeSet (const std::string &setName, const char *cset, bool assumeZeroBased=false)
Defines a node set by parsing a list of node numbers.
virtual int parseNodeBox (const std::string &, const char *)
Defines a node set by parsing a 3D bounding box.
void convertNodeSets ()
Converts node number sets to internal (1-based) node indices.
virtual int getElementSetIdx (const std::string &) const
Returns (1-based) index of a predefined element set in the patch.
virtual const IntVec & getElementSet (int) const
Returns an indexed predefined element set.
virtual bool getElementSet (int, std::string &) const
Returns the name of an indexed predefined element set.
virtual bool isInElementSet (int, int) const
Checks if an element is within a predefined element set.
virtual int parseElemSet (const std::string &, const char *)
Defines an element set by parsing a list of element numbers.
virtual int parseElemBox (const std::string &, const std::string &, const char *)
Defines an element set by parsing a 3D bounding box.
void printNodes (std::ostream &os) const
Prints out the nodal coordinates of this patch to the given stream.
void printElements (std::ostream &os) const
Prints out element connections of this patch to the given stream.
virtual void printElmInfo (int, const IntegrandBase *) const
Prints out additional app-dependent element information.
virtual void shiftGlobalNodeNums (int nshift)
Increase all global node numbers by nshift.
void setGlobalNodeNums (const IntVec &nodes)
Sets the global node numbers for this patch.
const IntVec & getMyNodeNums () const
Returns the actual global node numbers of this patch.
const IntVec & getGlobalNodeNums () const
Returns the global node numbers of this patch.
virtual void shiftGlobalElmNums (int eshift)
Increase all global element numbers by eshift.
const IntVec & getGlobalElementNums () const
Returns the global element numbers of this patch.
void setActiveElements (IntVec *active)
Sets the list of active elements during assembly.
bool isElementActive (int iel, double time=-1.0) const
Returns true if element with 0-based index iel is active.
bool inActive (double time=-1.0) const
Returns true if none of the elements in the patch are active.
double getAge (int iel, double time) const
Returns the age of the element with 0-based index iel.
bool isElementInPartition (int iel) const
Returns true if element is in process partition.
const IntVec & getElementNodes (int iel) const
Returns the nodal point correspondance array for an element.
size_t getNoElms (bool includeZeroVolElms=false, bool includeXElms=false) const
Returns the total number of elements in this patch.
int getMaxElmNo () const
Returns the highest external element number in this patch.
size_t getNoMPCs () const
Returns the total number of multi-point constraint equations.
BCVec::const_iterator begin_BC () const
Returns the beginning of the BCode array.
BCVec::const_iterator end_BC () const
Returns the end of the BCode array.
IntMat::const_iterator begin_elm () const
Returns the beginning of the MNPC array.
IntMat::const_iterator end_elm () const
Returns the end of the MNPC array.
MPCIter begin_MPC () const
Returns the beginning of the mpcs set.
MPCIter end_MPC () const
Returns the end of the mpcs set.
MPC * findMPC (int node, int dof) const
Returns a pointer to the MPC object for a specified slave, if any.
bool isShared () const
Returns true if this patch shares FE data with another patch.
bool hasXNodes () const
Returns true if this patch has additional (extraordinary) nodes.
virtual void copyParameterDomain (const ASMbase *)
Copies the parameter domain from another patch.
virtual void closeBoundaries (int dir=1, int basis=0, int master=1)
Makes two opposite boundaries periodic.
bool mergeNodes (size_t inod, int globalNum, bool verbose=true)
Merges a given node in this patch with a given global node.
int renumberNodes (std::map< int, int > &old2new, int &nNod)
Renumbers the global node numbers in this patch.
bool renumberNodes (const std::map< int, int > &old2new, const std::vector< int > &new2old={}, int renumGN=0, std::map< int, int > *degenElm=nullptr)
Renumbers the global node numbers referred by this patch.
virtual bool initConstraints ()
Initializes the multi-point constraint coefficients.
virtual void setNodeNumbers (const IntVec &nodes)
Sets the global node numbers for this patch.
bool hasTimeDependentDirichlet (const std::map< int, RealFunc * > &func, const std::map< int, VecFunc * > &vfunc)
Checks for time-dependent in-homogeneous Dirichlet conditions.
virtual bool transform (const Matrix &)
Applies a transformation matrix from local to global system.
virtual void generateThreadGroups (char, bool, bool)
Generates element groups for multi-threading of boundary integrals.
virtual bool validateThreadGroups (const SAM *) const
Validates the threading groups based on the assembly data in SAM.
virtual bool integrate (Integrand &integrand, GlobalIntegral &glbInt, const TimeDomain &time, const ASM::InterfaceChecker &iChk)
Evaluates an integral over element interfaces in the patch.
virtual ElementBlock * immersedGeometry (char *) const
Returns an additional geometry to visualize (immersed boundaries).
virtual ElementBlock * extraGeometry (char *) const
Returns an additional geometry to visualize (spiders, etc.).
virtual void filterResults (Matrix &, const ElementBlock *) const
Filters out result point values that are outside physical domain.
virtual bool immersedSolution (Matrix &, const Vector &) const
Evaluates the primary solution at the immersed geometry points.
virtual bool extraSolution (Matrix &, const Vector &) const
Evaluates the primary solution at the extra geometry points.
virtual bool evalSolutionPiola (Matrix &sField, const Vector &locSol, const RealArray *gpar, bool regular) const
Evaluates the primary solution field with Piola mapping.
virtual bool evaluate (const ASMbase *basis, const Vector &locVec, RealArray &vec, int basisNum=1) const
Evaluates and interpolates a field over a given geometry.
virtual bool evaluate (const Field *f, RealArray &vec, int basisNum=1) const
Evaluates and interpolates a scalar field over a given geometry.
bool globalL2projection (Matrix &sField, const L2Integrand &integrand, bool continuous=false, bool enforceEnds=false) const
Projects the secondary solution using a (discrete) global L2-fit.
bool L2projection (Matrix &sField, IntegrandBase *integrand, const TimeDomain &time)
Projects the secondary solution using a continuous global L2-fit.
bool L2projection (Matrix &fVals, FunctionBase *func, double t=0.0)
Projects an explicit function using a continuous global L2-fit.
bool L2projection (const std::vector< Matrix * > &fVals, const std::vector< FunctionBase * > &funcs, double t=0.0)
Projects explicit functions using a continuous global L2-fit.
void extractElmRes (const Vector &globRes, Vector &elmRes, size_t internalFirst=0) const
Extracts element results for this patch from a global vector.
void extractElmRes (const Matrix &globRes, Vector &elmRes, size_t irow) const
Extracts element results for this patch from a global matrix.
bool extractNodalVec (const RealArray &globVec, RealArray &nodeVec, const int *madof, int ngnod=-1) const
Extracts nodal results for this patch from the global vector.
bool injectNodalVec (const RealArray &nodeVec, RealArray &globVec, const IntVec &madof, int basis=0) const
Injects nodal results for this patch into the global vector.
bool add2PC (int slave, int dir, int master, int code=0)
Creates and adds a two-point constraint to this patch.
bool addMPC (MPC *&mpc, int code=0, bool verbose=false, bool overrideD=false)
Adds a general multi-point-constraint (MPC) equation to this patch.
virtual bool addRigidCpl (int lindx, int ldim, int basis, int &gMaster, const Vec3 &Xmaster, bool extraPt=true)
Adds MPC-equations representing a rigid coupling to this patch.
void addRigidCouplings (int gMaster, const Vec3 &Xmaster, const IntVec &slaveNodes)
Adds MPC-equations representing a rigid coupling to this patch.
void addNodalCouplings (int slave, const IntVec &masters, const RealArray &weights)
Adds MPC-equations for general nodal couplings in this patch.
void constrainPatch (int dof, int code=0)
Constrains all nodes in the patch.
void constrainNodes (const IntVec &nodes, int dof, int code=0, bool overrideD=false)
Constrains a list of nodes in the patch.
bool constrainXnode (int node, int dof, int code=0)
Constrains an extraordinary node in the patch.
int prescribe (size_t inod, int dirs, int code, bool overrideD=false)
Constrains DOFs in the given node to the given value.
int fix (size_t inod, int dirs=123)
Constrains DOFs in the given node to zero.
bool isFixed (int node, int dof, bool all=false) const
Checks if the given DOFs are fixed.
virtual bool selfInterconnect (const std::vector< Ipair > &nodes, double xtol=1.0e-8)
Connects a list of node pairs to each other.
Public Member Functions inherited from ASMunstruct
virtual ~ASMunstruct ()
Empty destructor.
virtual void storeMesh (const std::string &fName, int fType=15) const
Stores the mesh basis to encapsulated postscript files.
Public Member Functions inherited from ASM3D
virtual ~ASM3D ()
Empty destructor.
ASMbase * clone (const CharVec &nf=CharVec()) const
Returns a copy of this patch with identical FE discretization.
virtual bool checkRightHandSystem ()
Checks that the patch is modelled in a right-hand-side system.
virtual bool refine (int dir, const std::vector< double > &xi)=0
Refines the parametrization by inserting extra knots.
virtual bool getGridParameters (std::vector< double > &prm, int dir, int nSegSpan) const =0
Calculates parameter values for visualization nodal points.
Protected Member Functions
void generateThreadGroups (const Integrand &integrand, bool silence, bool ignoreGlobalLM)
Generates element groups for multi-threading of interior integrals.
Protected Member Functions inherited from ASMu3D
LR::LRSplineVolume * projectSolution (const IntegrandBase &integrand) const
Projects the secondary solution field onto the primary basis.
LR::LRSplineVolume * scRecovery (const IntegrandBase &integrand) const
Projects the secondary solution using a superconvergent approach.
LR::LRSplineVolume * regularInterpolation (const RealArray &upar, const RealArray &vpar, const RealArray &wpar, const Matrix &points, int basis) const
Interpolates an LR spline at a given set of parametric coordinates.
virtual void findBoundaryElms (IntVec &elms, int lIndex, int orient) const
Finds the patch-local element numbers on a patch boundary.
virtual bool assembleL2matrices (SystemMatrix &A, SystemVector &B, const L2Integrand &integrand, bool continuous) const
Assembles L2-projection matrices for the secondary solution.
bool connectBasis (int face, ASMu3D &neighbor, int nface, int norient, int basis=1, int slave=0, int master=0, bool coordCheck=true, int thick=1)
Connects all matching nodes on two adjacent boundary faces.
void getGaussPointParameters (RealArray &uGP, int dir, int nGauss, int iel, const double *xi, const LR::LRSplineVolume *spline=nullptr) const
Extracts parameter values of the Gauss points in one direction.
bool getGrevilleParameters (RealArray &prm, int dir, int basisNum=1) const
Calculates parameter values for the Greville points.
bool getQuasiInterplParameters (RealArray &prm, int dir) const
Calculates parameter values for the Quasi-Interpolation points.
double getParametricArea (int iel, int dir) const
Returns boundary face area in the parameter space for an element.
double getElementCorners (int iel, std::vector< Vec3 > &XC, RealArray *uC=nullptr) const
Computes the element corner coordinates.
void getCornerPoints (int iel, std::vector< utl::Point > &XC) const
Computes the element corner coordinates and parameters.
void evaluateBasis (int iel, double u, double v, double w, Vector &N, Matrix &dNdu, int basis=1) const
Evaluate all basis functions and first derivatives on one element.
void evaluateBasis (Vector &N, Matrix &dNdu, const Matrix &C, const Matrix &B) const
Evaluate all basis functions and first derivatives on one element.
void evaluateBasis (int iel, FiniteElement &fe, Matrix &dNdu, int basis=1) const
Evaluate all basis functions and first derivatives on one element.
void evaluateBasis (int iel, double u, double v, double w, Vector &N, Matrix &dNdu, Matrix3D &d2Ndu2, int basis=1) const
Evaluate all basis functions and second order derivatives on one element.
virtual int evalPoint (int iel, const double *param, Vec3 &X) const
Evaluates the geometry at a specified point.
virtual void generateThreadGroupsFromElms (const IntVec &elms)
Generate element groups from a partition.
virtual void generateProjThreadGroupsFromElms (const IntVec &elms)
Generate element groups from a partition.
virtual void changeNumThreads ()
Hook for changing number of threads.
virtual void extendRefinementDomain (IntSet &refineIndices, const IntSet &neighborIndices) const
Extends the refinement domain with information for neighbors.
std::shared_ptr< LR::LRSplineVolume > createLRfromTensor ()
Converts current tensor spline object to LR-spline.
Protected Member Functions inherited from ASMLRSpline
ASMLRSpline (unsigned char n_p, unsigned char n_s, unsigned char n_f)
The constructor sets the space dimensions.
ASMLRSpline (const ASMLRSpline &patch, unsigned char n_f)
Special copy constructor for sharing of FE data.
bool doRefine (const LR::RefineData &prm, LR::LRSpline *lrspline)
Refines the mesh adaptively.
Protected Member Functions inherited from ASMbase
ASMbase (unsigned char n_p, unsigned char n_s, unsigned char n_f)
The constructor sets the number of space dimensions and fields.
ASMbase (const ASMbase &patch, unsigned char n_f)
Special copy constructor for sharing of FE data.
ASMbase (const ASMbase &patch)
Default copy constructor, copying everything except neighbors.
void addLocal2GlobalCpl (int iSlave, int master, const Tensor &Tlg)
Creates constraint equations coupling global DOFs to local DOFs.
bool add3PC (int slave, int dir, int master1, int master2, int code=0)
Creates and adds a three-point constraint to this patch.
bool addPeriodicity (size_t master, size_t slave, int dir)
Creates and adds a periodicity constraint to this patch.
void makePeriodic (size_t master, size_t slave, int dirs=123)
Creates periodicity constraints between two nodes in this patch.
void addNeighbor (ASMbase *pch)
Adds a patch to the list of neighbors of this patch.
bool createRgdMasterNode (int &gMaster, const Vec3 &Xmaster)
Creates an additional master node for a rigid coupling.
void addRigidMPC (int gSlave, int gMaster, const Vec3 &dX)
Adds MPC-equations representing a rigid arm to a 6-DOF node.
int getNoGaussPt (int p, bool neumann=false) const
Returns the number of Gauss points to use in one direction.
int searchCtrlPt (RealArray::const_iterator cit, RealArray::const_iterator end, const Vec3 &X, int dimension, double xtol=0.001) const
Helper method used by evalPoint to search for a control point.
bool allDofs (int dirs) const
Returns true if dirs constains all local DOFs in the patch.
bool writeLagBasis (std::ostream &os, const char *type) const
Writes a Lagrangian basis to the given stream.
Protected Member Functions inherited from ASMunstruct
ASMunstruct ()
The constructor is protected to allow objects of sub-classes only.
Protected Member Functions inherited from ASM3D
ASM3D ()
The constructor is protected to allow objects of sub-classes only.
Private Types
using SplinePtr = std::shared_ptr< LR::LRSplineVolume >
Pointer to spline.
Private Types inherited from ASMmxBase
enum MixedType {
NONE = 0 , FULL_CONT_RAISE_BASIS1 , REDUCED_CONT_RAISE_BASIS1 , FULL_CONT_RAISE_BASIS2 ,
REDUCED_CONT_RAISE_BASIS2 , DIV_COMPATIBLE , SUBGRID
}
Enum defining available mixed formulation types.
typedef std::vector< std::shared_ptr< Go::SplineSurface > > SurfaceVec
Convenience type.
typedef std::vector< std::shared_ptr< Go::SplineVolume > > VolumeVec
Convenience type.
Private Member Functions
void getElementsAt (const RealArray &param, std::vector< int > &elms, std::vector< size_t > *sizes=nullptr) const
Finds the elements and associted sizes at given parametric point.
Private Member Functions inherited from ASMmxBase
ASMmxBase (const std::vector< unsigned char > &n_f)
The constructor sets the number of field variables.
void initMx (const std::vector< int > &MLGN, const int *sysMadof)
Initializes the patch level MADOF array.
void extractNodeVecMx (const RealArray &glbVec, RealArray &nodVec, int basis) const
Extracts nodal results for this patch from the global vector.
void injectNodeVecMx (RealArray &glbVec, const RealArray &nodVec, int basis) const
Injects nodal results for this patch into a global vector.
bool getSolutionMx (Matrix &sField, const Vector &locSol, const std::vector< int > &nodes) const
Extracts the primary solution field at the specified nodes.
Private Attributes
std::vector< SplinePtr > m_basis
All bases.
LR::LRSplineVolume * threadBasis
Basis for thread groups.
Private Attributes inherited from ASMmxBase
bool piola = false
True if last used integrand was Piola mapped.
std::vector< size_t > elem_size
Number of basis functions per element in each basis.
std::vector< size_t > nb
Total number of basis functions in each basis.
std::vector< unsigned char > nfx
Number of fields on each basis.
Additional Inherited Members
Public Types inherited from ASMbase
using BCVec = std::vector< BC >
Nodal boundary condition container.
Public Types inherited from ASM3D
typedef std::vector< unsigned char > CharVec
Convenience type.
Static Public Member Functions inherited from ASMLRSpline
static Go::BsplineBasis getBezierBasis (int p, double start=-1.0, double end=1.0)
Returns a Bezier basis of order p.
static void Sort (int u, int v, int orient, std::vector< LR::Basisfunction * > &functions)
Sort basis functions based on local knot vectors.
Static Public Member Functions inherited from ASMbase
static void resetNumbering (int n=0)
Resets the global element and node counters.
static int renumberNodes (const ASM::PatchVec &model, std::map< int, int > &old2new)
Renumbers all global node numbers in the entire model.
static void mergeAndGetAllMPCs (const ASM::PatchVec &model, MPCSet &allMPCs)
Computes the set of all MPC-equations over the whole model.
static void resolveMPCchains (const MPCSet &allMPCs, const ASM::PatchVec &model, bool setPtrOnly=false)
Resolves (possibly multi-level) chaining in MPC-equations.
Static Public Member Functions inherited from ASM3D
static ASMbase * create (ASM::Discretization type, const CharVec &nf, bool mixedFEM=false)
Creates a three-parametric patch of specified discretization type.
static ASMbase * create (ASM::Discretization type, unsigned char nf=1)
Creates a three-parametric patch of specified discretization type.
Public Attributes inherited from ASMbase
size_t idx
Index of this patch in the multi-patch model.
Static Public Attributes inherited from ASMbase
static bool fixHomogeneousDirichlet = true
If true, pre-eliminate fixed DOFs.
static int dbgElm = 0
One-based element index to print debugging info for.
static double modelSize = 1.0
Characteristic model size.
Protected Types inherited from ASMbase
using XYZ = std::array< double, 3 >
Convenience type definition.
Static Protected Member Functions inherited from ASMLRSpline
static bool checkThreadGroups (const IntMat &groups, const std::vector< const LR::LRSpline * > &bases, const LR::LRSpline *threadBasis)
Santity check thread groups.
Static Protected Member Functions inherited from ASMbase
static bool deformedConfig (const Matrix &Xnod, Vectors &eVec, bool force2nd=false)
Calculates the deformed configuration for current element.
static bool collapseNodes (ASMbase &pch1, int node1, ASMbase &pch2, int node2)
Collapses the given two nodes into one.
Static Protected Member Functions inherited from ASM3D
static double getElementSize (const std::vector< Vec3 > &XC)
Returns characteristic element size based on corner coordinates.
Protected Attributes inherited from ASMu3D
std::shared_ptr< LR::LRSplineVolume > lrspline
The LR-spline volume object.
const ASMu3D * outputMaster = nullptr
Master patch to use for VTF output.
Go::SplineVolume * tensorspline
Pointer to original tensor spline object.
Go::SplineVolume * tensorPrjBas
Pointer to tensor spline projection base.
std::vector< DirichletFace > dirich
Inhomogeneous Dirichlet boundary condition data.
const Matrices & bezierExtract
Bezier extraction matrices.
Matrices myBezierExtract
Bezier extraction matrices.
std::vector< std::unique_ptr< BasisFunctionCache > > myCache
Basis function cache.
Protected Attributes inherited from ASMLRSpline
std::shared_ptr< LR::LRSpline > geomB
Pointer to spline object of the geometry basis.
std::shared_ptr< LR::LRSpline > projB
Pointer to spline object of the projection basis.
std::shared_ptr< LR::LRSpline > projB2
Pointer to spline object of the secondary projection basis.
std::shared_ptr< LR::LRSpline > refB
Pointer to spline object of the refinement basis.
ThreadGroups threadGroups
Element groups for multi-threaded assembly.
ThreadGroups projThreadGroups
Element groups for multi-threaded assembly - projection basis.
ThreadGroups proj2ThreadGroups
Element groups for multi-threaded assembly - second projection basis.
Protected Attributes inherited from ASMbase
unsigned char ndim
Number of parametric dimensions (1, 2 or 3)
unsigned char nsd
Number of space dimensions (ndim <= nsd <= 3)
unsigned char nf
Number of primary solution fields (1 or larger)
unsigned char nLag
Number of Lagrange multipliers per node.
size_t nel
Number of regular elements in this patch.
size_t nnod
Number of regular nodes in this patch.
const IntVec & MLGE
Matrix of Local to Global Element numbers.
const IntVec & MLGN
Matrix of Local to Global Node numbers.
const IntMat & MNPC
Matrix of Nodal Point Correspondance.
const char shareFE
Flag telling whether this patch shares its data with another patch.
BCVec BCode
Array of Boundary Condition codes.
MPCMap dCode
Inhomogeneous Dirichlet condition codes for the MPCs.
MPCSet mpcs
All multi-point constraints with the slave in this patch.
std::vector< ASM::NodeSet > nodeSets
Node sets for explicit Dirichlet BCs.
IntVec myMLGE
The actual Matrix of Local to Global Element numbers.
IntVec myMLGN
The actual Matrix of Local to Global Node numbers.
IntMat myMNPC
The actual Matrix of Nodal Point Correspondance.
IntVec myElms
Elements on patch - used with partitioning.
int nGauss
Numerical integration scheme for this patch.
size_t firstEl
Global index to first element within this patch.
size_t firstIp
Global index to first interior integration point.
std::map< char, size_t > firstBp
Global indices to first integration point for the Neumann boundaries.
ASM::PatchVec neighbors
Patches having nodes in common with this one.
std::map< size_t, XYZ > myRmaster
Rigid master nodal points.
Static Protected Attributes inherited from ASMbase
static std::map< int, int > xNode
Auxilliary node number map used when establishing Dirichlet constraints.
static int gEl = 0
Global element counter.
static int gNod = 0
Global node counter.
Static Private Member Functions inherited from ASMmxBase
static SurfaceVec establishBases (Go::SplineSurface *surf, MixedType type)
Establish mixed bases in 2D.
static VolumeVec establishBases (Go::SplineVolume *svol, MixedType type)
Establish mixed bases in 3D.
static Go::SplineSurface * adjustBasis (const Go::SplineSurface &surf, const std::array< SplineUtils::AdjustOp, 2 > &ops)
Returns a C^p-1 basis of one degree higher than *surf.
static Go::SplineVolume * adjustBasis (const Go::SplineVolume &svol, const std::array< SplineUtils::AdjustOp, 3 > &ops)
Returns a C^p-1 basis of one degree higher than *svol.
Static Private Attributes inherited from ASMmxBase
static MixedType Type = ASMmxBase::FULL_CONT_RAISE_BASIS1
Type of mixed formulation used.
static char itgBasis = 2
1-based index of basis representing the integration elements
static bool includeExtra = false
True to include extra basis (geometry/projection) as FE basis.
Detailed Description
Driver for assembly of unstructured 3D spline mixed FE models.
This class implements a two-field mixed formulation with splines as basis functions. The first field is of one order higher than the second field, and its basis is obtained by order-elevating the input spline object once. By default, the geometry is represented by the second (lower order) basis, however, by negating the n_f1 argument to the constructor, the first basis is used instead.
Member Function Documentation
clear()
void ASMu3Dmx::clear (bool retainGeometry) virtual
Clears the contents of the patch, making it empty.
Parameters
[in] retainGeometry If true, the spline geometry is not cleared. This is used to reinitialize the patch after it has been refined.
Reimplemented from ASMu3D.
References ASMu3D::clear(), and m_basis.
evalSolution() [1/7]
LR::LRSpline * ASMu3D::evalSolution (const IntegrandBase & integrand) const virtual
Projects the secondary solution field onto the primary basis.
Parameters
[in] integrand Object with problem-specific data and methods
Reimplemented from ASMu3D.
evalSolution() [2/7]
bool ASMu3D::evalSolution (Matrix & sField, const IntegrandBase & integrand, const int * npe, char project = '\0') const virtual
Evaluates the secondary solution field at all visualization points.
Parameters
[out] sField Solution field
[in] integrand Object with problem-specific data and methods
[in] npe Number of visualization nodes over each knot span
[in] project Flag indicating result recovery method (0=none, 'D'=direct evaluation, 'S'=superconvergent recovery)
The secondary solution is derived from the primary solution, which is assumed to be stored within the integrand for current patch. If npe is null, the solution is recovered or evaluated at the Greville points and then projected onto the spline basis to obtain the control point values, which then are returned through sField. If npe is not null and project is defined, the solution is also projected onto the spline basis, and then evaluated at the npe points.
Reimplemented from ASMu3D.
evalSolution() [3/7]
bool ASMu3Dmx::evalSolution (Matrix & sField, const IntegrandBase & integrand, const RealArray * gpar, bool) const virtual
Evaluates the secondary solution field at the given points.
Parameters
[out] sField Solution field
[in] integrand Object with problem-specific data and methods
[in] gpar Parameter values of the result sampling points
The secondary solution is derived from the primary solution, which is assumed to be stored within the integrand for current patch. When regular is true, it is assumed that the parameter value array gpar forms a regular tensor-product point grid of dimension gpar[0].size() X gpar[1].size(). Otherwise, we assume that it contains the u and v parameters directly for each sampling point.
Reimplemented from ASMu3D.
References utl::matrixBase< T >::empty(), IntegrandBase::evalSol(), SplineUtils::extractBasis(), utl::matrix< T >::fillColumn(), ASMbase::firstIp, ASM::GEOMETRY_BASIS, getBasis(), ASMu3D::getElementCoordinates(), getElementsAt(), Integrand::getIntegrandType(), ASMmxBase::itgBasis, ASMu3D::lrspline, m_basis, ASMbase::MNPC, ASMmxBase::nb, utl::matrix< T >::resize(), Integrand::SECOND_DERIVATIVES, and utl::matrixBase< T >::size().
evalSolution() [4/7]
bool ASMu3D::evalSolution (Matrix & sField, const IntegrandBase & integrand, const RealArray * gpar, bool = false) const virtual
Evaluates the secondary solution field at the given points.
Parameters
[out] sField Solution field
[in] integrand Object with problem-specific data and methods
[in] gpar Parameter values of the result sampling points
The secondary solution is derived from the primary solution, which is assumed to be stored within the integrand for current patch. We assume that the parameter value array gpar contains the u, v and w parameters directly for each sampling point.
Reimplemented from ASMu3D.
References utl::findIndex(), ASMu3D::DirichletFace::lr, ASMu3D::lrspline, ASMu3D::DirichletFace::MLGE, ASMu3D::DirichletFace::MLGN, and ASMu3D::DirichletFace::MNPC.
evalSolution() [5/7]
bool ASMu3D::evalSolution (Matrix & sField, const Vector & locSol, const int * npe, int n_f, bool piola) const virtual
Evaluates the primary solution field at all visualization points.
Parameters
[out] sField Solution field
[in] locSol Solution vector in DOF-order
[in] npe Number of visualization nodes over each knot span
[in] n_f If nonzero, mixed evaluates n_f fields on first basis
[in] piola If true, use piola mapping
Reimplemented from ASMu3D.
evalSolution() [6/7]
bool ASMu3Dmx::evalSolution (Matrix & sField, const Vector & locSol, const RealArray * gpar, bool , int deriv, int nf) const virtual
Evaluates the primary solution field at the given points.
Parameters
[out] sField Solution field
[in] locSol Solution vector local to current patch
[in] gpar Parameter values of the result sampling points
[in] deriv Derivative order to return
[in] nf If nonzero, evaluates nf fields on first basis
When regular is true, it is assumed that the parameter value array gpar forms a regular tensor-product point grid of dimension gpar[0].size() X gpar[1].size(). Otherwise, we assume that it contains the u and v parameters directly for each sampling point.
Reimplemented from ASMu3D.
References utl::vector< T >::begin(), utl::vector< T >::end(), utl::matrix< T >::fillColumn(), getElementsAt(), m_basis, utl::matrix< T >::multiply(), ASMmxBase::nb, ASMbase::nf, ASMmxBase::nfx, utl::vector< T >::ptr(), and utl::matrix< T >::resize().
evalSolution() [7/7]
bool ASMu3D::evalSolution (Matrix & sField, const Vector & locSol, const RealArray * gpar, bool = false, int deriv = 0, int = 0) const virtual
Evaluates the primary solution field at the given points.
Parameters
[out] sField Solution field
[in] locSol Solution vector local to current patch
[in] gpar Parameter values of the result sampling points
[in] deriv Derivative order to return
Reimplemented from ASMu3D.
extractNodeVec()
void ASMu3Dmx::extractNodeVec (const RealArray & globVec, RealArray & nodeVec, unsigned char , int basis) const virtual
Extracts nodal results for this patch from the global vector.
Parameters
[in] globVec Global solution vector in DOF-order
[out] nodeVec Nodal result vector for this patch
[in] basis Which basis (or 0 for both) to extract nodal values for
Reimplemented from ASMbase.
References ASMmxBase::extractNodeVecMx().
Referenced by refine().
generateFEMTopology()
bool ASMu3Dmx::generateFEMTopology () virtual
Generates the finite element topology data for the patch.
The data generated are the element-to-node connectivity array, the node-to-IJ-index array, as well as global node and element numbers.
Reimplemented from ASMu3D.
References ASMmxBase::adjustBasis(), ASMmxBase::DIV_COMPATIBLE, ASMmxBase::establishBases(), ASMbase::firstEl, ASMmxBase::FULL_CONT_RAISE_BASIS1, ASMmxBase::FULL_CONT_RAISE_BASIS2, ASMbase::gEl, ASMLRSpline::geomB, ASMbase::gNod, ASMmxBase::includeExtra, ASMmxBase::itgBasis, ASMu3D::lrspline, m_basis, ASMbase::myMLGE, ASMbase::myMLGN, ASMbase::myMNPC, ASMmxBase::nb, ASMbase::nel, ASMbase::nnod, ASMmxBase::NONE, ASMLRSpline::projB, ASMLRSpline::projB2, SplineUtils::Raise, ASMmxBase::REDUCED_CONT_RAISE_BASIS1, ASMmxBase::REDUCED_CONT_RAISE_BASIS2, ASMLRSpline::refB, ASMbase::shareFE, ASMmxBase::SUBGRID, ASMu3D::tensorspline, and ASMmxBase::Type.
generateThreadGroups()
void ASMu3Dmx::generateThreadGroups (const Integrand & integrand, bool silence, bool ignoreGlobalLM) protected virtual
Generates element groups for multi-threading of interior integrals.
Parameters
[in] integrand Object with problem-specific data and methods
[in] silence If true, suppress threading group outprint
[in] ignoreGlobalLM If true, ignore global multipliers in sanity check
Reimplemented from ASMu3D.
References ThreadGroups::analyzeUnstruct(), ASMLRSpline::checkThreadGroups(), IFEM::cout, ASMmxBase::DIV_COMPATIBLE, LR::generateThreadGroups(), getBasis(), ASMmxBase::includeExtra, m_basis, ASMLRSpline::proj2ThreadGroups, ASMLRSpline::projB, ASMLRSpline::projB2, ASMLRSpline::projThreadGroups, ASMmxBase::REDUCED_CONT_RAISE_BASIS1, ASMmxBase::REDUCED_CONT_RAISE_BASIS2, ThreadGroups::size(), ASMmxBase::SUBGRID, threadBasis, ASMLRSpline::threadGroups, and ASMmxBase::Type.
getBasis() [1/2]
LR::LRSplineVolume * ASMu3Dmx::getBasis (int basis = 1) virtual
Returns the spline volume representing a basis of this patch.
Reimplemented from ASMu3D.
getBasis() [2/2]
const LR::LRSplineVolume * ASMu3Dmx::getBasis (int basis = 1) const virtual
Returns the spline volume representing a basis of this patch.
Reimplemented from ASMu3D.
References ASMu3D::getBasis(), and m_basis.
Referenced by evalSolution(), generateThreadGroups(), getCoord(), getElementsAt(), LRSplineFields3Dmx::gradFE(), LRSplineFields3Dmx::hessianFE(), integrate(), integrate(), refine(), remapErrors(), and LRSplineFields3Dmx::valueFE().
getCoord()
Vec3 ASMu3Dmx::getCoord (size_t inod) const virtual
Returns the global coordinates for the given node.
Parameters
[in] inod 1-based node index local to current patch
Reimplemented from ASMu3D.
References getBasis(), ASMmxBase::nb, and ASMbase::nsd.
getElementsAt()
void ASMu3Dmx::getElementsAt (const RealArray & param, std::vector< int > & elms, std::vector< size_t > * sizes = nullptr) const private
Finds the elements and associted sizes at given parametric point.
Parameters
[in] param Parametric point to find elements at
[out] elms List of elements on each basis containing given point
[out] sizes List of element sizes (number of element nodes)
References ASM::GEOMETRY_BASIS, getBasis(), ASMu3D::lrspline, and m_basis.
Referenced by evalSolution(), evalSolution(), integrate(), and integrate().
getNoBasis()
virtual size_t ASMu3Dmx::getNoBasis () const inline virtual
Returns the number of bases.
Reimplemented from ASMbase.
References m_basis.
Referenced by integrate().
getNodalDOFs()
unsigned char ASMu3Dmx::getNodalDOFs (size_t inod) const virtual
Returns the number of DOFs per node.
Parameters
[in] inod 1-based node index local to current patch
Reimplemented from ASMbase.
References ASMbase::isLMn(), ASMmxBase::nb, ASMmxBase::nfx, and ASMbase::nLag.
getNodeType()
char ASMu3Dmx::getNodeType (size_t inod) const virtual
Returns the classification of a node.
Parameters
[in] inod 1-based node index local to current patch
Reimplemented from ASMbase.
References ASMbase::isLMn(), and ASMmxBase::nb.
getNoFields()
unsigned char ASMu3Dmx::getNoFields (int basis) const virtual
Returns the number of solution fields.
Reimplemented from ASMbase.
References m_basis, and ASMmxBase::nfx.
Referenced by LRSplineFields3Dmx::gradFE(), LRSplineFields3Dmx::hessianFE(), and LRSplineFields3Dmx::LRSplineFields3Dmx().
getNoNodes()
size_t ASMu3Dmx::getNoNodes (int basis) const virtual
Returns the total number of nodes in this patch.
Reimplemented from ASMu3D.
References ASMbase::getNoNodes(), and ASMmxBase::nb.
Referenced by LRSplineFields3Dmx::gradFE(), LRSplineFields3Dmx::hessianFE(), LRSplineFields3Dmx::LRSplineFields3Dmx(), and LRSplineFields3Dmx::valueFE().
getNoRefineElms()
size_t ASMu3Dmx::getNoRefineElms () const virtual
Returns the number of refinement elements for this patch.
Reimplemented from ASMbase.
References ASMLRSpline::refB.
getNoRefineNodes()
size_t ASMu3Dmx::getNoRefineNodes () const virtual
Returns the number of refinement nodes for this patch.
Reimplemented from ASMbase.
References ASMLRSpline::refB.
getSolution()
bool ASMu3Dmx::getSolution (Matrix & sField, const Vector & locSol, const IntVec & nodes) const virtual
Extracts the primary solution field at the specified nodes.
Parameters
[out] sField Solution field
[in] locSol Solution vector local to current patch
[in] nodes 1-based local node numbers to extract solution for
Reimplemented from ASMbase.
References ASMmxBase::getSolutionMx().
initMADOF()
void ASMu3Dmx::initMADOF (const int * sysMadof) virtual
Initializes the patch level MADOF array for mixed problems.
Reimplemented from ASMbase.
References ASMmxBase::initMx(), and ASMbase::MLGN.
injectNodeVec()
bool ASMu3Dmx::injectNodeVec (const RealArray & nodeVec, RealArray & globVec, unsigned char , int basis) const virtual
Injects nodal results for this patch into a global vector.
Parameters
[in] nodeVec Nodal result vector for this patch
[out] globVec Global solution vector in DOF-order
[in] basis Which basis (or 0 for both) to extract nodal values for
Reimplemented from ASMbase.
References ASMmxBase::injectNodeVecMx().
integrate() [1/2]
bool ASMu3Dmx::integrate (Integrand & integrand, GlobalIntegral & glbInt, const TimeDomain & time) virtual
Evaluates an integral over the interior patch domain.
Parameters
integrand Object with problem-specific data and methods
glbInt The integrated quantity
[in] time Parameters for nonlinear/time-dependent simulations
Reimplemented from ASMu3D.
References utl::vector< T >::add(), GlobalIntegral::assemble(), Vec4::assign(), Integrand::AVERAGE, MxFiniteElement::basis(), ASM::cachePolicy, BasisFunctionCache< Dim >::clear(), BasisFunctionCache< Dim >::coord(), LocalIntegral::destruct(), FiniteElement::detJxW, BasisFunctionVals::dNdu, Integrand::ELEMENT_CENTER, Integrand::ELEMENT_CORNERS, ItgPoint::eta, Integrand::evalIntMx(), Integrand::finalizeElement(), ASMbase::firstEl, ASMbase::firstIp, FiniteElement::G, Integrand::G_MATRIX, ASM::GEOMETRY_BASIS, getBasis(), ASMu3D::getElementCoordinates(), ASMu3D::getElementCorners(), getElementsAt(), utl::getGmat(), Integrand::getIntegrandType(), Integrand::getLocalIntegral(), getNoBasis(), BasisFunctionCache< Dim >::getParam(), Integrand::getReducedIntegration(), FiniteElement::h, MxFiniteElement::Hessian(), ItgPoint::idx, ItgPoint::iel, ItgPoint::iGP, Integrand::initElement(), ASMmxBase::itgBasis, MxFiniteElement::Jacobian(), utl::Jacobian(), ASMu3D::lrspline, m_basis, ASMbase::MLGE, ASMbase::MNPC, ASMu3D::myCache, ASMbase::myElms, BasisFunctionVals::N, FiniteElement::Navg, ASMmxBase::nb, ASMbase::nel, ASMbase::nGauss, BasisFunctionCache< Dim >::nGauss(), ThreadGroups::oneGroup(), ASM::PRE_CACHE, PROFILE2, LocalIntegral::ref(), utl::vector< T >::resize(), Integrand::SECOND_DERIVATIVES, BasisFunctionCache< Dim >::setIntegrand(), ASMmxBase::SUBGRID, TimeDomain::t, threadBasis, ASMLRSpline::threadGroups, GlobalIntegral::threadSafe(), SplineUtils::toVec3(), ASMmxBase::Type, ItgPoint::u, ItgPoint::v, ItgPoint::w, BasisFunctionCache< Dim >::weight(), FiniteElement::XC, ItgPoint::xi, and ItgPoint::zeta.
integrate() [2/2]
bool ASMu3Dmx::integrate (Integrand & integrand, int lIndex, GlobalIntegral & glbInt, const TimeDomain & time) virtual
Evaluates a boundary integral over a patch edge.
Parameters
integrand Object with problem-specific data and methods
[in] lIndex Local index of the boundary edge
glbInt The integrated quantity
[in] time Parameters for nonlinear/time-dependent simulations
Reimplemented from ASMu3D.
References GlobalIntegral::assemble(), Vec4::assign(), MxFiniteElement::basis(), LocalIntegral::destruct(), FiniteElement::detJxW, Integrand::ELEMENT_CORNERS, ItgPoint::eta, Integrand::evalBouMx(), ASMu3D::evaluateBasis(), Integrand::finalizeElementBou(), ASMbase::firstBp, FiniteElement::G, Integrand::G_MATRIX, ASM::GEOMETRY_BASIS, getBasis(), Integrand::getBouIntegrationPoints(), GaussQuadrature::getCoord(), ASMu3D::getElementCoordinates(), ASMu3D::getElementCorners(), getElementsAt(), getFaceEnum(), ASMu3D::getGaussPointParameters(), utl::getGmat(), Integrand::getIntegrandType(), Integrand::getLocalIntegral(), ASMu3D::getParametricArea(), GaussQuadrature::getWeight(), FiniteElement::h, ItgPoint::iel, ItgPoint::iGP, Integrand::initElementBou(), ASMbase::isElementInPartition(), ASMmxBase::itgBasis, MxFiniteElement::Jacobian(), ASMu3D::lrspline, m_basis, ASMbase::MLGE, ASMbase::MNPC, ASMbase::myElms, ASMmxBase::nb, ASMbase::nGauss, PROFILE2, LocalIntegral::ref(), TimeDomain::t, ItgPoint::u, ItgPoint::v, ItgPoint::w, FiniteElement::XC, ItgPoint::xi, and ItgPoint::zeta.
readBasis()
bool ASMu3Dmx::readBasis (std::istream & is, size_t basis) virtual
Reads a basis from the given input stream.
Reimplemented from ASMbase.
References m_basis, ASMmxBase::nb, and ASMmxBase::nfx.
refine() [1/4]
bool ASMu3D::refine (const LR::RefineData & prm, Vectors & sol) virtual
Refines the mesh adaptively.
Parameters
[in] prm Input data used to control the mesh refinement
sol Control point results values that are transferred to new mesh
Reimplemented from ASMu3D.
refine() [2/4]
bool ASMLRSpline::refine (const LR::RefineData & prm, Vectors & sol) virtual
Refines the mesh adaptively.
Parameters
[in] prm Input data used to control the mesh refinement
sol Control point results values that are transferred to new mesh
Reimplemented from ASMu3D.
References ASMLRSpline::geomB, ASMLRSpline::projB, and ASMLRSpline::projB2.
refine() [3/4]
bool ASMu3Dmx::refine (const LR::RefineData & prm, Vectors & sol) virtual
Refines the mesh adaptively.
Parameters
[in] prm Input data used to control the refinement
sol Control point results values that are transferred to new mesh
Reimplemented from ASMu3D.
References LR::contractControlPoints(), ASMu3D::copyRefinement(), ASMLRSpline::doRefine(), LR::RefineData::elements, LR::RefineData::errors, LR::extendControlPoints(), extractNodeVec(), getBasis(), m_basis, ASMmxBase::nb, ASMmxBase::nfx, ASMLRSpline::projB, ASMLRSpline::projB2, ASMmxBase::REDUCED_CONT_RAISE_BASIS1, ASMmxBase::REDUCED_CONT_RAISE_BASIS2, ASMLRSpline::refB, ASM::REFINEMENT_BASIS, ASMbase::shareFE, ASMmxBase::SUBGRID, and ASMmxBase::Type.
refine() [4/4]
bool ASMu3D::refine (int dir, const RealArray & xi) virtual
Refines the parametrization by inserting extra tensor knots.
Parameters
[in] dir Parameter direction to refine
[in] xi Relative positions of added knots in each existing knot span
Reimplemented from ASMu3D.
remapErrors()
void ASMu3Dmx::remapErrors (RealArray & errors, const RealArray & origErr, bool elemErrors) const virtual
Remaps element-wise errors from geometry mesh to refinement mesh.
Parameters
[out] errors The remapped errors
[in] origErr The element-wise errors on the geometry mesh
[in] elemErrors If true, map to elements and not basis functions
Reimplemented from ASMu3D.
References getBasis(), ASMmxBase::itgBasis, and ASMLRSpline::refB.
separateProjectionBasis()
bool ASMu3Dmx::separateProjectionBasis () const virtual
Checks if a separate projection basis is used for this patch.
Reimplemented from ASMu3D.
References m_basis.
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/ASM/LR/ASMu3Dmx.h
/home/runner/work/IFEM-2/IFEM-2/src/ASM/LR/ASMu3Dmx.C