IFEM: Oval2D Class Reference
Oval2D Class Reference
Class representing a plate perforated by an oval hole.
#include <IBGeometries.h>
Public Member Functions
Oval2D (double r, double x0, double y0, double x1, double y1)
Default constructor initializing the radius and center of the hole.
virtual double Alpha (double X, double Y, double) const
Performs the inside-outside test for the perforated plate object.
virtual ElementBlock * tesselate () const
Creates a finite element model of the geometry for visualization.
Public Member Functions inherited from Hole2D
Hole2D (double r=1.0, double x=0.0, double y=0.0)
Default constructor initializing the radius and center of the hole.
Public Member Functions inherited from Immersed::Geometry
virtual ~Geometry ()
Empty destructor.
virtual double Alpha (const Vec3 &X) const
Performs the inside-outside test for the geometric object.
Private Attributes
double X1
X-coordinate of second circle center.
double Y1
Y-coordinate of second circle center.
double D2
Auxilliary parameter used by method Alpha.
double LR
Auxilliary parameter used by method Alpha.
Additional Inherited Members
Protected Member Functions inherited from Immersed::Geometry
Geometry ()
The default constructor is protected to allow sub-classes only.
Protected Attributes inherited from Hole2D
double R
Hole radius.
double Xc
X-coordinate of hole center.
double Yc
Y-coordinate of hole center.
Detailed Description
Class representing a plate perforated by an oval hole.
Member Function Documentation
Alpha()
double Oval2D::Alpha (double X, double Y, double) const virtual
Performs the inside-outside test for the perforated plate object.
Reimplemented from Hole2D.
References D2, Hole2D::R, X1, Hole2D::Xc, Y1, and Hole2D::Yc.
tesselate()
ElementBlock * Oval2D::tesselate () const virtual
Creates a finite element model of the geometry for visualization.
Reimplemented from Hole2D.
References Hole2D::R, ElementBlock::setCoor(), ElementBlock::setNode(), ElementBlock::unStructResize(), X1, Hole2D::Xc, Y1, and Hole2D::Yc.
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/ASM/IBGeometries.h
/home/runner/work/IFEM-2/IFEM-2/src/ASM/IBGeometries.C