IFEM: SPRMatrix Class Reference
SPRMatrix Class Reference
Class for representing the system matrix on the SPR-format.
#include <SPRMatrix.h>
Public Member Functions
SPRMatrix ()
Default constructor.
SPRMatrix (const SPRMatrix &A)
Copy constructor.
virtual ~SPRMatrix ()
The destructor frees the dynamically allocated arrays.
virtual LinAlg::MatrixType getType () const
Returns the matrix type.
virtual SystemMatrix * copy () const
Creates a copy of the system matrix and returns a pointer to it.
SPRMatrix & operator= (const SPRMatrix &)=delete
This class is not copyable.
virtual size_t dim (int idim) const
Returns the dimension of the system matrix.
virtual void initAssembly (const SAM &sam, char)
Initializes the element assembly process.
virtual void init ()
Initializes the matrix to zero assuming it is properly dimensioned.
virtual bool assemble (const Matrix &eM, const SAM &sam, int e)
Adds an element matrix into the associated system matrix.
virtual bool assemble (const Matrix &eM, const SAM &sam, SystemVector &B, int e)
Adds an element matrix into the associated system matrix.
virtual bool assemble (const Matrix &eM, const SAM &sam, SystemVector &B, const IntVec &meq)
Adds an element matrix into the associated system matrix.
virtual bool assemble (const Matrix &eM, const IntVec &meq)
Adds an element matrix into the associated system matrix.
virtual void mult (Real alpha)
Multiplication with a scalar.
virtual bool add (const SystemMatrix &B, Real alpha)
Adds a matrix with similar sparsity pattern to the current matrix.
virtual bool add (Real sigma, int ieq)
Adds the constant σ to the diagonal of this matrix.
virtual bool multiply (const SystemVector &B, SystemVector &C) const
Performs the matrix-vector multiplication C = *this * B.
virtual bool solve (SystemVector &B, Real *)
Solves the linear system of equations for a given right-hand-side.
bool solveEig (SPRMatrix &B, RealArray &val, Matrix &vec, int nev, Real shift=0.0, int iop=1)
Solves a generalized symmetric-definite eigenproblem.
virtual Real Linfnorm () const
Returns the L-infinity norm of the matrix.
bool convert (Matrix &fullMat) const
Converts to a dense matrix.
virtual void dump (std::ostream &os, LinAlg::StorageFormat fmt, const char *)
Dumps the system matrix on a specified format.
virtual bool load (const char *fileName, bool binary)
Loads the system matrix from specified file.
virtual bool assemble (const Matrix &eM, const SAM &sam, int e)=0
Adds an element matrix into the associated system matrix.
virtual bool assemble (const Matrix &eM, const SAM &sam, SystemVector &B, int e)=0
Adds an element matrix into the associated system matrix.
virtual bool assemble (const Matrix &eM, const SAM &sam, SystemVector &B, const IntVec &meq)=0
Adds an element matrix into the associated system matrix.
virtual bool assemble (const Matrix &eM, const IntVec &meq)=0
Adds an element matrix into the associated system matrix.
virtual bool solve (SystemVector &b, Real *rc=nullptr)=0
Solves the linear system of equations for a given right-hand-side.
virtual bool solve (const SystemVector &b, SystemVector &x)
Solves the linear system of equations for a given right-hand-side.
virtual bool solve (SystemVector &b, Matrix &x)
Solves a linear system of equations for multiple right-hand-sides.
Public Member Functions inherited from SystemMatrix
virtual ~SystemMatrix ()
Empty destructor.
virtual bool lockPattern (bool)
Locks or unlocks the sparsity pattern.
virtual bool empty () const
Checks if the matrix is empty.
bool isZero () const
Checks if the matrix have no non-zero contributions.
virtual void preAssemble (const std::vector< IntVec > &, size_t=0)
Initializes the element sparsity pattern based on node connections.
virtual void compressPattern ()
Compresses the sparsity pattern.
void initNonZeroEqs ()
Initializes the nonZeroEqs flags.
bool flagNonZeroEq (int ieq=0)
Flags equation ieq as pivot element with non-zero contributions.
bool flagNonZeroEqs (const SAM &sam, const IntVec &meq)
Flags the equations meq as pivots with non-zero contributions.
bool flagNonZeroEqs (const SystemMatrix &B)
Flags the non-zero equations from B as non-zero pivots in this.
virtual bool endAssembly ()
Finalizes the system matrix assembly.
virtual bool augment (const SystemMatrix &, size_t, size_t)
Augments a similar matrix symmetrically to the current matrix.
virtual bool truncate (Real=Real(1.0e-16))
Truncates all small matrix elements to zero.
virtual void dump (const char *fileName, std::streamsize precision=0, LinAlg::StorageFormat format=LinAlg::FLAT)
Dumps the system matrix to specified file.
StdVector operator* (const SystemVector &b) const
Calculates a matrix-vector product.
StdVector operator/ (const SystemVector &b)
Solves a linear equation system.
Protected Member Functions
bool assemble (int e, const Matrix &eM, const SAM &sam, Real *B=nullptr)
Adds an element matrix into the associated system matrix.
bool multiply (size_t n, const Real *b, Real *c)
Performs the matrix-vector multiplication c = *this * b.
virtual std::ostream & write (std::ostream &os) const
Writes the system matrix to the given output stream.
Protected Member Functions inherited from SystemMatrix
SystemMatrix ()
Default constructor.
SystemMatrix (const SystemMatrix &a)
Copy constructor.
Private Types
using SAM64 = SAM
Convenience alias when using 32-bit int version.
Private Attributes
Int_ ierr
Internal error flag.
Int_ mpar [NS]
Matrix of sparse PARameters.
Int_ * msica
Matrix of Storage Information for CA.
Int_ * msifa
Matrix of Storage Information for FA.
Int_ * mtrees
Matrix of elimination assembly TREES.
Int_ * mvarnc
Matrix of VARiable to Node Correspondence.
Real * values
The actual matrix VALUES.
std::vector< Int_ > iWork
Integer work array.
std::vector< Int_ > * jWork
Integer work arrays for multi-threaded assembly.
std::vector< Real > rWork
Real work array.
SAM64 * mySam
Possibly 64-bit integer version of SAM arrays.
Additional Inherited Members
Static Public Member Functions inherited from SystemMatrix
static SystemMatrix * create (const ProcessAdm *adm, LinAlg::MatrixType mType, int num_thread_SLU=1)
Static method creating a matrix of the given type.
static SystemMatrix * create (const ProcessAdm *adm, LinAlg::MatrixType mType, const LinSolParams &spar)
Static method creating a matrix of the given type.
Detailed Description
Class for representing the system matrix on the SPR-format.
It is an interface to a Fortran module for assembling and solving linear systems of equations.
Member Function Documentation
add() [1/2]
bool SPRMatrix::add (const SystemMatrix & B, Real alpha) virtual
Adds a matrix with similar sparsity pattern to the current matrix.
Parameters
[in] B The matrix to be added
[in] alpha Scale factor for matrix B
Reimplemented from SystemMatrix.
References SystemMatrix::flagNonZeroEqs(), SystemMatrix::isZero(), mpar, and values.
add() [2/2]
bool SPRMatrix::add (Real sigma, int ieq) virtual
Adds the constant σ to the diagonal of this matrix.
Reimplemented from SystemMatrix.
References SystemMatrix::flagNonZeroEq(), ierr, mpar, msifa, mtrees, sprdad_(), and values.
assemble() [1/9]
bool SPRMatrix::assemble (const Matrix & eM, const IntVec & meq) virtual
Adds an element matrix into the associated system matrix.
Parameters
[in] eM The element matrix
[in] meq Matrix of element equation numbers (0 based)
Returns
true on successful assembly, otherwise false
Implements SystemMatrix.
assemble() [2/9]
virtual bool SystemMatrix::assemble (const Matrix & eM, const IntVec & meq) virtual
Adds an element matrix into the associated system matrix.
Parameters
[in] eM The element matrix
[in] meq Matrix of element equation numbers (0 based)
Returns
true on successful assembly, otherwise false
To be used when there is no associated SAM object.
Implements SystemMatrix.
assemble() [3/9]
bool SPRMatrix::assemble (const Matrix & eM, const SAM & sam, int e) virtual
Adds an element matrix into the associated system matrix.
Parameters
[in] eM The element matrix
[in] sam Auxiliary data for FE assembly management
[in] e Identifier for the element that eM belongs to
Returns
true on successful assembly, otherwise false
Implements SystemMatrix.
References assemble().
Referenced by assemble(), and assemble().
assemble() [4/9]
virtual bool SystemMatrix::assemble (const Matrix & eM, const SAM & sam, int e) virtual
Adds an element matrix into the associated system matrix.
Parameters
[in] eM The element matrix
[in] sam Auxiliary data for FE assembly management
[in] e Identifier for the element that eM belongs to
Returns
true on successful assembly, otherwise false
Implements SystemMatrix.
assemble() [5/9]
bool SPRMatrix::assemble (const Matrix & eM, const SAM & sam, SystemVector & B, const IntVec & meq) virtual
Adds an element matrix into the associated system matrix.
Parameters
[in] eM The element matrix
[in] sam Auxiliary data for FE assembly management
B The system right-hand-side vector
[in] meq Matrix of element equation numbers
Returns
true on successful assembly, otherwise false
When multi-point constraints are present, contributions from these are also added into the system right-hand-side vector, B.
Implements SystemMatrix.
assemble() [6/9]
virtual bool SystemMatrix::assemble (const Matrix & eM, const SAM & sam, SystemVector & B, const IntVec & meq) virtual
Adds an element matrix into the associated system matrix.
Parameters
[in] eM The element matrix
[in] sam Auxiliary data for FE assembly management
B The system right-hand-side vector
[in] meq Matrix of element equation numbers
Returns
true on successful assembly, otherwise false
When multi-point constraints are present, contributions from these are also added into the system right-hand-side vector, B.
Implements SystemMatrix.
assemble() [7/9]
bool SPRMatrix::assemble (const Matrix & eM, const SAM & sam, SystemVector & B, int e) virtual
Adds an element matrix into the associated system matrix.
Parameters
[in] eM The element matrix
[in] sam Auxiliary data for FE assembly management
B The system right-hand-side vector
[in] e Identifier for the element that eM belongs to
Returns
true on successful assembly, otherwise false
When multi-point constraints are present, contributions from these are also added into the system right-hand-side vector, B.
Implements SystemMatrix.
References assemble(), LinAlg::DENSE, SystemVector::getPtr(), and SystemVector::getType().
assemble() [8/9]
virtual bool SystemMatrix::assemble (const Matrix & eM, const SAM & sam, SystemVector & B, int e) virtual
Adds an element matrix into the associated system matrix.
Parameters
[in] eM The element matrix
[in] sam Auxiliary data for FE assembly management
B The system right-hand-side vector
[in] e Identifier for the element that eM belongs to
Returns
true on successful assembly, otherwise false
When multi-point constraints are present, contributions from these are also added into the system right-hand-side vector, B.
Implements SystemMatrix.
assemble() [9/9]
bool SPRMatrix::assemble (int e, const Matrix & eM, const SAM & sam, Real * B = nullptr) protected
Adds an element matrix into the associated system matrix.
Parameters
[in] eM The element matrix
[in] sam Auxiliary data for FE assembly management
B Pointer to the system right-hand-side vector
[in] e Identifier for the element that eM belongs to
Returns
true on successful assembly, otherwise false
References SystemMatrix::flagNonZeroEqs(), ierr, jWork, SAM::madof, SAM::meqn, SAM::mmceq, SAM::mmnpc, SAM::mpar, mpar, SAM::mpmceq, SAM::mpmnpc, msica, msifa, mtrees, mvarnc, mySam, utl::matrixBase< T >::ptr(), utl::matrix< T >::rows(), rWork, spradm_(), SAM::ttcc, and values.
copy()
virtual SystemMatrix * SPRMatrix::copy () const inline virtual
Creates a copy of the system matrix and returns a pointer to it.
Implements SystemMatrix.
References SPRMatrix().
dim()
size_t SPRMatrix::dim (int idim) const virtual
Returns the dimension of the system matrix.
Implements SystemMatrix.
References mpar.
dump()
void SPRMatrix::dump (std::ostream & os, LinAlg::StorageFormat fmt, const char *) virtual
Dumps the system matrix on a specified format.
Reimplemented from SystemMatrix.
References LinAlg::BINARY, mpar, msica, msifa, mtrees, mvarnc, Real, and values.
getType()
virtual LinAlg::MatrixType SPRMatrix::getType () const inline virtual
Returns the matrix type.
Implements SystemMatrix.
References LinAlg::SPR.
init()
void SPRMatrix::init () virtual
Initializes the matrix to zero assuming it is properly dimensioned.
Implements SystemMatrix.
References mpar, Real, and values.
initAssembly()
void SPRMatrix::initAssembly (const SAM & sam, char) virtual
Initializes the element assembly process.
Parameters
[in] sam Auxiliary data describing the FE model topology, etc.
Must be called once before the element assembly loop. The SPR data structures are initialized and the all symbolic operations that are need before the actual assembly can start are performed.
Implements SystemMatrix.
References ierr, iWork, SAM::madof, SAM::meqn, SAM::minex, SAM::mmceq, SAM::mmnpc, SAM::mpar, mpar, SAM::mpmceq, SAM::mpmnpc, SAM::msc, msica, msifa, mtrees, mvarnc, mySam, SAM::ndof, SAM::neq, SAM::nnod, Real, sprpmp_(), sprprp_(), sprrnm_(), sprsas_(), sprsmb_(), sprtrs_(), and values.
Linfnorm()
Real SPRMatrix::Linfnorm () const virtual
Returns the L-infinity norm of the matrix.
Implements SystemMatrix.
References mpar, multiply(), and Real.
load()
bool SPRMatrix::load (const char * fileName, bool binary) virtual
Loads the system matrix from specified file.
Reimplemented from SystemMatrix.
References SystemMatrix::flagNonZeroEq(), mpar, msica, msifa, mtrees, mvarnc, Real, and values.
mult()
void SPRMatrix::mult (Real alpha) virtual
Multiplication with a scalar.
Implements SystemMatrix.
References mpar, and values.
multiply()
bool SPRMatrix::multiply (const SystemVector & B, SystemVector & C) const virtual
Performs the matrix-vector multiplication C = *this * B.
Reimplemented from SystemMatrix.
References LinAlg::DENSE, SystemVector::dim(), SystemVector::getPtr(), SystemVector::getRef(), SystemVector::getType(), mpar, multiply(), and SystemVector::redim().
Referenced by Linfnorm(), and multiply().
solve() [1/4]
virtual bool SystemMatrix::solve (const SystemVector & b, SystemVector & x) inline virtual
Solves the linear system of equations for a given right-hand-side.
Parameters
[in] b Right-hand-side vector
[out] x Solution vector
Reimplemented from SystemMatrix.
solve() [2/4]
bool SystemMatrix::solve (SystemVector & b, Matrix & x) virtual
Solves a linear system of equations for multiple right-hand-sides.
Parameters
b Right-hand-side vectors on input, solution vectors on output
[out] x Matrix of solution vectors (row-oriented)
Reimplemented from SystemMatrix.
solve() [3/4]
bool SPRMatrix::solve (SystemVector & B, Real *) virtual
Solves the linear system of equations for a given right-hand-side.
Parameters
B Right-hand-side vector on input, solution vector on output
Implements SystemMatrix.
References LinAlg::DENSE, SystemVector::dim(), SAM::getNodeAndLocalDof(), SystemVector::getPtr(), SystemVector::getType(), ierr, iWork, mpar, msifa, mtrees, mySam, Real, rWork, sprsol_(), and values.
solve() [4/4]
virtual bool SystemMatrix::solve (SystemVector & b, Real * rc = nullptr) virtual
Solves the linear system of equations for a given right-hand-side.
Parameters
b Right-hand-side vector on input, solution vector on output
[out] rc Reciprocal condition number of the LHS-matrix (optional)
Implements SystemMatrix.
solveEig()
bool SPRMatrix::solveEig (SPRMatrix & B, RealArray & val, Matrix & vec, int nev, Real shift = 0.0, int iop = 1)
Solves a generalized symmetric-definite eigenproblem.
Parameters
B Symmetric and positive definite mass matrix.
[out] val Computed eigenvalues
[out] vec Computed eigenvectors stored column by column
[in] nev The number of eigenvalues and eigenvectors to compute
[in] shift Eigenvalue shift
[in] iop Option telling whether to factorize matrix A or B.
The eigenproblem is assumed to be on the form A x = λ B x where A (= *this) and B both are assumed to be symmetric and B also to be positive definite. The eigenproblem is solved by the SAM library subroutine SPRLAN.
See also
SAM library documentation.
References ierr, iWork, mpar, msifa, mtrees, utl::matrixBase< T >::ptr(), Real, utl::matrix< T >::resize(), rWork, sprlax_(), and values.
Referenced by eig::solve().
write()
std::ostream & SPRMatrix::write (std::ostream & os) const protected virtual
Writes the system matrix to the given output stream.
Reimplemented from SystemMatrix.
References closeftnfile_(), convert(), mpar, msifa, mtrees, openftnfile_(), sprprn_(), and values.
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/LinAlg/SPRMatrix.h
/home/runner/work/IFEM-2/IFEM-2/src/LinAlg/SPRMatrix.C