IFEM: BDFMats Class Reference
BDFMats Class Reference
Class representing the element matrices for a dynamic FEM problem using backward difference formulae (BDF).
#include <BDFMats.h>
Public Member Functions
BDFMats (const TimeIntegration::BDFD2 &scheme)
The constructor initializes the time integration parameters. param[in] scheme BDF time discretization scheme.
virtual ~BDFMats ()
Empty destructor.
virtual void setStepSize (double dt, int)
Updates the time step size.
virtual const Matrix & getNewtonMatrix () const
Returns the element-level Newton matrix.
virtual const Vector & getRHSVector () const
Returns the element-level right-hand-side vector.
Public Member Functions inherited from ElmMats
ElmMats (bool lhs=true)
Default constructor.
virtual ~ElmMats ()
Empty destructor.
void resize (size_t nA, size_t nB, size_t nC=0)
Defines the number of element matrices and vectors.
void redim (size_t ndim)
Sets the dimension of the element matrices and vectors.
virtual bool empty () const
Checks if the element matrices are empty.
void printMat (std::ostream &os, size_t idx=0, const char *prefix=nullptr) const
Prints element matrix idx to output stream os.
void printVec (std::ostream &os, size_t idx=0, const char *prefix=nullptr) const
Prints element vector idx to output stream os.
void printScl (std::ostream &os, size_t idx=0, const char *prefix=nullptr) const
Prints element scalar idx to output stream os.
Public Member Functions inherited from LocalIntegral
virtual ~LocalIntegral ()
Empty destructor.
virtual void destruct ()
Virtual destruction method to clean up after numerical integration.
virtual const LocalIntegral * ref () const
Returns the LocalIntegral object to assemble into the global one.
void getSolution (size_t nsd, size_t nen, Matrix *u=nullptr, Matrix *v=nullptr, Matrix *a=nullptr, bool forceCurrent=false) const
Extracts element solution vectors as nsd by nen matrices.
Protected Attributes
TimeIntegration::BDFD2 bdf
BDF time integration scheme.
double h
Time step size.
Additional Inherited Members
Public Attributes inherited from ElmMats
std::vector< Matrix > A
The element coefficient matrices.
std::vector< Vector > b
The element right-hand-side vectors.
std::vector< double > c
The scalar quantities.
std::vector< const char * > Aname
Matrix names (for debug print)
std::vector< const char * > Bname
Vector names (for debug print)
std::vector< const char * > Cname
Scalar names (for debug print)
bool rhsOnly
If true, only the right-hand-sides are assembled.
bool withLHS
If true, left-hand-side element matrices are present.
Public Attributes inherited from LocalIntegral
Vectors vec
Element-level primary solution vectors.
Protected Member Functions inherited from LocalIntegral
LocalIntegral ()
The default constructor is protected to allow sub-classes only.
Detailed Description
Class representing the element matrices for a dynamic FEM problem using backward difference formulae (BDF).
Member Function Documentation
getNewtonMatrix()
const Matrix & BDFMats::getNewtonMatrix () const virtual
Returns the element-level Newton matrix.
Reimplemented from ElmMats.
References ElmMats::A, utl::matrix< T >::add(), bdf, TimeIntegration::BDF::getDegree(), h, and utl::matrix< T >::multiply().
getRHSVector()
const Vector & BDFMats::getRHSVector () const virtual
Returns the element-level right-hand-side vector.
Reimplemented from ElmMats.
References ElmMats::A, utl::vector< T >::add(), ElmMats::b, bdf, TimeIntegration::BDFD2::getCoefs(), TimeIntegration::BDF::getDegree(), h, and LocalIntegral::vec.
setStepSize()
virtual void BDFMats::setStepSize (double dt, int) inline virtual
Updates the time step size.
Reimplemented from ElmMats.
References h.
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/ASM/BDFMats.h
/home/runner/work/IFEM-2/IFEM-2/src/ASM/BDFMats.C