IFEM: MultiPatchModelGenerator3D Class Reference
MultiPatchModelGenerator3D Class Reference
3D multi-patch model generator for FEM simulators.
#include <MultiPatchModelGenerator.h>
Public Member Functions
MultiPatchModelGenerator3D (const tinyxml2::XMLElement *geo)
The constructor initializes common members.
virtual ~MultiPatchModelGenerator3D ()
Empty destructor.
virtual bool createGeometry (SIMinput &sim) const
Creates a geometry.
virtual bool createTopology (SIMinput &sim) const
Creates topology for geometry.
virtual bool createTopologySets (SIMinput &sim) const
Creates topology sets for geometry.
Public Member Functions inherited from ModelGenerator
ModelGenerator (const tinyxml2::XMLElement *elem)
The constructor initializes the common members.
virtual ~ModelGenerator ()
Empty destructor.
Protected Member Functions
virtual std::string createG2 (int, bool rational=false) const
Generates the G2 description of the geometry.
Protected Member Functions inherited from ModelGenerator
bool topologySets () const
Returns true if topology sets is to be generated.
Private Attributes
size_t nx
Number of blocks in x.
size_t ny
Number of blocks in y.
size_t nz
Number of blocks in z.
int periodic_x
If non-zero, make model periodic in x for given bases.
int periodic_y
If non-zero, make model periodic in y for given bases.
int periodic_z
If non-zero, make model periodic in z for given bases.
Additional Inherited Members
Protected Attributes inherited from ModelGenerator
const tinyxml2::XMLElement * geo
Pointer to XML element describing geometry.
Detailed Description
3D multi-patch model generator for FEM simulators.
Generates a hexahedra split in a given number of blocks.
Constructor & Destructor Documentation
MultiPatchModelGenerator3D()
MultiPatchModelGenerator3D::MultiPatchModelGenerator3D (const tinyxml2::XMLElement * geo) explicit
The constructor initializes common members.
Parameters
[in] geo XML element to parse
References ModelGenerator::geo, utl::getAttribute(), nx, ny, nz, periodic_x, periodic_y, and periodic_z.
Member Function Documentation
createG2()
std::string MultiPatchModelGenerator3D::createG2 (int , bool rational = false) const protected virtual
Generates the G2 description of the geometry.
Reimplemented from ModelGenerator.
References IFEM::cout, ModelGenerator::geo, utl::getAttribute(), nx, ny, and nz.
Referenced by createGeometry().
createGeometry()
bool MultiPatchModelGenerator3D::createGeometry (SIMinput & sim) const virtual
Creates a geometry.
Reimplemented from ModelGenerator.
References createG2(), ModelGenerator::geo, utl::getAttribute(), SIMbase::getNoSpaceDim(), and SIMinput::readPatches().
createTopology()
bool MultiPatchModelGenerator3D::createTopology (SIMinput & sim) const virtual
Creates topology for geometry.
Reimplemented from ModelGenerator.
References SIMinput::addConnection(), ASMbase::closeBoundaries(), IFEM::cout, SIMinput::createFEMmodel(), SIMbase::getPatch(), nx, ny, nz, periodic_x, periodic_y, and periodic_z.
createTopologySets()
bool MultiPatchModelGenerator3D::createTopologySets (SIMinput & sim) const virtual
Creates topology sets for geometry.
Implements ModelGenerator.
References SIMbase::getLocalPatchIndex(), TopItem::item, nx, ny, nz, TopItem::patch, SIMinput::topology(), and ModelGenerator::topologySets().
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/Apps/Utils/MultiPatchModelGenerator.h
/home/runner/work/IFEM-2/IFEM-2/Apps/Utils/MultiPatchModelGenerator.C