IFEM: ASMLagBase Class Reference
ASMLagBase Class Reference
Common base class for Lagrange FE models.
#include <ASMLagBase.h>
Public Member Functions
void updateOrigin (const Vec3 &origin)
Updates patch origin by adding a constant to all nodes.
Protected Member Functions
ASMLagBase ()
Default constructor.
ASMLagBase (const ASMLagBase &patch, bool cpCoord=true)
Copy constructor.
virtual ~ASMLagBase ()
Empty destructor.
bool nodalField (Matrix &field, const Vector &sol, size_t nno) const
Direct nodal evaluation of a solution field.
Vec3 getGeometricCenter (const std::vector< int > &MNPC) const
Returns the geometric center of an element.
bool updateCoords (const Vector &displ, unsigned char nsd)
Updates the nodal coordinates for this patch.
Protected Attributes
const Vec3Vec & coord
Const reference to the nodal coordinate container.
Vec3Vec myCoord
Nodal coordinate container.
Detailed Description
Common base class for Lagrange FE models.
This class contains a container for storing the nodal coordinates.
Member Function Documentation
updateCoords()
bool ASMLagBase::updateCoords (const Vector & displ, unsigned char nsd) protected
Updates the nodal coordinates for this patch.
Parameters
[in] displ Incremental displacements to update the coordinates with
[in] nsd Number of space dimensions
References coord, myCoord, utl::vector< T >::ptr(), and utl::vector< T >::size().
Referenced by ASMs1DLag::updateCoords(), ASMs2DLag::updateCoords(), and ASMs3DLag::updateCoords().
updateOrigin()
void ASMLagBase::updateOrigin (const Vec3 & origin)
Updates patch origin by adding a constant to all nodes.
Parameters
[in] origin The new origin of the patch
References myCoord.
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/ASM/ASMLagBase.h
/home/runner/work/IFEM-2/IFEM-2/src/ASM/ASMLagBase.C