IFEM: SIMadmin Class Reference
SIMadmin Class Reference
Administration base class for FEM simulators.
#include <SIMadmin.h>
Public Member Functions
virtual ~SIMadmin ()
Empty destructor.
virtual bool read (const char *fileName)
Reads model data from the specified input file *fileName.
virtual bool parse (char *keyWord, std::istream &is)
Parses a data section from an input stream.
virtual bool parse (const tinyxml2::XMLElement *elem)
Parses a data section from an XML document.
virtual bool preprocess (const IntVec &ignored={}, bool fixDup=false)
Performs some pre-processing tasks on the FE model.
virtual bool preprocessC (const IntVec &, bool, double=0.0)
Performs some pre-processing tasks on the FE model.
const ProcessAdm & getProcessAdm () const
Returns the parallel process administrator.
int getGlobalProcessID () const
Returns the global process ID.
const std::string & getHeading () const
Returns the simulator heading.
void setHeading (const std::string &heading)
Defines the simulator heading.
void printHeading (int &supStep) const
Prints the heading of this simulator, if any, to IFEM::cout.
Public Member Functions inherited from XMLInputBase
bool readXML (const char *fileName, bool verbose=true)
Reads an XML input file.
bool loadXML (const char *xml)
Loads data from an XML-formatted text string.
Public Attributes
SIMoptions & opt
Simulation control parameters.
Static Public Attributes
static int msgLevel = 2
Controls the console output amount during solving.
Protected Types
using IntVec = std::vector< int >
Convenience alias.
Protected Member Functions
SIMadmin (const char *heading=nullptr)
The default constructor initializes the process administrator.
SIMadmin (SIMadmin &anotherSIM)
Copy constructor.
Protected Member Functions inherited from XMLInputBase
const tinyxml2::XMLElement * loadFile (tinyxml2::XMLDocument &doc, const char *fileName, bool verbose=false)
Loads an XML input file into a tinyxml2::XMLDocument object.
virtual const char ** getPrioritizedTags () const
Returns a list of prioritized XML-tags.
Protected Attributes
ProcessAdm adm
Parallel administrator.
int myPid
Processor ID in parallel simulations.
int nProc
Number of processors in parallel simulations.
std::string myHeading
Heading written before reading the input file.
Private Member Functions
bool readFlat (const char *fileName)
Reads a flat text input file (the old file format).
Private Attributes
SIMoptions myOpts
Actual control parameters owned by this simulator.
Detailed Description
Administration base class for FEM simulators.
This class serves as a common base for all types of simulator drivers in IFEM and contains the general top-level methods for reading the model input file, as well as data for administration of parallel executions.
Member Function Documentation
getGlobalProcessID()
int SIMadmin::getGlobalProcessID () const inline
Returns the global process ID.
Note
May be different from the process ID used in the equation solver.
References myPid.
parse() [1/2]
bool SIMadmin::parse (char * keyWord, std::istream & is) virtual
Parses a data section from an input stream.
Reimplemented in SIMSolver< T1 >, SIMSemi3D< PlaneSolver >, AdaptiveSIM, MultiStepSIM, NewmarkSIM, NonLinSIM, SIM1D, SIM2D, SIM3D, SIMinput, SIMmultiCpl, SIMoutput, SIMoutput, and SIMSolverAdapImpl< T1, AdapSim >.
Referenced by SIM1D::parse(), SIM2D::parse(), SIM3D::parse(), SIM1D::parse(), SIM2D::parse(), SIM3D::parse(), SIMinput::parse(), SIMsupel::parse(), and readFlat().
parse() [2/2]
bool SIMadmin::parse (const tinyxml2::XMLElement * elem) virtual
Parses a data section from an XML document.
Implements XMLInputBase.
Reimplemented in SIMSemi3D< PlaneSolver >, SIMSolver< T1 >, SIMSolverAdapImpl< T1, AdapSim >, SIMSolverTS< T1 >, AdaptiveSIM, EigenModeSIM, EigenModeSIM, GenAlphaSIM, GenAlphaSIM, HHTSIM, HHTSIM, MultiStepSIM, MultiStepSIM, NewmarkNLSIM, NewmarkNLSIM, NewmarkSIM, NewmarkSIM, NewmarkSIM, NonLinSIM, SIM1D, SIM2D, SIM3D, SIMinput, SIMmultiCpl, SIMmultiCpl, SIMoutput, SIMsupel, SIMSemi3D< PlaneSolver >, and SIMSolverAdapInternal< T1 >.
References utl::getValue(), and msgLevel.
preprocess()
virtual bool SIMadmin::preprocess (const IntVec & ignored = {}, bool fixDup = false) inline virtual
Performs some pre-processing tasks on the FE model.
Reimplemented in SIMSemi3D< PlaneSolver >, and MultiStepSIM.
Referenced by MultiStepSIM::preprocess(), and AdaptiveSIM::solveStep().
preprocessC()
virtual bool SIMadmin::preprocessC (const IntVec & , bool , double = 0.0) inline virtual
Performs some pre-processing tasks on the FE model.
Reimplemented in AdaptiveSIM, SIMbase, and SIMmultiCpl.
read()
bool SIMadmin::read (const char * fileName) virtual
Reads model data from the specified input file *fileName.
Reimplemented in SIMSolverStat< T1 >, SIMSolver< T1 >, SIMSolverAdapImpl< T1, AdapSim >, SIMSolverTS< T1 >, SIMSolverAdapInternal< T1 >, and SIMSemi3D< PlaneSolver >.
References IFEM::applyCommandLineOptions(), opt, printHeading(), readFlat(), and XMLInputBase::readXML().
Referenced by SIMSolver< T1 >::read(), SIMSolverAdapImpl< T1, AdapSim >::read(), SIMSolverTS< T1 >::read(), SIMSolverAdapInternal< T1 >::read(), SIMSemi3D< PlaneSolver >::read(), SIMbase::readModel(), and AdaptiveSIM::solveStep().
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/SIM/SIMadmin.h
/home/runner/work/IFEM-2/IFEM-2/src/SIM/SIMadmin.C