IFEM: PerforatedPlate2D Class Reference
PerforatedPlate2D Class Reference
Class representing a plate perforated by multiple holes.
#include <IBGeometries.h>
Public Member Functions
PerforatedPlate2D ()
Default constructor.
PerforatedPlate2D (Hole2D *hole)
Constructor creating a single hole.
virtual ~PerforatedPlate2D ()
The destructor deletes the holes.
void addHole (double r, double x, double y)
Adds a hole to the perforated plate.
void addHole (double r, double x0, double y0, double x1, double y1)
Adds a hole to the perforated plate.
virtual double Alpha (double X, double Y, double) const
Performs the inside-outside test for the perforated plate object.
virtual ElementBlock * tesselate () const
Creates a finite element model of the geometry for visualization.
Public Member Functions inherited from Immersed::Geometry
virtual ~Geometry ()
Empty destructor.
virtual double Alpha (const Vec3 &X) const
Performs the inside-outside test for the geometric object.
Private Attributes
std::vector< Hole2D * > holes
The holes that perforate the plate.
Additional Inherited Members
Protected Member Functions inherited from Immersed::Geometry
Geometry ()
The default constructor is protected to allow sub-classes only.
Detailed Description
Class representing a plate perforated by multiple holes.
Member Function Documentation
Alpha()
double PerforatedPlate2D::Alpha (double X, double Y, double) const virtual
Performs the inside-outside test for the perforated plate object.
Reimplemented from Immersed::Geometry.
References Alpha(), and holes.
Referenced by Alpha().
tesselate()
ElementBlock * PerforatedPlate2D::tesselate () const virtual
Creates a finite element model of the geometry for visualization.
Reimplemented from Immersed::Geometry.
References holes, and ElementBlock::merge().
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/ASM/IBGeometries.h
/home/runner/work/IFEM-2/IFEM-2/src/ASM/IBGeometries.C