IFEM: SIMsolution Class Reference
SIMsolution Class Reference
Solution vector container with serialization support.
#include <SIMsolution.h>
Public Member Functions
virtual const Vectors & getSolutions () const
Returns a const reference to the solution vectors.
virtual Vectors & theSolutions ()
Returns a reference to the solution vectors (for assignment).
virtual const Vector & getSolution (int ix=0) const
Returns a const reference to current solution vector.
virtual void setSolution (const RealArray &s, int ix=0)
Modifies the current solution vector (used by sub-iterations only).
Protected Types
using SerializeMap = std::map< std::string, std::string >
Convenience type.
Protected Member Functions
SIMsolution ()=default
The default constructor is protected to allow sub-classes only.
virtual ~SIMsolution ()=default
Empty default destructor.
void initSolution (size_t ndof, size_t nsol=1)
Initializes the solution vectors.
void pushSolution (unsigned short int nVecState=1)
Pushes the solution vector stack.
bool saveSolution (SerializeMap &data, const std::string &name) const
Writes current solution to a serialization container.
bool restoreSolution (const SerializeMap &data, const std::string &name)
Restores the solution from a serialization container.
Static Protected Member Functions
static std::string serialize (const double *v, size_t n)
Helper method for serializing a double array into a text string.
static void deSerialize (const std::string &data, double *v, size_t n)
Helper method for deserializing a double array from a text string.
Protected Attributes
Vectors solution
Stack of solution vectors.
Detailed Description
Solution vector container with serialization support.
Member Function Documentation
deSerialize()
void SIMsolution::deSerialize (const std::string & data, double * v, size_t n) static protected
Helper method for deserializing a double array from a text string.
Parameters
[in] data The serialized string
[out] v Pointer to double array (assumed allocated outside)
[in] n Length of array
Referenced by HHTSIM::deSerialize(), MultiStepSIM::deSerialize(), and NewmarkNLSIM::deSerialize().
initSolution()
void SIMsolution::initSolution (size_t ndof, size_t nsol = 1) protected
Initializes the solution vectors.
Parameters
[in] ndof Number of degrees of freedom
[in] nsol Number of solution vectors
References solution.
Referenced by MultiStepSIM::initSol().
pushSolution()
void SIMsolution::pushSolution (unsigned short int nVecState = 1) protected
Pushes the solution vector stack.
Parameters
[in] nVecState Number of vectors per state
References solution.
Referenced by EigenModeSIM::advanceStep(), NewmarkSIM::advanceStep(), and NonLinSIM::advanceStep().
restoreSolution()
bool SIMsolution::restoreSolution (const SerializeMap & data, const std::string & name) protected
Restores the solution from a serialization container.
Parameters
[in] data Container for serialized data
[in] name Name of simulator the solution belongs to
References theSolutions().
Referenced by HHTSIM::deSerialize(), MultiStepSIM::deSerialize(), and NewmarkNLSIM::deSerialize().
saveSolution()
bool SIMsolution::saveSolution (SerializeMap & data, const std::string & name) const protected
Writes current solution to a serialization container.
Parameters
data Container for serialized data
[in] name Name of simulator the solution belongs to
References getSolutions().
Referenced by HHTSIM::serialize(), MultiStepSIM::serialize(), and NewmarkNLSIM::serialize().
serialize()
std::string SIMsolution::serialize (const double * v, size_t n) static protected
Helper method for serializing a double array into a text string.
Parameters
[in] v Pointer to double array
[in] n Length of array
Returns
The serialized string
Referenced by HHTSIM::serialize(), MultiStepSIM::serialize(), and NewmarkNLSIM::serialize().
setSolution()
virtual void SIMsolution::setSolution (const RealArray & s, int ix = 0) inline virtual
Modifies the current solution vector (used by sub-iterations only).
Reimplemented in GenAlphaSIM, HHTSIM, and NewmarkNLSIM.
References solution.
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/SIM/SIMsolution.h
/home/runner/work/IFEM-2/IFEM-2/src/SIM/SIMsolution.C