IFEM: L2Integrand Class Reference
L2Integrand Class Reference abstract
Abstract class for evaluating integrand or function.
#include <GlbL2projector.h>
Public Member Functions
L2Integrand (const ASMbase &patch)
The constructor initializes the patch reference.
virtual ~L2Integrand ()
Empty destructor.
virtual bool evaluate (Matrix &sField, const RealArray *gpar) const =0
Evaluates the entity in a set of points.
virtual size_t dim () const =0
Returns dimension of entity to evaluate.
double getTimeLevel () const
Returns current time/load parameter for 2ndary solution evaluation.
Protected Attributes
const ASMbase & m_patch
Reference to ASM holding geometry.
double myTime
Current time or load parameter.
Detailed Description
Abstract class for evaluating integrand or function.
Constructor & Destructor Documentation
L2Integrand()
L2Integrand::L2Integrand (const ASMbase & patch) inline
The constructor initializes the patch reference.
Parameters
[in] patch ASM holding geometry to evaluate on
References myTime.
Member Function Documentation
dim()
virtual size_t L2Integrand::dim () const pure virtual
Returns dimension of entity to evaluate.
Implemented in L2ProbIntegrand, and L2FuncIntegrand.
Referenced by ASMbase::globalL2projection().
evaluate()
virtual bool L2Integrand::evaluate (Matrix & sField, const RealArray * gpar) const pure virtual
Evaluates the entity in a set of points.
Parameters
[out] sField Matrix with results
[in] gpar Points to evaluate in
Implemented in L2ProbIntegrand, and L2FuncIntegrand.
Referenced by ASMs1D::assembleL2matrices(), ASMs2D::assembleL2matrices(), ASMs2DLag::assembleL2matrices(), ASMs3D::assembleL2matrices(), ASMs3DLag::assembleL2matrices(), ASMu2D::assembleL2matrices(), ASMu3D::assembleL2matrices(), and ASMbase::globalL2projection().
The documentation for this class was generated from the following file:
/home/runner/work/IFEM-2/IFEM-2/src/ASM/GlbL2projector.h