IFEM: ASMs2D Class Reference
ASMs2D Class Reference
Driver for assembly of structured 2D spline FE models.
#include <ASMs2D.h>
Classes
class BasisFunctionCache
Implementation of basis function cache.
struct BlockNodes
Struct with data for definition of global node numbers of a patch.
struct DirichletEdge
Struct representing an inhomogeneous Dirichlet boundary condition.
struct Edge
Struct for edge node definitions.
struct IJ
Struct for nodal point data.
class InterfaceChecker
Base class that checks if an element has interface contributions.
Public Member Functions
ASMs2D (unsigned char n_s=2, unsigned char n_f=2)
Default constructor.
ASMs2D (const ASMs2D &patch, unsigned char n_f)
Special copy constructor for sharing of FE data.
ASMs2D (const ASMs2D &patch)
Default copy constructor copying everything.
virtual ~ASMs2D ()
The destructor frees the dynamically allocated boundary curves.
virtual Go::SplineCurve * getBoundary (int dir, int=1)
Returns the spline curve representing a boundary of this patch.
virtual Go::SplineSurface * getBasis (int basis=1)
Returns the spline surface representing a basis of this patch.
virtual const Go::SplineSurface * getBasis (int basis=1) const
Returns the spline surface representing a basis of this patch.
virtual void copyParameterDomain (const ASMbase *other)
Copies the parameter domain from the other patch.
virtual bool read (std::istream &)
Creates an instance by reading the given input stream.
virtual bool write (std::ostream &, int) const
Writes the geometry of the SplineSurface object to given stream.
virtual bool generateFEMTopology ()
Generates the finite element topology data for the patch.
virtual void clear (bool retainGeometry=false)
Clears the contents of the patch, making it empty.
virtual bool addXElms (short int dim, short int item, size_t nXn, IntVec &nodes)
Adds extraordinary elements associated with a patch boundary.
bool addInterfaceElms (const ASM::InterfaceChecker &iChk)
Adds interface elements with coupling to all element DOFs.
virtual size_t getNodeIndex (int globalNum, bool noAddedNodes=false) const
Returns local 1-based index of the node with given global number.
virtual int getNodeID (size_t inod, bool noAddedNodes=false) const
Returns the global node number for the given node.
virtual bool getElementCoordinates (Matrix &X, int iel, bool forceItg=false) const
Returns a matrix with nodal coordinates for an element.
virtual void getNodalCoordinates (Matrix &X, bool geo=false) const
Returns a matrix with all nodal coordinates within the patch.
virtual Vec3 getCoord (size_t inod) const
Returns the global coordinates for the given node.
virtual Vec3 getElementCenter (int iel) const
Returns the coordinate of the element center.
virtual bool updateCoords (const Vector &displ)
Updates the nodal coordinates for this patch.
virtual void getBoundaryNodes (int lIndex, IntVec &nodes, int basis, int thick=1, int=0, bool local=false) const
Finds the global (or patch-local) node numbers on a patch boundary.
virtual int getCorner (int I, int J, int basis) const
Returns the node index for a given corner.
bool assignNodeNumbers (BlockNodes &nodes, int basis=0)
Assigns new global node numbers for all nodes of the patch.
virtual bool checkRightHandSystem ()
Checks that the patch is modelled in a right-hand-side system.
virtual bool refine (int dir, const RealArray &xi, double scale=1.0)
Refines the parametrization by inserting extra knots.
virtual bool uniformRefine (int dir, int nInsert)
Refines the parametrization by inserting extra knots uniformly.
virtual bool raiseOrder (int ru, int rv)
Raises the order of the SplineSurface object for this patch.
virtual bool createProjectionBasis (bool init)
Creates a separate projection basis for this patch.
virtual bool separateProjectionBasis () const
Checks if a separate projection basis is used for this patch.
virtual void constrainEdge (int dir, bool open, int dof, int code, char basis)
Constrains all DOFs on a given boundary edge.
virtual size_t constrainEdgeLocal (int dir, bool open, int dof, int code, bool project=false)
Constrains all DOFs in local directions on a given boundary edge.
virtual void constrainCorner (int I, int J, int dof, int code=0, char basis=1)
Constrains a corner node identified by the two parameter indices.
virtual void constrainNode (double xi, double eta, int dof, int code=0)
Constrains a node identified by two relative parameter values.
virtual bool connectPatch (int edge, ASM2D &neighbor, int nedge, bool revers, int=0, bool coordCheck=true, int thick=1)
Connects all matching nodes on two adjacent boundary edges.
virtual void closeBoundaries (int dir, int basis, int master)
Makes two opposite boundary edges periodic.
virtual bool collapseEdge (int dir, int basis=1)
Collapses a degenereated edge into a single node.
virtual bool addRigidCpl (int lindx, int ldim, int basis, int &gMaster, const Vec3 &Xmaster, bool extraPt)
Adds MPCs representing a rigid coupling to this patch.
virtual void setNodeNumbers (const IntVec &nodes)
Sets the global node numbers for this patch.
virtual bool updateDirichlet (const std::map< int, RealFunc * > &func, const std::map< int, VecFunc * > &vfunc, double time, const std::map< int, int > *g2l, bool tangent)
Updates the time-dependent in-homogeneous Dirichlet coefficients.
virtual bool selfInterconnect (const std::vector< Ipair > &nodes, double xtol)
Connects a list of node pairs to each other.
virtual bool integrate (Integrand &integrand, GlobalIntegral &glbInt, const TimeDomain &time)
Evaluates an integral over the interior patch domain.
virtual bool integrate (Integrand &integrand, int lIndex, GlobalIntegral &glbInt, const TimeDomain &time)
Evaluates a boundary integral over a patch edge.
virtual bool integrate (Integrand &integrand, GlobalIntegral &glbInt, const TimeDomain &time, const ASM::InterfaceChecker &iChk)
Evaluates an integral over element interfaces in the patch.
virtual int evalPoint (const double *xi, double *param, Vec3 &X) const
Evaluates the geometry at a specified point.
virtual int findElementContaining (const double *param) const
Returns the element that contains a specified spatial point.
virtual double findPoint (Vec3 &X, double *param) const
Searches for the specified Cartesian point in the patch.
virtual bool getGridParameters (RealArray &prm, int dir, int nSegSpan) const
Calculates parameter values for visualization nodal points.
virtual bool tesselate (ElementBlock &grid, const int *npe) const
Creates a quad element model of this patch for visualization.
virtual bool evalSolution (Matrix &sField, const Vector &locSol, const int *npe, int n_f, bool piola) const
Evaluates the primary solution field at all visualization points.
virtual bool evalSolution (Matrix &sField, const Vector &locSol, const RealArray *gpar, bool regular=true, int deriv=0, int=0) const
Evaluates the primary solution field at the given points.
virtual bool evalProjSolution (Matrix &sField, const Vector &locSol, const int *npe, int n_f) const
Evaluates the projected solution field at all visualization points.
virtual bool evaluate (const ASMbase *basis, const Vector &locVec, RealArray &vec, int basisNum) const
Evaluates and interpolates a field over a given geometry.
virtual bool evaluate (const Field *field, RealArray &vec, int basisNum) const
Evaluates and interpolates a field over a given geometry.
virtual bool evaluate (const FunctionBase *func, RealArray &vec, int basisNum, double time) const
Evaluates and interpolates a function over a given geometry.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const int *npe=nullptr, char project=0) const
Evaluates the secondary solution field at all visualization points.
virtual Go::GeomObject * evalSolution (const IntegrandBase &integrand) const
Projects the secondary solution field onto the primary basis.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const RealArray *gpar, bool regular=true) const
Evaluates the secondary solution field at the given points.
virtual bool getOrder (int &p1, int &p2, int &p3) const
Returns the polynomial order in each parameter direction.
virtual bool getSize (int &n1, int &n2, int basis=0) const
Returns the number of nodal points in each parameter direction.
virtual bool getSize (int &n1, int &n2, int &n3, int basis) const
Returns the number of nodal points in each parameter direction.
virtual bool getNoStructElms (int &n1, int &n2, int &n3) const
Returns the number of elements in each parameter direction.
virtual void getElmConnectivities (IntMat &neigh, int basis=ASM::INTEGRATION_BASIS) const
Calculates the matrix of element neighbour connectivities.
virtual IntMat getElmNodes (int basis) const
Returns the matrix of nodal point correspondance for given basis.
virtual size_t getNoBoundaryElms (char lIndex, char ldim) const
Returns the number of elements on a boundary.
virtual size_t getNoNodes (int basis=0) const
Returns the total number of nodes in this patch.
virtual size_t getNoProjectionNodes () const
Returns the number of projection nodes for this patch.
virtual bool getParameterDomain (Real2DMat &u, IntVec *corners) const
Returns parameter values and node numbers of the domain corners.
virtual void evaluateBasis (double u, double v, double, Vector &N) const
Evaluates the basis functions at the specified point.
void extractBasis (double u, double v, Vector &N, Matrix &dNdu, bool fromRight=true) const
Establishes matrices with basis functions and 1st derivatives.
void extractBasis (double u, double v, Vector &N, Matrix &dNdu, Matrix3D &d2Ndu2, bool fromRight=true) const
Establishes matrices with basis functions, 1st and 2nd derivatives.
void extractBasis (double u, double v, int dir, int p, Vector &dN, bool fromRight=true) const
Establishes a vector with basis function derivatives.
virtual Field * getProjectedField (const Vector &coefs) const
Returns a field using the projection basis.
virtual Fields * getProjectedFields (const Vector &coefs, size_t=0) const
Returns a field using the projection basis.
Public Member Functions inherited from ASMstruct
virtual ~ASMstruct ()
The destructor frees the dynamically allocated spline objects.
virtual bool empty () const
Checks if the patch is empty.
virtual bool diracPoint (Integrand &integr, GlobalIntegral &glInt, const double *u, const Vec3 &pval)
Integrates a spatial dirac-delta function over a patch.
virtual void swapProjectionBasis ()
Swaps between the first and second projection basis.
virtual bool evalSolution (Matrix &sField, const Vector &locSol, const int *npe, int n_f=0, bool piola=false) const
Evaluates the primary solution field at all visualization points.
virtual bool evalSolution (Matrix &sField, const Vector &locSol, const RealArray *gpar, bool regular=true, int deriv=0, int n_f=0) const
Evaluates the primary solution field at the given points.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const int *npe=nullptr, char project=0) const
Evaluates the secondary solution field at all visualization points.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const RealArray *gpar, bool regular=true) const
Evaluates the secondary solution field at the given points.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const IntVec &elements) const
Evaluates the secondary solution field at element centers.
Public Member Functions inherited from ASMbase
virtual ~ASMbase ()
The destructor frees the dynamically allocated data objects.
ASMbase * cloneUnShared () const
Returns a copy of this patch with identical FE discretization.
virtual bool readBasis (std::istream &, size_t)
Reads a basis from the given input stream.
virtual void addHole (double, double, double)
Adds a circular immersed boundary in the physical geometry.
virtual void addHole (double, double, double, double, double)
Adds an oval immersed boundary in the physical geometry.
virtual bool setGeometry (RealFunc *, double, double)
Defines the immersed geometry from a scalar function.
bool addLagrangeMultipliers (size_t iel, const IntVec &mGLag, unsigned char nnLag=1)
Adds a set of Lagrange multipliers to the specified element.
bool addGlobalLagrangeMultipliers (const IntVec &mGLag, unsigned char nnLag=1)
Adds global Lagrange multipliers to the system.
virtual void setGauss (int ng)
Defines the numerical integration scheme nGauss in the patch.
void setNoFields (unsigned char n)
Defines the number of solution fields in the patch.
void setElementActivator (IntFunc *efunc)
Sets the element activation function.
const IntFunc * getElementActivator () const
Returns a pointer to the element activation function.
virtual void setMinimumSize (double)
Sets the minimum element size for adaptive refinement.
virtual double getMinimumSize (int=0) const
Defines the minimum element size for adaptive refinement.
virtual bool checkElementSize (int, bool=true) const
Checks if the specified element is larger than the minimum size.
unsigned char getNoSpaceDim () const
Returns the number of spatial dimensions.
unsigned char getNoParamDim () const
Returns the number of parameter dimensions.
virtual unsigned char getNoFields (int b=0) const
Returns the number of solution fields.
unsigned char getNoLagPerNode () const
Returns the number of Lagrange multipliers per node.
size_t getElmIndex (int globalNum) const
Returns local 1-based index of element with given global number.
int getElmID (size_t iel) const
Returns the global element number for the given element.
virtual unsigned char getNodalDOFs (size_t inod) const
Returns the number of DOFs per node.
virtual char getNodeType (size_t inod) const
Returns the classification of a node.
bool isLMn (size_t n) const
Returns true if node n is a Lagrange multiplier node.
bool isRMn (size_t n) const
Returns true if node n is a master node of a rigid coupling.
char getLMType (size_t inod) const
Returns the type of a Lagrange multiplier node.
virtual void getBoundary1Nodes (int lIndex, IntVec &nodes, int basis=0, int orient=-1, bool local=false, bool open=false) const
Finds the global (or patch-local) node numbers on a patch boundary.
void getBoundaryElms (int lIndex, IntVec &elms, int orient=-1, bool local=false) const
Finds the global (or patch-local) element numbers on a boundary.
int getNodeSetIdx (const std::string &setName) const
Returns (1-based) index of a predefined node set in the patch.
const IntVec & getNodeSet (int iset) const
Returns an indexed predefined node set.
IntVec & getNodeSet (const std::string &setName, int &idx)
Returns a named node set for update.
bool isInNodeSet (int iset, int inod) const
Checks if node inod is within predefined node set iset.
int parseNodeSet (const std::string &setName, const char *cset, bool assumeZeroBased=false)
Defines a node set by parsing a list of node numbers.
virtual int parseNodeBox (const std::string &, const char *)
Defines a node set by parsing a 3D bounding box.
void convertNodeSets ()
Converts node number sets to internal (1-based) node indices.
virtual int getElementSetIdx (const std::string &) const
Returns (1-based) index of a predefined element set in the patch.
virtual const IntVec & getElementSet (int) const
Returns an indexed predefined element set.
virtual bool getElementSet (int, std::string &) const
Returns the name of an indexed predefined element set.
virtual bool isInElementSet (int, int) const
Checks if an element is within a predefined element set.
virtual int parseElemSet (const std::string &, const char *)
Defines an element set by parsing a list of element numbers.
virtual int parseElemBox (const std::string &, const std::string &, const char *)
Defines an element set by parsing a 3D bounding box.
virtual std::pair< size_t, double > findClosestNode (const Vec3 &) const
Finds the node that is closest to the given point.
void printNodes (std::ostream &os) const
Prints out the nodal coordinates of this patch to the given stream.
void printElements (std::ostream &os) const
Prints out element connections of this patch to the given stream.
virtual void printElmInfo (int, const IntegrandBase *) const
Prints out additional app-dependent element information.
virtual void shiftGlobalNodeNums (int nshift)
Increase all global node numbers by nshift.
void setGlobalNodeNums (const IntVec &nodes)
Sets the global node numbers for this patch.
const IntVec & getMyNodeNums () const
Returns the actual global node numbers of this patch.
const IntVec & getGlobalNodeNums () const
Returns the global node numbers of this patch.
virtual void shiftGlobalElmNums (int eshift)
Increase all global element numbers by eshift.
const IntVec & getGlobalElementNums () const
Returns the global element numbers of this patch.
void setActiveElements (IntVec *active)
Sets the list of active elements during assembly.
bool isElementActive (int iel, double time=-1.0) const
Returns true if element with 0-based index iel is active.
bool inActive (double time=-1.0) const
Returns true if none of the elements in the patch are active.
double getAge (int iel, double time) const
Returns the age of the element with 0-based index iel.
bool isElementInPartition (int iel) const
Returns true if element is in process partition.
const IntVec & getElementNodes (int iel) const
Returns the nodal point correspondance array for an element.
virtual size_t getNoBasis () const
Returns number of bases of this patch.
size_t getNoElms (bool includeZeroVolElms=false, bool includeXElms=false) const
Returns the total number of elements in this patch.
int getMaxElmNo () const
Returns the highest external element number in this patch.
size_t getNoMPCs () const
Returns the total number of multi-point constraint equations.
virtual void getNoIntPoints (size_t &nPt, size_t &nIPt)
Computes the total number of integration points in this patch.
virtual void getNoBouPoints (size_t &nPt, char ldim, char lindx)
Computes the number of boundary integration points in this patch.
BCVec::const_iterator begin_BC () const
Returns the beginning of the BCode array.
BCVec::const_iterator end_BC () const
Returns the end of the BCode array.
IntMat::const_iterator begin_elm () const
Returns the beginning of the MNPC array.
IntMat::const_iterator end_elm () const
Returns the end of the MNPC array.
MPCIter begin_MPC () const
Returns the beginning of the mpcs set.
MPCIter end_MPC () const
Returns the end of the mpcs set.
MPC * findMPC (int node, int dof) const
Returns a pointer to the MPC object for a specified slave, if any.
bool isShared () const
Returns true if this patch shares FE data with another patch.
bool hasXNodes () const
Returns true if this patch has additional (extraordinary) nodes.
bool mergeNodes (size_t inod, int globalNum, bool verbose=true)
Merges a given node in this patch with a given global node.
int renumberNodes (std::map< int, int > &old2new, int &nNod)
Renumbers the global node numbers in this patch.
bool renumberNodes (const std::map< int, int > &old2new, const std::vector< int > &new2old={}, int renumGN=0, std::map< int, int > *degenElm=nullptr)
Renumbers the global node numbers referred by this patch.
virtual bool initConstraints ()
Initializes the multi-point constraint coefficients.
bool hasTimeDependentDirichlet (const std::map< int, RealFunc * > &func, const std::map< int, VecFunc * > &vfunc)
Checks for time-dependent in-homogeneous Dirichlet conditions.
virtual bool transform (const Matrix &)
Applies a transformation matrix from local to global system.
virtual void initMADOF (const int *)
Initializes the patch level MADOF array for mixed problems.
virtual bool integrateEdge (Integrand &integrand, int lEdge, GlobalIntegral &glbInt, const TimeDomain &time)
Evaluates a boundary integral over a patch edge.
virtual ElementBlock * immersedGeometry (char *) const
Returns an additional geometry to visualize (immersed boundaries).
virtual ElementBlock * extraGeometry (char *) const
Returns an additional geometry to visualize (spiders, etc.).
virtual void filterResults (Matrix &, const ElementBlock *) const
Filters out result point values that are outside physical domain.
virtual bool getSolution (Matrix &sField, const Vector &locSol, const IntVec &nodes) const
Extract the primary solution field at the specified nodes.
virtual bool immersedSolution (Matrix &, const Vector &) const
Evaluates the primary solution at the immersed geometry points.
virtual bool extraSolution (Matrix &, const Vector &) const
Evaluates the primary solution at the extra geometry points.
virtual bool evalSolutionPiola (Matrix &sField, const Vector &locSol, const RealArray *gpar, bool regular) const
Evaluates the primary solution field with Piola mapping.
bool globalL2projection (Matrix &sField, const L2Integrand &integrand, bool continuous=false, bool enforceEnds=false) const
Projects the secondary solution using a (discrete) global L2-fit.
bool L2projection (Matrix &sField, IntegrandBase *integrand, const TimeDomain &time)
Projects the secondary solution using a continuous global L2-fit.
bool L2projection (Matrix &fVals, FunctionBase *func, double t=0.0)
Projects an explicit function using a continuous global L2-fit.
bool L2projection (const std::vector< Matrix * > &fVals, const std::vector< FunctionBase * > &funcs, double t=0.0)
Projects explicit functions using a continuous global L2-fit.
virtual size_t getNoRefineNodes () const
Returns the number of nodes on refinement basis for this patch.
virtual size_t getNoRefineElms () const
Returns the number of elements on refinement basis for this patch.
virtual const ASMbase * getOutputMaster () const
Returns the master patch to use for VTF- and HDF5-output.
void extractElmRes (const Vector &globRes, Vector &elmRes, size_t internalFirst=0) const
Extracts element results for this patch from a global vector.
void extractElmRes (const Matrix &globRes, Vector &elmRes, size_t irow) const
Extracts element results for this patch from a global matrix.
bool extractNodalVec (const RealArray &globVec, RealArray &nodeVec, const int *madof, int ngnod=-1) const
Extracts nodal results for this patch from the global vector.
virtual void extractNodeVec (const RealArray &globVec, RealArray &nodeVec, unsigned char nndof=0, int basis=0) const
Extracts nodal results for this patch from the global vector.
virtual bool injectNodeVec (const RealArray &nodeVec, RealArray &globVec, unsigned char nndof=0, int basis=0) const
Injects nodal results for this patch into the global vector.
bool injectNodalVec (const RealArray &nodeVec, RealArray &globVec, const IntVec &madof, int basis=0) const
Injects nodal results for this patch into the global vector.
bool add2PC (int slave, int dir, int master, int code=0)
Creates and adds a two-point constraint to this patch.
bool addMPC (MPC *&mpc, int code=0, bool verbose=false, bool overrideD=false)
Adds a general multi-point-constraint (MPC) equation to this patch.
void addRigidCouplings (int gMaster, const Vec3 &Xmaster, const IntVec &slaveNodes)
Adds MPC-equations representing a rigid coupling to this patch.
void addNodalCouplings (int slave, const IntVec &masters, const RealArray &weights)
Adds MPC-equations for general nodal couplings in this patch.
void constrainPatch (int dof, int code=0)
Constrains all nodes in the patch.
void constrainNodes (const IntVec &nodes, int dof, int code=0, bool overrideD=false)
Constrains a list of nodes in the patch.
bool constrainXnode (int node, int dof, int code=0)
Constrains an extraordinary node in the patch.
int prescribe (size_t inod, int dirs, int code, bool overrideD=false)
Constrains DOFs in the given node to the given value.
int fix (size_t inod, int dirs=123)
Constrains DOFs in the given node to zero.
bool isFixed (int node, int dof, bool all=false) const
Checks if the given DOFs are fixed.
Public Member Functions inherited from ASM2D
virtual ~ASM2D ()
Empty destructor.
ASMbase * clone (const CharVec &nf=CharVec()) const
Returns a copy of this patch with identical FE discretization.
virtual bool refine (int dir, const std::vector< double > &xi, double scale=1.0)=0
Refines the parametrization by inserting extra knots.
virtual bool getGridParameters (std::vector< double > &prm, int dir, int nSegSpan) const =0
Calculates parameter values for visualization nodal points.
Static Public Member Functions
static void scatterInd (int n1, int n2, int p1, int p2, const int *start, IntVec &index)
Auxilliary function for computation of basis function indices.
Static Public Member Functions inherited from ASMbase
static void resetNumbering (int n=0)
Resets the global element and node counters.
static int renumberNodes (const ASM::PatchVec &model, std::map< int, int > &old2new)
Renumbers all global node numbers in the entire model.
static void mergeAndGetAllMPCs (const ASM::PatchVec &model, MPCSet &allMPCs)
Computes the set of all MPC-equations over the whole model.
static void resolveMPCchains (const MPCSet &allMPCs, const ASM::PatchVec &model, bool setPtrOnly=false)
Resolves (possibly multi-level) chaining in MPC-equations.
Static Public Member Functions inherited from ASM2D
static ASMbase * create (ASM::Discretization type, unsigned char nd, const CharVec &nf, bool mixedFEM=false)
Creates a two-parametric patch of specified discretization type.
static ASMbase * create (ASM::Discretization type, unsigned char nf=1)
Creates a two-parametric patch of specified discretization type.
Protected Member Functions
bool integrate (Integrand &integrand, GlobalIntegral &glbInt, const TimeDomain &time, const Real3DMat &itgPts)
Evaluates an integral over the interior patch domain.
virtual void findBoundaryElms (IntVec &elms, int lIndex, int=0) const
Finds the patch-local element numbers on a patch boundary.
virtual bool assembleL2matrices (SystemMatrix &A, SystemVector &B, const L2Integrand &integrand, bool continuous) const
Assembles L2-projection matrices for the secondary solution.
bool connectBasis (int edge, ASMs2D &neighbor, int nedge, bool revers, int basis=1, int slave=0, int master=0, bool coordCheck=true, int thick=1)
Connects all matching nodes on two adjacent boundary edges.
void getGaussPointParameters (RealArray &uGP, int dir, int nGauss, const double *xi) const
Extracts parameter values of the Gauss points in one direction.
bool getGrevilleParameters (RealArray &prm, int dir, int basisNum=1) const
Calculates parameter values for the Greville points.
bool getQuasiInterplParameters (RealArray &prm, int dir) const
Calculates parameter values for the Quasi-Interpolation points.
double getParametricArea (int iel) const
Returns the area in the parameter space for an element.
double getParametricLength (int iel, int dir) const
Returns boundary edge length in the parameter space for an element.
bool getElementCoordinatesPrm (Matrix &X, double u, double v) const
Returns a matrix with nodal coordinates for element containing given parameters.
void getElementBorders (int i1, int i2, double *u, double *v) const
Computes the element border parameters.
virtual void getElementBorders (int iel, double *u) const
Computes the element border parameters.
double getElementCorners (int i1, int i2, std::vector< Vec3 > &XC, RealArray *uC=nullptr) const
Computes the element corner coordinates.
void getCornerPoints (int i1, int i2, std::vector< utl::Point > &XC) const
Computes the element corner coordinates and parameters.
virtual void generateThreadGroups (const Integrand &integrand, bool silence, bool ignoreGlobalLM)
Generates element groups for multi-threading of interior integrals.
virtual void changeNumThreads ()
Hook for changing number of threads.
void generateThreadGroups (size_t strip1, size_t strip2, bool silence, bool ignoreGlobalLM)
Generates element groups for multi-threading of interior integrals.
virtual void generateThreadGroupsFromElms (const IntVec &elms)
Generates element groups from a partition.
virtual void generateProjThreadGroupsFromElms (const IntVec &elms)
Generate element groups from a partition.
virtual bool validateThreadGroups (const SAM *sam) const
Validates the threading groups based on the assembly data in SAM.
virtual int getFirstItgElmNode () const
Returns 0-based index of first node on integration basis.
virtual int getLastItgElmNode () const
Returns 0-based index of last node on integration basis.
virtual void generateThreadGroups (const Integrand &, bool, bool)
Generates element groups for multi-threading of interior integrals.
virtual void generateThreadGroups (char, bool, bool)
Generates element groups for multi-threading of boundary integrals.
Protected Member Functions inherited from ASMstruct
ASMstruct (unsigned char n_p, unsigned char n_s, unsigned char n_f)
The constructor sets the number of space dimensions and fields.
ASMstruct (const ASMstruct &patch, unsigned char n_f)
Special copy constructor for sharing of FE data.
bool addXNodes (unsigned short int dim, size_t nXn, IntVec &nodes)
Adds extraordinary nodes associated with a patch boundary.
bool checkThreadGroups (const std::vector< std::set< int > > &nodes, int group, bool ignoreGlobalLM)
Performs a sanity check on the thread groups.
Protected Member Functions inherited from ASMbase
ASMbase (unsigned char n_p, unsigned char n_s, unsigned char n_f)
The constructor sets the number of space dimensions and fields.
ASMbase (const ASMbase &patch, unsigned char n_f)
Special copy constructor for sharing of FE data.
ASMbase (const ASMbase &patch)
Default copy constructor, copying everything except neighbors.
void addLocal2GlobalCpl (int iSlave, int master, const Tensor &Tlg)
Creates constraint equations coupling global DOFs to local DOFs.
bool add3PC (int slave, int dir, int master1, int master2, int code=0)
Creates and adds a three-point constraint to this patch.
bool addPeriodicity (size_t master, size_t slave, int dir)
Creates and adds a periodicity constraint to this patch.
void makePeriodic (size_t master, size_t slave, int dirs=123)
Creates periodicity constraints between two nodes in this patch.
void addNeighbor (ASMbase *pch)
Adds a patch to the list of neighbors of this patch.
bool createRgdMasterNode (int &gMaster, const Vec3 &Xmaster)
Creates an additional master node for a rigid coupling.
void addRigidMPC (int gSlave, int gMaster, const Vec3 &dX)
Adds MPC-equations representing a rigid arm to a 6-DOF node.
int getNoGaussPt (int p, bool neumann=false) const
Returns the number of Gauss points to use in one direction.
int searchCtrlPt (RealArray::const_iterator cit, RealArray::const_iterator end, const Vec3 &X, int dimension, double xtol=0.001) const
Helper method used by evalPoint to search for a control point.
bool allDofs (int dirs) const
Returns true if dirs constains all local DOFs in the patch.
bool writeLagBasis (std::ostream &os, const char *type) const
Writes a Lagrangian basis to the given stream.
Protected Member Functions inherited from ASM2D
ASM2D ()
The constructor is protected to allow objects of sub-classes only.
Protected Attributes
std::shared_ptr< Go::SplineSurface > surf
The actual spline surface object.
Go::SplineCurve * bou [4]
Pointers to the four boundary curves.
bool swapV
Has the v-parameter direction been swapped?
const IndexVec & nodeInd
IJ-pairs for the control points (nodes)
IndexVec myNodeInd
The actual IJ-pair container.
std::map< size_t, size_t > xnMap
Node index map used by getCoord()
std::map< size_t, size_t > nxMap
Node index map used by getNodeID()
std::vector< DirichletEdge > dirich
Inhomogeneous Dirichlet boundary condition data.
ThreadGroups threadGroups
Element groups for multi-threaded assembly.
std::vector< std::unique_ptr< BasisFunctionCache > > myCache
Basis function cache.
Protected Attributes inherited from ASMstruct
std::shared_ptr< Go::GeomObject > geomB
Pointer to spline object of the geometry basis.
std::shared_ptr< Go::GeomObject > projB
Pointer to spline object of the projection basis.
std::shared_ptr< Go::GeomObject > projB2
Pointer to spline object of the secondary projection basis.
ThreadGroups projThreadGroups
Element groups for multi-threaded assembly - projection basis.
ThreadGroups proj2ThreadGroups
Element groups for multi-threaded assembly - second projection basis.
Protected Attributes inherited from ASMbase
unsigned char ndim
Number of parametric dimensions (1, 2 or 3)
unsigned char nsd
Number of space dimensions (ndim <= nsd <= 3)
unsigned char nf
Number of primary solution fields (1 or larger)
unsigned char nLag
Number of Lagrange multipliers per node.
size_t nel
Number of regular elements in this patch.
size_t nnod
Number of regular nodes in this patch.
const IntVec & MLGE
Matrix of Local to Global Element numbers.
const IntVec & MLGN
Matrix of Local to Global Node numbers.
const IntMat & MNPC
Matrix of Nodal Point Correspondance.
const char shareFE
Flag telling whether this patch shares its data with another patch.
BCVec BCode
Array of Boundary Condition codes.
MPCMap dCode
Inhomogeneous Dirichlet condition codes for the MPCs.
MPCSet mpcs
All multi-point constraints with the slave in this patch.
std::vector< ASM::NodeSet > nodeSets
Node sets for explicit Dirichlet BCs.
IntVec myMLGE
The actual Matrix of Local to Global Element numbers.
IntVec myMLGN
The actual Matrix of Local to Global Node numbers.
IntMat myMNPC
The actual Matrix of Nodal Point Correspondance.
IntVec myElms
Elements on patch - used with partitioning.
int nGauss
Numerical integration scheme for this patch.
size_t firstEl
Global index to first element within this patch.
size_t firstIp
Global index to first interior integration point.
std::map< char, size_t > firstBp
Global indices to first integration point for the Neumann boundaries.
ASM::PatchVec neighbors
Patches having nodes in common with this one.
std::map< size_t, XYZ > myRmaster
Rigid master nodal points.
Private Types
using IndexVec = std::vector< IJ >
Node index container.
Private Member Functions
Go::SplineSurface * projectSolution (const IntegrandBase &integrand) const
Projects the secondary solution field onto the primary basis.
Go::SplineSurface * scRecovery (const IntegrandBase &) const
Projects the secondary solution using a superconvergent approach.
Go::SplineSurface * projectSolutionLocal (const IntegrandBase &) const
Projects the secondary solution using Quasi-Interpolation.
Go::SplineSurface * projectSolutionLocalApprox (const IntegrandBase &) const
Projects the secondary solution using Variation Diminishing Spline Approximation.
Go::SplineSurface * projectSolutionLeastSquare (const IntegrandBase &) const
Projects the secondary solution using Least-Square Approximation.
bool getOrder (int &p1, int &p2) const
Returns the polynomial order in each parameter direction.
int coeffInd (size_t inod) const
Returns an index into the internal coefficient array for a node.
Static Private Member Functions
static void createMNPC (const Go::SplineSurface *srf, IntMat &MNPC)
Creates matrix of nodal point correspondance for a spline surface.
Additional Inherited Members
Public Types inherited from ASMbase
using BCVec = std::vector< BC >
Nodal boundary condition container.
Public Types inherited from ASM2D
typedef std::vector< unsigned char > CharVec
Convenience type.
Public Attributes inherited from ASMbase
size_t idx
Index of this patch in the multi-patch model.
Static Public Attributes inherited from ASMbase
static bool fixHomogeneousDirichlet = true
If true, pre-eliminate fixed DOFs.
static int dbgElm = 0
One-based element index to print debugging info for.
static double modelSize = 1.0
Characteristic model size.
Protected Types inherited from ASMbase
using XYZ = std::array< double, 3 >
Convenience type definition.
Static Protected Member Functions inherited from ASMbase
static bool deformedConfig (const Matrix &Xnod, Vectors &eVec, bool force2nd=false)
Calculates the deformed configuration for current element.
static bool collapseNodes (ASMbase &pch1, int node1, ASMbase &pch2, int node2)
Collapses the given two nodes into one.
Static Protected Member Functions inherited from ASM2D
static double getElementSize (const std::vector< Vec3 > &XC)
Returns characteristic element size based on corner coordinates.
Static Protected Attributes inherited from ASMbase
static std::map< int, int > xNode
Auxilliary node number map used when establishing Dirichlet constraints.
static int gEl = 0
Global element counter.
static int gNod = 0
Global node counter.
Detailed Description
Driver for assembly of structured 2D spline FE models.
This class contains methods common for structured 2D spline patches.
Member Function Documentation
addInterfaceElms()
bool ASMs2D::addInterfaceElms (const ASM::InterfaceChecker & iChk)
Adds interface elements with coupling to all element DOFs.
Parameters
[in] iChk Object checking if an element interface has contributions
References ASM::InterfaceChecker::hasContribution(), ASMbase::MLGE, ASMbase::MNPC, ASMbase::nel, ASMbase::shareFE, and surf.
Referenced by ASMs2DIB::generateFEMTopology().
addRigidCpl()
bool ASMs2D::addRigidCpl (int lindx, int ldim, int basis, int & gMaster, const Vec3 & Xmaster, bool extraPt) virtual
Adds MPCs representing a rigid coupling to this patch.
Parameters
[in] lindx Local index of the boundary item that should be rigid
[in] ldim Dimension of the boundary item that should be rigid
[in] basis Which basis to add rigid coupling for (mixed methods)
gMaster Global node number of the master node
[in] Xmaster Position of the master nodal point
[in] extraPt If true, the master point is not a patch node
Returns
true if a new global node was added, otherwise false
Reimplemented from ASMbase.
Reimplemented in ASMs2DC1.
References ASMbase::addRigidCpl(), IFEM::cout, ASMbase::idx, ThreadGroups::stripDir, and threadGroups.
addXElms()
bool ASMs2D::addXElms (short int dim, short int item, size_t nXn, IntVec & nodes) virtual
Adds extraordinary elements associated with a patch boundary.
Parameters
[in] dim Dimension of the boundary (should be 1)
[in] item Local index of the boundary edge
[in] nXn Number of extraordinary nodes
[out] nodes Global numbers assigned to the extraordinary nodes
Reimplemented from ASMbase.
Reimplemented in ASMs2DLag, and ASMs2DTri.
References ASMstruct::addXNodes(), ASMbase::MLGE, ASMbase::MNPC, ASMbase::myMNPC, ASMbase::nel, and surf.
assembleL2matrices()
bool ASMs2D::assembleL2matrices (SystemMatrix & A, SystemVector & B, const L2Integrand & integrand, bool continuous) const protected virtual
Assembles L2-projection matrices for the secondary solution.
Parameters
[out] A Left-hand-side matrix
[out] B Right-hand-side vectors
[in] integrand Object with problem-specific data and methods
[in] continuous If false, a discrete L2-projection is used
Reimplemented from ASMbase.
Reimplemented in ASMs2DLag.
References L2Integrand::evaluate(), ASM::GEOMETRY_BASIS, getBasis(), GaussQuadrature::getCoord(), ASMbase::getElementActivator(), SplineUtils::getGaussParameters(), ASMbase::getNoBasis(), ASMbase::getNoGaussPt(), GaussQuadrature::getWeight(), ASMbase::idx, ASM::PROJECTION_BASIS, and utl::matrixBase< T >::size().
assignNodeNumbers()
bool ASMs2D::assignNodeNumbers (BlockNodes & nodes, int basis = 0)
Assigns new global node numbers for all nodes of the patch.
Parameters
nodes Object with global nodes numbers to assign to this patch
[in] basis Which basis to assign node numbers for in mixed methods
The global node numbers generated by generateFEMTopology() are non-unique in the sense that a node that is shared by two (or more) patches along a common interface has a different number in each patch. This method therefore assigns a new global number to each node in the patch. The data provided through the nodes argument is sufficient to determine the unique global number under the assumption that they are ordered in the sequence determined by the local orientation of the patch and its edges.
References ASMs2D::BlockNodes::edges, getSize(), ASMs2D::BlockNodes::ibnod, ASMs2D::BlockNodes::inc, ASMbase::MLGN, ASMbase::myMLGN, ASMs2D::Edge::next(), ASMs2D::BlockNodes::next(), ASMs2D::BlockNodes::nnodI, nodeInd, and ASMbase::shareFE.
changeNumThreads()
void ASMs2D::changeNumThreads () protected virtual
Hook for changing number of threads.
Reimplemented from ASMbase.
References myCache.
checkRightHandSystem()
bool ASMs2D::checkRightHandSystem () virtual
Checks that the patch is modelled in a right-hand-side system.
If it isn't, the v-parameter direction is swapped.
Reimplemented from ASM2D.
References ASMbase::shareFE, surf, and swapV.
clear()
void ASMs2D::clear (bool retainGeometry = false) virtual
Clears the contents of the patch, making it empty.
Parameters
[in] retainGeometry If true, the spline geometry is not cleared. This is used to reinitialize the patch after it has been refined.
Reimplemented from ASMbase.
Reimplemented in ASMs2Dmx, ASMs2DmxLag, and ASMs2DLag.
Referenced by ASMs2Dmx::clear(), and ASMs2DLag::clear().
closeBoundaries()
void ASMs2D::closeBoundaries (int dir, int basis, int master) virtual
Makes two opposite boundary edges periodic.
Parameters
[in] dir Parameter direction defining the periodic edges
[in] basis Which basis to connect (mixed methods)
[in] master 1-based index of the first master node in this basis
Reimplemented from ASMbase.
Reimplemented in ASMs2DC1, ASMs2Dmx, and ASMs2DmxLag.
References utl::getDirs(), ASMbase::getNoFields(), getSize(), ASMbase::makePeriodic(), ThreadGroups::stripDir, and threadGroups.
Referenced by ASMs2Dmx::closeBoundaries(), and ASMs2DmxLag::closeBoundaries().
coeffInd()
int ASMs2D::coeffInd (size_t inod) const private
Returns an index into the internal coefficient array for a node.
Parameters
[in] inod 0-based node index local to current patch
References ASMbase::nnod, nodeInd, and surf.
Referenced by getCoord(), and getElementCoordinates().
collapseEdge()
bool ASMs2D::collapseEdge (int dir, int basis = 1) virtual
Collapses a degenereated edge into a single node.
Parameters
[in] dir Parameter direction defining the edge to collapse
[in] basis Which basis to collapse edge for
References ASMbase::collapseNodes(), getCoord(), getSize(), ASMbase::nnod, ThreadGroups::stripDir, swapV, and threadGroups.
Referenced by SIM2D::parseGeometryTag().
connectBasis()
bool ASMs2D::connectBasis (int edge, ASMs2D & neighbor, int nedge, bool revers, int basis = 1, int slave = 0, int master = 0, bool coordCheck = true, int thick = 1) protected
Connects all matching nodes on two adjacent boundary edges.
Parameters
[in] edge Local edge index of this patch, in range [1,4]
neighbor The neighbor patch
[in] nedge Local edge index of neighbor patch, in range [1,4]
[in] revers Indicates whether the two edges have opposite directions
[in] basis Which basis to connect the nodes for (mixed methods)
[in] slave 0-based index of the first slave node in this basis
[in] master 0-based index of the first master node in this basis
[in] coordCheck False to disable coordinate checks (periodic connections)
[in] thick Thickness of connection
References getBoundaryNodes(), and ASMbase::isShared().
Referenced by ASMs2Dmx::connectPatch(), and ASMs2DmxLag::connectPatch().
connectPatch()
bool ASMs2D::connectPatch (int edge, ASM2D & neighbor, int nedge, bool revers, int = 0, bool coordCheck = true, int thick = 1) virtual
Connects all matching nodes on two adjacent boundary edges.
Parameters
[in] edge Local edge index of this patch, in range [1,4]
neighbor The neighbor patch
[in] nedge Local edge index of neighbor patch, in range [1,4]
[in] revers Indicates whether the two edges have opposite directions
[in] coordCheck False to disable coordinate checks (periodic connections)
[in] thick Thickness of connection
Implements ASM2D.
Reimplemented in ASMs2Dmx, and ASMs2DmxLag.
Referenced by SIM2D::parse().
constrainCorner()
void ASMs2D::constrainCorner (int I, int J, int dof, int code = 0, char basis = 1) virtual
Constrains a corner node identified by the two parameter indices.
Parameters
[in] I Parameter index in u-direction
[in] J Parameter index in v-direction
[in] dof Which DOFs to constrain at the node
[in] code Inhomogeneous dirichlet condition code
[in] basis Which basis to constrain node for
The sign of the two indices is used to define whether we want the node at the beginning or the end of that parameter direction. The magnitude of the indices are not used.
Implements ASM2D.
Reimplemented in ASMs2DC1.
References getCorner(), getSize(), and ASMbase::prescribe().
constrainEdge()
void ASMs2D::constrainEdge (int dir, bool open, int dof, int code, char basis) virtual
Constrains all DOFs on a given boundary edge.
Parameters
[in] dir Parameter direction defining the edge to constrain
[in] open If true, exclude the end points of the edge
[in] dof Which DOFs to constrain at each node along the edge
[in] code Inhomogeneous dirichlet condition code
[in] basis Which basis to constrain edge for
A negative code value implies direct evaluation of the Dirichlet condition function at the control point. Positive code implies projection onto the spline basis representing the boundary curve (needed for curved edges and/or non-constant functions).
Implements ASM2D.
Reimplemented in ASMs2DLag, and ASMs2DC1.
References dirich, getBoundary(), getSize(), ASMbase::prescribe(), and swapV.
Referenced by ASMs2DLag::constrainEdge().
constrainEdgeLocal()
size_t ASMs2D::constrainEdgeLocal (int dir, bool open, int dof, int code, bool project = false) virtual
Constrains all DOFs in local directions on a given boundary edge.
Parameters
[in] dir Parameter direction defining the edge to constrain
[in] open If true, exclude the end points of the edge
[in] dof Which local DOFs to constrain at each node on the edge
[in] code Inhomogeneous dirichlet condition code
[in] project If true, the local axis directions are projected
Returns
Number of additional nodes added due to local axis constraints
The local coordinate systems in which the constraints are applied, are constructed from the tangent direction of the edge curve, evaluated at the Greville points (giving the local Y-direction). The local X-direction is then the outward-directed normal, defined from the cross product between the surface normal vector and the edge tangent. If project is true, the tangent- and normal direction vectors are projected onto the curve basis of the edge in order to obtain corresponding control point values. Otherwise, they are used directly.
A negative code value implies direct evaluation of the Dirichlet condition function at the control point. Positive code implies projection onto the spline basis representing the boundary curve (needed for curved edges and/or non-constant functions).
Implements ASM2D.
References MPC::addMaster(), ASMbase::addMPC(), Vec3::cross(), dirich, getBoundary(), getGrevilleParameters(), getSize(), ASMbase::gNod, ASMbase::isFixed(), ASMbase::MLGN, ASMbase::myMLGN, ASMbase::nf, Vec3::normalize(), ASMbase::nsd, nxMap, ASMbase::prescribe(), ASMbase::shareFE, surf, swapV, SplineUtils::toVec3(), Vec3::x, xnMap, ASMbase::xNode, Vec3::y, and Vec3::z.
constrainNode()
void ASMs2D::constrainNode (double xi, double eta, int dof, int code = 0) virtual
Constrains a node identified by two relative parameter values.
Parameters
[in] xi Parameter in u-direction
[in] eta Parameter in v-direction
[in] dof Which DOFs to constrain at the node
[in] code Inhomogeneous dirichlet condition code
The parameter values have to be in the domain [0.0,1.0], where 0.0 means the beginning of the domain and 1.0 means the end. For values in between, the actual index is taken as the integer value closest to r*n, where r denotes the given relative parameter value, and n is the number of nodes along that parameter direction.
Implements ASM2D.
Reimplemented in ASMs2DC1.
References getSize(), ASMbase::prescribe(), and swapV.
copyParameterDomain()
void ASMs2D::copyParameterDomain (const ASMbase * other) virtual
Copies the parameter domain from the other patch.
Reimplemented from ASMbase.
References getBasis().
createProjectionBasis()
bool ASMs2D::createProjectionBasis (bool init) virtual
Creates a separate projection basis for this patch.
This method is supposed to be invoked twice during the model generation. In the first call, with init = true, the spline surface object *surf is cloned into *proj and the two pointers are then swapped, such that the subsequent refine and raiseOrder operations will apply to the projection basis and not on the geometry basis. In the second call, the pointers are swapped back.
The method can also be invoked twice with init = false in case the projection basis is to be read from a file.
Reimplemented from ASMbase.
References ASMstruct::projB, and surf.
evalPoint()
int ASMs2D::evalPoint (const double * xi, double * param, Vec3 & X) const virtual
Evaluates the geometry at a specified point.
Parameters
[in] xi Dimensionless parameters in range [0.0,1.0] of the point
[out] param The (u,v) parameters of the point in knot-span domain
[out] X The Cartesian coordinates of the point
Returns
Local node number within the patch that matches the point, if any
0 if no node (control point) matches this point
Implements ASMbase.
Reimplemented in ASMs2DLag, and ASMs2Dmx.
References ASM::GEOMETRY_BASIS, getBasis(), SplineUtils::point(), ASMbase::searchCtrlPt(), and surf.
evalProjSolution()
bool ASMs2D::evalProjSolution (Matrix & sField, const Vector & locSol, const int * npe, int n_f) const virtual
Evaluates the projected solution field at all visualization points.
Parameters
[out] sField Solution field
[in] locSol Solution vector local to current patch
[in] npe Number of visualization nodes over each knot span
[in] n_f If nonzero, mixed evaluates n_f fields on first basis
Reimplemented from ASMbase.
References evalSolution(), utl::matrix< T >::fillColumn(), getGridParameters(), Fields::getNoFields(), getProjectedFields(), utl::matrix< T >::resize(), separateProjectionBasis(), and Fields::valueFE().
evalSolution() [1/5]
Go::GeomObject * ASMs2D::evalSolution (const IntegrandBase & integrand) const virtual
Projects the secondary solution field onto the primary basis.
Parameters
[in] integrand Object with problem-specific data and methods
Implements ASMstruct.
Reimplemented in ASMs2DLag, ASMs2Dmx, ASMs2DmxLag, ASMs2DSpec, and ASMs2DTri.
References projectSolution().
evalSolution() [2/5]
bool ASMs2D::evalSolution (Matrix & sField, const IntegrandBase & integrand, const int * npe = nullptr, char project = 0) const virtual
Evaluates the secondary solution field at all visualization points.
Parameters
[out] sField Solution field
[in] integrand Object with problem-specific data and methods
[in] npe Number of visualization nodes over each knot span
[in] project Flag indicating result recovery method (0=none, 'D'=direct evaluation, 'S'=superconvergent recovery)
The secondary solution is derived from the primary solution, which is assumed to be stored within the integrand for current patch. If npe is null, the solution is recovered or evaluated at the Greville points and then projected onto the spline basis to obtain the control point values, which then are returned through sField. If npe is not null and project is defined, the solution is also projected onto the spline basis, and then evaluated at the npe points.
Reimplemented from ASMbase.
Reimplemented in ASMs2DLag, ASMs2DmxLag, ASMs2DSpec, ASMs2DTri, ASMs2DmxLag, ASMs2DTri, ASMs2DLag, ASMs2Dmx, ASMs2DmxLag, ASMs2DSpec, and ASMs2DTri.
References evalSolution(), utl::matrix< T >::fill(), getGridParameters(), projectSolution(), projectSolutionLeastSquare(), projectSolutionLocal(), projectSolutionLocalApprox(), utl::matrix< T >::resize(), and scRecovery().
evalSolution() [3/5]
bool ASMs2D::evalSolution (Matrix & sField, const IntegrandBase & integrand, const RealArray * gpar, bool regular = true) const virtual
Evaluates the secondary solution field at the given points.
Parameters
[out] sField Solution field
[in] integrand Object with problem-specific data and methods
[in] gpar Parameter values of the result sampling points
[in] regular Flag indicating how the sampling points are defined
The secondary solution is derived from the primary solution, which is assumed to be stored within the integrand for current patch. When regular is true, it is assumed that the parameter value array gpar forms a regular tensor-product point grid of dimension gpar[0].size() X gpar[1].size(). Otherwise, we assume that it contains the u and v parameters directly for each sampling point.
Reimplemented from ASMbase.
Reimplemented in ASMs2DTri, ASMs2DSpec, ASMs2DLag, ASMs2Dmx, ASMs2DmxLag, ASMs2DSpec, ASMs2DTri, ASMs2DLag, ASMs2Dmx, ASMs2DmxLag, ASMs2DSpec, ASMs2DTri, and ASMs2DmxLag.
References FiniteElement::age, Vec4::assign(), FiniteElement::d2NdX2, FiniteElement::d3NdX3, ASMbase::deformedConfig(), FiniteElement::detJxW, FiniteElement::dNdX, utl::matrixBase< T >::empty(), IntegrandBase::evalSol(), SplineUtils::extractBasis(), utl::matrix< T >::fillColumn(), findElementContaining(), ASMbase::firstIp, FiniteElement::G, utl::gather(), Integrand::getIntegrandType(), getNodalCoordinates(), IntegrandBase::getTimeLevel(), FiniteElement::H, utl::Hessian(), utl::Hessian2(), ItgPoint::iGP, utl::Jacobian(), FiniteElement::N, ASMbase::nsd, FiniteElement::p, PROFILE2, FiniteElement::q, utl::matrix< T >::resize(), scatterInd(), Integrand::SECOND_DERIVATIVES, utl::vector< T >::size(), surf, Vec4::t, Integrand::THIRD_DERIVATIVES, ItgPoint::u, Integrand::UPDATED_NODES, and ItgPoint::v.
evalSolution() [4/5]
bool ASMs2D::evalSolution (Matrix & sField, const Vector & locSol, const int * npe, int n_f, bool piola) const virtual
Evaluates the primary solution field at all visualization points.
Parameters
[out] sField Solution field
[in] locSol Solution vector in DOF-order
[in] npe Number of visualization nodes over each knot span
[in] n_f If nonzero, mixed evaluates n_f fields on first basis
[in] piola If true, use piola mapping
Reimplemented from ASMbase.
Reimplemented in ASMs2DLag, ASMs2DmxLag, ASMs2DSpec, ASMs2DTri, ASMs2DLag, ASMs2Dmx, ASMs2DmxLag, ASMs2DSpec, and ASMs2DTri.
References evalSolution(), ASMbase::evalSolutionPiola(), and getGridParameters().
Referenced by evalProjSolution(), evalSolution(), evalSolution(), evaluate(), projectSolution(), projectSolutionLeastSquare(), projectSolutionLocal(), projectSolutionLocalApprox(), and scRecovery().
evalSolution() [5/5]
bool ASMs2D::evalSolution (Matrix & sField, const Vector & locSol, const RealArray * gpar, bool regular = true, int deriv = 0, int = 0) const virtual
Evaluates the primary solution field at the given points.
Parameters
[out] sField Solution field
[in] locSol Solution vector local to current patch
[in] gpar Parameter values of the result sampling points
[in] regular Flag indicating how the sampling points are defined
[in] deriv Derivative order to return
When regular is true, it is assumed that the parameter value array gpar forms a regular tensor-product point grid of dimension gpar[0].size() X gpar[1].size(). Otherwise, we assume that it contains the u and v parameters directly for each sampling point.
Reimplemented from ASMbase.
Reimplemented in ASMs2DmxLag, ASMs2Dmx, ASMs2DLag, ASMs2DmxLag, ASMs2DSpec, ASMs2DTri, ASMs2DLag, ASMs2Dmx, ASMs2DmxLag, ASMs2DSpec, and ASMs2DTri.
References SplineUtils::extractBasis(), utl::matrix< T >::fillColumn(), utl::gather(), getNodalCoordinates(), utl::Hessian(), utl::Jacobian(), utl::matrix< T >::multiply(), utl::matrix3d< T >::multiply(), ASMbase::nsd, PROFILE2, utl::matrix< T >::resize(), scatterInd(), utl::vector< T >::size(), and surf.
evaluate() [1/3]
bool ASMs2D::evaluate (const ASMbase * basis, const Vector & locVec, RealArray & vec, int basisNum) const virtual
Evaluates and interpolates a field over a given geometry.
Parameters
[in] basis The basis of the field to evaluate
[in] locVec The coefficients of the field to evaluate
[out] vec The obtained coefficients after interpolation
[in] basisNum Basis number (mixed)
Reimplemented from ASMbase.
Reimplemented in ASMs2DLag.
References evalSolution(), getBasis(), getGrevilleParameters(), utl::matrix< T >::rows(), and surf.
evaluate() [2/3]
bool ASMs2D::evaluate (const Field * field, RealArray & vec, int basisNum) const virtual
Evaluates and interpolates a field over a given geometry.
Parameters
[in] field The field to evaluate
[out] vec The obtained coefficients after interpolation
[in] basisNum Basis number (mixed)
Note
A Variation Diminishing Spline Approximation is used here as the regular interpolation method in GoTools only works with uniform knots.
Reimplemented from ASMbase.
References getBasis(), getGrevilleParameters(), utl::vector< T >::push_back(), utl::vector< T >::reserve(), and Field::valueFE().
evaluate() [3/3]
bool ASMs2D::evaluate (const FunctionBase * func, RealArray & vec, int basisNum, double time) const virtual
Evaluates and interpolates a function over a given geometry.
Parameters
[in] func The function to evaluate
[out] vec The obtained coefficients after interpolation
[in] basisNum Basis number (mixed)
[in] time Current time
Reimplemented from ASMbase.
References FunctionBase::dim(), getBasis(), and SplineUtils::project().
evaluateBasis()
void ASMs2D::evaluateBasis (double u, double v, double , Vector & N) const virtual
Evaluates the basis functions at the specified point.
Parameters
[in] u First parameter value of evaluation point
[in] v Second parameter value of evaluation point
[out] N Basis function values
Implements ASMstruct.
References surf.
extractBasis() [1/3]
void ASMs2D::extractBasis (double u, double v, int dir, int p, Vector & dN, bool fromRight = true) const
Establishes a vector with basis function derivatives.
Parameters
[in] u First parameter value of current integration point
[in] v Second parameter value of current integration point
[in] dir Which parameter to establish derivatives with respect to
[in] p The derivation order
[out] dN Basis function derivatives
[in] fromRight If true, evaluate from right if at a knot
References utl::vector< T >::resize(), and surf.
extractBasis() [2/3]
void ASMs2D::extractBasis (double u, double v, Vector & N, Matrix & dNdu, bool fromRight = true) const
Establishes matrices with basis functions and 1st derivatives.
Parameters
[in] u First parameter value of current integration point
[in] v Second parameter value of current integration point
[out] N Basis function values
[out] dNdu First derivatives of basis functions
[in] fromRight If true, evaluate from right if at a knot
References SplineUtils::extractBasis(), and surf.
Referenced by integrate().
extractBasis() [3/3]
void ASMs2D::extractBasis (double u, double v, Vector & N, Matrix & dNdu, Matrix3D & d2Ndu2, bool fromRight = true) const
Establishes matrices with basis functions, 1st and 2nd derivatives.
Parameters
[in] u First parameter value of current integration point
[in] v Second parameter value of current integration point
[out] N Basis function values
[out] dNdu First derivatives of basis functions
[out] d2Ndu2 Second derivatives of basis functions
[in] fromRight If true, evaluate from right if at a knot
References SplineUtils::extractBasis(), and surf.
findBoundaryElms()
void ASMs2D::findBoundaryElms (IntVec & elms, int lIndex, int = 0) const protected virtual
Finds the patch-local element numbers on a patch boundary.
Parameters
[out] elms Array of element numbers
[in] lIndex Local index of the boundary edge
Implements ASMbase.
Reimplemented in ASMs2DLag.
References surf.
findElementContaining()
int ASMs2D::findElementContaining (const double * param) const virtual
Returns the element that contains a specified spatial point.
Parameters
[in] param The parameters of the point in the knot-span domain
Returns
Local element number within the patch that contains the point
Implements ASMbase.
References surf.
Referenced by evalSolution().
findPoint()
double ASMs2D::findPoint (Vec3 & X, double * param) const virtual
Searches for the specified Cartesian point in the patch.
Parameters
X The Cartesian coordinates of the point, updated on output
[out] param The parameters of the point in the knot-span domain
Returns
Distance from the point X to the found point
Implements ASMbase.
References surf, Vec3::x, Vec3::y, and Vec3::z.
generateFEMTopology()
bool ASMs2D::generateFEMTopology () virtual
Generates the finite element topology data for the patch.
The data generated are the element-to-node connectivity array, the node-to-IJ-index array, as well as global node and element numbers.
Implements ASMbase.
Reimplemented in ASMs2DC1, ASMs2DIB, ASMs2DLag, ASMs2Dmx, ASMs2DmxLag, ASMs2DTri, and ASMu2DLag.
References ASMbase::gNod, ASMbase::MLGN, ASMbase::myMLGN, ASMbase::nel, ASMbase::nnod, nodeInd, ASMstruct::projB, ASMbase::shareFE, and surf.
Referenced by ASMs2DC1::generateFEMTopology(), and ASMs2DIB::generateFEMTopology().
generateProjThreadGroupsFromElms()
void ASMs2D::generateProjThreadGroupsFromElms (const IntVec & elms) protected virtual
Generate element groups from a partition.
Reimplemented from ASMbase.
References ThreadGroups::filter(), and ASMstruct::projThreadGroups.
generateThreadGroups() [1/4]
virtual void ASMbase::generateThreadGroups (char , bool , bool) inline protected virtual
Generates element groups for multi-threading of boundary integrals.
Reimplemented from ASMbase.
Reimplemented in ASMs2DLag, ASMs2Dmx, ASMs2DTri, and ASMu2DLag.
generateThreadGroups() [2/4]
virtual void ASMbase::generateThreadGroups (const Integrand & , bool , bool) inline protected virtual
Generates element groups for multi-threading of interior integrals.
Reimplemented from ASMbase.
Reimplemented in ASMu2DLag, ASMs2DLag, ASMs2DLag, ASMs2Dmx, ASMs2DTri, ASMs2DTri, ASMs2DTri, ASMu2DLag, ASMu2DLag, ASMs2DLag, ASMs2Dmx, ASMs2Dmx, ASMs2DTri, and ASMu2DLag.
generateThreadGroups() [3/4]
void ASMs2D::generateThreadGroups (const Integrand & integrand, bool silence, bool ignoreGlobalLM) protected virtual
Generates element groups for multi-threading of interior integrals.
Parameters
[in] integrand Object with problem-specific data and methods
[in] silence If true, suppress threading group outprint
[in] ignoreGlobalLM Sanity check option
Reimplemented from ASMbase.
Reimplemented in ASMu2DLag, ASMs2DLag, ASMs2DLag, ASMs2Dmx, ASMs2DTri, ASMs2DTri, ASMs2DTri, ASMu2DLag, ASMu2DLag, ASMs2DLag, ASMs2Dmx, ASMs2Dmx, ASMs2DTri, and ASMu2DLag.
References generateThreadGroups(), getBasis(), ASMbase::nel, ThreadGroups::oneGroup(), ASMstruct::proj2ThreadGroups, ASM::PROJECTION_BASIS_2, ASMstruct::projThreadGroups, ThreadGroups::stripDir, surf, and threadGroups.
Referenced by generateThreadGroups(), and ASMs2Dmx::generateThreadGroups().
generateThreadGroups() [4/4]
void ASMs2D::generateThreadGroups (size_t strip1, size_t strip2, bool silence, bool ignoreGlobalLM) protected
Generates element groups for multi-threading of interior integrals.
Parameters
[in] strip1 Strip width in first direction
[in] strip2 Strip width in second direction
[in] silence If true, suppress threading group outprint
[in] ignoreGlobalLM Sanity check option
Lamba for setting up thread groups for basis.
References ThreadGroups::calcGroups(), ASMstruct::checkThreadGroups(), IFEM::cout, getBasis(), ASMbase::MLGE, ASMbase::MNPC, ASMstruct::proj2ThreadGroups, ASM::PROJECTION_BASIS, ASM::PROJECTION_BASIS_2, ASMstruct::projThreadGroups, separateProjectionBasis(), ThreadGroups::size(), surf, and threadGroups.
generateThreadGroupsFromElms()
void ASMs2D::generateThreadGroupsFromElms (const IntVec & elms) protected virtual
Generates element groups from a partition.
Reimplemented from ASMbase.
References ThreadGroups::filter(), ASMbase::getElmIndex(), ASMbase::myElms, and threadGroups.
getBasis() [1/2]
Go::SplineSurface * ASMs2D::getBasis (int basis = 1) virtual
Returns the spline surface representing a basis of this patch.
Reimplemented in ASMs2Dmx.
Referenced by assembleL2matrices(), ASMs2DLag::assembleL2matrices(), copyParameterDomain(), evalPoint(), evaluate(), evaluate(), evaluate(), generateThreadGroups(), generateThreadGroups(), ASMs2Dmx::getBasis(), getElementCoordinates(), getElementCoordinatesPrm(), getElmConnectivities(), getElmNodes(), ASMs2DLag::getElmNodes(), getGrevilleParameters(), getNodalCoordinates(), projectSolution(), and write().
getBasis() [2/2]
const Go::SplineSurface * ASMs2D::getBasis (int basis = 1) const virtual
Returns the spline surface representing a basis of this patch.
Reimplemented in ASMs2Dmx.
References ASMstruct::geomB, ASM::GEOMETRY_BASIS, ASMstruct::projB, ASMstruct::projB2, ASM::PROJECTION_BASIS, ASM::PROJECTION_BASIS_2, ASM::REFINEMENT_BASIS, and surf.
getBoundary()
Go::SplineCurve * ASMs2D::getBoundary (int dir, int = 1) virtual
Returns the spline curve representing a boundary of this patch.
Parameters
[in] dir Parameter direction defining which boundary to return
Reimplemented in ASMs2Dmx.
References bou, and surf.
Referenced by constrainEdge(), and constrainEdgeLocal().
getBoundaryNodes()
void ASMs2D::getBoundaryNodes (int lIndex, IntVec & nodes, int basis, int thick = 1, int = 0, bool local = false) const virtual
Finds the global (or patch-local) node numbers on a patch boundary.
Parameters
[in] lIndex Local index of the boundary edge
nodes Array of node numbers
[in] basis Which basis to grab nodes for (for mixed methods)
[in] thick Thickness of connection
[in] local If true, return patch-local node numbers
Implements ASMbase.
Reimplemented in ASMs2Dmx, and ASMu2DLag.
References getNodeID(), getSize(), and ASMbase::idx.
Referenced by ASMs2DC1::addRigidCpl(), connectBasis(), and ASMs2Dmx::getBoundaryNodes().
getCoord()
Vec3 ASMs2D::getCoord (size_t inod) const virtual
Returns the global coordinates for the given node.
Parameters
[in] inod 1-based node index local to current patch
Implements ASMbase.
Reimplemented in ASMs2DLag, and ASMs2Dmx.
References coeffInd(), ASMbase::MLGN, ASMbase::myRmaster, ASMbase::nnod, ASMbase::nsd, surf, and xnMap.
Referenced by ASMs2DC1::addRigidCpl(), collapseEdge(), ASMs2DC1::initConstraints(), and ASMs2DC1::updateDirichlet().
getCorner()
int ASMs2D::getCorner (int I, int J, int basis) const virtual
Returns the node index for a given corner.
Parameters
[in] I -1 or +1 for either umin or umax corner
[in] J -1 or +1 for either vmin or vmax corner
[in] basis which basis to consider (for mixed methods)
Implements ASM2D.
References getSize(), and swapV.
Referenced by constrainCorner().
getCornerPoints()
void ASMs2D::getCornerPoints (int i1, int i2, std::vector< utl::Point > & XC) const protected
Computes the element corner coordinates and parameters.
Parameters
[in] i1 Parameter index in u-direction
[in] i2 Parameter index in v-direction
[out] XC Coordinates and parameters of the element corners
References getElementCorners().
Referenced by ASMs2DIB::generateFEMTopology().
getElementBorders() [1/2]
void ASMs2D::getElementBorders (int i1, int i2, double * u, double * v) const protected
Computes the element border parameters.
Parameters
[in] i1 Parameter index in u-direction
[in] i2 Parameter index in v-direction
[out] u Parameter values of the west-east borders
[out] v Parameter values of the south-north borders
References surf.
Referenced by getElementBorders(), getElementCorners(), integrate(), and ASMs2Dmx::integrate().
getElementBorders() [2/2]
void ASMs2D::getElementBorders (int iel, double * u) const protected virtual
Computes the element border parameters.
Parameters
[in] iel 1-based element index
[out] u Parameter values of the element borders
Implements ASMstruct.
References getElementBorders(), and surf.
getElementCenter()
Vec3 ASMs2D::getElementCenter (int iel) const virtual
Returns the coordinate of the element center.
Implements ASMbase.
Reimplemented in ASMs2DLag.
getElementCoordinates()
bool ASMs2D::getElementCoordinates (Matrix & X, int iel, bool forceItg = false) const virtual
Returns a matrix with nodal coordinates for an element.
Parameters
[out] X 3 \(\times\)n-matrix, where n is the number of nodes in one element
[in] iel 1-based element index local to current patch
[in] forceItg If true, return the integration basis coordinates otherwise the geometry basis coordinates are returned
Implements ASMbase.
Reimplemented in ASMs2DLag.
References coeffInd(), utl::matrix< T >::cols(), ASM::GEOMETRY_BASIS, getBasis(), getElementCoordinatesPrm(), getFirstItgElmNode(), ASMs2D::IJ::I, ASMs2D::IJ::J, ASMbase::MNPC, nodeInd, ASMbase::nsd, utl::matrix< T >::resize(), and surf.
Referenced by integrate(), ASMs2Dmx::integrate(), integrate(), ASMs2Dmx::integrate(), integrate(), integrate(), and ASMs2Dmx::integrate().
getElementCoordinatesPrm()
bool ASMs2D::getElementCoordinatesPrm (Matrix & X, double u, double v) const protected
Returns a matrix with nodal coordinates for element containing given parameters.
Parameters
[out] X 3 \(\times\)n-matrix, where n is the number of nodes
[in] u First parameter of point
[in] v Second parameter of point
References utl::matrix< T >::cols(), ASM::GEOMETRY_BASIS, getBasis(), ASMbase::nsd, and utl::matrix< T >::resize().
Referenced by ASMs2Dmx::evalSolutionPiola(), and getElementCoordinates().
getElementCorners()
double ASMs2D::getElementCorners (int i1, int i2, std::vector< Vec3 > & XC, RealArray * uC = nullptr) const protected
Computes the element corner coordinates.
Parameters
[in] i1 Parameter index in u-direction
[in] i2 Parameter index in v-direction
[out] XC Coordinates of the element corners
[out] uC Spline parameters of the element corners (optional)
Returns
Characteristic element size
References getElementBorders(), ASM2D::getElementSize(), ASMbase::nsd, and surf.
Referenced by getCornerPoints(), integrate(), ASMs2Dmx::integrate(), ASMs2DmxLag::integrate(), integrate(), ASMs2Dmx::integrate(), integrate(), integrate(), and ASMs2Dmx::integrate().
getElmConnectivities()
void ASMs2D::getElmConnectivities (IntMat & neigh, int basis = ASM::INTEGRATION_BASIS) const virtual
Calculates the matrix of element neighbour connectivities.
Parameters
[out] neigh List of element neighbors for each element
[in] basis Basis to obtain connectivities for
Implements ASMbase.
References getBasis(), ASMbase::idx, ASM::INTEGRATION_BASIS, and ASMbase::MLGE.
getElmNodes()
IntMat ASMs2D::getElmNodes (int basis) const virtual
Returns the matrix of nodal point correspondance for given basis.
Reimplemented from ASMbase.
Reimplemented in ASMs2DLag.
References createMNPC(), and getBasis().
getFirstItgElmNode()
virtual int ASMs2D::getFirstItgElmNode () const inline protected virtual
Returns 0-based index of first node on integration basis.
Reimplemented in ASMs2Dmx.
Referenced by getElementCoordinates().
getGaussPointParameters()
void ASMs2D::getGaussPointParameters (RealArray & uGP, int dir, int nGauss, const double * xi) const protected
Extracts parameter values of the Gauss points in one direction.
Parameters
[out] uGP Parameter values in given direction for all points
[in] dir Parameter direction (0,1)
[in] nGauss Number of Gauss points along a knot-span
[in] xi Dimensionless Gauss point coordinates [-1,1]
References SplineUtils::getGaussParameters(), ASMbase::nGauss, and surf.
getGrevilleParameters()
bool ASMs2D::getGrevilleParameters (RealArray & prm, int dir, int basisNum = 1) const protected
Calculates parameter values for the Greville points.
Parameters
[out] prm Parameter values in given direction for all points
[in] dir Parameter direction (0,1)
[in] basisNum Which basis to get Greville point parameters for
References getBasis().
Referenced by constrainEdgeLocal(), evaluate(), evaluate(), projectSolution(), projectSolutionLocalApprox(), and scRecovery().
getGridParameters()
bool ASMs2D::getGridParameters (RealArray & prm, int dir, int nSegSpan) const virtual
Calculates parameter values for visualization nodal points.
Parameters
[out] prm Parameter values in given direction for all points
[in] dir Parameter direction (0,1)
[in] nSegSpan Number of visualization segments over each knot-span
Reimplemented in ASMs2DSpec.
References surf.
Referenced by ASMs2DLag::evalPoint(), evalProjSolution(), evalSolution(), evalSolution(), ASMs2DLag::generateFEMTopology(), ASMs2DmxLag::generateFEMTopology(), ASMs2DTri::integrate(), ASMs2DLag::integrate(), ASMs2DTri::integrate(), and tesselate().
getLastItgElmNode()
int ASMs2D::getLastItgElmNode () const protected virtual
Returns 0-based index of last node on integration basis.
Reimplemented in ASMs2Dmx.
References surf.
Referenced by getParametricArea(), and getParametricLength().
getNoBoundaryElms()
size_t ASMs2D::getNoBoundaryElms (char lIndex, char ldim) const virtual
Returns the number of elements on a boundary.
Reimplemented from ASMbase.
Reimplemented in ASMs2DLag.
References surf.
getNodalCoordinates()
void ASMs2D::getNodalCoordinates (Matrix & X, bool geo = false) const virtual
Returns a matrix with all nodal coordinates within the patch.
Parameters
[out] X 3 \(\times\)n-matrix, where n is the number of nodes
[in] geo If true, coordinates for the geometry basis are returned otherwise the integration basis coordinates are returned
Implements ASMbase.
Reimplemented in ASMs2DLag.
References ASM::GEOMETRY_BASIS, getBasis(), ASMbase::nsd, utl::matrix< T >::resize(), and surf.
Referenced by ASMs2Dmx::evalSolution(), evalSolution(), and evalSolution().
getNodeID()
int ASMs2D::getNodeID (size_t inod, bool noAddedNodes = false) const virtual
Returns the global node number for the given node.
Parameters
[in] inod 1-based node index local to current patch
[in] noAddedNodes If true, use nxMap to find the real node
Reimplemented from ASMbase.
References ASMbase::MLGN, and nxMap.
Referenced by getBoundaryNodes(), and ASMu2DLag::getBoundaryNodes().
getNodeIndex()
size_t ASMs2D::getNodeIndex (int globalNum, bool noAddedNodes = false) const virtual
Returns local 1-based index of the node with given global number.
If the given node number is not present, 0 is returned.
Parameters
[in] globalNum Global node number
[in] noAddedNodes If true, use xnMap to find the real node
Reimplemented from ASMbase.
References utl::findIndex(), ASMbase::MLGN, ASMbase::nnod, and xnMap.
Referenced by ASMu2DLag::addToNodeSet(), ASMu2DLag::generateThreadGroupsMultiColored(), ASMs2DC1::initConstraints(), and ASMs2DC1::updateDirichlet().
getNoNodes()
size_t ASMs2D::getNoNodes (int basis = 0) const virtual
Returns the total number of nodes in this patch.
Reimplemented from ASMbase.
Reimplemented in ASMs2Dmx, and ASMs2DmxLag.
References ASMbase::getNoNodes(), and surf.
Referenced by ASMs2DSpec::evalSolution(), ASMs2DIB::filterResults(), ASMs2DLag::getNoProjectionNodes(), LagrangeField2D::LagrangeField2D(), LagrangeFields2D::LagrangeFields2D(), SplineField2D::SplineField2D(), and SplineFields2D::SplineFields2D().
getNoProjectionNodes()
size_t ASMs2D::getNoProjectionNodes () const virtual
Returns the number of projection nodes for this patch.
Reimplemented from ASMbase.
Reimplemented in ASMs2DLag.
References ASMstruct::projB.
Referenced by getProjectedField(), and getProjectedFields().
getNoStructElms()
bool ASMs2D::getNoStructElms (int & n1, int & n2, int & n3) const virtual
Returns the number of elements in each parameter direction.
Parameters
[out] n1 Number of nodes in first (u) direction
[out] n2 Number of nodes in second (v) direction
[out] n3 Number of nodes in third (w) direction
Implements ASMstruct.
References surf.
getOrder() [1/2]
bool ASMs2D::getOrder (int & p1, int & p2) const private
Returns the polynomial order in each parameter direction.
Parameters
[out] p1 Order in first (u) direction
[out] p2 Order in second (v) direction
References surf.
Referenced by getOrder().
getOrder() [2/2]
bool ASMs2D::getOrder (int & p1, int & p2, int & p3) const virtual
Returns the polynomial order in each parameter direction.
Parameters
[out] p1 Order in first (u) direction
[out] p2 Order in second (v) direction
[out] p3 Order in third (w) direction (always zero)
Reimplemented from ASMbase.
Reimplemented in ASMs2DLag.
References getOrder().
getParameterDomain()
bool ASMs2D::getParameterDomain (Real2DMat & u, IntVec * corners) const virtual
Returns parameter values and node numbers of the domain corners.
Parameters
[out] u Parameter values of the domain corners
[out] corners 1-based indices of the corner nodes (optional)
Implements ASMbase.
References surf.
getParametricArea()
double ASMs2D::getParametricArea (int iel) const protected
Returns the area in the parameter space for an element.
Parameters
[in] iel Element index
References ASMstruct::empty(), getLastItgElmNode(), ASMbase::MNPC, ASMbase::nnod, nodeInd, and surf.
Referenced by integrate(), ASMs2Dmx::integrate(), and integrate().
getParametricLength()
double ASMs2D::getParametricLength (int iel, int dir) const protected
Returns boundary edge length in the parameter space for an element.
Parameters
[in] iel Element index
[in] dir Local index of the boundary edge
References ASMstruct::empty(), getLastItgElmNode(), ASMbase::MNPC, ASMbase::nnod, nodeInd, and surf.
Referenced by integrate(), ASMs2Dmx::integrate(), integrate(), and ASMs2Dmx::integrate().
getProjectedField()
Field * ASMs2D::getProjectedField (const Vector & coefs) const virtual
Returns a field using the projection basis.
Parameters
[in] coefs The coefficients for the field
Reimplemented from ASMbase.
References getNoProjectionNodes(), ASMstruct::projB, and utl::vector< T >::size().
getProjectedFields()
Fields * ASMs2D::getProjectedFields (const Vector & coefs, size_t = 0) const virtual
Returns a field using the projection basis.
Parameters
[in] coefs The coefficients for the field
Reimplemented from ASMbase.
References getNoProjectionNodes(), ASMstruct::projB, and utl::vector< T >::size().
Referenced by evalProjSolution().
getQuasiInterplParameters()
bool ASMs2D::getQuasiInterplParameters (RealArray & prm, int dir) const protected
Calculates parameter values for the Quasi-Interpolation points.
Parameters
[out] prm Parameter values in given direction for all points
[in] dir Parameter direction (0,1)
References surf.
Referenced by projectSolutionLocal().
getSize() [1/2]
bool ASMs2D::getSize (int & n1, int & n2, int & n3, int basis) const virtual
Returns the number of nodal points in each parameter direction.
Parameters
[out] n1 Number of nodes in first (u) direction
[out] n2 Number of nodes in second (v) direction
[out] n3 Number of nodes in third (w) direction
[in] basis Which basis to return size parameters for (mixed methods)
Implements ASMstruct.
Reimplemented in ASMs2DLag, ASMs2Dmx, and ASMs2DmxLag.
References getSize().
getSize() [2/2]
bool ASMs2D::getSize (int & n1, int & n2, int basis = 0) const virtual
Returns the number of nodal points in each parameter direction.
Parameters
[out] n1 Number of nodes in first (u) direction
[out] n2 Number of nodes in second (v) direction
[in] basis Which basis to return size parameters for (mixed methods)
Reimplemented in ASMs2Dmx, ASMs2DmxLag, ASMs2DLag, ASMs2Dmx, ASMs2DmxLag, ASMs2DLag, and ASMs2DmxLag.
References surf.
Referenced by assignNodeNumbers(), closeBoundaries(), ASMs2DC1::closeBoundaries(), collapseEdge(), ASMs2DC1::connectC1(), constrainCorner(), ASMs2DC1::constrainCorner(), constrainEdge(), ASMs2DC1::constrainEdge(), constrainEdgeLocal(), constrainNode(), ASMs2DC1::constrainNode(), getBoundaryNodes(), getCorner(), getSize(), and ASMs2Dmx::getSize().
integrate() [1/4]
bool ASMs2D::integrate (Integrand & integrand, GlobalIntegral & glbInt, const TimeDomain & time) virtual
Evaluates an integral over the interior patch domain.
Parameters
integrand Object with problem-specific data and methods
glbInt The integrated quantity
[in] time Parameters for nonlinear/time-dependent simulations
Implements ASMbase.
Reimplemented in ASMs2DIB, ASMs2DIB, ASMs2DLag, ASMs2Dmx, ASMs2DmxLag, ASMs2DSpec, ASMs2DTri, ASMu2DLag, and ASMu2DLag.
References utl::vector< T >::add(), FiniteElement::age, GlobalIntegral::assemble(), Vec4::assign(), Integrand::AVERAGE, ASM::cachePolicy, BasisFunctionCache< Dim >::clear(), BasisFunctionCache< Dim >::coord(), BasisFunctionVals::d2Ndu2, FiniteElement::d2NdX2, BasisFunctionVals::d3Ndu3, FiniteElement::d3NdX3, ASMbase::dbgElm, ASMbase::deformedConfig(), LocalIntegral::destruct(), FiniteElement::detJxW, BasisFunctionVals::dNdu, FiniteElement::dNdX, Integrand::ELEMENT_CENTER, Integrand::ELEMENT_CORNERS, ItgPoint::eta, Integrand::evalInt(), Integrand::finalizeElement(), TimeDomain::first, ASMbase::firstEl, ASMbase::firstIp, FiniteElement::G, Integrand::G_MATRIX, getElementCoordinates(), getElementCorners(), utl::getGmat(), Integrand::getIntegrandType(), Integrand::getLocalIntegral(), BasisFunctionCache< Dim >::getParam(), getParametricArea(), BasisFunctionCache< Dim >::getVals(), FiniteElement::H, FiniteElement::h, utl::Hessian(), utl::Hessian2(), ItgPoint::idx, ItgPoint::iel, ItgPoint::iGP, BasisFunctionCache< Dim >::init(), Integrand::initElement(), TimeDomain::it, utl::Jacobian(), ASMbase::MLGE, ASMbase::MNPC, myCache, ASMbase::myElms, BasisFunctionVals::N, FiniteElement::N, FiniteElement::Navg, ASMbase::nel, BasisFunctionCache< Dim >::nGauss(), ASMbase::nsd, ThreadGroups::oneStripe(), FiniteElement::p, SplineUtils::point(), ASM::PRE_CACHE, PROFILE2, PROFILE3, FiniteElement::q, Integrand::reducedInt(), LocalIntegral::ref(), utl::vector< T >::resize(), Integrand::SECOND_DERIVATIVES, BasisFunctionCache< Dim >::setIntegrand(), utl::vector< T >::size(), ThreadGroups::size(), surf, TimeDomain::t, Integrand::THIRD_DERIVATIVES, threadGroups, GlobalIntegral::threadSafe(), ItgPoint::u, Integrand::UPDATED_NODES, ItgPoint::v, LocalIntegral::vec, BasisFunctionCache< Dim >::weight(), FiniteElement::XC, and ItgPoint::xi.
Referenced by ASMs2DIB::integrate().
integrate() [2/4]
bool ASMs2D::integrate (Integrand & integrand, GlobalIntegral & glbInt, const TimeDomain & time, const ASM::InterfaceChecker & iChk) virtual
Evaluates an integral over element interfaces in the patch.
Parameters
integrand Object with problem-specific data and methods
glbInt The integrated quantity
[in] time Parameters for nonlinear/time-dependent simulations
[in] iChk Object checking if an element interface has contributions
Reimplemented from ASMbase.
Reimplemented in ASMs2DIB, and ASMs2Dmx.
References FiniteElement::age, GlobalIntegral::assemble(), Vec4::assign(), LocalIntegral::destruct(), FiniteElement::detJxW, FiniteElement::dNdX, Integrand::ELEMENT_CORNERS, ASM::InterfaceChecker::elmBorderMask(), ItgPoint::eta, Integrand::evalInt(), extractBasis(), ASMbase::firstEl, utl::matrix< T >::getColumn(), GaussQuadrature::getCoord(), getElementBorders(), getElementCoordinates(), getElementCorners(), Integrand::getIntegrandType(), Integrand::getLocalIntegral(), ASMbase::getNoGaussPt(), getParametricLength(), GaussQuadrature::getWeight(), FiniteElement::h, ASM::InterfaceChecker::hasContribution(), ItgPoint::idx, ItgPoint::iel, Integrand::initElement(), Integrand::INTERFACE_TERMS, utl::Jacobian(), utl::merge(), ASMbase::MLGE, ASMbase::MNPC, FiniteElement::N, ASMbase::nel, Integrand::NORMAL_DERIVS, FiniteElement::p, PROFILE2, LocalIntegral::ref(), surf, TimeDomain::t, ItgPoint::u, ItgPoint::v, FiniteElement::XC, and ItgPoint::xi.
integrate() [3/4]
bool ASMs2D::integrate (Integrand & integrand, GlobalIntegral & glbInt, const TimeDomain & time, const Real3DMat & itgPts) protected
Evaluates an integral over the interior patch domain.
Parameters
integrand Object with problem-specific data and methods
glbInt The integrated quantity
[in] time Parameters for nonlinear/time-dependent simulations
[in] itgPts Parameters and weights of the integration points
References FiniteElement::age, GlobalIntegral::assemble(), Vec4::assign(), FiniteElement::d2NdX2, ASMbase::dbgElm, ASMbase::deformedConfig(), LocalIntegral::destruct(), FiniteElement::detJxW, FiniteElement::dNdX, Integrand::ELEMENT_CENTER, Integrand::ELEMENT_CORNERS, ASMstruct::empty(), Integrand::evalInt(), SplineUtils::extractBasis(), Integrand::finalizeElement(), TimeDomain::first, ASMbase::firstEl, ASMbase::firstIp, FiniteElement::G, Integrand::G_MATRIX, getElementCoordinates(), getElementCorners(), utl::getGmat(), Integrand::getIntegrandType(), Integrand::getLocalIntegral(), getParametricArea(), Integrand::getReducedIntegration(), FiniteElement::H, FiniteElement::h, utl::Hessian(), ItgPoint::idx, ItgPoint::iel, ItgPoint::iGP, Integrand::initElement(), TimeDomain::it, utl::Jacobian(), ASMbase::MLGE, ASMbase::MNPC, ASMbase::myElms, FiniteElement::N, ASMbase::nel, ASMbase::nsd, ThreadGroups::oneStripe(), FiniteElement::p, PROFILE2, PROFILE3, FiniteElement::q, LocalIntegral::ref(), Integrand::SECOND_DERIVATIVES, utl::vector< T >::size(), ThreadGroups::size(), surf, TimeDomain::t, threadGroups, GlobalIntegral::threadSafe(), ItgPoint::u, Vec4::u, Integrand::UPDATED_NODES, ItgPoint::v, LocalIntegral::vec, and FiniteElement::XC.
integrate() [4/4]
bool ASMs2D::integrate (Integrand & integrand, int lIndex, GlobalIntegral & glbInt, const TimeDomain & time) virtual
Evaluates a boundary integral over a patch edge.
Parameters
integrand Object with problem-specific data and methods
[in] lIndex Local index [1,4] of the boundary edge
glbInt The integrated quantity
[in] time Parameters for nonlinear/time-dependent simulations
Implements ASMbase.
Reimplemented in ASMs2DIB, ASMs2DLag, ASMs2Dmx, ASMs2DmxLag, ASMs2DSpec, ASMs2DTri, and ASMu2DLag.
References FiniteElement::age, GlobalIntegral::assemble(), Vec4::assign(), ASMbase::dbgElm, LocalIntegral::destruct(), FiniteElement::detJxW, FiniteElement::dNdX, Integrand::ELEMENT_CORNERS, ItgPoint::eta, Integrand::evalBou(), SplineUtils::extractBasis(), Integrand::finalizeElementBou(), ASMbase::firstBp, ASMbase::firstEl, FiniteElement::G, Integrand::G_MATRIX, Integrand::getBouIntegrationPoints(), GaussQuadrature::getCoord(), getElementCoordinates(), getElementCorners(), SplineUtils::getGaussParameters(), utl::getGmat(), Integrand::getIntegrandType(), Integrand::getLocalIntegral(), ASMbase::getNoGaussPt(), getParametricLength(), GaussQuadrature::getWeight(), FiniteElement::h, ItgPoint::idx, ItgPoint::iel, ItgPoint::iGP, Integrand::initElementBou(), ASMbase::isElementInPartition(), utl::Jacobian(), ASMbase::MLGE, ASMbase::MNPC, ASMbase::myElms, FiniteElement::N, ASMbase::nsd, FiniteElement::p, PROFILE2, FiniteElement::q, LocalIntegral::ref(), Integrand::setNeumannOrder(), utl::vector< T >::size(), surf, TimeDomain::t, ItgPoint::u, ItgPoint::v, FiniteElement::XC, ItgPoint::xi, and Integrand::XO_ELEMENTS.
projectSolution()
Go::SplineSurface * ASMs2D::projectSolution (const IntegrandBase & integrand) const private
Projects the secondary solution field onto the primary basis.
Parameters
[in] integrand Object with problem-specific data and methods
References evalSolution(), getBasis(), getGrevilleParameters(), PROFILE2, and utl::matrix< T >::rows().
Referenced by evalSolution(), and evalSolution().
raiseOrder()
bool ASMs2D::raiseOrder (int ru, int rv) virtual
Raises the order of the SplineSurface object for this patch.
Parameters
[in] ru Number of times to raise the order in u-direction
[in] rv Number of times to raise the order in v-direction
Implements ASM2D.
References ASMbase::shareFE, and surf.
read()
bool ASMs2D::read (std::istream & is) virtual
Creates an instance by reading the given input stream.
Implements ASMbase.
Reimplemented in ASMu2DLag.
References IFEM::cout, ASMstruct::geomB, ASMbase::nsd, ASMbase::shareFE, and surf.
refine()
bool ASMs2D::refine (int dir, const RealArray & xi, double scale = 1.0) virtual
Refines the parametrization by inserting extra knots.
Parameters
[in] dir Parameter direction to refine
[in] xi Relative positions of added knots in each existing knot span
[in] scale Scaling factor for the added knot values
References ASMbase::shareFE, and surf.
selfInterconnect()
bool ASMs2D::selfInterconnect (const std::vector< Ipair > & nodes, double xtol) virtual
Connects a list of node pairs to each other.
Parameters
[in] nodes List of node number pairs that should share common DOFs.
[in] xtol Coordinate tolerance for matching nodes
Reimplemented from ASMbase.
References IFEM::cout, ASMbase::idx, ASMbase::selfInterconnect(), ThreadGroups::stripDir, and threadGroups.
separateProjectionBasis()
bool ASMs2D::separateProjectionBasis () const virtual
Checks if a separate projection basis is used for this patch.
Reimplemented from ASMstruct.
Reimplemented in ASMs2Dmx.
References ASMstruct::projB, and surf.
Referenced by evalProjSolution(), and generateThreadGroups().
setNodeNumbers()
void ASMs2D::setNodeNumbers (const IntVec & nodes) virtual
Sets the global node numbers for this patch.
Parameters
[in] nodes Vector of global node numbers (zero-based)
Reimplemented from ASMbase.
References ASMbase::myMLGN, ASMbase::setNodeNumbers(), surf, and swapV.
tesselate()
bool ASMs2D::tesselate (ElementBlock & grid, const int * npe) const virtual
Creates a quad element model of this patch for visualization.
Parameters
[out] grid The generated quadrilateral grid
[in] npe Number of visualization nodes over each knot span
Note
The number of element nodes must be set in grid on input.
Implements ASMbase.
Reimplemented in ASMs2DLag, ASMs2DTri, and ASMu2DLag.
References getGridParameters(), ElementBlock::getNoNodes(), ASMbase::nsd, ElementBlock::resize(), ElementBlock::setCoor(), ElementBlock::setElmId(), ElementBlock::setNode(), ElementBlock::setParams(), and surf.
Referenced by ASMs2DLag::tesselate().
uniformRefine()
bool ASMs2D::uniformRefine (int dir, int nInsert) virtual
Refines the parametrization by inserting extra knots uniformly.
Parameters
[in] dir Parameter direction to refine
[in] nInsert Number of extra knots to insert in each knot-span
Implements ASM2D.
updateCoords()
bool ASMs2D::updateCoords (const Vector & displ) virtual
Updates the nodal coordinates for this patch.
Parameters
[in] displ Incremental displacements to update the coordinates with
Implements ASMbase.
Reimplemented in ASMs2DLag.
References ASMbase::MLGN, ASMbase::nsd, ASMbase::shareFE, utl::vector< T >::size(), and surf.
updateDirichlet()
bool ASMs2D::updateDirichlet (const std::map< int, RealFunc * > & func, const std::map< int, VecFunc * > & vfunc, double time, const std::map< int, int > * g2l, bool tangent) virtual
Updates the time-dependent in-homogeneous Dirichlet coefficients.
Parameters
[in] func Scalar property fields
[in] vfunc Vector property fields
[in] time Current time
[in] g2l Pointer to global-to-local node number mapping
[in] tangent If true, use time-derivatives of prescribed values
This method projects the function describing the in-homogeneous Dirichlet boundary condition onto the spline basis defining the boundary curve, in order to find the control point values which are used as the prescribed values of the boundary DOFs.
Reimplemented from ASMbase.
Reimplemented in ASMs2DC1.
References dirich, ASMbase::MLGN, ASMbase::mpcs, SplineUtils::project(), and ASMbase::updateDirichlet().
Referenced by ASMs2DC1::updateDirichlet().
validateThreadGroups()
bool ASMs2D::validateThreadGroups (const SAM * sam) const protected virtual
Validates the threading groups based on the assembly data in SAM.
Reimplemented from ASMbase.
References DiagMatrix::assembleStruct(), IFEM::cout, DiagMatrix::dim(), SAM::getElmEqns(), SAM::getNodeAndLocalDof(), SAM::getNoEquations(), ASMbase::MLGE, ThreadGroups::size(), and threadGroups.
write()
bool ASMs2D::write (std::ostream & os, int basis) const virtual
Writes the geometry of the SplineSurface object to given stream.
Implements ASMbase.
Reimplemented in ASMs2DLag, and ASMs2DTri.
References getBasis(), ASMbase::getNoBasis(), and surf.
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/ASM/ASMs2D.h
/home/runner/work/IFEM-2/IFEM-2/src/ASM/ASMs2D.C
/home/runner/work/IFEM-2/IFEM-2/src/ASM/ASMs2Drecovery.C