IFEM: CompatibleOperators::Weak Class Reference
CompatibleOperators::Weak Class Reference
Common weak operators using div-compatible discretizations.
#include <CompatibleOperators.h>
Static Public Member Functions
static void Advection (std::vector< Matrix > &EM, const FiniteElement &fe, const Vec3 &AC, const std::array< std::array< int, 3 >, 3 > &idx, double scale=1.0, WeakOperators::ConvectionForm cnvForm=WeakOperators::CONVECTIVE)
Compute an advection term.
static void Convection (std::vector< Matrix > &EM, const FiniteElement &fe, const Vec3 &U, const Tensor &dUdX, const std::array< std::array< int, 3 >, 3 > &idx, double scale, WeakOperators::ConvectionForm form=WeakOperators::CONVECTIVE)
Compute a (nonlinear) convection term.
static void Gradient (std::vector< Matrix > &EM, const FiniteElement &fe, const std::array< int, 3 > &idx, double scale=1.0)
Compute a gradient term.
static void ItgConstraint (std::vector< Matrix > &EM, const FiniteElement &fe, const std::array< int, 3 > &idx)
Compute an integration constraint.
static void Laplacian (std::vector< Matrix > &EM, const FiniteElement &fe, const std::array< std::array< int, 3 >, 3 > &idx, double scale=1.0, bool stress=false)
Compute a laplacian.
static void Mass (std::vector< Matrix > &EM, const FiniteElement &fe, const std::array< std::array< int, 3 >, 3 > &idx, double scale=1.0)
Compute a mass term.
static void Source (Vectors &EV, const FiniteElement &fe, const std::array< int, 3 > &idx, double scale=1.0)
Compute a scalar source term.
static void Source (Vectors &EV, const FiniteElement &fe, const Vec3 &f, const std::array< int, 3 > &idx, double scale=1.0)
Compute a vector-source term.
Detailed Description
Common weak operators using div-compatible discretizations.
Member Function Documentation
Advection()
void CompatibleOperators::Weak::Advection (std::vector< Matrix > & EM, const FiniteElement & fe, const Vec3 & AC, const std::array< std::array< int, 3 >, 3 > & idx, double scale = 1.0, WeakOperators::ConvectionForm cnvForm = WeakOperators::CONVECTIVE) static
Compute an advection term.
Parameters
[out] EM The element matrices to add contribution to
[in] fe The finite element to evaluate for
[in] AC Advecting field
[in] idx Matrix block indices
[in] scale Scaling factor for contribution
[in] cnvForm Form of advection operator
References FiniteElement::basis(), utl::matrix< T >::cols(), FiniteElement::detJxW, utl::matrix< T >::getColumn(), and FiniteElement::grad().
Convection()
void CompatibleOperators::Weak::Convection (std::vector< Matrix > & EM, const FiniteElement & fe, const Vec3 & U, const Tensor & dUdX, const std::array< std::array< int, 3 >, 3 > & idx, double scale, WeakOperators::ConvectionForm form = WeakOperators::CONVECTIVE) static
Compute a (nonlinear) convection term.
Parameters
[out] EM The element matrix to add contribution to
[in] fe The finite element to evaluate for
[in] U Advecting field
[in] dUdX Field gradient
[in] idx Matrix block indices
[in] scale Scaling factor for contribution
[in] form Which form of the convective form to use
References FiniteElement::basis(), utl::matrix< T >::cols(), FiniteElement::detJxW, utl::matrix< T >::getColumn(), and FiniteElement::grad().
Gradient()
void CompatibleOperators::Weak::Gradient (std::vector< Matrix > & EM, const FiniteElement & fe, const std::array< int, 3 > & idx, double scale = 1.0) static
Compute a gradient term.
Parameters
[out] EM The element matrix to add contribution to
[in] fe The finite element to evaluate for
[in] idx Matrix block indices
[in] scale Scaling factor for contribution
References FiniteElement::basis(), utl::matrix< T >::cols(), FiniteElement::detJxW, utl::matrix< T >::getColumn(), and FiniteElement::grad().
ItgConstraint()
void CompatibleOperators::Weak::ItgConstraint (std::vector< Matrix > & EM, const FiniteElement & fe, const std::array< int, 3 > & idx) static
Compute an integration constraint.
Parameters
[out] EM The element matrix to add contribution to
[in] idx Matrix block indices
[in] fe The finite element to evaluate for
References utl::matrix< T >::cols(), FiniteElement::grad(), and EqualOrderOperators::Weak::ItgConstraint().
Laplacian()
void CompatibleOperators::Weak::Laplacian (std::vector< Matrix > & EM, const FiniteElement & fe, const std::array< std::array< int, 3 >, 3 > & idx, double scale = 1.0, bool stress = false) static
Compute a laplacian.
Parameters
[out] EM The element matrix to add contribution to
[in] fe The finite element to evaluate for
[in] idx Matrix block indices
[in] scale Scaling factor for contribution
[in] stress Whether to add extra stress formulation terms
Only the upper blocks are added with the stress formulation
References utl::matrix< T >::cols(), FiniteElement::detJxW, utl::matrix< T >::getColumn(), FiniteElement::grad(), and EqualOrderOperators::Weak::Laplacian().
Mass()
void CompatibleOperators::Weak::Mass (std::vector< Matrix > & EM, const FiniteElement & fe, const std::array< std::array< int, 3 >, 3 > & idx, double scale = 1.0) static
Compute a mass term.
Parameters
[out] EM The element matrices to add contribution to
[in] fe The finite element to evaluate for
[in] idx Matrix block indices
[in] scale Scaling factor for contribution
References FiniteElement::grad(), and EqualOrderOperators::Weak::Mass().
Source() [1/2]
void CompatibleOperators::Weak::Source (Vectors & EV, const FiniteElement & fe, const std::array< int, 3 > & idx, double scale = 1.0) static
Compute a scalar source term.
Parameters
[out] EV The element vectors to add contribution to
[in] fe The finite element to evaluate for
idx Vector block indices
[in] scale Scaling factor for contribution
References FiniteElement::grad(), and EqualOrderOperators::Weak::Source().
Source() [2/2]
void CompatibleOperators::Weak::Source (Vectors & EV, const FiniteElement & fe, const Vec3 & f, const std::array< int, 3 > & idx, double scale = 1.0) static
Compute a vector-source term.
Parameters
[out] EV The element vectors to add contribution to
[in] fe The finite element to evaluate for
[in] f Vector with contributions
idx Vector block indices
[in] scale Scaling factor for contribution
References FiniteElement::grad(), and EqualOrderOperators::Weak::Source().
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/Apps/Utils/CompatibleOperators.h
/home/runner/work/IFEM-2/IFEM-2/Apps/Utils/CompatibleOperators.C