IFEM: ASMs2DC1 Class Reference
ASMs2DC1 Class Reference
Driver for assembly of C1-continuous structured 2D spline FE models.
#include <ASMs2DC1.h>
Public Member Functions
ASMs2DC1 (unsigned char n_s=2, unsigned char n_f=1)
Default constructor.
ASMs2DC1 (const ASMs2DC1 &patch, unsigned char n_f=0)
Copy constructor.
virtual ~ASMs2DC1 ()
Empty destructor.
virtual bool generateFEMTopology ()
Generates the finite element topology data for the patch.
virtual void constrainEdge (int dir, bool open, int dof=12, int code=0, char basis=1)
Constrains all DOFs on a given boundary edge.
virtual void constrainCorner (int I, int J, int dof=12, int code=0)
Constrains a corner node identified by the two parameter indices.
virtual void constrainNode (double xi, double eta, int dof=12, int code=0)
Constrains a node identified by two relative parameter values.
bool connectC1 (int edge, ASMs2DC1 *neighbor, int nedge, bool revers=false)
Connects all matching nodes on two adjacent boundary edges.
virtual void closeBoundaries (int dir, int, int)
Makes two opposite boundary edges periodic.
virtual bool addRigidCpl (int lindx, int ldim, int basis, int &gMaster, const Vec3 &Xmaster, bool extraPt)
Adds MPCs representing a rigid coupling to this patch.
virtual bool initConstraints ()
Initializes constraint equations enforcing C1-continuity.
virtual bool updateDirichlet (const std::map< int, RealFunc * > &func, const std::map< int, VecFunc * > &vfunc, double time, const std::map< int, int > *g2l=nullptr, bool tangent=false)
Updates the time-dependent in-homogeneous Dirichlet coefficients.
virtual void constrainCorner (int I, int J, int dof, int code=0, char basis=1)
Constrains a corner node identified by the two parameter indices.
Public Member Functions inherited from ASMs2D
ASMs2D (unsigned char n_s=2, unsigned char n_f=2)
Default constructor.
ASMs2D (const ASMs2D &patch, unsigned char n_f)
Special copy constructor for sharing of FE data.
ASMs2D (const ASMs2D &patch)
Default copy constructor copying everything.
virtual ~ASMs2D ()
The destructor frees the dynamically allocated boundary curves.
virtual Go::SplineCurve * getBoundary (int dir, int=1)
Returns the spline curve representing a boundary of this patch.
virtual Go::SplineSurface * getBasis (int basis=1)
Returns the spline surface representing a basis of this patch.
virtual const Go::SplineSurface * getBasis (int basis=1) const
Returns the spline surface representing a basis of this patch.
virtual void copyParameterDomain (const ASMbase *other)
Copies the parameter domain from the other patch.
virtual bool read (std::istream &)
Creates an instance by reading the given input stream.
virtual bool write (std::ostream &, int) const
Writes the geometry of the SplineSurface object to given stream.
virtual void clear (bool retainGeometry=false)
Clears the contents of the patch, making it empty.
virtual bool addXElms (short int dim, short int item, size_t nXn, IntVec &nodes)
Adds extraordinary elements associated with a patch boundary.
bool addInterfaceElms (const ASM::InterfaceChecker &iChk)
Adds interface elements with coupling to all element DOFs.
virtual size_t getNodeIndex (int globalNum, bool noAddedNodes=false) const
Returns local 1-based index of the node with given global number.
virtual int getNodeID (size_t inod, bool noAddedNodes=false) const
Returns the global node number for the given node.
virtual bool getElementCoordinates (Matrix &X, int iel, bool forceItg=false) const
Returns a matrix with nodal coordinates for an element.
virtual void getNodalCoordinates (Matrix &X, bool geo=false) const
Returns a matrix with all nodal coordinates within the patch.
virtual Vec3 getCoord (size_t inod) const
Returns the global coordinates for the given node.
virtual Vec3 getElementCenter (int iel) const
Returns the coordinate of the element center.
virtual bool updateCoords (const Vector &displ)
Updates the nodal coordinates for this patch.
virtual void getBoundaryNodes (int lIndex, IntVec &nodes, int basis, int thick=1, int=0, bool local=false) const
Finds the global (or patch-local) node numbers on a patch boundary.
virtual int getCorner (int I, int J, int basis) const
Returns the node index for a given corner.
bool assignNodeNumbers (BlockNodes &nodes, int basis=0)
Assigns new global node numbers for all nodes of the patch.
virtual bool checkRightHandSystem ()
Checks that the patch is modelled in a right-hand-side system.
virtual bool refine (int dir, const RealArray &xi, double scale=1.0)
Refines the parametrization by inserting extra knots.
virtual bool uniformRefine (int dir, int nInsert)
Refines the parametrization by inserting extra knots uniformly.
virtual bool raiseOrder (int ru, int rv)
Raises the order of the SplineSurface object for this patch.
virtual bool createProjectionBasis (bool init)
Creates a separate projection basis for this patch.
virtual bool separateProjectionBasis () const
Checks if a separate projection basis is used for this patch.
virtual size_t constrainEdgeLocal (int dir, bool open, int dof, int code, bool project=false)
Constrains all DOFs in local directions on a given boundary edge.
virtual bool connectPatch (int edge, ASM2D &neighbor, int nedge, bool revers, int=0, bool coordCheck=true, int thick=1)
Connects all matching nodes on two adjacent boundary edges.
virtual bool collapseEdge (int dir, int basis=1)
Collapses a degenereated edge into a single node.
virtual void setNodeNumbers (const IntVec &nodes)
Sets the global node numbers for this patch.
virtual bool selfInterconnect (const std::vector< Ipair > &nodes, double xtol)
Connects a list of node pairs to each other.
virtual bool integrate (Integrand &integrand, GlobalIntegral &glbInt, const TimeDomain &time)
Evaluates an integral over the interior patch domain.
virtual bool integrate (Integrand &integrand, int lIndex, GlobalIntegral &glbInt, const TimeDomain &time)
Evaluates a boundary integral over a patch edge.
virtual bool integrate (Integrand &integrand, GlobalIntegral &glbInt, const TimeDomain &time, const ASM::InterfaceChecker &iChk)
Evaluates an integral over element interfaces in the patch.
virtual int evalPoint (const double *xi, double *param, Vec3 &X) const
Evaluates the geometry at a specified point.
virtual int findElementContaining (const double *param) const
Returns the element that contains a specified spatial point.
virtual double findPoint (Vec3 &X, double *param) const
Searches for the specified Cartesian point in the patch.
virtual bool getGridParameters (RealArray &prm, int dir, int nSegSpan) const
Calculates parameter values for visualization nodal points.
virtual bool tesselate (ElementBlock &grid, const int *npe) const
Creates a quad element model of this patch for visualization.
virtual bool evalSolution (Matrix &sField, const Vector &locSol, const int *npe, int n_f, bool piola) const
Evaluates the primary solution field at all visualization points.
virtual bool evalSolution (Matrix &sField, const Vector &locSol, const RealArray *gpar, bool regular=true, int deriv=0, int=0) const
Evaluates the primary solution field at the given points.
virtual bool evalProjSolution (Matrix &sField, const Vector &locSol, const int *npe, int n_f) const
Evaluates the projected solution field at all visualization points.
virtual bool evaluate (const ASMbase *basis, const Vector &locVec, RealArray &vec, int basisNum) const
Evaluates and interpolates a field over a given geometry.
virtual bool evaluate (const Field *field, RealArray &vec, int basisNum) const
Evaluates and interpolates a field over a given geometry.
virtual bool evaluate (const FunctionBase *func, RealArray &vec, int basisNum, double time) const
Evaluates and interpolates a function over a given geometry.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const int *npe=nullptr, char project=0) const
Evaluates the secondary solution field at all visualization points.
virtual Go::GeomObject * evalSolution (const IntegrandBase &integrand) const
Projects the secondary solution field onto the primary basis.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const RealArray *gpar, bool regular=true) const
Evaluates the secondary solution field at the given points.
virtual bool getOrder (int &p1, int &p2, int &p3) const
Returns the polynomial order in each parameter direction.
virtual bool getSize (int &n1, int &n2, int basis=0) const
Returns the number of nodal points in each parameter direction.
virtual bool getSize (int &n1, int &n2, int &n3, int basis) const
Returns the number of nodal points in each parameter direction.
virtual bool getNoStructElms (int &n1, int &n2, int &n3) const
Returns the number of elements in each parameter direction.
virtual void getElmConnectivities (IntMat &neigh, int basis=ASM::INTEGRATION_BASIS) const
Calculates the matrix of element neighbour connectivities.
virtual IntMat getElmNodes (int basis) const
Returns the matrix of nodal point correspondance for given basis.
virtual size_t getNoBoundaryElms (char lIndex, char ldim) const
Returns the number of elements on a boundary.
virtual size_t getNoNodes (int basis=0) const
Returns the total number of nodes in this patch.
virtual size_t getNoProjectionNodes () const
Returns the number of projection nodes for this patch.
virtual bool getParameterDomain (Real2DMat &u, IntVec *corners) const
Returns parameter values and node numbers of the domain corners.
virtual void evaluateBasis (double u, double v, double, Vector &N) const
Evaluates the basis functions at the specified point.
void extractBasis (double u, double v, Vector &N, Matrix &dNdu, bool fromRight=true) const
Establishes matrices with basis functions and 1st derivatives.
void extractBasis (double u, double v, Vector &N, Matrix &dNdu, Matrix3D &d2Ndu2, bool fromRight=true) const
Establishes matrices with basis functions, 1st and 2nd derivatives.
void extractBasis (double u, double v, int dir, int p, Vector &dN, bool fromRight=true) const
Establishes a vector with basis function derivatives.
virtual Field * getProjectedField (const Vector &coefs) const
Returns a field using the projection basis.
virtual Fields * getProjectedFields (const Vector &coefs, size_t=0) const
Returns a field using the projection basis.
Public Member Functions inherited from ASMstruct
virtual ~ASMstruct ()
The destructor frees the dynamically allocated spline objects.
virtual bool empty () const
Checks if the patch is empty.
virtual bool diracPoint (Integrand &integr, GlobalIntegral &glInt, const double *u, const Vec3 &pval)
Integrates a spatial dirac-delta function over a patch.
virtual void swapProjectionBasis ()
Swaps between the first and second projection basis.
virtual bool evalSolution (Matrix &sField, const Vector &locSol, const int *npe, int n_f=0, bool piola=false) const
Evaluates the primary solution field at all visualization points.
virtual bool evalSolution (Matrix &sField, const Vector &locSol, const RealArray *gpar, bool regular=true, int deriv=0, int n_f=0) const
Evaluates the primary solution field at the given points.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const int *npe=nullptr, char project=0) const
Evaluates the secondary solution field at all visualization points.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const RealArray *gpar, bool regular=true) const
Evaluates the secondary solution field at the given points.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const IntVec &elements) const
Evaluates the secondary solution field at element centers.
Public Member Functions inherited from ASMbase
virtual ~ASMbase ()
The destructor frees the dynamically allocated data objects.
ASMbase * cloneUnShared () const
Returns a copy of this patch with identical FE discretization.
virtual bool readBasis (std::istream &, size_t)
Reads a basis from the given input stream.
virtual void addHole (double, double, double)
Adds a circular immersed boundary in the physical geometry.
virtual void addHole (double, double, double, double, double)
Adds an oval immersed boundary in the physical geometry.
virtual bool setGeometry (RealFunc *, double, double)
Defines the immersed geometry from a scalar function.
bool addLagrangeMultipliers (size_t iel, const IntVec &mGLag, unsigned char nnLag=1)
Adds a set of Lagrange multipliers to the specified element.
bool addGlobalLagrangeMultipliers (const IntVec &mGLag, unsigned char nnLag=1)
Adds global Lagrange multipliers to the system.
virtual void setGauss (int ng)
Defines the numerical integration scheme nGauss in the patch.
void setNoFields (unsigned char n)
Defines the number of solution fields in the patch.
void setElementActivator (IntFunc *efunc)
Sets the element activation function.
const IntFunc * getElementActivator () const
Returns a pointer to the element activation function.
virtual void setMinimumSize (double)
Sets the minimum element size for adaptive refinement.
virtual double getMinimumSize (int=0) const
Defines the minimum element size for adaptive refinement.
virtual bool checkElementSize (int, bool=true) const
Checks if the specified element is larger than the minimum size.
unsigned char getNoSpaceDim () const
Returns the number of spatial dimensions.
unsigned char getNoParamDim () const
Returns the number of parameter dimensions.
virtual unsigned char getNoFields (int b=0) const
Returns the number of solution fields.
unsigned char getNoLagPerNode () const
Returns the number of Lagrange multipliers per node.
size_t getElmIndex (int globalNum) const
Returns local 1-based index of element with given global number.
int getElmID (size_t iel) const
Returns the global element number for the given element.
virtual unsigned char getNodalDOFs (size_t inod) const
Returns the number of DOFs per node.
virtual char getNodeType (size_t inod) const
Returns the classification of a node.
bool isLMn (size_t n) const
Returns true if node n is a Lagrange multiplier node.
bool isRMn (size_t n) const
Returns true if node n is a master node of a rigid coupling.
char getLMType (size_t inod) const
Returns the type of a Lagrange multiplier node.
virtual void getBoundary1Nodes (int lIndex, IntVec &nodes, int basis=0, int orient=-1, bool local=false, bool open=false) const
Finds the global (or patch-local) node numbers on a patch boundary.
void getBoundaryElms (int lIndex, IntVec &elms, int orient=-1, bool local=false) const
Finds the global (or patch-local) element numbers on a boundary.
int getNodeSetIdx (const std::string &setName) const
Returns (1-based) index of a predefined node set in the patch.
const IntVec & getNodeSet (int iset) const
Returns an indexed predefined node set.
IntVec & getNodeSet (const std::string &setName, int &idx)
Returns a named node set for update.
bool isInNodeSet (int iset, int inod) const
Checks if node inod is within predefined node set iset.
int parseNodeSet (const std::string &setName, const char *cset, bool assumeZeroBased=false)
Defines a node set by parsing a list of node numbers.
virtual int parseNodeBox (const std::string &, const char *)
Defines a node set by parsing a 3D bounding box.
void convertNodeSets ()
Converts node number sets to internal (1-based) node indices.
virtual int getElementSetIdx (const std::string &) const
Returns (1-based) index of a predefined element set in the patch.
virtual const IntVec & getElementSet (int) const
Returns an indexed predefined element set.
virtual bool getElementSet (int, std::string &) const
Returns the name of an indexed predefined element set.
virtual bool isInElementSet (int, int) const
Checks if an element is within a predefined element set.
virtual int parseElemSet (const std::string &, const char *)
Defines an element set by parsing a list of element numbers.
virtual int parseElemBox (const std::string &, const std::string &, const char *)
Defines an element set by parsing a 3D bounding box.
virtual std::pair< size_t, double > findClosestNode (const Vec3 &) const
Finds the node that is closest to the given point.
void printNodes (std::ostream &os) const
Prints out the nodal coordinates of this patch to the given stream.
void printElements (std::ostream &os) const
Prints out element connections of this patch to the given stream.
virtual void printElmInfo (int, const IntegrandBase *) const
Prints out additional app-dependent element information.
virtual void shiftGlobalNodeNums (int nshift)
Increase all global node numbers by nshift.
void setGlobalNodeNums (const IntVec &nodes)
Sets the global node numbers for this patch.
const IntVec & getMyNodeNums () const
Returns the actual global node numbers of this patch.
const IntVec & getGlobalNodeNums () const
Returns the global node numbers of this patch.
virtual void shiftGlobalElmNums (int eshift)
Increase all global element numbers by eshift.
const IntVec & getGlobalElementNums () const
Returns the global element numbers of this patch.
void setActiveElements (IntVec *active)
Sets the list of active elements during assembly.
bool isElementActive (int iel, double time=-1.0) const
Returns true if element with 0-based index iel is active.
bool inActive (double time=-1.0) const
Returns true if none of the elements in the patch are active.
double getAge (int iel, double time) const
Returns the age of the element with 0-based index iel.
bool isElementInPartition (int iel) const
Returns true if element is in process partition.
const IntVec & getElementNodes (int iel) const
Returns the nodal point correspondance array for an element.
virtual size_t getNoBasis () const
Returns number of bases of this patch.
size_t getNoElms (bool includeZeroVolElms=false, bool includeXElms=false) const
Returns the total number of elements in this patch.
int getMaxElmNo () const
Returns the highest external element number in this patch.
size_t getNoMPCs () const
Returns the total number of multi-point constraint equations.
virtual void getNoIntPoints (size_t &nPt, size_t &nIPt)
Computes the total number of integration points in this patch.
virtual void getNoBouPoints (size_t &nPt, char ldim, char lindx)
Computes the number of boundary integration points in this patch.
BCVec::const_iterator begin_BC () const
Returns the beginning of the BCode array.
BCVec::const_iterator end_BC () const
Returns the end of the BCode array.
IntMat::const_iterator begin_elm () const
Returns the beginning of the MNPC array.
IntMat::const_iterator end_elm () const
Returns the end of the MNPC array.
MPCIter begin_MPC () const
Returns the beginning of the mpcs set.
MPCIter end_MPC () const
Returns the end of the mpcs set.
MPC * findMPC (int node, int dof) const
Returns a pointer to the MPC object for a specified slave, if any.
bool isShared () const
Returns true if this patch shares FE data with another patch.
bool hasXNodes () const
Returns true if this patch has additional (extraordinary) nodes.
bool mergeNodes (size_t inod, int globalNum, bool verbose=true)
Merges a given node in this patch with a given global node.
int renumberNodes (std::map< int, int > &old2new, int &nNod)
Renumbers the global node numbers in this patch.
bool renumberNodes (const std::map< int, int > &old2new, const std::vector< int > &new2old={}, int renumGN=0, std::map< int, int > *degenElm=nullptr)
Renumbers the global node numbers referred by this patch.
bool hasTimeDependentDirichlet (const std::map< int, RealFunc * > &func, const std::map< int, VecFunc * > &vfunc)
Checks for time-dependent in-homogeneous Dirichlet conditions.
virtual bool transform (const Matrix &)
Applies a transformation matrix from local to global system.
virtual void initMADOF (const int *)
Initializes the patch level MADOF array for mixed problems.
virtual bool integrateEdge (Integrand &integrand, int lEdge, GlobalIntegral &glbInt, const TimeDomain &time)
Evaluates a boundary integral over a patch edge.
virtual ElementBlock * immersedGeometry (char *) const
Returns an additional geometry to visualize (immersed boundaries).
virtual ElementBlock * extraGeometry (char *) const
Returns an additional geometry to visualize (spiders, etc.).
virtual void filterResults (Matrix &, const ElementBlock *) const
Filters out result point values that are outside physical domain.
virtual bool getSolution (Matrix &sField, const Vector &locSol, const IntVec &nodes) const
Extract the primary solution field at the specified nodes.
virtual bool immersedSolution (Matrix &, const Vector &) const
Evaluates the primary solution at the immersed geometry points.
virtual bool extraSolution (Matrix &, const Vector &) const
Evaluates the primary solution at the extra geometry points.
virtual bool evalSolutionPiola (Matrix &sField, const Vector &locSol, const RealArray *gpar, bool regular) const
Evaluates the primary solution field with Piola mapping.
bool globalL2projection (Matrix &sField, const L2Integrand &integrand, bool continuous=false, bool enforceEnds=false) const
Projects the secondary solution using a (discrete) global L2-fit.
bool L2projection (Matrix &sField, IntegrandBase *integrand, const TimeDomain &time)
Projects the secondary solution using a continuous global L2-fit.
bool L2projection (Matrix &fVals, FunctionBase *func, double t=0.0)
Projects an explicit function using a continuous global L2-fit.
bool L2projection (const std::vector< Matrix * > &fVals, const std::vector< FunctionBase * > &funcs, double t=0.0)
Projects explicit functions using a continuous global L2-fit.
virtual size_t getNoRefineNodes () const
Returns the number of nodes on refinement basis for this patch.
virtual size_t getNoRefineElms () const
Returns the number of elements on refinement basis for this patch.
virtual const ASMbase * getOutputMaster () const
Returns the master patch to use for VTF- and HDF5-output.
void extractElmRes (const Vector &globRes, Vector &elmRes, size_t internalFirst=0) const
Extracts element results for this patch from a global vector.
void extractElmRes (const Matrix &globRes, Vector &elmRes, size_t irow) const
Extracts element results for this patch from a global matrix.
bool extractNodalVec (const RealArray &globVec, RealArray &nodeVec, const int *madof, int ngnod=-1) const
Extracts nodal results for this patch from the global vector.
virtual void extractNodeVec (const RealArray &globVec, RealArray &nodeVec, unsigned char nndof=0, int basis=0) const
Extracts nodal results for this patch from the global vector.
virtual bool injectNodeVec (const RealArray &nodeVec, RealArray &globVec, unsigned char nndof=0, int basis=0) const
Injects nodal results for this patch into the global vector.
bool injectNodalVec (const RealArray &nodeVec, RealArray &globVec, const IntVec &madof, int basis=0) const
Injects nodal results for this patch into the global vector.
bool add2PC (int slave, int dir, int master, int code=0)
Creates and adds a two-point constraint to this patch.
bool addMPC (MPC *&mpc, int code=0, bool verbose=false, bool overrideD=false)
Adds a general multi-point-constraint (MPC) equation to this patch.
void addRigidCouplings (int gMaster, const Vec3 &Xmaster, const IntVec &slaveNodes)
Adds MPC-equations representing a rigid coupling to this patch.
void addNodalCouplings (int slave, const IntVec &masters, const RealArray &weights)
Adds MPC-equations for general nodal couplings in this patch.
void constrainPatch (int dof, int code=0)
Constrains all nodes in the patch.
void constrainNodes (const IntVec &nodes, int dof, int code=0, bool overrideD=false)
Constrains a list of nodes in the patch.
bool constrainXnode (int node, int dof, int code=0)
Constrains an extraordinary node in the patch.
int prescribe (size_t inod, int dirs, int code, bool overrideD=false)
Constrains DOFs in the given node to the given value.
int fix (size_t inod, int dirs=123)
Constrains DOFs in the given node to zero.
bool isFixed (int node, int dof, bool all=false) const
Checks if the given DOFs are fixed.
Public Member Functions inherited from ASM2D
virtual ~ASM2D ()
Empty destructor.
ASMbase * clone (const CharVec &nf=CharVec()) const
Returns a copy of this patch with identical FE discretization.
virtual bool refine (int dir, const std::vector< double > &xi, double scale=1.0)=0
Refines the parametrization by inserting extra knots.
virtual bool getGridParameters (std::vector< double > &prm, int dir, int nSegSpan) const =0
Calculates parameter values for visualization nodal points.
Static Public Member Functions
static void renumberNodes (const std::map< int, int > &old2new)
Renumbers the global node numbers in the neighbors map.
Static Public Member Functions inherited from ASMs2D
static void scatterInd (int n1, int n2, int p1, int p2, const int *start, IntVec &index)
Auxilliary function for computation of basis function indices.
Static Public Member Functions inherited from ASMbase
static void resetNumbering (int n=0)
Resets the global element and node counters.
static int renumberNodes (const ASM::PatchVec &model, std::map< int, int > &old2new)
Renumbers all global node numbers in the entire model.
static void mergeAndGetAllMPCs (const ASM::PatchVec &model, MPCSet &allMPCs)
Computes the set of all MPC-equations over the whole model.
static void resolveMPCchains (const MPCSet &allMPCs, const ASM::PatchVec &model, bool setPtrOnly=false)
Resolves (possibly multi-level) chaining in MPC-equations.
Static Public Member Functions inherited from ASM2D
static ASMbase * create (ASM::Discretization type, unsigned char nd, const CharVec &nf, bool mixedFEM=false)
Creates a two-parametric patch of specified discretization type.
static ASMbase * create (ASM::Discretization type, unsigned char nf=1)
Creates a two-parametric patch of specified discretization type.
Protected Member Functions
void addC1MPC (int slave, int dir, int master1, int master2=0, int code=0)
Creates and adds a constraint equation enforcing C1-continuity.
Protected Member Functions inherited from ASMs2D
bool integrate (Integrand &integrand, GlobalIntegral &glbInt, const TimeDomain &time, const Real3DMat &itgPts)
Evaluates an integral over the interior patch domain.
virtual void findBoundaryElms (IntVec &elms, int lIndex, int=0) const
Finds the patch-local element numbers on a patch boundary.
virtual bool assembleL2matrices (SystemMatrix &A, SystemVector &B, const L2Integrand &integrand, bool continuous) const
Assembles L2-projection matrices for the secondary solution.
bool connectBasis (int edge, ASMs2D &neighbor, int nedge, bool revers, int basis=1, int slave=0, int master=0, bool coordCheck=true, int thick=1)
Connects all matching nodes on two adjacent boundary edges.
void getGaussPointParameters (RealArray &uGP, int dir, int nGauss, const double *xi) const
Extracts parameter values of the Gauss points in one direction.
bool getGrevilleParameters (RealArray &prm, int dir, int basisNum=1) const
Calculates parameter values for the Greville points.
bool getQuasiInterplParameters (RealArray &prm, int dir) const
Calculates parameter values for the Quasi-Interpolation points.
double getParametricArea (int iel) const
Returns the area in the parameter space for an element.
double getParametricLength (int iel, int dir) const
Returns boundary edge length in the parameter space for an element.
bool getElementCoordinatesPrm (Matrix &X, double u, double v) const
Returns a matrix with nodal coordinates for element containing given parameters.
void getElementBorders (int i1, int i2, double *u, double *v) const
Computes the element border parameters.
virtual void getElementBorders (int iel, double *u) const
Computes the element border parameters.
double getElementCorners (int i1, int i2, std::vector< Vec3 > &XC, RealArray *uC=nullptr) const
Computes the element corner coordinates.
void getCornerPoints (int i1, int i2, std::vector< utl::Point > &XC) const
Computes the element corner coordinates and parameters.
virtual void generateThreadGroups (const Integrand &integrand, bool silence, bool ignoreGlobalLM)
Generates element groups for multi-threading of interior integrals.
virtual void changeNumThreads ()
Hook for changing number of threads.
void generateThreadGroups (size_t strip1, size_t strip2, bool silence, bool ignoreGlobalLM)
Generates element groups for multi-threading of interior integrals.
virtual void generateThreadGroupsFromElms (const IntVec &elms)
Generates element groups from a partition.
virtual void generateProjThreadGroupsFromElms (const IntVec &elms)
Generate element groups from a partition.
virtual bool validateThreadGroups (const SAM *sam) const
Validates the threading groups based on the assembly data in SAM.
virtual int getFirstItgElmNode () const
Returns 0-based index of first node on integration basis.
virtual int getLastItgElmNode () const
Returns 0-based index of last node on integration basis.
virtual void generateThreadGroups (const Integrand &, bool, bool)
Generates element groups for multi-threading of interior integrals.
virtual void generateThreadGroups (char, bool, bool)
Generates element groups for multi-threading of boundary integrals.
Protected Member Functions inherited from ASMstruct
ASMstruct (unsigned char n_p, unsigned char n_s, unsigned char n_f)
The constructor sets the number of space dimensions and fields.
ASMstruct (const ASMstruct &patch, unsigned char n_f)
Special copy constructor for sharing of FE data.
bool addXNodes (unsigned short int dim, size_t nXn, IntVec &nodes)
Adds extraordinary nodes associated with a patch boundary.
bool checkThreadGroups (const std::vector< std::set< int > > &nodes, int group, bool ignoreGlobalLM)
Performs a sanity check on the thread groups.
Protected Member Functions inherited from ASMbase
ASMbase (unsigned char n_p, unsigned char n_s, unsigned char n_f)
The constructor sets the number of space dimensions and fields.
ASMbase (const ASMbase &patch, unsigned char n_f)
Special copy constructor for sharing of FE data.
ASMbase (const ASMbase &patch)
Default copy constructor, copying everything except neighbors.
void addLocal2GlobalCpl (int iSlave, int master, const Tensor &Tlg)
Creates constraint equations coupling global DOFs to local DOFs.
bool add3PC (int slave, int dir, int master1, int master2, int code=0)
Creates and adds a three-point constraint to this patch.
bool addPeriodicity (size_t master, size_t slave, int dir)
Creates and adds a periodicity constraint to this patch.
void makePeriodic (size_t master, size_t slave, int dirs=123)
Creates periodicity constraints between two nodes in this patch.
void addNeighbor (ASMbase *pch)
Adds a patch to the list of neighbors of this patch.
bool createRgdMasterNode (int &gMaster, const Vec3 &Xmaster)
Creates an additional master node for a rigid coupling.
void addRigidMPC (int gSlave, int gMaster, const Vec3 &dX)
Adds MPC-equations representing a rigid arm to a 6-DOF node.
int getNoGaussPt (int p, bool neumann=false) const
Returns the number of Gauss points to use in one direction.
int searchCtrlPt (RealArray::const_iterator cit, RealArray::const_iterator end, const Vec3 &X, int dimension, double xtol=0.001) const
Helper method used by evalPoint to search for a control point.
bool allDofs (int dirs) const
Returns true if dirs constains all local DOFs in the patch.
bool writeLagBasis (std::ostream &os, const char *type) const
Writes a Lagrangian basis to the given stream.
Protected Member Functions inherited from ASM2D
ASM2D ()
The constructor is protected to allow objects of sub-classes only.
Private Attributes
std::set< int > myC1slaves
Set of slave DOFs for C1-continuity enforcement.
Static Private Attributes
static std::map< int, ASMs2DC1 * > neighbors
Global node to patch mapping.
Additional Inherited Members
Public Types inherited from ASMbase
using BCVec = std::vector< BC >
Nodal boundary condition container.
Public Types inherited from ASM2D
typedef std::vector< unsigned char > CharVec
Convenience type.
Public Attributes inherited from ASMbase
size_t idx
Index of this patch in the multi-patch model.
Static Public Attributes inherited from ASMbase
static bool fixHomogeneousDirichlet = true
If true, pre-eliminate fixed DOFs.
static int dbgElm = 0
One-based element index to print debugging info for.
static double modelSize = 1.0
Characteristic model size.
Protected Types inherited from ASMbase
using XYZ = std::array< double, 3 >
Convenience type definition.
Static Protected Member Functions inherited from ASMbase
static bool deformedConfig (const Matrix &Xnod, Vectors &eVec, bool force2nd=false)
Calculates the deformed configuration for current element.
static bool collapseNodes (ASMbase &pch1, int node1, ASMbase &pch2, int node2)
Collapses the given two nodes into one.
Static Protected Member Functions inherited from ASM2D
static double getElementSize (const std::vector< Vec3 > &XC)
Returns characteristic element size based on corner coordinates.
Protected Attributes inherited from ASMs2D
std::shared_ptr< Go::SplineSurface > surf
The actual spline surface object.
Go::SplineCurve * bou [4]
Pointers to the four boundary curves.
bool swapV
Has the v-parameter direction been swapped?
const IndexVec & nodeInd
IJ-pairs for the control points (nodes)
IndexVec myNodeInd
The actual IJ-pair container.
std::map< size_t, size_t > xnMap
Node index map used by getCoord()
std::map< size_t, size_t > nxMap
Node index map used by getNodeID()
std::vector< DirichletEdge > dirich
Inhomogeneous Dirichlet boundary condition data.
ThreadGroups threadGroups
Element groups for multi-threaded assembly.
std::vector< std::unique_ptr< BasisFunctionCache > > myCache
Basis function cache.
Protected Attributes inherited from ASMstruct
std::shared_ptr< Go::GeomObject > geomB
Pointer to spline object of the geometry basis.
std::shared_ptr< Go::GeomObject > projB
Pointer to spline object of the projection basis.
std::shared_ptr< Go::GeomObject > projB2
Pointer to spline object of the secondary projection basis.
ThreadGroups projThreadGroups
Element groups for multi-threaded assembly - projection basis.
ThreadGroups proj2ThreadGroups
Element groups for multi-threaded assembly - second projection basis.
Protected Attributes inherited from ASMbase
unsigned char ndim
Number of parametric dimensions (1, 2 or 3)
unsigned char nsd
Number of space dimensions (ndim <= nsd <= 3)
unsigned char nf
Number of primary solution fields (1 or larger)
unsigned char nLag
Number of Lagrange multipliers per node.
size_t nel
Number of regular elements in this patch.
size_t nnod
Number of regular nodes in this patch.
const IntVec & MLGE
Matrix of Local to Global Element numbers.
const IntVec & MLGN
Matrix of Local to Global Node numbers.
const IntMat & MNPC
Matrix of Nodal Point Correspondance.
const char shareFE
Flag telling whether this patch shares its data with another patch.
BCVec BCode
Array of Boundary Condition codes.
MPCMap dCode
Inhomogeneous Dirichlet condition codes for the MPCs.
MPCSet mpcs
All multi-point constraints with the slave in this patch.
std::vector< ASM::NodeSet > nodeSets
Node sets for explicit Dirichlet BCs.
IntVec myMLGE
The actual Matrix of Local to Global Element numbers.
IntVec myMLGN
The actual Matrix of Local to Global Node numbers.
IntMat myMNPC
The actual Matrix of Nodal Point Correspondance.
IntVec myElms
Elements on patch - used with partitioning.
int nGauss
Numerical integration scheme for this patch.
size_t firstEl
Global index to first element within this patch.
size_t firstIp
Global index to first interior integration point.
std::map< char, size_t > firstBp
Global indices to first integration point for the Neumann boundaries.
ASM::PatchVec neighbors
Patches having nodes in common with this one.
std::map< size_t, XYZ > myRmaster
Rigid master nodal points.
Static Protected Attributes inherited from ASMbase
static std::map< int, int > xNode
Auxilliary node number map used when establishing Dirichlet constraints.
static int gEl = 0
Global element counter.
static int gNod = 0
Global node counter.
Detailed Description
Driver for assembly of C1-continuous structured 2D spline FE models.
This class extends the ASMs2D class to handle C1-continuity over patch interfaces, as well as boundary conditions on derivatives.
Member Function Documentation
addC1MPC()
void ASMs2DC1::addC1MPC (int slave, int dir, int master1, int master2 = 0, int code = 0) protected
Creates and adds a constraint equation enforcing C1-continuity.
Parameters
[in] slave Global node number of the node to constrain
[in] dir Which local DOF to constrain (1, 2, 3)
[in] master1 Global node number of 1st master node of the constraint
[in] master2 Global node number of 2nd master node of the constraint
[in] code Identifier for inhomogeneous Dirichlet condition field
References ASMbase::add2PC(), ASMbase::add3PC(), myC1slaves, and ASMbase::nf.
Referenced by closeBoundaries(), connectC1(), and constrainEdge().
addRigidCpl()
bool ASMs2DC1::addRigidCpl (int lindx, int ldim, int basis, int & gMaster, const Vec3 & Xmaster, bool extraPt) virtual
Adds MPCs representing a rigid coupling to this patch.
Parameters
[in] lindx Local index of the boundary item that should be rigid
[in] ldim Dimension of the boundary item that should be rigid
[in] basis Which basis to add rigid coupling for (mixed methods)
gMaster Global node number of the master node
[in] Xmaster Position of the master nodal point
[in] extraPt If true, the master point is not a patch node
Returns
true if a new global node was added, otherwise false
Reimplemented from ASMs2D.
References MPC::addMaster(), ASMbase::addMPC(), ASMbase::addRigidMPC(), IFEM::cout, ASMbase::createRgdMasterNode(), ASMs2D::getBoundaryNodes(), ASMs2D::getCoord(), ASMbase::idx, ASMbase::MLGN, ASMbase::nf, ASMbase::nsd, ThreadGroups::stripDir, ASMs2D::threadGroups, Vec3::x, and Vec3::y.
closeBoundaries()
void ASMs2DC1::closeBoundaries (int dir, int , int) virtual
Makes two opposite boundary edges periodic.
Parameters
[in] dir Parameter direction defining the periodic edges
Reimplemented from ASMs2D.
References addC1MPC(), ASMs2D::getSize(), ASMbase::makePeriodic(), ASMbase::MLGN, ThreadGroups::stripDir, and ASMs2D::threadGroups.
connectC1()
bool ASMs2DC1::connectC1 (int edge, ASMs2DC1 * neighbor, int nedge, bool revers = false)
Connects all matching nodes on two adjacent boundary edges.
Parameters
[in] edge Local edge index of this patch, in range [1,4]
neighbor The neighbor patch
[in] nedge Local edge index of neighbor patch, in range [1,4]
[in] revers Indicates whether the two edges have opposite directions
References addC1MPC(), ASMs2D::getSize(), ASMbase::MLGN, ASMbase::myMLGN, neighbors, ASMbase::nf, and ASMbase::shareFE.
constrainCorner() [1/2]
void ASMs2D::constrainCorner (int I, int J, int dof, int code = 0, char basis = 1) virtual
Constrains a corner node identified by the two parameter indices.
Parameters
[in] I Parameter index in u-direction
[in] J Parameter index in v-direction
[in] dof Which DOFs to constrain at the node
[in] code Inhomogeneous dirichlet condition code
[in] basis Which basis to constrain node for
The sign of the two indices is used to define whether we want the node at the beginning or the end of that parameter direction. The magnitude of the indices are not used.
Reimplemented from ASMs2D.
constrainCorner() [2/2]
void ASMs2DC1::constrainCorner (int I, int J, int dof = 12, int code = 0) virtual
Constrains a corner node identified by the two parameter indices.
Parameters
[in] I Parameter index in u-direction
[in] J Parameter index in v-direction
[in] dof Which DOFs to constrain at the node
[in] code Inhomogeneous dirichlet condition code
The sign of the two indices is used to define whether we want the node at the beginning or the end of that parameter direction. The magnitude of the indices are not used.
References ASMs2D::getSize(), and ASMbase::prescribe().
constrainEdge()
void ASMs2DC1::constrainEdge (int dir, bool open, int dof = 12, int code = 0, char basis = 1) virtual
Constrains all DOFs on a given boundary edge.
Parameters
[in] dir Parameter direction defining the edge to constrain
[in] open If true, exclude the end points of the edge
[in] dof Which DOFs to constrain at each node on the edge
[in] code Inhomogeneous dirichlet condition code
[in] basis Basis to constrain
Reimplemented from ASMs2D.
References addC1MPC(), utl::getDigits(), ASMs2D::getSize(), ASMbase::MLGN, and ASMbase::prescribe().
constrainNode()
void ASMs2DC1::constrainNode (double xi, double eta, int dof = 12, int code = 0) virtual
Constrains a node identified by two relative parameter values.
Parameters
[in] xi Parameter in u-direction
[in] eta Parameter in v-direction
[in] dof Which DOFs to constrain at the node
[in] code Inhomogeneous dirichlet condition code
The parameter values have to be in the domain [0.0,1.0], where 0.0 means the beginning of the domain and 1.0 means the end. For values in between, the actual index is taken as the integer value closest to r*n, where r denotes the given relative parameter value, and n is the number of nodes along that parameter direction.
Reimplemented from ASMs2D.
References ASMs2D::getSize(), and ASMbase::prescribe().
generateFEMTopology()
bool ASMs2DC1::generateFEMTopology () virtual
Generates the finite element topology data for the patch.
This method is reimplemented to check that the patch has sufficient polynomial order.
Reimplemented from ASMs2D.
References ASMs2D::generateFEMTopology(), and ASMs2D::surf.
initConstraints()
bool ASMs2DC1::initConstraints () virtual
Initializes constraint equations enforcing C1-continuity.
Reimplemented from ASMbase.
References ASMs2D::getCoord(), ASMs2D::getNodeIndex(), initMPC2(), initMPC3(), initMPC4flat(), ASMbase::mpcs, myC1slaves, neighbors, and ASMbase::nf.
renumberNodes()
void ASMs2DC1::renumberNodes (const std::map< int, int > & old2new) static
Renumbers the global node numbers in the neighbors map.
Parameters
[in] old2new Old-to-new node number mapping
References neighbors.
Referenced by SIMbase::renumberNodes().
updateDirichlet()
bool ASMs2DC1::updateDirichlet (const std::map< int, RealFunc * > & func, const std::map< int, VecFunc * > & vfunc, double time, const std::map< int, int > * g2l = nullptr, bool tangent = false) virtual
Updates the time-dependent in-homogeneous Dirichlet coefficients.
Parameters
[in] func Scalar property fields
[in] vfunc Vector property fields
[in] time Current time
[in] g2l Pointer to global-to-local node number mapping
[in] tangent If true, use time-derivatives of prescribed values
Reimplemented from ASMs2D.
References ASMbase::dCode, ASMs2D::getCoord(), ASMs2D::getNodeIndex(), neighbors, and ASMs2D::updateDirichlet().
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/ASM/ASMs2DC1.h
/home/runner/work/IFEM-2/IFEM-2/src/ASM/ASMs2DC1.C