IFEM: SymmTensor4 Class Reference
SymmTensor4 Class Reference
Simple class for representing a symmetric fourth-order tensor.
#include <Tensor4.h>
Public Member Functions
SymmTensor4 (t_ind nsd=3, bool makeJ=false)
The default constructor creates an identity tensor.
SymmTensor4 (const std::vector< Real > &x, t_ind nsd=3)
Constructor creating a tensor from a vector of components.
const Real & operator() (t_ind i, t_ind j, t_ind d, t_ind l) const
Index-1 based component reference.
Real & operator() (t_ind i, t_ind j, t_ind k, t_ind l)
Index-1 based component access.
Public Member Functions inherited from Tensor4
Tensor4 (t_ind nsd=3, Real scale=Real(1), bool makeJ=false)
The default constructor creates a (scaled) identity tensor.
Tensor4 (const std::vector< Real > &x, t_ind nsd=3)
Constructor creating a tensor from a vector of components.
void zero ()
Sets this to the 0-tensor.
operator const std::vector< Real > & () const
Type casting to a one-dimensional vector, for referencing.
operator std::vector< Real > & ()
Type casting to a one-dimensional vector, for assignment.
const Real * ptr () const
Reference through a pointer.
const Real & operator() (t_ind i, t_ind j, t_ind d, t_ind l) const
Index-1 based component reference.
Real & operator() (t_ind i, t_ind j, t_ind k, t_ind l)
Index-1 based component access.
Tensor4 & operator= (const Tensor4 &T)
Assignment operator.
Tensor4 & operator= (Real val)
Overloaded assignment operator.
Tensor4 & operator+= (Real val)
Incrementation operator.
Protected Member Functions
virtual void redim (t_ind nsd)
Auxilliary method used by the constructors.
virtual std::ostream & print (std::ostream &os) const
Prints out the tensor to an output stream.
Private Member Functions
t_ind index (t_ind i, t_ind j) const
Returns a 0-based array index for the given row and column indices.
Additional Inherited Members
Protected Types inherited from Tensor4
typedef unsigned short int t_ind
Tensor index type (for convenience)
Protected Attributes inherited from Tensor4
t_ind n
Number of spatial dimensions for the tensor.
t_ind m
Dimension of the matrix representation.
std::vector< Real > v
The actual tensor component values.
Detailed Description
Simple class for representing a symmetric fourth-order tensor.
Constructor & Destructor Documentation
SymmTensor4()
SymmTensor4::SymmTensor4 (const std::vector< Real > & x, t_ind nsd = 3)
Constructor creating a tensor from a vector of components.
The provided vector is assumed to contain the components of the matrix representation of the tensor, stored in a one-dimensional array.
Member Function Documentation
index()
t_ind SymmTensor4::index (t_ind i, t_ind j) const inline private
Returns a 0-based array index for the given row and column indices.
Symmetric second-order tensors in 3D are assumed stored with the following order in a one-dimensional array: s11, s22, s33, s12, s23, s13.
References Tensor4::n.
Referenced by operator()(), operator()(), and print().
print()
std::ostream & SymmTensor4::print (std::ostream & os) const protected virtual
Prints out the tensor to an output stream.
Reimplemented from Tensor4.
References index(), Tensor4::m, Tensor4::n, and Tensor4::v.
redim()
void SymmTensor4::redim (t_ind nsd) protected virtual
Auxilliary method used by the constructors.
Reimplemented from Tensor4.
References Tensor4::m, and Tensor4::n.
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/Utility/Tensor4.h
/home/runner/work/IFEM-2/IFEM-2/src/Utility/Tensor4.C