IFEM: ASMu2D::InterfaceChecker Class Reference
ASMu2D::InterfaceChecker Class Reference
Base class that checks if an element has interface contributions.
#include <ASMu2D.h>
Classes
struct Intersection
Struct describing an intersection of mesh lines.
Public Member Functions
InterfaceChecker (const ASMu2D &pch)
The constructor initialises the reference to current patch.
virtual ~InterfaceChecker ()
Empty destructor.
virtual short int hasContribution (int iel, int=-1, int=-1, int=-1) const
Returns non-zero if the specified element have contributions.
const RealArray & getIntersections (int iel, int edge, int *cont=nullptr) const
Get intersections for a given element edge.
Public Member Functions inherited from ASM::InterfaceChecker
virtual short int elmBorderMask (double u0, double u1, double v0, double v1, double w0=0.0, double w1=1.0) const
Returns a status mask based on the element boundary parameters.
Protected Attributes
const ASMu2D & myPatch
Reference to the patch being integrated.
std::map< int, Intersection > intersections
Intersections for elements. Key: element << 4 + edge (1..4).
Detailed Description
Base class that checks if an element has interface contributions.
Constructor & Destructor Documentation
~InterfaceChecker()
virtual ASMu2D::InterfaceChecker::~InterfaceChecker () inline virtual
Empty destructor.
Reimplemented from ASM::InterfaceChecker.
Member Function Documentation
getIntersections()
const RealArray & ASMu2D::InterfaceChecker::getIntersections (int iel, int edge, int * cont = nullptr) const
Get intersections for a given element edge.
Parameters
[in] iel Element index (1-based)
[in] edge Edge to get intersections for (1..4)
[out] cont If not null, the intersection continuity is given here
References ASMLRSpline::empty().
Referenced by ASMu2D::integrate(), and ASMu2Dmx::integrate().
hasContribution()
short int ASMu2D::InterfaceChecker::hasContribution (int iel, int = -1, int = -1, int = -1) const virtual
Returns non-zero if the specified element have contributions.
Parameters
[in] iel Element number
Implements ASM::InterfaceChecker.
References ASMu2D::lrspline.
Referenced by ASMu2D::integrate(), and ASMu2Dmx::integrate().
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/ASM/LR/ASMu2D.h
/home/runner/work/IFEM-2/IFEM-2/src/ASM/LR/ASMu2D.C