IFEM: L2FuncIntegrand Class Reference
L2FuncIntegrand Class Reference
Evaluation class for functions.
#include <GlbL2projector.h>
Public Member Functions
L2FuncIntegrand (const ASMbase &patch, const FunctionBase &func, double time=0.0)
The constructor initializes the function reference.
bool evaluate (Matrix &sField, const RealArray *gpar) const override
Evaluates the function in a set of points.
size_t dim () const override
Returns number of function components.
Public Member Functions inherited from L2Integrand
L2Integrand (const ASMbase &patch)
The constructor initializes the patch reference.
virtual ~L2Integrand ()
Empty destructor.
double getTimeLevel () const
Returns current time/load parameter for 2ndary solution evaluation.
Private Attributes
const FunctionBase & m_func
Reference to function.
Additional Inherited Members
Protected Attributes inherited from L2Integrand
const ASMbase & m_patch
Reference to ASM holding geometry.
double myTime
Current time or load parameter.
Detailed Description
Evaluation class for functions.
Constructor & Destructor Documentation
L2FuncIntegrand()
L2FuncIntegrand::L2FuncIntegrand (const ASMbase & patch, const FunctionBase & func, double time = 0.0)
The constructor initializes the function reference.
Parameters
[in] patch ASM holding geometry to evaluate on
[in] func Function to evaluate
[in] time Current time
References L2Integrand::myTime.
Member Function Documentation
dim()
size_t L2FuncIntegrand::dim () const override virtual
Returns number of function components.
Implements L2Integrand.
References FunctionBase::dim(), and m_func.
evaluate()
bool L2FuncIntegrand::evaluate (Matrix & sField, const RealArray * gpar) const override virtual
Evaluates the function in a set of points.
Parameters
[out] sField Matrix with results
[in] gpar Points to evaluate in
Implements L2Integrand.
References FunctionBase::dim(), ASMbase::evalPoint(), utl::matrix< T >::fillColumn(), ASMbase::getNoSpaceDim(), ASMbase::getParameterDomain(), FunctionBase::getValue(), m_func, L2Integrand::m_patch, L2Integrand::myTime, and utl::matrix< T >::resize().
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/ASM/GlbL2projector.h
/home/runner/work/IFEM-2/IFEM-2/src/ASM/GlbL2projector.C