IFEM: L2ProbIntegrand Class Reference
L2ProbIntegrand Class Reference
Evaluation class for secondary solutions of an integrand.
#include <GlbL2projector.h>
Public Member Functions
L2ProbIntegrand (const ASMbase &patch, const IntegrandBase &itg)
The constructor initializes the integrand reference.
bool evaluate (Matrix &sField, const RealArray *gpar) const override
Evaluates the secondary solutions in a set of points.
size_t dim () const override
Returns number of secondary solutions.
Public Member Functions inherited from L2Integrand
L2Integrand (const ASMbase &patch)
The constructor initializes the patch reference.
virtual ~L2Integrand ()
Empty destructor.
double getTimeLevel () const
Returns current time/load parameter for 2ndary solution evaluation.
Private Attributes
const IntegrandBase & m_itg
Reference to integrand.
Additional Inherited Members
Protected Attributes inherited from L2Integrand
const ASMbase & m_patch
Reference to ASM holding geometry.
double myTime
Current time or load parameter.
Detailed Description
Evaluation class for secondary solutions of an integrand.
Constructor & Destructor Documentation
L2ProbIntegrand()
L2ProbIntegrand::L2ProbIntegrand (const ASMbase & patch, const IntegrandBase & itg)
The constructor initializes the integrand reference.
Parameters
[in] patch ASM holding geometry to evaluate on
[in] itg Integrand to evaluate
References IntegrandBase::getTimeLevel(), and L2Integrand::myTime.
Member Function Documentation
dim()
size_t L2ProbIntegrand::dim () const override virtual
Returns number of secondary solutions.
Implements L2Integrand.
References IntegrandBase::getNoFields(), and m_itg.
evaluate()
bool L2ProbIntegrand::evaluate (Matrix & sField, const RealArray * gpar) const override virtual
Evaluates the secondary solutions in a set of points.
Parameters
[out] sField Matrix with results
[in] gpar Points to evaluate in
Implements L2Integrand.
References ASMbase::evalSolution(), m_itg, and L2Integrand::m_patch.
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/ASM/GlbL2projector.h
/home/runner/work/IFEM-2/IFEM-2/src/ASM/GlbL2projector.C