IFEM: ReactionsOnly Class Reference
ReactionsOnly Class Reference
Class for assembly of reaction- and interface forces.
#include <ReactionsOnly.h>
Public Member Functions
ReactionsOnly (const SAM *sam, const ProcessAdm &adm, RealArray *rf=nullptr, Vector *sf=nullptr)
The constructor initializes the data members.
virtual ~ReactionsOnly ()
Empty destructor.
virtual void initialize (char)
Initializes the integrated quantity to zero.
virtual bool finalize (bool)
Finalizes the integrated quantity after element assembly.
virtual bool assemble (const LocalIntegral *elmObj, int elmId)
Adds a LocalIntegral object into a corresponding global object.
virtual bool haveContributions (size_t pidx, const std::vector< Property > &pvec) const
Returns true if the patch pidx have any force contributions.
Public Member Functions inherited from GlobalIntegral
GlobalIntegral ()
The default constructor.
virtual ~GlobalIntegral ()
Empty destructor.
virtual bool threadSafe () const
Returns true if all elements can be assembled in parallel.
Private Attributes
const SAM * mySam
Data for FE assembly management.
const ProcessAdm & myAdm
Parallel processing administrator.
StdVector b
Internal right-hand-side vector used in the force assembly.
RealArray * R
Nodal reaction forces.
Vector * S
Nodal internal forces.
Detailed Description
Class for assembly of reaction- and interface forces.
This class can be used for linear problems which normally consists of a single assembly loop. For non-linear problems, the reaction forces for a given solution state is calculated during the subsequent iteration where the solution vector of the previous iteration is used. In linear problems we therefore need a separate assembly loop where only the reaction forces are calculated. This class is provided to facilitate such calculations.
The class can also be used to calculate interface force resultants, for boundaries not associated with dirichlet conditions.
Constructor & Destructor Documentation
ReactionsOnly()
ReactionsOnly::ReactionsOnly (const SAM * sam, const ProcessAdm & adm, RealArray * rf = nullptr, Vector * sf = nullptr)
The constructor initializes the data members.
Parameters
[in] sam Data for FE assembly management
[in] adm Parallell processing administrator
[in] rf Reaction forces to be assembled
[in] sf Internal force vector to be assembled
References b, SAM::getNoEquations(), SAM::getNoSpecifiedDOFs(), R, and StdVector::redim().
Member Function Documentation
assemble()
bool ReactionsOnly::assemble (const LocalIntegral * elmObj, int elmId) virtual
Adds a LocalIntegral object into a corresponding global object.
Parameters
[in] elmObj The local integral object to add into *this.
[in] elmId Global number of the element associated with elmObj
Reimplemented from GlobalIntegral.
References SAM::assembleSystem(), b, ElmMats::getRHSVector(), mySam, and R.
finalize()
bool ReactionsOnly::finalize (bool) virtual
Finalizes the integrated quantity after element assembly.
Reimplemented from GlobalIntegral.
References ProcessAdm::allReduceAsSum(), b, ProcessAdm::dd, SystemVector::endAssembly(), SAM::expandSolution(), DomainDecomposition::isPartitioned(), myAdm, mySam, SAM::printVector(), R, and S.
haveContributions()
bool ReactionsOnly::haveContributions (size_t pidx, const std::vector< Property > & pvec) const virtual
Returns true if the patch pidx have any force contributions.
Parameters
[in] pidx 1-based patch index
[in] pvec Physical property mapping
Reimplemented from GlobalIntegral.
References R, and S.
initialize()
void ReactionsOnly::initialize (char) virtual
Initializes the integrated quantity to zero.
Reimplemented from GlobalIntegral.
References b, StdVector::init(), and R.
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/ASM/ReactionsOnly.h
/home/runner/work/IFEM-2/IFEM-2/src/ASM/ReactionsOnly.C