IFEM: ScalarFunc Class Reference
ScalarFunc Class Reference
Scalar-valued unary function of a scalar value.
#include <Function.h>
Public Member Functions
Real eval (Real x) const
Returns the function value for the argument x.
virtual Real deriv (Real) const
Returns the first-derivative of the function.
Public Member Functions inherited from utl::Function< Real, Real >
virtual ~Function ()
Empty destructor.
virtual bool isZero () const
Returns whether the function is identically zero or not.
virtual bool isConstant () const
Returns whether the function is time-independent or not.
Real operator() (const Real &x) const
Operator returning the function value for the given argument.
Protected Member Functions
ScalarFunc ()
The constructor is protected to allow sub-class instances only.
Protected Member Functions inherited from utl::Function< Real, Real >
Function ()
The constructor is protected to allow sub-class instances only.
virtual Real evaluate (const Real &x) const=0
Evaluates the function for the argument x.
Additional Inherited Members
Public Types inherited from utl::Function< Real, Real >
typedef Real Input
Input type.
typedef Real Output
Output type.
Detailed Description
Scalar-valued unary function of a scalar value.
Member Function Documentation
deriv()
virtual Real ScalarFunc::deriv (Real) const inline virtual
Returns the first-derivative of the function.
Reimplemented in EvalFuncScalar< Scalar >, EvalFuncScalar< Scalar >, LinearFunc, RampFunc, and SineFunc.
References Real.
Referenced by SpaceTimeFunc::dderiv(), ConstTimeFunc::deriv(), and SpaceTimeFunc::deriv().
The documentation for this class was generated from the following file:
/home/runner/work/IFEM-2/IFEM-2/src/Utility/Function.h