IFEM: LocalIntegral Class Reference
LocalIntegral Class Reference
Abstract base class representing an element level integrated quantity.
#include <LocalIntegral.h>
Public Member Functions
virtual ~LocalIntegral ()
Empty destructor.
virtual void destruct ()
Virtual destruction method to clean up after numerical integration.
virtual const LocalIntegral * ref () const
Returns the LocalIntegral object to assemble into the global one.
void getSolution (size_t nsd, size_t nen, Matrix *u=nullptr, Matrix *v=nullptr, Matrix *a=nullptr, bool forceCurrent=false) const
Extracts element solution vectors as nsd by nen matrices.
Public Attributes
Vectors vec
Element-level primary solution vectors.
Protected Member Functions
LocalIntegral ()
The default constructor is protected to allow sub-classes only.
Detailed Description
Abstract base class representing an element level integrated quantity.
Member Function Documentation
destruct()
virtual void LocalIntegral::destruct () inline virtual
Virtual destruction method to clean up after numerical integration.
Reimplemented in ElmNorm.
Referenced by ASMstruct::diracPoint(), ASMu2D::diracPoint(), ASMu3D::diracPoint(), ASMs1D::integrate(), ASMs1DLag::integrate(), ASMs1DSpec::integrate(), ASMs2D::integrate(), ASMs2Dmx::integrate(), ASMs2DmxLag::integrate(), ASMs2DSpec::integrate(), ASMs2DTri::integrate(), ASMs3D::integrate(), ASMs3DLag::integrate(), ASMs3Dmx::integrate(), ASMs3DmxLag::integrate(), ASMs3DSpec::integrate(), ASMu2D::integrate(), ASMu2Dmx::integrate(), ASMu3D::integrate(), ASMu3Dmx::integrate(), ASMs2D::integrate(), ASMs2Dmx::integrate(), ASMs3Dmx::integrate(), ASMu2D::integrate(), ASMu2Dmx::integrate(), ASMs2D::integrate(), ASMs3D::integrate(), ASMu2D::integrate(), ASMs1D::integrate(), ASMs1DLag::integrate(), ASMs2D::integrate(), ASMs2DLag::integrate(), ASMs2Dmx::integrate(), ASMs2DmxLag::integrate(), ASMs2DSpec::integrate(), ASMs2DTri::integrate(), ASMs3D::integrate(), ASMs3DLag::integrate(), ASMs3Dmx::integrate(), ASMs3DmxLag::integrate(), ASMs3DSpec::integrate(), ASMu2D::integrate(), ASMu2Dmx::integrate(), ASMu3D::integrate(), ASMu3Dmx::integrate(), ASMs3D::integrateEdge(), ASMs3DLag::integrateEdge(), and ASMs2DLag::integrateElm().
getSolution()
void LocalIntegral::getSolution (size_t nsd, size_t nen, Matrix * u = nullptr, Matrix * v = nullptr, Matrix * a = nullptr, bool forceCurrent = false) const inline
Extracts element solution vectors as nsd by nen matrices.
Parameters
[in] nsd Number of space dimensions
[in] nen Number of element nodes
[out] u First element solution vector (deformation)
[out] v Second element solution vector (velocity)
[out] a Third element solution vector (acceleration)
[in] forceCurrent If true, return the current values also if previous values are present
This method is intended for extraction of element-level solution vectors (deformation, velocity and acceleration for dynamics problems) on a matrix form, such that equivalent integration point values can be obtained by multiplying with the basis function value vector, fe.N. If the size of vec is 6 or more and forceCurrent is false, the previous values stored in positions {3,4,5} are returned, otherwise the current values stored in positions {0,1,2} are returned.
References vec.
Referenced by ASMs2DLag::integrate(), and ASMs2DLag::integrateElm().
The documentation for this class was generated from the following file:
/home/runner/work/IFEM-2/IFEM-2/src/ASM/LocalIntegral.h