IFEM: PETScVectors Class Reference
PETScVectors Class Reference
Class for representing a set of system vectors in PETSc format.
#include <PETScMatrix.h>
Public Member Functions
PETScVectors (const PETScMatrix &A, int nvec)
Constructor creating a set of system vectors.
~PETScVectors ()
Destructor frees up the dynamically allocated vectors.
LinAlg::MatrixType getType () const override
Returns the vector type.
SystemVector * copy () const override
Creates a copy of the system vector and returns a pointer to it.
size_t dim () const override
Returns the dimension of the system vector.
void redim (size_t) override
Sets the dimension of the system vector.
Real * getPtr () override
Access through pointer.
const Real * getRef () const override
Reference through pointer.
const Vector & vec () const override
Reference to underlying utl::vector.
void init (Real) override
Initializes the vector to a given scalar value.
void mult (Real) override
Multiplication with a scalar.
void add (const SystemVector &, Real) override
Addition of another system vector to this one.
Real L1norm () const override
L1-norm of the vector.
Real L2norm () const override
L2-norm of the vector.
Real Linfnorm () const override
Linfinity-norm of the vector.
void assemble (const Vectors &vecs, const IntVec &meqn, int=0) override
Adds element vectors into the system vector.
Vec get (size_t idx)
Returns a particular vector.
size_t size () const
Returns number of vectors.
Public Member Functions inherited from SystemVector
virtual ~SystemVector ()
Empty destructor.
virtual void resize (size_t n, bool=false)
Resizes the vector to length n.
bool empty () const
Checks if the vector is empty.
SystemVector & copy (const SystemVector &x)
Copies entries from input vector x into *this.
virtual bool endAssembly ()
Finalizes the system vector assembly.
virtual void dump (std::ostream &, LinAlg::StorageFormat, const char *=nullptr) const
Dumps the system vector on a specified format.
Private Attributes
size_t myDim
Global dimension of vectors.
std::vector< Vec > vectors
Array of vectors.
const PETScMatrix & myA
Reference to matrix vectors are associated with.
Additional Inherited Members
Static Public Member Functions inherited from SystemVector
static SystemVector * create (const ProcessAdm *adm, LinAlg::MatrixType vtype)
Static method creating a vector of the given type.
Protected Member Functions inherited from SystemVector
SystemVector ()
The default constructor is protected to allow sub-classes only.
virtual std::ostream & write (std::ostream &os) const
Writes the system vector to the given output stream.
Detailed Description
Class for representing a set of system vectors in PETSc format.
Used for solving systems with multiple RHS vectors.
Constructor & Destructor Documentation
PETScVectors()
PETScVectors::PETScVectors (const PETScMatrix & A, int nvec)
Constructor creating a set of system vectors.
Parameters
A Matrix with vector layout to use
nvec Number of RHS vectors
References PETScMatrix::getMatrix(), myDim, size(), and vectors.
Member Function Documentation
add()
void PETScVectors::add (const SystemVector & , Real) inline override virtual
Addition of another system vector to this one.
Implements SystemVector.
assemble()
void PETScVectors::assemble (const Vectors & vecs, const IntVec & meqn, int = 0) override virtual
Adds element vectors into the system vector.
Parameters
[in] vecs The element vectors
[in] meqn Matrix of element equation numbers (0 based)
Implements SystemVector.
References PETScMatrix::getDD(), DomainDecomposition::getGlobalEq(), myA, and vectors.
copy()
SystemVector * PETScVectors::copy () const inline override virtual
Creates a copy of the system vector and returns a pointer to it.
Implements SystemVector.
dim()
size_t PETScVectors::dim () const inline override virtual
Returns the dimension of the system vector.
Implements SystemVector.
References myDim.
Referenced by PETScMatrix::solve().
get()
Vec PETScVectors::get (size_t idx) inline
Returns a particular vector.
Parameters
idx Index of vector to return
References vectors.
Referenced by PETScMatrix::solve().
getPtr()
Real * PETScVectors::getPtr () inline override virtual
Access through pointer.
Implements SystemVector.
getRef()
const Real * PETScVectors::getRef () const inline override virtual
Reference through pointer.
Implements SystemVector.
getType()
LinAlg::MatrixType PETScVectors::getType () const inline override virtual
Returns the vector type.
Implements SystemVector.
References LinAlg::PETSC.
init()
void PETScVectors::init (Real) inline override virtual
Initializes the vector to a given scalar value.
Implements SystemVector.
L1norm()
Real PETScVectors::L1norm () const inline override virtual
L1-norm of the vector.
Implements SystemVector.
L2norm()
Real PETScVectors::L2norm () const inline override virtual
L2-norm of the vector.
Implements SystemVector.
Linfnorm()
Real PETScVectors::Linfnorm () const inline override virtual
Linfinity-norm of the vector.
Implements SystemVector.
mult()
void PETScVectors::mult (Real) inline override virtual
Multiplication with a scalar.
Implements SystemVector.
redim()
void PETScVectors::redim (size_t) inline override virtual
Sets the dimension of the system vector.
Implements SystemVector.
vec()
const Vector & PETScVectors::vec () const inline override virtual
Reference to underlying utl::vector.
Implements SystemVector.
References SystemVector::empty().
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/LinAlg/PETScMatrix.h
/home/runner/work/IFEM-2/IFEM-2/src/LinAlg/PETScMatrix.C