IFEM: Immersed::Geometry Class Reference
Immersed::Geometry Class Reference
Interface class representing a geometric object.
#include <ImmersedBoundaries.h>
Public Member Functions
virtual ~Geometry ()
Empty destructor.
virtual double Alpha (double X, double Y, double Z) const
Performs the inside-outside test for the geometric object.
virtual double Alpha (const Vec3 &X) const
Performs the inside-outside test for the geometric object.
virtual ElementBlock * tesselate () const
Creates a finite element model of the geometry for visualization.
Protected Member Functions
Geometry ()
The default constructor is protected to allow sub-classes only.
Detailed Description
Interface class representing a geometric object.
Member Function Documentation
Alpha() [1/2]
double Immersed::Geometry::Alpha (const Vec3 & X) const virtual
Performs the inside-outside test for the geometric object.
Reimplemented in GeoFunc2D.
References Alpha(), Vec3::x, Vec3::y, and Vec3::z.
Alpha() [2/2]
virtual double Immersed::Geometry::Alpha (double X, double Y, double Z) const inline virtual
Performs the inside-outside test for the geometric object.
Alpha is used as an indicator here: Alpha = 0.0 if the point is lying outside the physical domain Alpha = 0.0 if the point is lying directly on the boundary Alpha = 1.0 if the point is lying inside the physical domain
Reimplemented in Oval2D, PerforatedPlate2D, and Hole2D.
Referenced by Alpha(), ASMs2DIB::filterResults(), ASMu2DIB::filterResults(), and Immersed::getQuadraturePoints().
tesselate()
virtual ElementBlock * Immersed::Geometry::tesselate () const inline virtual
Creates a finite element model of the geometry for visualization.
Reimplemented in Hole2D, Oval2D, and PerforatedPlate2D.
Referenced by ASMs2DIB::immersedGeometry(), and ASMu2DIB::immersedGeometry().
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/ASM/ImmersedBoundaries.h
/home/runner/work/IFEM-2/IFEM-2/src/ASM/ImmersedBoundaries.C