IFEM: SIMargsBase Class Reference
SIMargsBase Class Reference
Base class for input file pre-parsing in applications.
#include <SIMargsBase.h>
Public Member Functions
SIMargsBase (const char *ctx)
The constructor initializes the default parameter values.
virtual bool parseArg (const char *argv)
Parses a command-line argument.
Public Member Functions inherited from XMLInputBase
bool readXML (const char *fileName, bool verbose=true)
Reads an XML input file.
bool loadXML (const char *xml)
Loads data from an XML-formatted text string.
Public Attributes
int dim
Dimensionality of simulation.
char adap
If ≠ 0, run an adaptive simulator.
Protected Member Functions
bool parse (const tinyxml2::XMLElement *elem) override
Parses a data section from an XML element.
Protected Member Functions inherited from XMLInputBase
const tinyxml2::XMLElement * loadFile (tinyxml2::XMLDocument &doc, const char *fileName, bool verbose=false)
Loads an XML input file into a tinyxml2::XMLDocument object.
virtual const char ** getPrioritizedTags () const
Returns a list of prioritized XML-tags.
Private Attributes
const char * context
Application-specific context tag.
Detailed Description
Base class for input file pre-parsing in applications.
Member Function Documentation
parse()
bool SIMargsBase::parse (const tinyxml2::XMLElement * elem) override protected virtual
Parses a data section from an XML element.
Implements XMLInputBase.
References adap, context, dim, utl::getAttribute(), IFEM::getOptions(), and SIMoptions::parseDiscretizationTag().
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/SIM/SIMargsBase.h
/home/runner/work/IFEM-2/IFEM-2/src/SIM/SIMargsBase.C