IFEM: TextureProperties Class Reference
TextureProperties Class Reference
Class containing a set of properties defined through a texture map.
#include <TextureProperties.h>
Classes
struct Property
Struct holding information about a property.
Public Member Functions
void parse (const tinyxml2::XMLElement *elem)
Parse an XML definition. param elem XML element to parse.
void printLog () const
Print property information to log.
bool getProperty (const std::string &name, const Vec3 &X, double &val) const
Get value for a property.
bool hasProperty (const std::string &name) const
Check if a property is available.
Protected Attributes
std::map< std::string, Property > properties
Map of available properties.
Detailed Description
Class containing a set of properties defined through a texture map.
Member Function Documentation
getProperty()
bool TextureProperties::getProperty (const std::string & name, const Vec3 & X, double & val) const
Get value for a property.
Parameters
[in] name Name of property
[in] X Position (including parameter values) to evaluate property for
[out] val Property value
References utl::matrixBase< T >::dim(), TextureProperties::Property::max, TextureProperties::Property::min, TextureProperties::Property::prescaled, properties, TextureProperties::Property::textureData, and Vec4::u.
Referenced by PropertyFunc::evaluate().
hasProperty()
bool TextureProperties::hasProperty (const std::string & name) const
Check if a property is available.
Parameters
name Name of property
References utl::matrixBase< T >::end(), and properties.
The documentation for this class was generated from the following files:
/home/runner/work/IFEM-2/IFEM-2/src/Utility/TextureProperties.h
/home/runner/work/IFEM-2/IFEM-2/src/Utility/TextureProperties.C