IFEM: /home/runner/work/IFEM-2/IFEM-2/src/LinAlg/DenseMatrix.C File Reference
DenseMatrix.C File Reference
Dense system matrix representation.
#include "DenseMatrix.h"
#include "SparseMatrix.h"
#include "SAM.h"
#include "LAPack.h"
#include <fstream>
#include <sstream>
Functions
static void assemDense (const Matrix &eM, Matrix &SM, Vector &SV, const IntVec &meen, const int *meqn, const int *mpmceq, const int *mmceq, const Real *ttcc)
This is a C++ version of the F77 subroutine ADDEM2 (SAM library).
DenseMatrix operator* (Real alpha, const DenseMatrix &A)
Multiply a matrix with a scalar.
DenseMatrix operator* (const DenseMatrix &A, Real alpha)
Multiply a matrix with a scalar.
Detailed Description
Dense system matrix representation.
Date
Jan 4 2008
Author
Knut Morten Okstad / SINTEF
Function Documentation
assemDense()
static void assemDense (const Matrix & eM, Matrix & SM, Vector & SV, const IntVec & meen, const int * meqn, const int * mpmceq, const int * mmceq, const Real * ttcc) static
This is a C++ version of the F77 subroutine ADDEM2 (SAM library).
It performs exactly the same tasks, except that NRHS always is 1.
References utl::vector< T >::empty(), and Real.
Referenced by DenseMatrix::assemble(), DenseMatrix::assemble(), and DenseMatrix::assemble().
operator*() [1/2]
DenseMatrix operator* (const DenseMatrix & A, Real alpha)
Multiply a matrix with a scalar.
Parameters
[in] A The matrix to scale
[in] alpha Scalar value
References DenseMatrix::getMat().
operator*() [2/2]
DenseMatrix operator* (Real alpha, const DenseMatrix & A)
Multiply a matrix with a scalar.
Parameters
[in] alpha Scalar value
[in] A The matrix to scale
References DenseMatrix::getMat().