IFEM: /home/runner/work/IFEM-2/IFEM-2/src/SIM/ModelGenerator.C File Reference
ModelGenerator.C File Reference
Base class for model generators for NURBS-based FEM simulators.
#include "ModelGenerator.h"
#include "SIMinput.h"
#include "Utilities.h"
#include "Vec3.h"
#include "Vec3Oper.h"
#include "IFEM.h"
#include "tinyxml2.h"
#include <array>
Functions
static std::string parseKnots (const tinyxml2::XMLElement *geo, int num)
Static helper parsing knot vector domain from an XML element.
Detailed Description
Base class for model generators for NURBS-based FEM simulators.
Date
Sep 2 2016
Author
Arne Morten Kvarving / SINTEF
Function Documentation
parseKnots()
static std::string parseKnots (const tinyxml2::XMLElement * geo, int num) static
Static helper parsing knot vector domain from an XML element.
Parameters
[in] geo XML element describing geometry
[in] num Number of knot vectors to add
References IFEM::cout, and utl::getAttribute().
Referenced by DefaultGeometry1D::createG2(), DefaultGeometry2D::createG2(), and DefaultGeometry3D::createG2().