IFEM: /home/runner/work/IFEM-2/IFEM-2/src/LinAlg/SparseMatrix.C File Reference
SparseMatrix.C File Reference
Representation of the system matrix on an unstructured sparse format.
#include "SparseMatrix.h"
#include "IFEM.h"
#include "SAM.h"
#include <algorithm>
Classes
struct SuperLUdata
Data structures for the SuperLU equation solver.
Functions
static void assemSparse (const Matrix &eM, SparseMatrix &SM, Vector &SV, const IntVec &meen, const int *meqn, const int *mpmceq, const int *mmceq, const Real *ttcc)
This is a C++ version of the F77 subroutine ADDEM2 (SAM library).
static void assemSparse (const RealArray &V, SparseMatrix &SM, size_t col, const IntVec &mnen, const int *meqn, const int *mpmceq, const int *mmceq, const Real *ttcc)
Adds a nodal vector into a non-symmetric rectangular sparse matrix.
Detailed Description
Representation of the system matrix on an unstructured sparse format.
Date
Jan 8 2008
Author
Knut Morten Okstad / SINTEF
Function Documentation
assemSparse() [1/2]
static void assemSparse (const Matrix & eM, SparseMatrix & SM, Vector & SV, const IntVec & meen, const int * meqn, const int * mpmceq, const int * mmceq, const Real * ttcc) static
This is a C++ version of the F77 subroutine ADDEM2 (SAM library).
It performs exactly the same tasks, except that NRHS always is 1, and that the system matrix SM here is an object of the SparseMatrix class.
References utl::vector< T >::empty(), Real, and utl::vector< T >::size().
Referenced by SparseMatrix::assemble(), SparseMatrix::assemble(), SparseMatrix::assemble(), and SparseMatrix::assembleCol().
assemSparse() [2/2]
static void assemSparse (const RealArray & V, SparseMatrix & SM, size_t col, const IntVec & mnen, const int * meqn, const int * mpmceq, const int * mmceq, const Real * ttcc) static
Adds a nodal vector into a non-symmetric rectangular sparse matrix.
The nodal values are added into the columns col to col+2.
References Real.