IFEM: /home/runner/work/IFEM-2/IFEM-2/src/Utility/Vec3Oper.C File Reference
Vec3Oper.C File Reference
Global algebraic operations involving Vec3 objects.
#include "Vec3Oper.h"
#include "Vec3.h"
Functions
Vec3 operator* (const utl::matrix< Real > &A, const std::vector< Real > &x)
Multiplication of a matrix and a vector.
Vec3 operator* (const utl::matrix< Real > &A, const Vec3 &x)
Multiplication of a matrix and a vector.
Vec3 operator* (const std::vector< Real > &x, const utl::matrix< Real > &A)
Multiplication of a vector and a matrix,.
Vec3 operator* (const Vec3 &x, const utl::matrix< Real > &A)
Multiplication of a vector and a matrix.
Vec3 operator* (const Vec3 &a, Real value)
Multiplication of a vector and a scalar.
Vec3 operator* (Real value, const Vec3 &a)
Multiplication of a scalar and a vector.
Vec3 operator/ (const Vec3 &a, Real value)
Division of a vector by a scalar,.
Real operator* (const Vec3 &a, const Vec3 &b)
Dot product between two vectors.
Vec3 operator+ (const Vec3 &a, const Vec3 &b)
Summation of two vectors.
Vec3 operator- (const Vec3 &a, const Vec3 &b)
Subtraction of two vectors.
Vec3 operator+ (const Vec3 &a, Real value)
Summation of vector and a scalar.
Vec3 operator- (const Vec3 &a, Real value)
Subtraction of a vector and a scalar.
bool operator== (const Vec3 &a, const Vec3 &b)
Equality operator.
bool operator!= (const Vec3 &a, const Vec3 &b)
Unequality operator.
bool operator< (const Vec3 &a, const Vec3 &b)
Less-than operator.
std::ostream & operator<< (std::ostream &os, const Vec3 &a)
Output stream operator.
std::istream & operator>> (std::istream &is, Vec3 &a)
Input stream operator.
Detailed Description
Global algebraic operations involving Vec3 objects.
Date
Dec 19 2008
Author
Knut Morten Okstad / SINTEF
Function Documentation
operator*() [1/2]
Vec3 operator* (const std::vector< Real > & x, const utl::matrix< Real > & A)
Multiplication of a vector and a matrix,.
Multiplication of a vector and a matrix.
Returns
\({\bf y} = {\bf A}^T {\bf x} \)
Special version for computation of 3D point vectors. The number of columns in A must be (at least) 3. Extra columns (if any) in A are ignored.
References utl::matrix< T >::cols(), and utl::matrix< T >::multiply().
operator*() [2/2]
Vec3 operator* (const utl::matrix< Real > & A, const std::vector< Real > & x)
Multiplication of a matrix and a vector.
Returns
\({\bf y} = {\bf A} {\bf x} \)
Special version for computation of 3D point vectors. The number of rows in A must be (at least) 3. Extra rows (if any) in A are ignored.
References utl::matrix< T >::multiply(), and utl::matrix< T >::rows().