IFEM: /home/runner/work/IFEM-2/IFEM-2/src/Utility/VTF.C File Reference
VTF.C File Reference
Output of FE model and results to VTF file.
#include "VTF.h"
#include "ElementBlock.h"
#include "Function.h"
#include "Tensor.h"
#include <iostream>
#include <cstdio>
Macros
#define VTFA_FAILURE(x) x <= 0
Convenience macro.
#define VTFA_SUCCESS(x) x > 0
Convenience macro.
Functions
static bool showError (const char *msg, int ID1=-1, int ID2=-2)
Static helper printing an error message to std::cerr.
Detailed Description
Output of FE model and results to VTF file.
Date
Dec 1 2008
Author
Knut Morten Okstad / SINTEF
Function Documentation
showError()
static bool showError (const char * msg, int ID1 = -1, int ID2 = -2) static
Static helper printing an error message to std::cerr.
Parameters
[in] msg The message to print
[in] ID1 If non-negative, the value is appended to the message
[in] ID2 If non-negative, the value is appended to the message
Returns
false (always)
Referenced by VTF::VTF(), VTF::writeDblk(), VTF::writeEres(), VTF::writeGrid(), VTF::writeNfunc(), VTF::writeNres(), VTF::writePoints(), VTF::writeSblk(), VTF::writeSblk(), VTF::writeState(), VTF::writeTblk(), VTF::writeTransformation(), VTF::writeVblk(), VTF::writeVblk(), VTF::writeVectors(), VTF::writeVres(), and VTF::~VTF().