# Options for the IFEM library

option(IFEM_USE_OPENMP         "Compile with OpenMP support?"         ON)
option(IFEM_USE_LRSPLINES      "Compile with LR-splines support?"     ON)
option(IFEM_USE_SUPERLU        "Compile with SuperLU support?"        ON)
option(IFEM_USE_SUPERLU_MT     "Compile with SuperLU_MT support?"     OFF)
option(IFEM_USE_PETSC          "Compile with PETSc support?"          ON)
option(IFEM_USE_MPI            "Compile with MPI support?"            OFF)
option(IFEM_USE_ISTL           "Compile with dune-istl support?"      ON)
option(IFEM_USE_SLEPC          "Compile with SLEPc support?"          OFF)
option(IFEM_USE_SAMG           "Compile with SAMG support?"           OFF)
option(IFEM_USE_HDF5           "Compile with HDF5 support?"           ON)
option(IFEM_USE_VTFWRITER      "Compile with VTFWriter support?"      ON)
option(IFEM_USE_UMFPACK        "Compile with UMFPACK support?"        ON)
option(IFEM_USE_CEREAL         "Compile with cereal support?"         ON)
option(IFEM_USE_ZOLTAN         "Compile with zoltan support?"         OFF)
option(IFEM_USE_TRACY          "Enable tracer profiler?"              OFF)
option(IFEM_USE_LTO            "Enable link-time optimizoation?"      OFF)

set(IFEM_USE_SPR "OFF" CACHE STRING "Compile with SPR support?")
set_property(CACHE IFEM_USE_SPR PROPERTY STRINGS ON I32 I64 OFF)

message(STATUS "Here are the current IFEM configuration settings:")
message(STATUS "IFEM_USE_OPENMP     = ${IFEM_USE_OPENMP}")
message(STATUS "IFEM_USE_LRSPLINES  = ${IFEM_USE_LRSPLINES}")
message(STATUS "IFEM_USE_SUPERLU    = ${IFEM_USE_SUPERLU}")
message(STATUS "IFEM_USE_SUPERLU_MT = ${IFEM_USE_SUPERLU_MT}")
message(STATUS "IFEM_USE_PETSC      = ${IFEM_USE_PETSC}")
message(STATUS "IFEM_USE_MPI        = ${IFEM_USE_MPI}")
message(STATUS "IFEM_USE_ISTL       = ${IFEM_USE_ISTL}")
message(STATUS "IFEM_USE_SLEPC      = ${IFEM_USE_SLEPC}")
message(STATUS "IFEM_USE_SAMG       = ${IFEM_USE_SAMG}")
message(STATUS "IFEM_USE_HDF5       = ${IFEM_USE_HDF5}")
message(STATUS "IFEM_USE_VTFWRITER  = ${IFEM_USE_VTFWRITER}")
message(STATUS "IFEM_USE_UMFPACK    = ${IFEM_USE_UMFPACK}")
message(STATUS "IFEM_USE_CEREAL     = ${IFEM_USE_CEREAL}")
message(STATUS "IFEM_USE_ZOLTAN     = ${IFEM_USE_ZOLTAN}")
message(STATUS "IFEM_USE_TRACY      = ${IFEM_USE_TRACY}")
message(STATUS "IFEM_USE_LTO        = ${IFEM_USE_LTO}")
message(STATUS "IFEM_USE_SPR        = ${IFEM_USE_SPR}")

include(IFEMOptionsDownstream)
